import { AdGroupPolicyMatchingCheck, AdInfrastructureMatchingCheck, AdPracticeMatchingCheck } from "./active-directory-checks";
import { AdPracticeDesignOverview, AdReplicationOverview, AdTroubleshootingFlow, DomainServiceLocationFlow, GroupPolicyHierarchy } from "./active-directory-visualizations";
import { LearningObjectives } from "./learning-objectives";
import { SingleChoiceCheck, type SingleChoiceOption } from "./single-choice-check";

export function ActiveDirectoryControllerLesson() {
  return <Body>
    <LearningObjectives context="lesson" objectives={["die Rolle eines Domain Controllers erklären", "mehrere DCs als aktive, replizierende Systeme einordnen", "die DNS-Abhängigkeit von AD DS und SRV-Dienstsuche erklären", "Replikation und Multi-Master-Modell verstehen", "FSMO als begrenzte Ausnahme erkennen", "Global Catalog, Sites und Subnetze konzeptionell erklären", "die Bedeutung synchroner Systemzeit für Kerberos verstehen", "geeignete interne DNS-Auflösung für Domänenclients begründen"]} />
    <Section title="Domain Controller: Verzeichnis und Authentifizierung"><p>Ein <strong>Domain Controller (DC)</strong> führt AD DS aus und stellt für seine Domänen- und Forest-Umgebung Verzeichnis- und Authentifizierungsfunktionen bereit. Dazu gehören Anmeldungen, Verzeichnisabfragen und -änderungen, Unterstützung für Gruppenrichtliniendienste sowie Replikation mit anderen DCs. Er speichert weit mehr als Benutzernamen und Passwörter.</p><p>Organisationen betreiben häufig mehrere beschreibbare DCs für Redundanz, Verfügbarkeit, Netzwerknähe und Replikation. DC02 ist kein ausgeschalteter passiver Backup-Server: Normalerweise können mehrere DCs Clients authentifizieren und viele Änderungen annehmen.</p></Section>
    <Section title="AD DS braucht DNS"><p>AD DS und <strong>DNS</strong> sind getrennte Technologien. AD ersetzt DNS nicht. Domänenclients fragen DNS nach geeigneten Domänendiensten. <strong>SRV-Records</strong> können Dienst, Protokoll, Zielhost und Port bekannt machen. <code>_ldap._tcp.dc._msdcs.firma.test</code> ist ein Beispiel für LDAP-DC-Dienstsuche, kein auswendig zu lernender Universalrecord.</p><p>Ein Domänenclient sollte Resolver verwenden, die den privaten AD-DNS-Namensraum und dessen Dienstrecords korrekt auflösen. Ein beliebiger öffentlicher Resolver kennt diese internen Records normalerweise nicht und ist deshalb als einzige Client-DNS-Konfiguration ungeeignet.</p></Section>
    <DomainServiceLocationFlow />
    <Section title="Replikation und Multi-Master"><p>DCs replizieren Änderungen an Objekten und Attributen über Replikationspartner. Für die meisten gewöhnlichen Verzeichnisänderungen gilt ein <strong>Multi-Master-Modell</strong>: Eine Änderung kann auf einem geeigneten beschreibbaren DC erfolgen und wird weitergegeben. AD besitzt Mechanismen, replizierte Änderungen abzugleichen; DC-Datenbanken werden nicht manuell als Dateien kopiert.</p><p>Die Systeme erreichen eine spätere Konvergenz, aber nicht jede Änderung ist im exakt selben Augenblick auf jedem DC sichtbar. Bestimmte spezialisierte Operationen besitzen mit <strong>FSMO</strong> bezeichnete Rolleninhaber. Das ist eine begrenzte Ausnahme und macht den ersten DC nicht dauerhaft zum Master aller Änderungen.</p></Section>
    <AdReplicationOverview />
    <Section title="Global Catalog, Sites und Zeit"><p>Der <strong>Global Catalog (GC)</strong> bietet forestweit durchsuchbare Informationen und unterstützt bestimmte Anmelde- und Verzeichnisszenarien. Er ist keine vollständige Kopie jedes Attributs jedes Forest-Objekts, sondern enthält eine partielle forestweite Repräsentation sowie passende vollständige Informationen für die eigene Domänenpartition.</p><p><strong>AD Sites</strong> bilden physische beziehungsweise Netzwerktopologie für Dienstwahl und Replikationsoptimierung ab. Subnetze können Sites zugeordnet werden. <code>firma.test</code> kann Site-A mit <code>192.168.10.0/24</code> und Site-B mit <code>192.168.20.0/24</code> überspannen. Site, Domain, Subnetz und OU bleiben verschieden; ein Sitename muss keine Stadt bezeichnen.</p><p>Domänenauthentifizierung nutzt häufig <strong>Kerberos</strong>. Kerberos reagiert empfindlich auf übermäßige Uhrabweichungen, daher ist verlässliche Zeitsynchronisation wichtig. Eine feste Toleranz ist hier kein universeller Lernwert.</p></Section>
    <AdInfrastructureMatchingCheck />
    <Section title="Planungsfall firma.test"><p><code>DC01</code> (<code>192.168.10.10</code>) steht in Site-A, <code>DC02</code> (<code>192.168.20.10</code>) in Site-B. Zwei DCs verbessern Verfügbarkeit und Netzwerknähe. DNS führt Clients über Dienstrecords zu passenden DC-Kandidaten. Die Subnetzzuteilung unterstützt Dienstwahl und Replikationsplanung. Ändert sich ein Objekt auf DC01, wird die Änderung konzeptionell über Replikationspartner weitergegeben und später auch auf DC02 sichtbar.</p><Safety>Die Aufgabe plant und beobachtet nur. Sie verändert weder AD, DNS noch Replikation.</Safety></Section>
    <Misconceptions items={["Zweiter Domain Controller ist nur ein ausgeschalteter Backup-Server.", "AD funktioniert sauber mit ausschließlich irgendeinem öffentlichen DNS-Resolver.", "DNS authentifiziert Domänenbenutzer.", "Alle AD-Änderungen passieren nur auf einem Master-DC.", "Forest, Site und Domain sind dasselbe.", "Eine Site muss einer Stadt entsprechen.", "Replikation bedeutet sofortige Sichtbarkeit auf jedem DC."]} />
    <Memory items={["DNS lokalisiert den AD-Dienst; der DC authentifiziert.", "Gewöhnliche Änderungen sind überwiegend Multi-Master; FSMO ist eine spezielle Ausnahme.", "Replikation führt zur Konvergenz, nicht zwingend zur Gleichzeitigkeit.", "Site ≠ Domain ≠ OU ≠ Subnetz."]} />
  </Body>;
}

export function ActiveDirectoryGroupPolicyLesson() {
  return <Body>
    <LearningObjectives context="lesson" objectives={["Zweck und Aufbau eines GPO erklären", "Benutzer- und Computerkonfiguration unterscheiden", "Site-, Domain- und OU-Links einordnen", "LSDOU, Vererbung und Rangfolge vorsichtig erklären", "Security Filtering konzeptionell verstehen", "lokale Richtlinie und Domain-GPO unterscheiden", "Policy und Preference unterscheiden", "gpresult als Diagnose und gpupdate als Verarbeitungsanforderung einordnen"]} />
    <Section title="Zentrale Konfiguration mit GPOs"><p><strong>Group Policy</strong> verwaltet viele Konfigurationen für Domänenbenutzer und -computer zentral, etwa Sicherheits-, Desktop-, Skript- und Systemeinstellungen. Nicht jede Windows-Einstellung ist damit steuerbar, und GPOs sind weder nur Login-Skripte noch nur Softwareinstallation.</p><p>Ein <strong>Group Policy Object (GPO)</strong> enthält Einstellungen und wird separat verwaltet. Es lebt nicht „in einer OU“, sondern kann an unterstützte Bereiche verlinkt werden: <strong>Site, Domain oder OU</strong>. Security Groups sind keine normalen Linkziele; Security Filtering und Berechtigungen können jedoch die Anwendbarkeit einschränken.</p></Section>
    <Section title="Benutzer, Computer und Verarbeitung"><p><strong>Computer Configuration</strong> wird im Computerkontext verarbeitet, <strong>User Configuration</strong> im Benutzerkontext. Das klassische Merkwort <strong>LSDOU</strong> beschreibt Local → Site → Domain → OU, danach verschachtelte OUs. Spätere anwendbare Einstellungen können frühere Konflikte überschreiben, aber „der letzte Wert gewinnt immer“ ist falsch: Manche Einstellungen wirken kumulativ oder folgen besonderen Regeln.</p><p>Links und Einstellungen können entlang der AD-Hierarchie vererbt werden. Child-OUs erhalten daher mögliche Domain- und Parent-OU-Richtlinien. Block Inheritance und Enforced existieren als fortgeschrittene Ausnahmen, sollten aber nicht reflexartig das Design ersetzen.</p></Section>
    <GroupPolicyHierarchy />
    <Section title="OU-Design, lokale Richtlinie und Preferences"><p>OUs sollten Verwaltung, Delegation und GPO-Targeting unterstützen, nicht ohne Bedarf ein Organigramm kopieren. Gruppen ersetzen keine OUs. Ein eigenständiges Windows-System kann lokale Richtlinien besitzen; nach dem Domain Join verschwinden diese nicht. Anwendbare Domain-GPOs können relevante lokale Einstellungen gemäß den Verarbeitungsregeln beeinflussen oder überschreiben.</p><p>Erzwungene <strong>Policy</strong>-Einstellungen und <strong>Group Policy Preferences</strong> konfigurieren Elemente mit unterschiedlichem Verhalten. Preferences sind nicht in jeder Hinsicht so erzwungen wie Administrative-Template-Richtlinien.</p></Section>
    <Section title="Erst untersuchen, dann aktualisieren"><Command command="gpresult /r" classification="A · read-only" text="zeigt Resultant-Set-of-Policy-Informationen für den verfügbaren Benutzer-/Computerkontext; einige Computerdetails können erhöhte Rechte benötigen" /><p><code>gpresult /h report.html</code> erzeugt eine Datei und gehört deshalb nicht zur verpflichtenden read-only Übung. <code>gpupdate</code> fordert eine Richtlinienaktualisierung an und verändert den Verarbeitungszustand. <code>gpupdate /force</code> ist kein universeller erster Troubleshooting-Schritt, sondern allenfalls eine autorisierte administrative Aktion nach der Diagnose.</p></Section>
    <AdGroupPolicyMatchingCheck />
    <SingleChoiceCheck title="OU-Targeting" question="Eine GPO ist an OU Clients verlinkt. PC01 liegt in OU Clients, PC02 in OU Server. Welcher Computer ist das direkte beabsichtigte OU-Ziel?" options={gpoScenarioOptions} correctOptionId="pc01" successMessage="PC01 ist das direkte OU-Ziel. Zusätzlich können für beide Computer anwendbare lokale, Site- oder Domain-Richtlinien existieren." inputName="gpo-target" />
    <Misconceptions items={["GPO und OU sind dasselbe.", "GPO wird direkt an Benutzergruppen gelinkt.", "gpupdate /force ist immer der erste Troubleshooting-Schritt.", "Nach Domain Join gibt es keine Local Policy mehr.", "LSDOU bedeutet bei jeder Einstellung: letzter Wert gewinnt.", "Jede GPO gilt automatisch für jedes Objekt in der Domäne."]} />
  </Body>;
}

export function ActiveDirectoryTroubleshootingLesson() {
  return <Body>
    <LearningObjectives context="lesson" objectives={["lokale und Domänenprobleme trennen", "IP-, DNS-, DC- und Zeit-Evidenz prüfen", "Authentifizierung und Autorisierung unterscheiden", "Kontostatus und Gruppenmitgliedschaften einordnen", "angewendete GPOs untersuchen", "Replikationsverzögerung und veraltete Daten vorsichtig prüfen", "Evidenz vor Änderungen dokumentieren"]} />
    <Section title="Vom Symptom zur prüfbaren Hypothese"><p>Frage zuerst: Was genau schlägt fehl, mit lokalem oder Domänenkonto? Prüfe dann IP-Konfiguration, geeigneten DNS-Resolver, AD-Namensauflösung und DC-Dienstsuche, Netzpfad, Zeit, Kontostatus und Anmeldedaten. Erst danach folgen Gruppen/Autorisierung, GPO und mögliche Replikations- oder Stale-DC-Effekte.</p><p>Wenn <code>PC01\Administrator</code> funktioniert, aber <code>FIRMA\anna</code> nicht, funktioniert zumindest eine lokale Authentifizierung. DNS, DC-Erreichbarkeit, Anmeldedaten/Kontostatus, Zeit, Netzpfad oder die Computer-Domain-Vertrauensbeziehung bleiben offen; die Ursache ist noch nicht bewiesen.</p></Section>
    <AdTroubleshootingFlow />
    <Section title="Sichere Diagnosebefehle"><Command command="ipconfig /all" classification="A · read-only" text="zeigt Adapter-, IP-, Gateway- und DNS-Konfiguration" /><Command command="nslookup firma.test" classification="A · read-only" text="prüft eine normale Namensabfrage, beweist allein aber keine AD-Dienstsuche" /><Command command="nslookup -type=SRV _ldap._tcp.dc._msdcs.firma.test" classification="A · read-only" text="fragt beispielhaft LDAP-DC-SRV-Records ab" /><Command command="nltest /dsgetdc:firma.test" classification="A · read-only, bedingt verfügbar" text="sucht auf domainfähigen Windows-Systemen mit vorhandenen Domänentools einen DC; nicht jede Home-/Basisumgebung enthält nltest" /><Command command="w32tm /query /status" classification="A · read-only, bedingt verfügbar" text="liest den Windows-Zeitdienststatus; große Uhrabweichungen können Kerberos stören" /></Section>
    <Section title="Konten, Tokens und Berechtigungen"><p>Falsches Passwort, deaktiviertes oder gesperrtes Konto sowie abgelaufene Konto-/Anmeldedatenszenarien hängen von der Richtlinie ab. Das sind Authentifizierungskategorien, aber nicht jede Anmeldefehlerursache. Erfolgt die Anmeldung und <code>\\fileserver\support</code> verweigert Zugriff, untersuche <strong>Autorisierung</strong>, Gruppen sowie Freigabe-/NTFS-Berechtigungen.</p><Command command="whoami /groups" classification="A · read-only" text="zeigt Gruppen im aktuellen Sicherheitstoken; eine neue AD-Mitgliedschaft erscheint möglicherweise erst nach neuer Authentifizierung beziehungsweise Anmeldung" /><Command command="gpresult /r" classification="A · read-only" text="zeigt gemeldete resultierende Richtlinien und hilft, Benutzer- von Computer-Scope zu trennen" /></Section>
    <Section title="Replikation, Trust und Protokolle"><p>Zeigt ein anderer Standort nach einer Gruppenänderung alte Daten, dokumentiere zuerst DC, Objekt, Sitzung/Token und Änderungszeit. Replikation ist eine Möglichkeit, aber nicht jede Inkonsistenz. Ein domänenverbundener Computer besitzt außerdem ein Maschinenkonto und eine Sicherheitsbeziehung zur Domäne; ein beschädigtes Trust-Verhältnis kann Symptome verursachen. Reset- oder Rejoin-Befehle gehören nicht in diese Grundlagen-Diagnose.</p><p>Event Viewer kann kontextabhängig Evidenz in System, Application oder authentifizierungsbezogenen Kanälen liefern. Zugriff auf das Security-Log ist nicht vorausgesetzt, und keine einzelne Event ID wird als universell versprochen.</p></Section>
    <SingleChoiceCheck title="Domänenanmeldung eingrenzen" question="Lokaler Login funktioniert, Domain-Login nicht; der Client nutzt ausschließlich einen externen DNS-Resolver. Welcher Bereich ist als Nächstes am stärksten zu untersuchen?" options={dnsDiagnosisOptions} correctOptionId="dns" successMessage="Prüfe die DNS-Konfiguration und AD-Dienstsuche: Ein externer Resolver kennt private SRV-Records normalerweise nicht." inputName="ad-dns-diagnosis" />
    <SingleChoiceCheck title="Zugriff statt Anmeldung" question="Die Domänenanmeldung gelingt, aber Zugriff auf \\fileserver\support wird verweigert. Welche Richtung passt?" options={authorizationOptions} correctOptionId="authorization" successMessage="Die Identität wurde authentifiziert; nun sind Gruppen, Token sowie Freigabe- und NTFS-Berechtigungen zu prüfen." inputName="ad-authorization" />
    <SingleChoiceCheck title="Fehlende Richtlinie" question="Eine erwartete GPO fehlt. Welche Evidenz ist zuerst sinnvoll?" options={gpoDiagnosisOptions} correctOptionId="gpresult" successMessage="gpresult /r und die Prüfung von Objektort, Link und Scope liefern lesende Evidenz." inputName="ad-gpo-diagnosis" />
    <Misconceptions items={["Lokaler Login beweist, dass AD in Ordnung ist.", "Eine A-Auflösung von firma.test beweist alle AD-Dienste.", "Jeder Domain-Login-Fehler ist ein Passwortproblem.", "Dateizugriff verweigert bedeutet Authentifizierung fehlgeschlagen.", "Neue Gruppenmitgliedschaft wirkt sofort in jedem bestehenden Token.", "GPO-Problem bedeutet immer gpupdate /force.", "Domäne neu beitreten ist der normale erste Reparaturschritt."]} />
  </Body>;
}

export function ActiveDirectoryPracticeLesson() {
  return <Body>
    <LearningObjectives context="lesson" objectives={["einen einfachen Forest-/Domain-Entwurf begründen", "OU-, Gruppen-, Site- und GPO-Aufgaben trennen", "AGDLP für Ressourcenrechte planen", "DC-/DNS-Redundanz konzeptionell planen", "read-only Evidenz auswählen", "zwei typische Vorfälle systematisch einordnen", "einen Entwurf nachvollziehbar dokumentieren"]} />
    <Safety prominent>Planen → beobachten → dokumentieren → diagnostizieren → erst dann autorisiert ändern.</Safety>
    <Section title="Firma Beispiel GmbH"><p>Die Firma plant einen Forest mit einer Domäne <code>firma.test</code>. Support: Anna und Ben; Verwaltung: Clara; IT: David. Clients: <code>PC-SUP-01</code>, <code>PC-SUP-02</code>, <code>PC-VERW-01</code>, <code>ADMIN-01</code>. Server: <code>DC01</code>, <code>DC02</code>, <code>FILE01</code>. Netze: <code>192.168.10.0/24</code> und <code>192.168.20.0/24</code>.</p><p>Nichts verlangt mehrere Domains. Ein Forest und <code>firma.test</code> vermeiden unnötige Komplexität.</p></Section>
    <AdPracticeDesignOverview />
    <Section title="Zehn Planungsphasen"><ol className="list-decimal space-y-2 pl-6"><li>Forest und Domain definieren</li><li>OU-Struktur planen</li><li>Benutzer und Computer planen</li><li>Security Groups planen</li><li>AGDLP-Berechtigungen planen</li><li>DC-/DNS-Redundanz planen</li><li>Sites und Subnetze planen</li><li>GPO-Targeting planen</li><li>Troubleshooting-Evidenz prüfen</li><li>Design dokumentieren</li></ol></Section>
    <Section title="OU-, Gruppen- und Berechtigungsentwurf"><p>Eine mögliche, nicht einzig richtige OU-Struktur ist <code>Benutzer\Support</code>, <code>Benutzer\Verwaltung</code>, <code>Benutzer\IT</code>, <code>Computer\Clients</code>, <code>Computer\Admin</code> und <code>Server</code>. Jede OU braucht eine Begründung durch Delegation, GPO-Targeting oder administrative Klarheit.</p><p>Anna + Ben → <code>GG_Support</code> → <code>DL_Share_Support_Modify</code> → Modify auf <code>\\FILE01\Support</code>. Clara → <code>GG_Verwaltung</code> → <code>DL_Share_Verwaltung_Modify</code> → Modify auf <code>\\FILE01\Verwaltung</code>. Broad Full Control ist nicht erforderlich.</p></Section>
    <Section title="DC, DNS, Sites und GPO"><p><code>DC01</code> kann beispielhaft <code>192.168.10.10</code>, <code>DC02</code> <code>192.168.20.10</code> verwenden; beide Adressen sind in den genannten /24-Netzen gültige Hostadressen. Beide DCs stellen AD DS bereit. Geeignete interne DNS-Verfügbarkeit ermöglicht Dienstsuche; konkrete Konfiguration ist nicht Teil des Labs.</p><p>Site-A ordnet <code>192.168.10.0/24</code>, Site-B <code>192.168.20.0/24</code> zu. Beide bleiben in <code>firma.test</code>. Sites unterstützen Netzwerknähe und Replikation, sie sind keine OUs. Eine Client Baseline kann an die passende Clients-OU, Admin-Workstation-Vorgaben an die Admin-OU verlinkt werden.</p></Section>
    <AdPracticeMatchingCheck />
    <Section title="Optionale read-only Untersuchung"><p>Nur in einer vorhandenen, autorisierten und passend ausgestatteten Domänenumgebung: <code>whoami</code>, <code>whoami /user</code>, <code>whoami /groups</code>, <code>ipconfig /all</code>, <code>nslookup</code>, <code>gpresult /r</code>, <code>nltest /dsgetdc:firma.test</code> und <code>w32tm /query /status</code>. <code>nltest</code> benötigt passende Windows-Domänentools.</p><p>Optional lesen <code>Get-ADUser</code>, <code>Get-ADComputer</code> und <code>Get-ADGroup</code> mit vorhandenem ActiveDirectory-Modul/RSAT und Leserechten. Eine Installation ist nicht erforderlich.</p></Section>
    <Section title="Zwei Vorfälle"><p><strong>PC-SUP-02:</strong> Lokaler Login funktioniert, IP und Gateway sind gültig, Domain-Login scheitert, aber nur ein externer DNS-Resolver ist eingetragen. Untersuche AD-DNS und Dienstsuche mit <code>ipconfig /all</code>, geeigneten <code>nslookup</code>-Abfragen und optional <code>nltest</code>. Ändere nicht spontan OUs, Konten oder Domain-Mitgliedschaft.</p><p><strong>Anna:</strong> Anmeldung gelingt, Schreiben auf <code>\\FILE01\Support</code> nicht; Ben kann schreiben. Untersuche Autorisierung: Gruppenmitgliedschaften, aktuellen Token sowie Share-/NTFS-Berechtigungen. DNS-Authentifizierung ist nicht die erste Hypothese.</p></Section>
    <Section title="Dokumentationsvorlage"><div className="overflow-x-auto"><table className="min-w-[44rem] border-collapse text-left text-sm"><caption className="sr-only">Vorlage zur AD-Planung und Untersuchung</caption><thead><tr>{["Area", "Planned/observed state", "Reason", "Evidence", "Potential problem", "Next check"].map((heading) => <th key={heading} className="border border-slate-300 bg-slate-100 p-3">{heading}</th>)}</tr></thead><tbody>{["Forest/domain", "OUs", "Users/computers", "Groups", "Permissions", "DCs", "DNS", "Sites/subnets", "GPOs", "Troubleshooting"].map((area) => <tr key={area}><th className="border border-slate-300 p-3 font-semibold">{area}</th>{Array.from({ length: 5 }, (_, index) => <td key={index} className="border border-slate-300 p-3">—</td>)}</tr>)}</tbody></table></div><p>Die Vorlage bleibt lokal im Unterricht und wird nicht persistiert.</p></Section>
    <Safety>Keine Domain Joins/Rejoins, Benutzer-/Gruppen-/OU-/GPO-/DNS-Änderungen, Passwortresets, DC-Promotion, erzwungene Replikation oder Dienstneustarts sind erforderlich.</Safety>
  </Body>;
}

const gpoScenarioOptions: readonly SingleChoiceOption[] = [{ id: "pc01", label: "PC01", explanation: "PC01 liegt in OU Clients." }, { id: "pc02", label: "PC02", explanation: "PC02 liegt in OU Server und ist nicht das direkte Linkziel." }];
const dnsDiagnosisOptions: readonly SingleChoiceOption[] = [{ id: "dns", label: "DNS-Konfiguration und AD-Dienstsuche", explanation: "Das ist die stärkste Spur." }, { id: "ou", label: "Eine weitere OU erstellen", explanation: "Das behebt keine Dienstsuche." }, { id: "full", label: "Full Control vergeben", explanation: "Berechtigungen lösen keine DNS-Suche." }, { id: "uac", label: "UAC deaktivieren", explanation: "UAC ist hier nicht belegt." }, { id: "browser", label: "Browser neu installieren", explanation: "Der Browser ist nicht beteiligt." }];
const authorizationOptions: readonly SingleChoiceOption[] = [{ id: "authorization", label: "Gruppen, aktuelles Token sowie Share-/NTFS-Berechtigungen", explanation: "Der Zugriff scheitert nach erfolgreicher Anmeldung." }, { id: "password", label: "Domänenpasswort als einzige Ursache", explanation: "Die Anmeldung war erfolgreich." }, { id: "dns", label: "DNS zuerst als Authentifizierungsfehler behandeln", explanation: "Der konkrete Fehler betrifft Ressourcenzugriff." }, { id: "rejoin", label: "Computer sofort neu zur Domäne hinzufügen", explanation: "Das ist invasiv und unbegründet." }];
const gpoDiagnosisOptions: readonly SingleChoiceOption[] = [{ id: "gpresult", label: "gpresult /r sowie Objektort, Link und Scope prüfen", explanation: "Das sammelt zuerst Evidenz." }, { id: "force", label: "sofort gpupdate /force", explanation: "Das stößt Verarbeitung an, bevor die Ursache bekannt ist." }, { id: "rejoin", label: "Computer aus der Domäne entfernen", explanation: "Das ist kein normaler erster Schritt." }];

function Body({ children }: { children: React.ReactNode }) { return <div className="space-y-10 text-base leading-7 text-slate-700 [&_code]:break-words sm:text-lg sm:leading-8">{children}</div>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="text-2xl font-bold tracking-tight text-slate-950">{title}</h2><div className="mt-4 space-y-4">{children}</div></section>; }
function Command({ command, classification, text }: { command: string; classification: string; text: string }) { return <div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><code className="block overflow-wrap-anywhere font-bold text-blue-950">{command}</code><p className="mt-2 text-sm"><strong>{classification}:</strong> {text}</p></div>; }
function Safety({ children, prominent = false }: { children: React.ReactNode; prominent?: boolean }) { return <aside className={`rounded-xl border p-5 ${prominent ? "border-amber-300 bg-amber-50 text-slate-950" : "border-emerald-200 bg-emerald-50 text-emerald-950"}`}><strong>Sicherheitsregel:</strong> {children}</aside>; }
function Memory({ items }: { items: readonly string[] }) { return <aside className="rounded-2xl bg-blue-950 p-5 text-white"><h2 className="text-xl font-bold">Merksätze</h2><ul className="mt-3 list-disc space-y-2 pl-6 text-sm">{items.map((item) => <li key={item}>{item}</li>)}</ul></aside>; }
function Misconceptions({ items }: { items: readonly string[] }) { return <section><h2 className="text-2xl font-bold text-slate-950">Typische Fehlvorstellungen</h2><ul className="mt-5 grid gap-3">{items.map((item) => <li key={item} className="rounded-xl border border-slate-200 bg-white p-4"><strong>Falsch:</strong> „{item}“</li>)}</ul></section>; }
