import { AdConceptMatchingCheck, AdObjectMatchingCheck } from "./active-directory-checks";
import { ActiveDirectoryPurposeFlow, AdHierarchyVisualization, AdObjectOverview, AgdlpVisualization, LocalDomainComparison, LogicalNetworkComparison } from "./active-directory-visualizations";
import { LearningObjectives } from "./learning-objectives";
import { MultipleSelectionCheck, type MultipleSelectionOption } from "./multiple-selection-check";

const adBasicsOptions: readonly MultipleSelectionOption[] = [
  { id: "central", label: "AD DS kann Verzeichnisidentitäten zentral verwalten.", explanation: "Das ist eine Kernaufgabe des Verzeichnisdienstes." },
  { id: "different", label: "Ein Domänenbenutzer unterscheidet sich von einem rein lokalen PC-Konto.", explanation: "Beide Identitäten haben unterschiedliche Gültigkeitsbereiche und Sicherheitskennungen." },
  { id: "computer", label: "Domänencomputer können Computerobjekte in AD besitzen.", explanation: "Der Computer nimmt mit einer eigenen Sicherheitsidentität an der Domäne teil." },
  { id: "auth", label: "Authentifizierung und Autorisierung sind verschiedene Konzepte.", explanation: "Zuerst wird die Identität geprüft; Ressourcen werten danach Berechtigungen aus." },
  { id: "replace-dns", label: "AD DS ersetzt DNS.", explanation: "AD DS und DNS sind getrennte Dienste. AD DS ist für die Dienstsuche stark von funktionierendem DNS abhängig." },
  { id: "required", label: "Jedes Windows-Netzwerk benötigt eine Domäne.", explanation: "Auch Arbeitsgruppen und lokale Konten sind gültige Modelle; nicht jedes kleine Netz braucht AD DS." },
  { id: "duplicate", label: "Ein Domänenkonto existiert automatisch als separates lokales Konto auf jedem PC.", explanation: "Das Domänenkonto bleibt eine Identität im Domänenkontext und wird nicht pro PC dupliziert." },
  { id: "password-list", label: "Active Directory ist nur eine Liste aus Benutzernamen und Passwörtern.", explanation: "AD DS verwaltet strukturierte Objekte, Attribute, Beziehungen und Sicherheitsinformationen." },
];

export function ActiveDirectoryIntroductionLesson() {
  return <LessonBody>
    <LearningObjectives context="lesson" objectives={["AD DS als Active Directory Domain Services ausschreiben", "den grundlegenden Zweck von AD DS erklären", "lokales Konto und Domänenkonto unterscheiden", "zentrale Authentifizierung konzeptionell erklären", "Authentifizierung und Autorisierung unterscheiden", "Verzeichnisobjekte, Attribute und typische Objekttypen erkennen", "Domänenmitgliedschaft konzeptionell erklären", "AD DS von einer einfachen Windows-Benutzerliste unterscheiden", "die Bedeutung von DNS für AD DS einordnen"]} />
    <Section title="Active Directory und AD DS"><p><strong>Active Directory</strong> ist ein Oberbegriff für Microsoft-Technologien rund um Verzeichnisdienste. Dieses Modul behandelt <strong>Active Directory Domain Services (AD DS)</strong>, im Administrationsalltag oft verkürzt als Active Directory oder AD.</p><p>AD DS stellt einen zentralen Verzeichnisdienst für Windows-Domänen bereit. Microsoft Entra ID ist ein anderes Identitätssystem und wird hier nicht mit lokal betriebenem AD DS gleichgesetzt.</p></Section>
    <Section title="Ein strukturierter Verzeichnisdienst"><p>Ein Verzeichnisdienst speichert strukturierte Informationen über Objekte einer Umgebung: Benutzer, Gruppen, Computer, Organisationseinheiten, dienstbezogene Objekte sowie Verweise auf Richtlinien oder Konfiguration. Jedes Objekt besitzt Attribute.</p><Example title="Beispiel: Benutzerobjekt" items={["Name: Anna Beispiel", "Anmeldename: Anna", "UPN: Anna@firma.test", "Gruppenmitgliedschaften", "Kontostatus und weitere Verzeichnisattribute"]} /><p>AD DS ist damit weder eine reine Passwortliste noch Unterricht über relationale Datenbanken.</p></Section>
    <Section title="Warum zentral verwalten?"><p>Bei 20 unabhängigen Arbeitsstationen müssten lokale Identitäten und viele Einstellungen womöglich an jedem Computer separat gepflegt werden. Mit AD DS lassen sich Domänenidentitäten und viele administrative Vorgaben zentral verwalten.</p><p>Das beseitigt weder alle lokalen Konten noch jede lokale Konfiguration. Eine Domäne ist eine betriebliche Entscheidung, keine Pflicht für jedes kleine Netzwerk.</p></Section>
    <LocalDomainComparison />
    <Section title="Authentifizierung und Autorisierung"><p><strong>Authentifizierung</strong> beantwortet: „Wer bist du?“ <strong>Autorisierung</strong> beantwortet: „Was darfst du?“ AD DS kann eine Domänenidentität authentifizieren. Ein Fileserver bewertet anschließend seinen Sicherheitskontext, Gruppen und Ressourcenberechtigungen. AD entscheidet daher nicht automatisch jede Autorisierungsregel jeder Anwendung.</p></Section>
    <ActiveDirectoryPurposeFlow />
    <Section title="Domänenmitgliedschaft, DC und DNS"><p>Ein Windows-Computer kann einer AD-Domäne beitreten. Ein domänenverbundener Computer besitzt normalerweise ein Computerobjekt mit eigener Sicherheitsidentität und kann an Domänenauthentifizierung und zentraler Verwaltung teilnehmen. Lokale Konten und Richtlinien verschwinden dadurch nicht.</p><p>Ein <strong>Domain Controller (DC)</strong> ist ein Server mit AD DS, der Verzeichnisinformationen für die Domäne bereitstellt. DCs bearbeiten Authentifizierung sowie Verzeichnisabfragen und -änderungen und replizieren mit weiteren DCs. Es darf mehr als einen DC geben; AD DS ist für viele Änderungen kein dauerhaftes Ein-Master-System.</p><p>AD DS und <strong>DNS</strong> sind getrennte Dienste. AD DS benötigt funktionierendes DNS, damit Clients Domänendienste wie Domain Controller finden. Details zu Dienstsuche und Replikation folgen in Lektion 4.</p></Section>
    <MultipleSelectionCheck title="AD DS verstehen" question="Welche Aussagen über Active Directory Domain Services sind korrekt?" options={adBasicsOptions} correctOptionIds={["central", "different", "computer", "auth"]} successMessage="Richtig: AD DS zentralisiert Verzeichnisidentitäten, trennt Domänen- von lokalen Konten, kennt Computerobjekte und ändert nichts an der Trennung von Authentifizierung und Autorisierung." missedCorrectMessage="Gesucht sind zentrale Identitätsverwaltung, die Konto-Unterscheidung, Computerobjekte und die Trennung der beiden Sicherheitskonzepte." inputName="ad-ds-basics" />
    <Misconceptions items={[["Active Directory = Benutzerliste.", "AD DS verwaltet viele Objekttypen, Attribute und Sicherheitsbeziehungen."], ["Domänenkonto und lokales Konto sind dasselbe.", "FIRMA\\azubi und PC01\\azubi sind unterschiedliche Sicherheitsidentitäten."], ["AD ersetzt DNS.", "Beide Dienste sind getrennt; AD DS ist stark von DNS abhängig."], ["Jeder Windows-PC muss Mitglied einer AD-Domäne sein.", "Lokale oder Arbeitsgruppenmodelle bleiben möglich."], ["Nach der AD-Authentifizierung darf ein Benutzer auf alle Dateien zugreifen.", "Die jeweilige Ressource muss den Zugriff zusätzlich autorisieren."], ["Es darf nur einen Domain Controller geben.", "Mehrere DCs ermöglichen Redundanz und replizieren Verzeichnisinformationen."]]} />
    <Section title="Sichere Beobachtungsübung"><p>Führe auf einem Windows-Rechner nur <code>whoami</code>, <code>whoami /user</code>, <code>whoami /groups</code> und <code>hostname</code> aus; optional ergänzt <code>systeminfo</code>. Ordne die angezeigte Identität anhand einer Schreibweise wie <code>PC01\azubi</code> oder <code>FIRMA\azubi</code> als lokal oder domänenbezogen ein. Eine echte Domänenumgebung ist nicht erforderlich.</p><Safety>Alle Befehle lesen Informationen. Die Übung verlangt weder erhöhte Rechte noch Beitritt, Austritt oder Konfigurationsänderungen.</Safety></Section>
    <Memory items={["AD DS = zentraler Verzeichnisdienst für Windows-Domänen.", "Lokales Konto ≠ Domänenkonto.", "Authentifizierung = Wer bist du?", "Autorisierung = Was darfst du?", "DC = Domain Controller.", "AD DS braucht funktionierendes DNS."]} />
  </LessonBody>;
}

export function ActiveDirectoryStructureLesson() {
  return <LessonBody>
    <LearningObjectives context="lesson" objectives={["AD-Domäne, Forest und Organisationseinheit erklären", "Domäne und OU unterscheiden", "Objekte und verschachtelte OUs einordnen", "Forest-weite Infrastruktur und Vertrauensbeziehungen vorsichtig einordnen", "DNS-artige Domänennamen erklären", "logische AD-Struktur und physische Netzstruktur unterscheiden", "OUs für Organisation, Delegation und GPO-Ziele begründen", "unnötige OU-Strukturen vermeiden"]} />
    <Section title="Domäne und DNS-Name"><p>Eine AD-<strong>Domäne</strong> ist ein logischer Verzeichnis-, Verwaltungs- und Sicherheitsbereich innerhalb eines Forests. Sie enthält Objekte und besitzt einen gemeinsamen Namensraum sowie eine Domänen-Verzeichnispartition. Im Beispiel verwendet die AD-Domäne den DNS-Namen <code>firma.test</code> und enthält Anna, PC01, die Gruppe Support und SERVER01.</p><p>Ein DNS-Domainname und eine AD-Domäne sind verwandte, aber nicht austauschbare Dienstdefinitionen: DNS löst Namen auf und hilft bei der Dienstsuche; AD DS speichert Verzeichnis- und Sicherheitsinformationen.</p></Section>
    <Section title="Forest und Organisationseinheit"><p>Ein <strong>Forest</strong> (Gesamtstruktur) ist die oberste AD-DS-Struktur und enthält eine oder mehrere Domänen. Ein Forest mit nur <code>firma.test</code> ist häufig, vollständig und gültig. Domänen desselben Forests teilen wichtige Forest-weite Infrastruktur und Vertrauensbeziehungen; mehrere Domänen erhöhen die Komplexität und sind keine Standardpflicht.</p><p>Eine <strong>Organizational Unit (OU)</strong> organisiert Objekte innerhalb einer Domäne. OUs unterstützen administrative Gliederung, Delegation und das gezielte Anwenden von Gruppenrichtlinien (GPOs). Sie dürfen verschachtelt sein, etwa Computer → Clients → Schulungsraum; zu tiefe Strukturen erschweren jedoch die Verwaltung.</p></Section>
    <AdHierarchyVisualization />
    <Section title="OU ist nicht Gruppe"><p>Eine OU ist ein Verzeichniscontainer. Eine <strong>Gruppe</strong> sammelt Mitgliedschaften und dient je nach Typ vor allem Berechtigungs-/Autorisierungs- oder Verteilungszwecken. Benutzer in eine OU zu legen erteilt ihnen keine Dateiberechtigung.</p><p>Die eingebauten Ordner <strong>Users</strong> und <strong>Computers</strong> können Container sein, ohne OUs zu sein. Nicht jedes ordnerartige Symbol in „Active Directory Users and Computers“ ist daher eine Organisationseinheit.</p></Section>
    <LogicalNetworkComparison />
    <Section title="Logisch und physisch trennen"><p>Domänen und OUs strukturieren AD logisch. IP-Subnetze, VLANs und Standorte beschreiben Netzwerk- beziehungsweise physische Topologie. Ein Forest ist kein physischer Standort und eine Domäne ist kein Subnetz. AD Sites und Subnetze werden später nur als Bindeglied zur physischen Topologie relevant.</p></Section>
    <AdConceptMatchingCheck />
    <Section title="Zwei Anforderungen, zwei Werkzeuge"><p>„Alle Support-Mitarbeiter sollen Schreibrechte auf <code>\\fileserver\support</code> erhalten.“ Das wird primär mit einer <strong>Security Group</strong> gelöst, nicht mit einer OU.</p><p>„Support-Clientcomputer sollen eine bestimmte GPO erhalten.“ Dafür kann eine sachgerechte OU-Struktur das GPO-Targeting unterstützen. Die Gruppenrichtlinie selbst folgt in Lektion 5.</p></Section>
    <Misconceptions items={[["Eine Domäne entspricht einem IP-Subnetz.", "Domäne und Subnetz beschreiben verschiedene Ebenen."], ["Jede Firma braucht mehrere AD-Domänen.", "Ein Single-Domain-Forest ist gültig und oft sinnvoll."], ["OU und Gruppe sind dasselbe.", "OU strukturiert und delegiert; Gruppen bilden Mitgliedschaften ab."], ["OUs dienen hauptsächlich dazu, Dateiberechtigungen zu vergeben.", "Dateirechte werden typischerweise Security Groups zugeordnet."], ["Jede Unterabteilung muss zwingend eine eigene OU haben.", "Jede OU braucht einen administrativen Zweck."], ["Forest bedeutet mehrere physische Standorte.", "Ein Forest ist eine logische AD-Struktur."]]} />
    <Section title="Planungsübung"><p>Skizziere für <code>firma.test</code> eine einfache Struktur für Verwaltung, Support, Clients und Server. Begründe jede OU durch Organisation, Delegation oder späteres GPO-Targeting. Verwirf eine OU je Benutzer, eine Domäne je Abteilung und eine Domäne je IP-Subnetz. Es werden keine echten AD-Objekte angelegt.</p></Section>
    <Memory items={["Forest → oberste AD-Struktur", "Domain → logischer AD-Bereich/Namespace", "OU → Organisation/Delegation/GPO-Ziel", "Group → Berechtigungen/Mitgliedschaft", "Subnet → Netzwerk, nicht AD-Domäne"]} />
  </LessonBody>;
}

export function ActiveDirectoryObjectsLesson() {
  return <LessonBody>
    <LearningObjectives context="lesson" objectives={["Benutzer-, Computer- und Gruppenobjekte erklären", "Sicherheitsprinzipale und SIDs konzeptionell verstehen", "Security und Distribution Groups unterscheiden", "Global, Domain Local und Universal konzeptionell einordnen", "Gruppenverschachtelung verstehen", "rollenbasierte Berechtigungen und AGDLP erklären", "Gruppen statt direkter Benutzer-ACLs begründen", "Deaktivieren und Löschen unterscheiden", "Computer als Domänen-Sicherheitsidentitäten verstehen"]} />
    <AdObjectOverview />
    <Section title="Benutzer, Computer und Sicherheitsprinzipale"><p>Ein Benutzerobjekt repräsentiert eine Identität. Typische konzeptionelle Attribute sind Name, Anmeldename, User Principal Name (UPN), Gruppenmitgliedschaften, Kontostatus und weitere Verzeichnisdaten. Beispiele enthalten keine Passwörter.</p><p>Domänenverbundene Computer besitzen normalerweise Computerobjekte und eine eigene Sicherheitsidentität. Sie sind nicht bloß Inventareinträge und können sich für maschinenbezogene Vorgänge gegenüber der Domäne authentifizieren.</p><p>Benutzer, Computer und <strong>Security Groups</strong> können Sicherheitsprinzipale mit einer <strong>Security Identifier (SID)</strong> sein. Zugriffslisten referenzieren diese SIDs. Nicht jedes AD-Objekt ist ein Sicherheitsprinzipal: Eine OU ersetzt beispielsweise keine Security Group in einer normalen Ressourcen-ACL.</p></Section>
    <Section title="SID und Lebensdauer"><p>Der Name eines Objekts kann sich ändern, während seine SID innerhalb seiner Lebensdauer die entscheidende Sicherheitsreferenz bleibt. Wird ein Benutzer gelöscht und mit demselben Namen neu erstellt, entsteht ein neuer Sicherheitsprinzipal mit neuer SID. SID-Zeichenfolgen müssen hier nicht auswendig gelernt werden.</p></Section>
    <Section title="Gruppentyp und Gruppenbereich"><p>Eine <strong>Security Group</strong> kann für Autorisierung und Zugriffsrechte verwendet werden. Eine <strong>Distribution Group</strong> ist für Verteilung beziehungsweise Messaging vorgesehen und wird nicht als Windows-Sicherheitsprinzipal für ACL-Berechtigungen eingesetzt.</p><ScopeCards /><p>Diese Rollen sind einsteigerfreundliche Entwurfszusammenfassungen, keine vollständige Liste aller technischen Mitgliedschaftsregeln.</p></Section>
    <Section title="Verschachtelung und AGDLP"><p>Gruppen dürfen im Rahmen ihrer Typ- und Bereichsregeln Mitglieder anderer Gruppen sein. Dadurch lassen sich berufliche Rollen von Ressourcenrechten trennen, direkte Benutzer-ACLs reduzieren und Wechsel einfacher verwalten. Beliebig tiefe Verschachtelung bleibt unübersichtlich.</p></Section>
    <AgdlpVisualization />
    <Section title="Warum nicht direkt pro Benutzer?"><p>Direkte Benutzerberechtigungen sind technisch möglich, werden bei vielen Benutzern aber schwer wartbar. Wo praktikabel, verbindet ein rollenbasierter Gruppenentwurf Least Privilege mit nachvollziehbaren Berechtigungen. Tägliche Arbeit als Domain Admin, pauschales Full Control und geteilte Administratorkonten sind keine geeigneten Standards.</p></Section>
    <AdObjectMatchingCheck />
    <Section title="Planungsfall"><p>Anna und Ben arbeiten im Support; Clara in der Verwaltung. Entwirf Benutzerobjekte, Rollen- und Ressourcenberechtigungsgruppen: Anna und Ben → <code>GG_Support</code> → <code>DL_Support_Modify</code> → Ändern auf <code>\\fileserver\support</code>. Clara → <code>GG_Verwaltung</code> → <code>DL_Verwaltung_Modify</code> → Ändern auf <code>\\fileserver\verwaltung</code>. Die Namen sind Beispiele, kein universeller Standard.</p><p>Ungeeignet wären direktes Full Control für jeden Benutzer, eine eigene Domäne für Support, eine OU als vermeintliche Dateiberechtigung oder eine IP-Adresse als Gruppenmitglied.</p></Section>
    <Section title="Deaktivieren statt sofort löschen"><p>Beim <strong>Deaktivieren</strong> bleibt das Objekt mit seinen Mitgliedschaften erhalten, kann aber normalerweise nicht als aktivierte Identität für interaktive beziehungsweise Domänenauthentifizierung verwendet werden. Beim <strong>Löschen</strong> wird das Verzeichnisobjekt entfernt. In Offboarding- oder Untersuchungsabläufen kann zuerstiges Deaktivieren den Kontext bewahren.</p></Section>
    <Misconceptions items={[["Computerobjekte sind nur Inventareinträge.", "Computer besitzen eine eigene Domänen-Sicherheitsidentität."], ["Jedes AD-Objekt hat dieselbe Sicherheitsfunktion.", "Nur geeignete Objekttypen sind Sicherheitsprinzipale."], ["Eine OU kann statt einer Security Group Dateirechte erhalten.", "OU und Berechtigungsgruppe haben verschiedene Aufgaben."], ["Berechtigungen sollten immer direkt Benutzern gegeben werden.", "Gruppenbasierte Vergabe ist meist wartbarer; direkte ACLs sind dennoch technisch möglich."], ["Security Group und Distribution Group sind dasselbe.", "Nur die Security Group ist für Windows-Autorisierung vorgesehen."], ["Neu erstellen mit gleichem Namen ergibt dieselbe Sicherheitsidentität.", "Das neue Objekt erhält eine neue SID."], ["AGDLP ist ein zwingendes AD-Protokoll.", "AGDLP ist ein Entwurfsmuster."]]} />
    <Section title="Optionale, nur lesende Beobachtung"><p>In einer vorhandenen, autorisierten AD-Umgebung können <code>Get-ADUser</code>, <code>Get-ADComputer</code> und <code>Get-ADGroup</code> optional Informationen lesen. Sie benötigen das PowerShell-Modul <code>ActiveDirectory</code> beziehungsweise RSAT, eine passende AD-Umgebung und ausreichende Leserechte. Modul oder RSAT werden nicht installiert; die Basislektion funktioniert ohne Domain Controller.</p></Section>
    <Memory items={["SID = dauerhafte Sicherheitsreferenz während der Objektlebensdauer.", "Computerobjekt = Sicherheitsidentität, nicht nur Inventar.", "Security Group ≠ Distribution Group.", "Rolle und Ressourcenrecht durch Gruppen trennen.", "AGDLP = Muster, kein Protokoll.", "Deaktivieren ≠ Löschen."]} />
    <aside className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><h2 className="text-xl font-bold text-slate-950">Als Nächstes: Domänencontroller, DNS und Replikation</h2><p className="mt-3 text-sm leading-7">Lektion 4 behandelt Domain Controllers, Authentifizierung und Dienstsuche, DNS und SRV, Replikation, mehrere DCs, den Global Catalog auf Einsteigerniveau sowie die Bedeutung von Zeit und DNS.</p></aside>
  </LessonBody>;
}

function LessonBody({ children }: { children: React.ReactNode }) { return <div className="space-y-10 text-base leading-7 text-slate-700 [&_code]:break-words sm:text-lg sm:leading-8">{children}</div>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="text-2xl font-bold tracking-tight text-slate-950">{title}</h2><div className="mt-4 space-y-4">{children}</div></section>; }
function Example({ title, items }: { title: string; items: readonly string[] }) { return <aside className="rounded-xl border border-slate-200 bg-slate-50 p-4"><h3 className="font-bold text-slate-950">{title}</h3><ul className="mt-2 list-disc space-y-1 pl-6 text-sm">{items.map((item) => <li key={item}>{item}</li>)}</ul></aside>; }
function Safety({ children }: { children: React.ReactNode }) { return <aside className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950"><strong>Sicherheit:</strong> {children}</aside>; }
function Memory({ items }: { items: readonly string[] }) { return <aside className="rounded-2xl bg-blue-950 p-5 text-white"><h2 className="text-xl font-bold">Merksätze</h2><ul className="mt-3 list-disc space-y-2 pl-6 text-sm">{items.map((item) => <li key={item}>{item}</li>)}</ul></aside>; }
function Misconceptions({ items }: { items: readonly (readonly [string, string])[] }) { return <section><h2 className="text-2xl font-bold text-slate-950">Typische Fehlvorstellungen</h2><dl className="mt-5 space-y-3">{items.map(([wrong, correction]) => <div key={wrong} className="rounded-xl border border-slate-200 bg-white p-4"><dt className="font-bold text-slate-950">Falsch: „{wrong}“</dt><dd className="mt-2 text-sm"><strong>Korrektur:</strong> {correction}</dd></div>)}</dl></section>; }
function ScopeCards() { const scopes = [["Global", "bildet häufig Konten mit einer Rolle aus derselben Domäne ab"], ["Domain Local", "bildet häufig eine Berechtigung auf eine Ressource in einer Domäne ab"], ["Universal", "kann Forest-Domänen überspannen und ist für Mehrdomänen-Szenarien nützlich"]] as const; return <dl className="grid gap-3 md:grid-cols-3">{scopes.map(([name, detail]) => <div key={name} className="rounded-xl border border-slate-200 bg-white p-4"><dt className="font-bold text-slate-950">{name}</dt><dd className="mt-2 text-sm leading-6">{detail}</dd></div>)}</dl>; }
