import type { ReactNode } from "react";
import { backupExerciseDefinitions } from "../../data/learning-exercises/backup";
import { FundamentalsLesson, ResponsiveTable, TextFlow, type LessonSection } from "./fundamentals-lesson-elements";
import { PracticeExercise } from "./practice-exercise";

type BackupLesson = {
  objectives: readonly string[];
  intro: ReactNode;
  sections: readonly LessonSection[];
  visual?: ReactNode;
  scenario: { title: string; situation: ReactNode; tasks: readonly ReactNode[]; solution: ReactNode };
  takeaway: readonly ReactNode[];
};

const typeRows = [
  ["Vollbackup", "alle ausgewählten Daten", "meist längste Sicherung, größter Speicher je Lauf", "nur passendes Vollbackup", "einfacher Restore, aber hoher regelmäßiger Aufwand"],
  ["inkrementell", "Änderungen seit der letzten Sicherung dieser Kette", "meist kurz und klein", "Vollbackup plus jedes Inkrement bis zum Ziel", "effiziente Sicherung, längere/empfindlichere Restore-Kette"],
  ["differentiell", "Änderungen seit dem letzten Vollbackup", "wächst bis zum nächsten Vollbackup", "Vollbackup plus jüngstes Differential", "kürzere Restore-Kette, mehr Speicher als inkrementell"],
] as const;

const lessons: Record<string, BackupLesson> = {
  "backup-grundlagen-und-schutzziele": {
    objectives: ["Backup von Hochverfügbarkeit, Synchronisation und Archivierung unterscheiden", "typische Verlustursachen benennen", "RAID korrekt einordnen", "Wiederherstellbarkeit als Schutzziel erklären"],
    intro: <><p>Ein Backup ist eine getrennt verwaltete Datenkopie, aus der ein definierter Zustand wiederhergestellt werden kann. Sein Wert entsteht nicht beim Kopieren, sondern beim erfolgreichen Restore innerhalb der Anforderungen.</p></>,
    sections: [
      { title: "Wogegen ein Backup schützt", paragraphs: [<>Sicherungen können bei versehentlichem Löschen, logischer Beschädigung, Malware, Geräteausfall, Diebstahl oder Standortschaden helfen. Ob sie tatsächlich helfen, hängt von Kopien, Trennung, Versionen und Restore-Fähigkeit ab.</>, <>Ein Backup-Konzept benennt Datenumfang, Verantwortliche, Zeitplan, Aufbewahrung, Schutz, Überwachung und getestete Wiederherstellungsverfahren.</>], points: ["Vertraulichkeit: nur Berechtigte lesen Sicherungen", "Integrität: Daten und Metadaten sind unverändert nutzbar", "Verfügbarkeit/Wiederherstellbarkeit: Restore ist rechtzeitig möglich"] },
      { title: "Backup ist nicht Synchronisation oder Archiv", paragraphs: [<>Synchronisation hält Arbeitsstände auf mehreren Orten gleich und kann Löschung oder Verschlüsselung schnell übertragen. Versionierung kann helfen, ersetzt aber nur dann ein Backup, wenn Schutz- und Restore-Anforderungen erfüllt sind.</>, <>Archivierung dient langfristiger, oft rechtlich oder fachlich begründeter Aufbewahrung. Sie hat andere Such-, Unveränderbarkeits- und Fristanforderungen als eine betriebliche Sicherung.</>] },
      { title: "RAID ist kein Backup", paragraphs: [<>RAID kann je nach Level den Weiterbetrieb bei bestimmten Laufwerksausfällen ermöglichen. Es erhöht Verfügbarkeit beziehungsweise Fehlertoleranz innerhalb eines Systems.</>, <>Löschen, Ransomware, Dateikorruption, Controllerfehler, Diebstahl, Feuer oder Fehladministration können mehrere RAID-Daten gleichzeitig betreffen. Eine zeitlich und technisch getrennte Wiederherstellungskopie fehlt dann weiterhin.</>], note: <><strong>Prüfungsmerksatz:</strong> RAID beantwortet vor allem „Kann das Speichersystem trotz bestimmter Plattenfehler weiterarbeiten?“. Backup beantwortet „Können wir einen früheren Datenzustand wiederherstellen?“.</> },
    ],
    visual: <ResponsiveTable caption="Ähnliche Begriffe sauber trennen" headers={["Maßnahme", "Hauptzweck", "hilft typischerweise bei", "ersetzt Backup?"]} rows={[["RAID", "Verfügbarkeit bei bestimmten Datenträgerfehlern", "Ausfall einzelner Laufwerke je nach Level", "nein"], ["Replikation/Synchronisation", "zweite aktuelle Kopie/Betriebsfähigkeit", "Standort- oder Systemausfall je nach Design", "nicht automatisch"], ["Snapshot", "schneller Zustands-/Rollback-Punkt", "logische Rücksetzung je nach Technik", "nicht automatisch"], ["Backup", "wiederherstellbare getrennte Kopie", "definierte Verlustszenarien", "ist die eigene Schutzmaßnahme"]]} />,
    scenario: { title: "Ordner versehentlich gelöscht", situation: <p>Ein gespiegeltes RAID läuft fehlerfrei. Eine Administratorin löscht jedoch einen Projektordner; die Löschung wird sofort auf beide Spiegelplatten geschrieben.</p>, tasks: ["Warum hilft RAID hier nicht?", "Welche Eigenschaft der Sicherung wird gebraucht?"], solution: <p>RAID spiegelt den aktuellen Zustand einschließlich der Löschung. Benötigt wird eine getrennte, ausreichend alte Version mit passender Retention und ein erprobter Datei-Restore.</p> },
    takeaway: ["Backup bedeutet geplante Wiederherstellbarkeit, nicht nur eine zweite Kopie.", "RAID, Synchronisation, Snapshot und Archiv haben andere Hauptzwecke.", "Schutzumfang und Restore müssen zu realen Verlustszenarien passen."],
  },
  "voll-inkrementell-differentiell": {
    objectives: ["Voll-, inkrementelle und differentielle Sicherung erklären", "Sicherungsdauer und Speicherbedarf vergleichen", "Abhängigkeiten der Restore-Ketten erkennen", "eine Backup-Art begründet auswählen"],
    intro: <><p>Die drei Begriffe beschreiben, welcher Datenstand bei einem Lauf gesichert wird. Komprimierung, Deduplizierung oder herstellerspezifische „synthetic full“-Verfahren können reale Datenmengen verändern, ohne die logische Grundidee aufzuheben.</p></>,
    sections: [
      { title: "Vollbackup", paragraphs: [<>Ein Vollbackup enthält alle für diesen Sicherungssatz ausgewählten Daten. Die Sicherung benötigt meist viel Zeit, Speicher und Übertragungsbandbreite.</>, <>Der Restore ist übersichtlich, weil ein passender Vollstand genügt. Trotzdem müssen Katalog, Metadaten, Verschlüsselungsschlüssel und Anwendungskonsistenz verfügbar sein.</>] },
      { title: "Inkrementelles Backup", paragraphs: [<>Ein Inkrement sichert Änderungen seit der vorherigen Sicherung der Kette – je nach Produkt etwa seit Voll- oder letztem Inkrement. Tägliche Läufe sind meist klein und schnell.</>, <>Zur Wiederherstellung eines späteren Tages werden der Basis-Vollstand und alle nachfolgenden Inkremente bis zum Ziel benötigt. Ein fehlendes oder defektes Glied kann spätere Stände gefährden.</>] },
      { title: "Differentielles Backup", paragraphs: [<>Ein Differential sichert alle Änderungen seit dem letzten Vollbackup. Dadurch wächst seine Datenmenge im Verlauf der Woche.</>, <>Für den Restore genügen das Vollbackup und das jüngste passende Differential. Das reduziert Kettenabhängigkeiten gegenüber inkrementellen Läufen, kostet aber oft mehr Sicherungszeit und Speicher.</>], activity: <PracticeExercise exercise={backupExerciseDefinitions.strategyProperties} /> },
    ],
    visual: <ResponsiveTable caption="Logischer Vergleich der Backup-Arten" headers={["Art", "gespeichert", "Backup-Aufwand", "Restore benötigt", "Trade-off"]} rows={typeRows} />,
    scenario: { title: "Enges Nachtfenster", situation: <p>Ein Dateiserver hat werktags nur ein kurzes Sicherungsfenster. Das Team akzeptiert im Restore mehrere Sicherungssätze, testet diese Kette aber automatisiert und regelmäßig.</p>, tasks: ["Welche Art kann zum kurzen täglichen Fenster passen?", "Welche zusätzliche Abhängigkeit entsteht?"], solution: <p>Inkrementelle Backups können wegen kleiner täglicher Änderungsmengen passen. Der Restore hängt dann vom Vollbackup und jedem benötigten Inkrement ab. Die Entscheidung muss außerdem RTO, Speicher, Integritätsprüfung und Produktfunktionen berücksichtigen.</p> },
    takeaway: ["Voll sichert alles, inkrementell seit dem letzten Lauf, differentiell seit dem Vollbackup.", "Kleine Backup-Fenster können längere Restore-Ketten verursachen.", "Die passende Methode hängt von RPO, RTO, Datenmenge und Werkzeug ab."],
  },
  "restore-ketten-praktisch-planen": {
    objectives: ["inkrementelle und differentielle Restore-Ketten bestimmen", "einen Zielzeitpunkt aus einer Wochenzeitleiste ableiten", "Folgen fehlender Sicherungen erklären", "Restore-Reihenfolge dokumentieren"],
    intro: <><p>Für eine Wiederherstellung zählt nicht, wie viele Jobs grün angezeigt werden, sondern welche konsistente Kette den gewünschten Zeitpunkt enthält.</p></>,
    sections: [
      { title: "Wochenplan: inkrementell", paragraphs: [<>Montag entsteht ein Vollbackup. Dienstag enthält Inkrement I-Di nur Änderungen seit Montag, Mittwoch I-Mi Änderungen seit Dienstag und Donnerstag I-Do Änderungen seit Mittwoch.</>, <>Für den Stand Donnerstag werden in Reihenfolge benötigt: <strong>Voll Mo + I-Di + I-Mi + I-Do</strong>. Fehlt I-Mi, kann die normale Kette nicht einfach direkt mit I-Do fortgesetzt werden.</>], activity: <PracticeExercise exercise={backupExerciseDefinitions.incrementalRestore} /> },
      { title: "Wochenplan: differentiell", paragraphs: [<>Montag entsteht dasselbe Vollbackup. D-Di enthält Änderungen seit Montag; D-Mi enthält Änderungen von Dienstag und Mittwoch seit dem Vollbackup; D-Do enthält alle Änderungen seit Montag bis Donnerstag.</>, <>Für Donnerstag werden <strong>Voll Mo + D-Do</strong> benötigt. Die älteren Differentiale sind für genau diesen Restore nicht Teil der Kette.</>], activity: <PracticeExercise exercise={backupExerciseDefinitions.differentialRestore} /> },
      { title: "Zeitpunkt und Konsistenz", paragraphs: [<>„Stand Donnerstag“ muss präzisiert werden: direkt nach dem Backup oder vor einem Vorfall? Änderungen nach dem letzten erfolgreichen Lauf sind nicht in einer periodischen Sicherung enthalten.</>, <>Datenbanken und laufende VMs benötigen anwendungskonsistente Verfahren. Ein crash-konsistenter Zustand kann zwar technisch startbar sein, erfüllt aber nicht automatisch jede fachliche Restore-Anforderung.</>] },
    ],
    visual: <><ResponsiveTable caption="Sicherungswoche" headers={["Tag", "inkrementell", "differentiell"]} rows={[["Montag", "Voll Mo", "Voll Mo"], ["Dienstag", "I-Di: seit Mo", "D-Di: seit Mo"], ["Mittwoch", "I-Mi: seit Di", "D-Mi: seit Mo"], ["Donnerstag", "I-Do: seit Mi", "D-Do: seit Mo"]]} /><ResponsiveTable caption="Restore auf Donnerstag" headers={["Strategie", "benötigte Sicherungen", "Reihenfolge"]} rows={[["inkrementell", "Voll Mo, I-Di, I-Mi, I-Do", "vollständig chronologisch"], ["differentiell", "Voll Mo, D-Do", "Vollstand, dann jüngstes Differential"]]} /></>,
    scenario: { title: "Löschung am Donnerstagmittag", situation: <p>Die Sicherungen laufen täglich um 02:00 Uhr. Ein Ordner wird Donnerstag um 13:00 Uhr gelöscht. Ziel ist der jüngste gesicherte Zustand vor der Löschung.</p>, tasks: ["Welche Donnerstag-Sicherung ist relevant?", "Welche Kette braucht die inkrementelle Strategie?", "Welche Daten können fehlen?"], solution: <p>Relevant ist der Lauf Donnerstag 02:00 Uhr. Inkrementell: Voll Mo plus Di, Mi und Do. Änderungen zwischen Donnerstag 02:00 und 13:00 liegen bei diesem Tagesplan außerhalb der Sicherung und können verloren sein; das beschreibt die tatsächliche Recovery-Point-Lücke.</p> },
    takeaway: ["Inkrementell braucht jedes Kettenglied bis zum Ziel.", "Differentiell braucht Vollstand plus jüngstes Differential.", "Zielzeitpunkt, Anwendungskonsistenz und letzte erfolgreiche Sicherung müssen dokumentiert sein."],
  },
  "datei-image-und-snapshot": {
    objectives: ["Datei- und Image-Backup unterscheiden", "Snapshot-Arten einordnen", "erklären, warum ein Snapshot nicht automatisch ein Backup ist", "eine Sicherungsebene passend zum Restore wählen"],
    intro: <><p>Backup-Arten wie voll oder inkrementell beschreiben den Änderungsumfang. Datei, Image und Snapshot beschreiben dagegen eher Ebene beziehungsweise Technik. Diese Achsen können kombiniert werden.</p></>,
    sections: [
      { title: "Datei- und Verzeichnis-Backup", paragraphs: [<>Ein Datei-Backup schützt ausgewählte Dateien, Ordner und Metadaten. Einzelne Dokumente lassen sich oft schnell finden und zurückholen.</>, <>Ein vollständiger Systemwiederaufbau benötigt zusätzlich Betriebssystem, Anwendungen, Konfiguration und Bootinformationen. Nicht jede geöffnete Datenbank ist durch reines Dateikopieren konsistent gesichert.</>] },
      { title: "Image-/System-Backup", paragraphs: [<>Ein Image erfasst Datenträger, Volumes oder eine ganze Maschine einschließlich systemnaher Strukturen. Das kann Bare-Metal- oder VM-Wiederherstellung beschleunigen.</>, <>Images können größer und weniger granular sein. Treiber, Hardwareunterschiede, Hypervisorintegration und Anwendungskonsistenz bleiben zu planen.</>] },
      { title: "Snapshot ist nicht automatisch Backup", paragraphs: [<>VM-, Dateisystem- oder Storage-Snapshots markieren einen Zustand und nutzen häufig Copy-on-Write beziehungsweise Speicherreferenzen. Sie ermöglichen schnelle Rollbacks und können eine Backup-Erstellung unterstützen.</>, <>Bleibt der Snapshot jedoch auf demselben Storage, schützt er nicht vor dessen Ausfall, Diebstahl oder Zerstörung. Auch Ransomware oder kompromittierte Administrationskonten können erreichbare Snapshots löschen oder verschlüsseln.</>], note: <><strong>Entscheidender Test:</strong> Gibt es eine unabhängig geschützte Kopie auf einer eigenen Fehler- und Sicherheitsdomäne? Falls nein, ist der Snapshot allein kein belastbares Backup.</>, activity: <PracticeExercise exercise={backupExerciseDefinitions.protectionClassification} /> },
    ],
    visual: <ResponsiveTable caption="Sicherungsebenen vergleichen" headers={["Technik", "gute Eignung", "Grenze", "Backup nur wenn …"]} rows={[["Datei-Backup", "granularer Datei-Restore", "Systemaufbau separat", "Kopie getrennt, geschützt und restorable"], ["Image/System", "gesamte Maschine/Volume", "Größe und Plattformabhängigkeit", "Wiederherstellung geprüft"], ["VM-Snapshot", "kurzer Rollback/Backup-Quiescing", "Abhängigkeit vom VM-Storage", "extern übertragen und geschützt"], ["Storage-/FS-Snapshot", "schneller lokaler Zeitpunkt", "gleiche Storage-Fehlerdomäne möglich", "unabhängige Kopie vorhanden"]]} />,
    scenario: { title: "VM-Snapshots auf demselben Datastore", situation: <p>Alle virtuellen Server besitzen tägliche Snapshots. Die VM-Dateien und Snapshots liegen ausschließlich auf einem Storage-System.</p>, tasks: ["Welches Risiko bleibt?", "Wie wird daraus ein belastbareres Backup-Konzept?"], solution: <p>Der Ausfall oder die Kompromittierung des Storage kann Originale und Snapshots gleichzeitig treffen. Benötigt wird eine getrennte, geschützte Kopie – idealerweise mit Offsite-/Offline-/Immutability-Eigenschaften – sowie geprüfte VM- und Anwendungs-Restores.</p> },
    takeaway: ["Datei und Image bedienen unterschiedliche Restore-Ebenen.", "Snapshots sind wertvolle Werkzeuge, aber nicht automatisch unabhängige Sicherungen.", "Die Fehlerdomäne der Kopie entscheidet über ihren Schutzwert."],
  },
  "backup-strategien-321": {
    objectives: ["3-2-1 erklären und anwenden", "3-2-1-1-0 einordnen", "Offsite, Offline, Air Gap und immutable unterscheiden", "gemeinsame Fehlerdomänen erkennen"],
    intro: <><p>Die 3-2-1-Regel ist eine robuste Planungsheuristik: drei Datenkopien insgesamt, auf zwei unterschiedlichen Speicherarten oder -systemen, davon eine Kopie extern beziehungsweise offsite.</p></>,
    sections: [
      { title: "3-2-1 praktisch lesen", paragraphs: [<>Die Produktionsdaten zählen als erste Kopie, zwei weitere sind Sicherungskopien. „Zwei Medien“ soll gemeinsame technische Fehler reduzieren; moderne Interpretationen betrachten eher unabhängige Speicher- und Fehlerdomänen als zwingend zwei physische Medientypen.</>, <>Offsite schützt vor Standortschäden wie Brand oder Diebstahl. Eine Cloud-Kopie ist nur dann unabhängig, wenn Konto, Region, Berechtigungen, Löschschutz und Exit-/Restore-Pfad passend gestaltet sind.</>] },
      { title: "Die Erweiterung 3-2-1-1-0", paragraphs: [<>Die zusätzliche 1 steht für mindestens eine offline, air-gapped oder unveränderbare (immutable) Kopie. Diese Begriffe sind nicht identisch: offline ist nicht erreichbar, Air Gap beschreibt eine starke Trennung, immutable verhindert Änderungen innerhalb definierter Regeln/Fristen.</>, <>Die 0 steht für null ungeklärte Fehler nach automatisierten Prüfungen und Restore-Verifikation. Sie ist ein Qualitätsziel, keine Garantie, dass jeder denkbare Restore immer gelingt.</>], activity: <PracticeExercise exercise={backupExerciseDefinitions.ruleAssessment} /> },
      { title: "Trennung gegen Ransomware", paragraphs: [<>Sicherungen, die dauerhaft mit denselben Produktions-Administratorrechten beschreibbar sind, können mitkompromittiert werden. Separate Konten, Least Privilege, MFA wo passend, Löschschutz und getrennte Managementpfade reduzieren das Risiko.</>, <>Auch offline oder immutable Kopien benötigen Verschlüsselung, Schlüsselmanagement, Aufbewahrung, Monitoring und regelmäßige Wiederherstellungstests.</>] },
    ],
    visual: <TextFlow caption="3-2-1-1-0 als Prüfkette" steps={["3 Kopien", "2 Fehlerdomänen", "1 offsite", "1 offline/immutable", "0 ungeklärte Prüffehler"]} />,
    scenario: { title: "NAS und Produktionsdomäne", situation: <p>Server sichern nachts auf ein NAS. Das NAS ist mit denselben Domänen-Admin-Zugangsdaten dauerhaft beschreibbar und steht im selben Brandabschnitt.</p>, tasks: ["Welche gemeinsamen Risiken bestehen?", "Welche 3-2-1-1-0-Maßnahmen helfen?"], solution: <p>Ransomware/Accountkompromittierung und Standortschaden können beide Kopien treffen. Sinnvoll sind getrennte Backup-Identitäten, Least Privilege, eine Offsite-Kopie und eine offline oder immutable geschützte Version sowie verifizierte Restore-Tests. Die konkrete Architektur hängt von Anforderungen und Budget ab.</p> },
    takeaway: ["3-2-1 verteilt Kopien über unabhängige Orte und Systeme.", "3-2-1-1-0 ergänzt Widerstandsfähigkeit und Verifikation.", "Zählregeln ersetzen keine Analyse gemeinsamer Konten, Standorte und Fehlerdomänen."],
  },
  "aufbewahrung-rotation-und-gfs": {
    objectives: ["Retention und Versionierung unterscheiden", "Backup-Rotation erklären", "GFS praktisch anwenden", "Aufbewahrung aus Anforderungen ableiten"],
    intro: <><p><strong>Retention</strong> beschreibt, wie lange Sicherungspunkte aufbewahrt werden. Versionierung hält mehrere Zustände eines Objekts. Rotation legt fest, welche Sicherungssätze wann wiederverwendet, gelöscht oder länger behalten werden.</p></>,
    sections: [
      { title: "Warum mehrere Zeitstände?", paragraphs: [<>Ein Fehler kann erst Wochen später auffallen. Wenn alle täglichen Sicherungen nach sieben Tagen verschwinden, ist ein älterer intakter Zustand nicht mehr verfügbar.</>, <>Längere Aufbewahrung kostet Speicher und erhöht den Umfang geschützter personenbezogener oder vertraulicher Daten. Fachliche, rechtliche und Löschanforderungen müssen gemeinsam bewertet werden.</>] },
      { title: "Grandfather-Father-Son (GFS)", paragraphs: [<>GFS kombiniert häufig tägliche „Sons“, wöchentliche „Fathers“ und monatliche „Grandfathers“. Beispiel: sieben tägliche Stände, vier Wochenstände und zwölf Monatsstände.</>, <>Welche Wochentage, Monatsstände und Fristen gelten, ist eine Designentscheidung. GFS ist kein Pflichtstandard und garantiert allein weder Offsite-Schutz noch funktionierende Restores.</>], activity: <PracticeExercise exercise={backupExerciseDefinitions.gfs} /> },
      { title: "Rotation sicher betreiben", paragraphs: [<>Löschung alter Sätze muss mit Abhängigkeiten von Voll-, Differential- und Inkrementketten abgestimmt sein. Ein benötigtes Basisbackup darf nicht vor seinen abhängigen Ständen entfernt werden.</>, <>Katalog, Kennzeichnung, Medienzustand, Verschlüsselungsschlüssel und dokumentierte Restore-Reihenfolge gehören zur Aufbewahrung. Monitoring muss erkennen, wenn erwartete Generationen fehlen.</>] },
    ],
    visual: <ResponsiveTable caption="Beispiel einer GFS-Rotation" headers={["Generation", "Beispiel", "Aufbewahrung", "Zweck"]} rows={[["Son", "täglicher Stand Mo–So", "7 Tage", "kurzfristige granulare Wiederherstellung"], ["Father", "Sonntags-/Wochenstand", "4 Wochen", "mittlere Zeitstände"], ["Grandfather", "letzter Monatsstand", "12 Monate", "langfristigere Monatsstände"]]} />,
    scenario: { title: "Fehler nach fünf Wochen entdeckt", situation: <p>Eine Datei wurde vor fünf Wochen beschädigt. Es existieren sieben Tages-, vier Wochen- und zwölf Monatsstände.</p>, tasks: ["Warum reichen Tagesstände nicht?", "Welcher GFS-Stand könnte helfen?", "Was muss zusätzlich geprüft werden?"], solution: <p>Die Tagesstände reichen nur eine Woche zurück, Wochenstände hier vier Wochen. Ein Monatsstand vor der Beschädigung könnte passen. Zu prüfen sind exakter Zeitpunkt, Inhalt, Kettenintegrität, Schlüssel und ob der Restore testweise isoliert möglich ist.</p> },
    takeaway: ["Retention bestimmt die verfügbare Zeitreise.", "GFS ist eine optionale Rotation aus Tages-, Wochen- und Monatsgenerationen.", "Aufbewahrung muss Ketten, Schutz, Kosten und Löschpflichten berücksichtigen."],
  },
  "rpo-und-rto": {
    objectives: ["RPO und RTO korrekt definieren", "beide Ziele voneinander unterscheiden", "Anforderungen in Sicherungs- und Restore-Maßnahmen übersetzen", "Szenarien mit realistischen Zielwerten bewerten"],
    intro: <><p><strong>Recovery Point Objective (RPO)</strong> beschreibt den maximal akzeptierten Datenverlust als Zeitraum. <strong>Recovery Time Objective (RTO)</strong> beschreibt die maximal akzeptierte Zeit bis zur Wiederherstellung des Dienstes oder Prozesses.</p></>,
    sections: [
      { title: "RPO: Bis zu welchem Datenstand?", paragraphs: [<>Bei einem täglich um 02:00 Uhr erfolgreichen Backup kann ein Ausfall kurz vor dem nächsten Lauf annähernd 24 Stunden Änderungen kosten. Ein RPO von vier Stunden würde zusätzliche Sicherungs-, Replikations- oder Journalverfahren erfordern.</>, <>RPO ist eine Geschäftsanforderung, nicht einfach die Jobfrequenz. Ob ein 24-Stunden-Plan das Ziel erfüllt, hängt von Laufzeit, Erfolgsquote, Transaktionsschutz und gewünschtem Wiederherstellungspunkt ab.</>] },
      { title: "RTO: Wie schnell wieder arbeitsfähig?", paragraphs: [<>RTO umfasst Erkennung, Entscheidung, Bereitstellung, Datenübertragung, Wiederherstellung, Prüfungen und Freigabe. Ein schnelles Kopieren allein erfüllt kein RTO, wenn anschließend Datenbank- oder Anwendungstests Stunden dauern.</>, <>Große Offsite-Bestände können ein gutes RPO haben, aber über eine langsame Leitung ein schlechtes RTO. Lokale Restore-Caches können beschleunigen, benötigen aber weiterhin getrennte Schutzkopien.</>] },
      { title: "Anforderungen priorisieren", paragraphs: [<>Nicht jeder Dienst braucht dieselben Werte. Zeiterfassung, Dateifreigabe und Archiv können unterschiedliche Auswirkungen bei Datenverlust und Ausfall haben.</>, <>Ziele müssen messbar, mit Verantwortlichen abgestimmt und regelmäßig durch Restore- beziehungsweise Notfalltests validiert werden.</>], note: <><strong>Nicht verwechseln:</strong> RPO fragt nach dem tolerierten Datenstand-Verlust. RTO fragt nach der tolerierten Wiederanlaufdauer.</>, activity: <PracticeExercise exercise={backupExerciseDefinitions.rpoRto} /> },
    ],
    visual: <ResponsiveTable caption="RPO und RTO in einem Vorfall" headers={["Ziel", "Leitfrage", "Beispielanforderung", "technische Folge"]} rows={[["RPO", "Wie weit darf der letzte nutzbare Stand zurückliegen?", "maximal 4 Stunden Datenverlust", "häufigere/fortlaufende Recovery Points"], ["RTO", "Wie lange darf der Dienst ausfallen?", "innerhalb 2 Stunden nutzbar", "schneller Restorepfad, Runbook, Kapazität und Tests"]]} />,
    scenario: { title: "Dateiserver und Produktionssystem", situation: <p>Für den Dateiserver sind 24 Stunden Datenverlust und 12 Stunden Ausfall akzeptabel. Das Produktionssystem toleriert nur 15 Minuten Datenverlust und 1 Stunde Ausfall.</p>, tasks: ["Welche Ziele sind strenger?", "Kann derselbe Tagesbackup-Plan beide erfüllen?", "Welche Nachweise braucht die Planung?"], solution: <p>Das Produktionssystem hat RPO 15 Minuten und RTO 1 Stunde und ist deutlich strenger. Ein einfacher Tageslauf kann dessen RPO nicht erfüllen. Benötigt werden passend häufige Recovery Points und ein durch Tests belegter Restore-/Failoverpfad innerhalb einer Stunde.</p> },
    takeaway: ["RPO begrenzt Datenverlust, RTO die Wiederanlaufzeit.", "Backup-Häufigkeit allein definiert kein garantiertes RPO.", "Beide Werte müssen fachlich festgelegt und technisch getestet werden."],
  },
  "backup-sicherheit-und-restore-tests": {
    objectives: ["Sicherungen gegen Ransomware und Missbrauch schützen", "Least Privilege und getrennte Identitäten anwenden", "Integrität, Monitoring und Verschlüsselung einordnen", "Restore-Tests fachlich planen"],
    intro: <><p>Eine Sicherung ist ein hochsensibler Datenbestand und ein attraktives Angriffsziel. Sie benötigt mindestens ebenso sorgfältige Zugriffskontrollen, Überwachung und Lebenszyklusregeln wie die Produktionsdaten.</p></>,
    sections: [
      { title: "Berechtigungen und Isolation", paragraphs: [<>Backup-Dienste sollten separate, minimal berechtigte Identitäten verwenden. Produktionsadministratoren benötigen nicht automatisch Löschrechte auf immutable oder offline Kopien; Backup-Systeme sollten nicht unnötig in dieselbe Vertrauensdomäne eingebunden sein.</>, <>MFA, getrennte Managementzugänge, Netzwerksegmentierung, verzögerter/Löschschutz und Vier-Augen-Prozesse können je nach Risiko helfen. Kein einzelner Mechanismus ist absolut.</>] },
      { title: "Verschlüsselung und Schlüssel", paragraphs: [<>Verschlüsselung schützt Sicherungen bei Transport und Speicherung. Die Schlüssel müssen getrennt, verfügbar, gesichert und mit geregeltem Zugriff verwaltet werden.</>, <>Ein perfekt verschlüsseltes Backup ohne verfügbaren Schlüssel ist nicht wiederherstellbar. Umgekehrt darf ein Schlüssel nicht ungeschützt neben dem Medium liegen.</>] },
      { title: "Monitoring, Integrität und Restore-Test", paragraphs: [<>Überwache nicht nur Jobstatus, sondern Datenmenge, Laufzeit, erwartete Systeme, Repositories, Kapazität, Unveränderbarkeit und Prüfsummen beziehungsweise Produktintegrität.</>, <>Ein grüner Job beweist keinen erfolgreichen Restore. Teste Datei-, VM-, System- und Anwendungsszenarien in kontrollierter Umgebung, dokumentiere Dauer und Abweichungen und korrigiere Runbooks.</>], note: <><strong>Leitsatz:</strong> Ein Backup ist erst dann wirklich vertrauenswürdig, wenn die Wiederherstellung geprüft wurde.</>, activity: <PracticeExercise exercise={backupExerciseDefinitions.restoreSecurity} /> },
    ],
    visual: <TextFlow caption="Vom Job zur belastbaren Wiederherstellung" steps={["Backup überwachen", "Integrität prüfen", "isoliert wiederherstellen", "Anwendung validieren", "Ergebnis dokumentieren"]} />,
    scenario: { title: "Alle Jobs grün, Restore scheitert", situation: <p>Das Dashboard meldet seit Monaten erfolgreiche Läufe. Beim ersten echten Restore fehlt jedoch der benötigte Verschlüsselungsschlüssel.</p>, tasks: ["Warum war der Jobstatus unzureichend?", "Welche Kontrolle hätte das Problem entdeckt?"], solution: <p>Der Job prüfte offenbar nur das Schreiben der Daten, nicht den vollständigen Restorepfad. Ein regelmäßiger isolierter Test einschließlich Schlüsselabruf, Katalog, Berechtigungen und Anwendungsvalidierung hätte die Lücke sichtbar gemacht.</p> },
    takeaway: ["Backup-Identitäten und Löschrechte gehören von Produktion getrennt.", "Verschlüsselung braucht belastbares Schlüsselmanagement.", "Monitoring und echte Restore-Tests prüfen unterschiedliche Teile derselben Schutzkette."],
  },
  "backup-praxis": {
    objectives: ["Anforderungen eines kleinen Unternehmens erfassen", "Backup-Arten und -ebenen kombinieren", "RPO, RTO, Retention und Schutz begründen", "Restore-Test und Betrieb dokumentieren"],
    intro: <><p>Die Beispiel GmbH betreibt einen Windows-Dateiserver, drei virtuelle Fachanwendungsserver, ein NAS und 35 Arbeitsplätze. Dateiänderungen sind geschäftskritisch; ein längerer Produktionsstillstand verursacht hohe Kosten.</p></>,
    sections: [
      { title: "1. Schutzbedarf und Ziele", paragraphs: [<>Erfasse Datenbesitzer, Datenmenge, Änderungsrate, Abhängigkeiten und Folgen eines Verlusts. Vereinbare für Dateifreigaben und jede VM konkrete RPO-/RTO-Werte.</>, <>Beispiel: Dateifreigaben RPO vier Stunden/RTO acht Stunden, Fachanwendung RPO eine Stunde/RTO vier Stunden. Diese Werte sind Annahmen und müssen vom Unternehmen bestätigt werden.</>], points: ["Welche Daten und Systeme sind im Scope?", "Welche Reihenfolge gilt im Notfall?", "Welche Compliance-/Löschfristen bestehen?", "Wer darf einen Restore freigeben?"] },
      { title: "2. Sicherungs- und Aufbewahrungsplan", paragraphs: [<>Ein möglicher Entwurf kombiniert wöchentliche Voll- und tägliche inkrementelle Sicherungen, häufigere anwendungskonsistente Recovery Points für kritische VMs und Datei-Versionen. Eine andere Kombination kann ebenso begründbar sein.</>, <>Plane Retention passend zu Fehlerentdeckungszeit und Regeln, beispielsweise Tages-, Wochen- und Monatsstände. Stelle sicher, dass Basis und abhängige Ketten gemeinsam aufbewahrt werden.</>] },
      { title: "3. Trennung und Sicherheit", paragraphs: [<>Das lokale NAS ermöglicht schnelle Restores, ist aber allein unzureichend. Ergänze eine offsite Kopie und eine offline oder immutable Generation, getrennte Backup-Identitäten und geschütztes Schlüsselmanagement.</>, <>Prüfe gemeinsame Strom-, Brand-, Konto-, Netzwerk- und Providerabhängigkeiten. RAID im NAS verbessert je nach Level Verfügbarkeit, ersetzt die externen Versionen nicht.</>] },
      { title: "4. Betrieb und Tests", paragraphs: [<>Definiere Monitoring, Eskalation und Kapazitätsplanung. Teste monatlich Stichproben einzelner Dateien und regelmäßig vollständige VM-/Anwendungs-Restores in isolierter Umgebung.</>, <>Messe dabei die tatsächliche Dauer gegen RTO, prüfe Datenstand gegen RPO und aktualisiere Runbooks, Kontakte und Abhängigkeiten.</>] },
    ],
    visual: <ResponsiveTable caption="Nicht-persistente Konzeptvorlage" headers={["Bereich", "geplanter Zustand", "Begründung/Evidenz", "nächste Prüfung"]} rows={[["Scope", "Dateifreigaben, VMs, Konfiguration", "Schutzbedarfsanalyse", "Vollständigkeit mit Datenverantwortlichen"], ["RPO/RTO", "je Dienst festlegen", "Ausfallkosten und Änderungsrate", "Restore-Test"], ["Kopien", "lokal + offsite + offline/immutable", "3-2-1-1-0", "Unabhängigkeit und Löschschutz"], ["Retention", "Tages-/Wochen-/Monatsstände", "Entdeckungszeit und Regeln", "Ketten und Löschfristen"], ["Sicherheit", "separate Identitäten, Verschlüsselung", "Ransomware-/Datenschutzrisiko", "Rechte- und Schlüsseltest"], ["Restore", "Datei, VM, Anwendung", "Runbook und Messwerte", "regelmäßiger Testplan"]]} />,
    scenario: { title: "Ransomware am Mittwoch", situation: <p>Am Mittwochmorgen werden Dateifreigaben und erreichbare NAS-Freigaben verschlüsselt. Eine Fachanwendung ist ebenfalls betroffen.</p>, tasks: ["Welche Kopie darf nicht mitbetroffen sein?", "Welche Recovery-Ziele steuern die Reihenfolge?", "Welche Evidenz wird vor dem Restore benötigt?"], solution: <p>Eine getrennte offsite und insbesondere offline/immutable geschützte Generation sollte außerhalb des kompromittierten Schreibpfads liegen. RPO bestimmt den gewählten sauberen Stand, RTO und Geschäftspriorität die Reihenfolge. Benötigt werden Vorfallszeitlinie, letzter nachweislich sauberer Recovery Point, Integritäts-/Malwareprüfung, verfügbare Schlüssel, isolierter Restorepfad und Freigabe. Mehrere konkrete Architekturen können diese Anforderungen erfüllen.</p> },
    takeaway: ["Ein Backup-Konzept beginnt mit Geschäftsanforderungen und Restore-Zielen.", "Lokale schnelle und getrennte widerstandsfähige Kopien ergänzen sich.", "Der Plan ist erst belastbar, wenn vollständige Restores gemessen und dokumentiert wurden."],
  },
};

export function BackupLesson({ lessonSlug }: { lessonSlug: string }) {
  const lesson = lessons[lessonSlug];
  if (!lesson) return null;
  return <FundamentalsLesson lessonId={`backup-${lessonSlug}`} {...lesson} relatedLinks={[{ href: "/lernen/storage-und-raid", label: "Storage & RAID: Verfügbarkeit ist kein Backup" }]}>{lesson.visual}</FundamentalsLesson>;
}

export const backupLessonSlugs = Object.freeze(Object.keys(lessons));
