import type { ReactNode } from "react";
import { FundamentalsLesson, ResponsiveTable, TextFlow, type LessonSection } from "./fundamentals-lesson-elements";
import { SingleChoiceCheck } from "./single-choice-check";

type LessonContent = { objectives: readonly string[]; intro: ReactNode; sections: readonly LessonSection[]; visual?: ReactNode; scenario: { title: string; situation: ReactNode; tasks: readonly ReactNode[]; solution: ReactNode }; takeaway: readonly ReactNode[]; relatedLinks?: readonly { href: string; label: string }[] };

const lessons: Record<string, LessonContent> = {
  "kundenbedarf-und-anforderungen": {
    objectives: ["Kundenwunsch und tatsächlichen Bedarf unterscheiden", "offene, geschlossene und klärende Fragen einsetzen", "funktionale und nicht-funktionale Anforderungen trennen"],
    intro: <p>„Wir brauchen einen schnellen Server“ ist ein Gesprächseinstieg, noch keine prüfbare Anforderung. Gute Bedarfsermittlung klärt Nutzer, Aufgabe, Randbedingungen und Erfolgskriterien.</p>,
    sections: [
      { title: "Vom Wunsch zur Anforderung", paragraphs: [<>Ein Stakeholder ist betroffen oder beeinflusst die Lösung; Anwender sind eine wichtige Stakeholdergruppe. Ihre Arbeitsabläufe, Risiken und Barrieren werden beobachtbar beschrieben.</>, <>Funktionale Anforderungen sagen, was das System leisten soll. Nicht-funktionale Anforderungen beschreiben Qualitäts- und Randbedingungen wie Verfügbarkeit, Leistung, Barrierefreiheit, Sicherheit, Datenschutz und Wartbarkeit.</>], activity: <SingleChoiceCheck title="Anforderung einordnen" question="Der Dateidienst muss werktags von 7 bis 19 Uhr mindestens 99,5 % verfügbar sein. Welche Art ist das?" inputName="customer-requirement" correctOptionId="non-functional" successMessage="Verfügbarkeit ist eine messbare nicht-funktionale Anforderung." options={[{id:"functional",label:"funktionale Anforderung",explanation:"Sie beschreibt hier keine Fachfunktion."},{id:"non-functional",label:"nicht-funktionale Anforderung",explanation:"Richtig."},{id:"implementation",label:"konkrete Implementierung",explanation:"Noch ist kein Produkt oder Aufbau festgelegt."},{id:"wish",label:"nur ein unprüfbarer Wunsch",explanation:"Zeitraum und Messgröße machen sie prüfbar."}]} /> },
      { title: "Fragen passend kombinieren", paragraphs: [<>Offene Fragen erkunden Abläufe: „Wie bearbeiten Sie heute Rechnungen?“ Geschlossene Fragen bestätigen Fakten: „Benötigen alle sechs Personen Zugriff?“ Klärende Fragen lösen Mehrdeutigkeit: „Was bedeutet ‚schnell‘ in Sekunden?“</>, <>Keine Frageart ist grundsätzlich besser. Offene Fragen schaffen Breite, geschlossene sichern Entscheidungen ab; Antworten werden zusammengefasst und vom Gegenüber bestätigt.</>] },
    ],
    visual: <TextFlow caption="Bedarfsermittlung" steps={["Stakeholder/Ablauf", "offen erkunden", "Details klären", "Anforderungen formulieren", "Verständnis bestätigen"]} />,
    scenario: { title: "Fileservice für sechs Personen", situation: <p>„Wir brauchen einen sicheren gemeinsamen Ordner, der immer funktioniert.“</p>, tasks: ["Formuliere drei klärende Fragen.", "Nenne je eine funktionale und nicht-funktionale Anforderung."], solution: <p>Fragen betreffen Rollen/Dateien, benötigte Zeiten, Datenmenge, Wiederherstellung und externen Zugriff. Funktional: berechtigte Nutzer speichern und versionieren Dateien. Nicht-funktional: definierte Verfügbarkeit und Wiederherstellungsziel.</p> },
    takeaway: ["Ein Wunsch wird erst durch Klärung prüfbar.", "Funktion beschreibt das Was, nicht-funktionale Anforderungen die Qualität/Randbedingung.", "Fragearten ergänzen sich."],
    relatedLinks: [{href:"/lernen/projektmanagement/phasen-arbeitspakete-und-anforderungen",label:"Projektmanagement: Lasten- und Pflichtenheft"}],
  },
  "anforderungen-priorisieren": {
    objectives: ["Muss, Soll und Kann nachvollziehbar priorisieren", "Anforderung und Lösung trennen", "Änderungen mit Stakeholdern dokumentieren"],
    intro: <p>Priorisierung macht Zielkonflikte sichtbar. Sie ist eine vereinbarte Entscheidung über Bedeutung, keine spontane Bewertung durch die Technik.</p>,
    sections: [
      { title: "Muss, Soll und Kann", paragraphs: [<>Muss-Anforderungen sind für Akzeptanz oder Betrieb zwingend. Soll-Anforderungen haben hohen Nutzen, können aber begründet verschoben werden. Kann- beziehungsweise Nice-to-have-Anforderungen sind optional.</>, <>Begriffe und Entscheidungsregeln werden im Auftrag definiert. Eine hohe Priorität ersetzt keine genaue Messgröße und kein Abnahmekriterium.</>], activity: <SingleChoiceCheck title="Bedarf oder Lösung?" question="Welche Formulierung beschreibt eine Anforderung ohne vorschnell ein Produkt festzulegen?" inputName="customer-solution" correctOptionId="need" successMessage="Die Anforderung benennt Nutzer, Funktion und messbare Reaktionszeit." options={[{id:"product",label:"Es muss Produkt X auf Server Y sein.",explanation:"Das legt eine Umsetzung fest, ohne den Bedarf zu erklären."},{id:"need",label:"Sechs Berechtigte müssen Belege innerhalb von zwei Sekunden finden können.",explanation:"Richtig."},{id:"brand",label:"Der Kunde möchte eine bekannte Marke.",explanation:"Das ist zunächst ein Wunsch."},{id:"vague",label:"Das System soll modern sein.",explanation:"Das ist nicht prüfbar."}]} /> },
      { title: "Lösungsvorschläge getrennt halten", paragraphs: [<>„Neue Workstation für die Buchhaltung“ kann mehrere Anforderungen enthalten: Fachsoftware, zwei Monitore, Kartenleser, barrierearme Eingabe und definierte Antwortzeit. CPU, Modell und Betriebssystem sind Lösungselemente, sofern sie nicht selbst begründete Randbedingungen sind.</>, <>Ändern sich Prioritäten, werden Auswirkung, Entscheidung, Verantwortliche und neue Abnahmekriterien dokumentiert.</>] },
    ],
    visual: <ResponsiveTable caption="Beispielpriorisierung" headers={["Aussage", "Einordnung", "Begründung"]} rows={[["Fachsoftware startet","Muss","Arbeitsprozess sonst unmöglich"],["Belege ≤ 2 s","Soll/Muss nach Geschäftskritik","messbares Leistungsziel"],["drittes Display","Kann","Komfortnutzen, nicht zwingend"],["Modellname Z","Lösungsvorschlag","Bedarf dahinter klären"]]} />,
    scenario: { title: "Buchhaltungsarbeitsplatz", situation: <p>Budget ist begrenzt. Pflicht sind Fachsoftware, Smartcard und Bedienhilfe; gewünscht sind drei Monitore und ein bestimmtes Notebookmodell.</p>, tasks: ["Priorisiere die Aussagen.", "Welche davon sind Lösungen statt Anforderungen?"], solution: <p>Fachfunktion, Smartcard-Kompatibilität und benötigte Bedienhilfe sind Muss. Monitoranzahl wird am Ablauf begründet; das konkrete Notebook ist zunächst ein Lösungsvorschlag.</p> },
    takeaway: ["Priorität wird begründet und vereinbart.", "Anforderung und Implementierung bleiben getrennt.", "Jede wichtige Anforderung braucht ein prüfbares Kriterium."],
    relatedLinks: [{href:"/lernen/arbeitsplatz-hardware/arbeitsplatz-auswaehlen",label:"Hardware: Arbeitsplatz auswählen"}],
  },
  "kundenkommunikation-und-fachinformationen": {
    objectives: ["zielgruppengerecht ohne unnötigen Jargon erklären", "Feedback und Vier-Seiten-Modell praktisch nutzen", "relevante Fakten aus technischen Kurztexten entnehmen"],
    intro: <p>Professionelle Kommunikation zeigt sich nicht an möglichst vielen Fachwörtern, sondern an gemeinsamer, dokumentierter Bedeutung.</p>,
    sections: [
      { title: "Senden, empfangen, rückkoppeln", paragraphs: [<>Im Sender-Empfänger-Modell wird eine Nachricht codiert, über einen Kanal übermittelt und vom Empfänger interpretiert. Rückfragen und Zusammenfassung prüfen, ob dieselbe Bedeutung angekommen ist.</>, <>Das Vier-Seiten-/Vier-Ohren-Modell betrachtet Sachinhalt, Selbstoffenbarung, Beziehung und Appell. Es hilft, Missverständnisse zu reflektieren, diagnostiziert aber nicht automatisch die Absicht einer Person.</>], activity: <SingleChoiceCheck title="Verständnis sichern" question="Welche Reaktion prüft das gemeinsame Verständnis am besten?" inputName="customer-feedback" correctOptionId="summary" successMessage="Eine Zusammenfassung mit Bestätigung schafft überprüfbares Feedback." options={[{id:"jargon",label:"Noch mehr Fachbegriffe verwenden.",explanation:"Das kann die Hürde erhöhen."},{id:"summary",label:"Vereinbarung in eigenen Worten zusammenfassen und bestätigen lassen.",explanation:"Richtig."},{id:"assume",label:"Schweigen als Zustimmung werten.",explanation:"Schweigen belegt kein Verständnis."},{id:"repeat",label:"Denselben Satz lauter wiederholen.",explanation:"Das klärt Mehrdeutigkeit nicht."}]} /> },
      { title: "Technische Fakten statt Vollübersetzung", paragraphs: [<>Ein Datenblatt wird nach den benötigten Fakten gelesen: „minimum 16 GB RAM“, „supports SSO via SAML“, „three-year security update policy“ und „export in CSV format“ benennen Mindestressource, Authentisierungsschnittstelle, Pflegezeitraum und Exportmöglichkeit.</>, <>Unklare Begriffe werden im Kontext geprüft. Eine Marketingaussage wie „enterprise ready“ ist keine messbare Spezifikation.</>] },
    ],
    visual: <ResponsiveTable caption="Technical English gezielt auswerten" headers={["Textausschnitt", "relevanter Fakt", "offene Frage"]} rows={[["requires 16 GB RAM","Mindest-RAM 16 GB","gilt je Client/Server?"],["supports SAML SSO","SAML-basierte Anmeldung möglich","welche Rollen/IdP-Version?"],["99.9% monthly availability target","monatliches Verfügbarkeitsziel","Messpunkt/Ausschlüsse?"],["export available","Export vorhanden","Format, Vollständigkeit, Rechte?"]]} />,
    scenario: { title: "Technische Produktbeschreibung", situation: <p>„Hosted service; supports CSV export and SAML SSO; retention configurable up to 365 days; mobile client requires Android 14 or later.“</p>, tasks: ["Entnimm vier relevante Fakten.", "Welche zwei Rückfragen sind für die Auswahl nötig?"], solution: <p>Gehosteter Dienst, CSV-Export, SAML-SSO, konfigurierbare Aufbewahrung bis 365 Tage und Android-Mindestversion. Zu klären sind etwa vollständiger Export, Datenstandort, IdP-Kompatibilität und benötigte Aufbewahrungsdauer.</p> },
    takeaway: ["Feedback prüft Bedeutung.", "Kommunikationsmodelle sind Reflexionshilfen.", "Technische Texte werden an Anforderungen ausgewertet, nicht nur übersetzt."],
  },
  "angebot-und-vertragsgrundlagen": {
    objectives: ["Angebot und Annahme konzeptionell einordnen", "Kauf, Miete und Leasing unterscheiden", "Lizenz- und Servicevereinbarungen erkennen"],
    intro: <p>IT-Aufträge kombinieren häufig Sachen, Nutzungsrechte und Dienstleistungen. Die Bezeichnung allein entscheidet nicht jede Rechtsfolge; Inhalt und tatsächliche Leistung werden fachkundig geprüft.</p>,
    sections: [
      { title: "Vom Angebot zur Vereinbarung", paragraphs: [<>Ein hinreichend bestimmtes Angebot und eine inhaltlich passende Annahme können einen Vertrag begründen. Leistungsumfang, Preis, Termine, Mitwirkung, Dokumentation und Abnahmebedingungen sollten nachvollziehbar sein.</>, <>Änderungen oder Vorbehalte können ein neues Angebot darstellen. Diese Grundorientierung ersetzt keine rechtliche Prüfung eines Einzelfalls.</>], activity: <SingleChoiceCheck title="Vertragsinhalt erkennen" question="Was macht ein IT-Angebot am besten prüfbar?" inputName="customer-offer" correctOptionId="scope" successMessage="Konkreter Umfang, Preis, Termin und Kriterien schaffen Vergleichbarkeit." options={[{id:"vague",label:"Nur die Aussage „alles inklusive“.",explanation:"Umfang und Grenzen bleiben offen."},{id:"scope",label:"Leistung, Preis, Termine, Mitwirkung und Kriterien.",explanation:"Richtig."},{id:"brand",label:"Nur das Anbieterlogo.",explanation:"Das beschreibt keine Leistung."},{id:"oral-only",label:"Ausschließlich undokumentierte Nebenabsprachen.",explanation:"Das erschwert Nachvollziehbarkeit."}]} /> },
      { title: "Vertragliche Grundmodelle", paragraphs: [<>Beim Kauf stehen Sache/Eigentumsverschaffung und Kaufpreis im Mittelpunkt; Miete gewährt Gebrauch auf Zeit. Leasing ist ein vertraglich ausgestaltetes Nutzungs-/Finanzierungsmodell mit Bedingungen zu Laufzeit, Raten, Risiko und Rückgabe.</>, <>Ein Lizenzvertrag regelt Nutzungsrechte an Software. Service-/Supportvereinbarungen beschreiben Leistungen und Serviceziele. Ein Auftrag kann mehrere Elemente enthalten; keine Kategorie wird allein aus dem Produktnamen abgeleitet.</>] },
    ],
    visual: <ResponsiveTable caption="Grundmodelle im IT-Kontext" headers={["Modell", "Kernidee", "typische Prüfpunkte"]} rows={[["Kauf","Sache gegen Kaufpreis","Umfang, Beschaffenheit, Übergabe"],["Miete","Gebrauch auf Zeit","Laufzeit, Zustand, Rückgabe"],["Leasing","vertragliche Nutzung/Finanzierung","Raten, Risiko, Rückgabe/Optionen"],["Lizenz","Nutzungsrechte","Nutzer/Geräte, Dauer, Grenzen"],["Service","Tätigkeit/Serviceumfang","Zeiten, Rollen, Eskalation"]]} />,
    scenario: { title: "Arbeitsplätze als Paket", situation: <p>Ein Anbieter liefert gekaufte Monitore, geleaste Notebooks, Softwareabonnements und dreijährigen Vor-Ort-Service.</p>, tasks: ["Welche Vertrags-/Leistungselemente erkennst du?", "Warum reicht ein Gesamtpreis für den Vergleich nicht?"], solution: <p>Kauf, Leasing, Lizenzabonnement und Service werden getrennt geprüft. Laufzeiten, Rechte, Rückgabe, Serviceumfang, Risiken und TCO unterscheiden sich.</p> },
    takeaway: ["Angebot und Annahme brauchen übereinstimmenden Inhalt.", "IT-Verträge können mehrere Leistungstypen kombinieren.", "Leistungsbeschreibung und Bedingungen sind wichtiger als Etiketten."],
    relatedLinks: [{href:"/lernen/wirtschaftlichkeit-und-beschaffung/kauf-miete-leasing-und-make-or-buy",label:"Wirtschaftlichkeit: Bezugsmodelle"},{href:"/lernen/software-und-lizenzierung/lizenzmodelle-und-nutzungsrechte",label:"Software: Lizenzmodelle"}],
  },
  "dienstvertrag-werkvertrag-und-maengel": {
    objectives: ["Dienst- und Werkvertrag grundlegend unterscheiden", "Abnahme beim geschuldeten Werk einordnen", "gesetzliche Mängelrechte und Garantie trennen"],
    intro: <p>Die Unterscheidung richtet sich nach dem vereinbarten Inhalt. Nicht jede IT-Leistung passt ohne Prüfung vollständig in genau eine Schublade.</p>,
    sections: [
      { title: "Tätigkeit oder Erfolg", paragraphs: [<>Beim Dienstvertrag steht die versprochene Tätigkeit im Mittelpunkt. Beim Werkvertrag wird ein bestimmter Erfolg beziehungsweise ein herzustellendes Werk geschuldet; die Abnahme ist dort ein zentraler Begriff.</>, <>Laufender Beratungs- oder Bereitschaftsdienst kann dienstvertragliche Merkmale haben, eine konkret vereinbarte funktionsfähige Installation werkvertragliche. Mischleistungen und Einzelfälle werden rechtlich geprüft.</>], activity: <SingleChoiceCheck title="Grundunterschied" question="Welche Aussage beschreibt den Werkvertrag auf Grundniveau am besten?" inputName="customer-contract-type" correctOptionId="result" successMessage="Beim Werkvertrag steht ein vereinbarter Erfolg beziehungsweise ein Werk im Mittelpunkt." options={[{id:"time",label:"Nur Anwesenheit ohne vereinbarten Erfolg.",explanation:"Das beschreibt eher eine Tätigkeit."},{id:"result",label:"Ein bestimmter Erfolg beziehungsweise ein Werk wird geschuldet.",explanation:"Richtig."},{id:"license",label:"Automatische Übertragung sämtlicher Urheberrechte.",explanation:"Das folgt daraus nicht."},{id:"cloud",label:"Jeder Cloud-Dienst ist zwingend Werkvertrag.",explanation:"Die konkrete Leistung entscheidet."}]} /> },
      { title: "Mangel, Gewährleistung und Garantie", paragraphs: [<>Gesetzliche Mängelrechte knüpfen an eine mangelhafte Leistung beziehungsweise Sache und den jeweiligen Vertragspartner an. Ein Mangel wird sachlich mit vereinbarter Leistung, Umgebung, Soll und Ist dokumentiert.</>, <>Eine Garantie ist eine zusätzliche freiwillige Zusage des Garantiegebers nach ihren Bedingungen und verdrängt gesetzliche Ansprüche nicht. Konkrete Fristen oder Rechtsfolgen werden hier bewusst nicht pauschalisiert.</>] },
    ],
    visual: <ResponsiveTable caption="Dienst und Werk konzeptionell" headers={["Aspekt", "Dienstvertrag", "Werkvertrag"]} rows={[["Schwerpunkt","versprochene Dienste/Tätigkeit","vereinbarter Erfolg/Werk"],["Beispielrichtung","laufende Beratung/Unterstützung","definierte funktionsfähige Installation"],["Abnahme","nicht allgemeines Kernelement wie beim Werk","zentral für vertragsgemäß hergestelltes Werk"],["Grenze","Inhalt des Einzelfalls entscheidet","Mischleistungen möglich"]]} />,
    scenario: { title: "Migration mit Bereitschaft", situation: <p>Ein Auftrag enthält eine abnahmefähige Migration auf einen definierten Sollstand und anschließend monatliche Unterstützungsstunden.</p>, tasks: ["Welche unterschiedlichen Leistungsmerkmale liegen vor?", "Welche Kriterien müssen dokumentiert sein?"], solution: <p>Die Migration hat werkbezogene Erfolgs-/Abnahmekriterien; laufende Unterstützung kann dienstbezogene Merkmale haben. Sollzustand, Tests, Mitwirkung, Übergabe und Serviceumfang werden getrennt beschrieben.</p> },
    takeaway: ["Dienstvertrag fokussiert Tätigkeit, Werkvertrag Erfolg/Werk.", "Die konkrete Vereinbarung entscheidet.", "Garantie und gesetzliche Mängelrechte sind nicht dasselbe."],
  },
  "sla-support-und-kundeneinweisung": {
    objectives: ["SLA-Kennzahlen korrekt lesen", "Reaktions- und Lösungsziel unterscheiden", "Kundeneinweisung sicher strukturieren"],
    intro: <p>Ein Service Level Agreement konkretisiert messbare Erwartungen. Es ersetzt weder Architektur noch Kommunikation und verspricht nur das, was eindeutig definiert ist.</p>,
    sections: [
      { title: "Serviceziele richtig lesen", paragraphs: [<>Ein SLA kann Servicezeiten, Verfügbarkeit, Reaktionszeit, Wiederherstellungs- oder Lösungsziel, Messpunkt, Ausschlüsse, Priorisierung und Eskalation definieren. Reaktionszeit ist die Zeit bis zur vereinbarten Reaktion, nicht automatisch bis zur Lösung.</>, <>99,9 % Verfügbarkeit bedeutet nicht „nie Ausfall“. Bezugszeitraum, Messort, Wartungsfenster und Rundung bestimmen die Aussage; Ziele und Folgen werden vertraglich präzisiert.</>], activity: <SingleChoiceCheck title="SLA interpretieren" question="Ein SLA nennt 30 Minuten Reaktionszeit. Was ist damit sicher zugesagt?" inputName="customer-sla" correctOptionId="reaction" successMessage="Zugesagt ist die definierte Reaktion innerhalb des Messfensters, nicht automatisch die Lösung." options={[{id:"solution",label:"Jeder Fehler ist nach 30 Minuten gelöst.",explanation:"Reaktions- und Lösungszeit sind verschieden."},{id:"reaction",label:"Die vereinbarte Reaktion erfolgt innerhalb von 30 Minuten.",explanation:"Richtig, sofern Messpunkt und Servicezeit gelten."},{id:"availability",label:"100 % Verfügbarkeit.",explanation:"Das folgt nicht aus einer Reaktionszeit."},{id:"no-ticket",label:"Es wird kein Ticket benötigt.",explanation:"Meldeweg und Messbeginn müssen definiert sein."}]} /> },
      { title: "Einweisung als Teil der Übergabe", paragraphs: [<>Eine Einweisung erklärt Änderung und Zweck, demonstriert Kernfunktionen, weist auf Grenzen und Sicherheitsregeln hin, lässt Nutzer üben und gibt Raum für Fragen. Zielgruppe und Barrierefreiheit werden berücksichtigt.</>, <>Teilnehmende, Inhalte, offene Fragen und bereitgestellte Unterlagen werden angemessen dokumentiert. Die Einweisung ersetzt keine technische Dokumentation oder formale Abnahme.</>] },
    ],
    visual: <TextFlow caption="Kundeneinweisung" steps={["Änderung/Ziel", "Kernfunktion zeigen", "Sicherheit/Grenzen", "Nutzer übt", "Fragen/Feedback", "dokumentieren"]} />,
    scenario: { title: "Neuer Dateidienst", situation: <p>Nach Migration sollen sechs Mitarbeitende Anmeldung, Ablage, Versionswiederherstellung und Meldeweg kennen.</p>, tasks: ["Plane eine kurze Einweisung.", "Welche SLA-Aussage darf nicht versprochen werden?"], solution: <p>Ziel erklären, typische Aufgabe demonstrieren, Berechtigungen und sichere Nutzung nennen, Wiederherstellung üben, Supportweg zeigen und Fragen dokumentieren. Aus Reaktionsziel darf keine garantierte Sofortlösung abgeleitet werden.</p> },
    takeaway: ["SLA-Werte brauchen Definition und Messkontext.", "Reaktionszeit ist nicht Lösungszeit.", "Einweisung verbindet Demonstration, sichere Nutzung, Feedback und Dokumentation."],
    relatedLinks: [{href:"/lernen/qualitaetssicherung-und-uebergabe/abnahme-uebergabe-und-einweisung",label:"Qualität: Abnahme und Übergabe"}],
  },
};

export function CustomerContractLesson({ lessonSlug }: { lessonSlug: string }) {
  const lesson = lessons[lessonSlug];
  if (!lesson) return null;
  return <FundamentalsLesson lessonId={`customer-${lessonSlug}`} {...lesson} relatedLinks={lesson.relatedLinks}>{lesson.visual}</FundamentalsLesson>;
}
