import { DhcpConfigurationVisualization, DhcpPoolVisualization, DoraSequence } from "./dhcp-visualizations";
import { DoraOrderCheck } from "./dora-order-check";
import { LearningObjectives } from "./learning-objectives";
import { MultipleSelectionCheck, type MultipleSelectionOption } from "./multiple-selection-check";

const configurationOptions: readonly MultipleSelectionOption[] = [
  { id: "ip", label: "IPv4-Adresse", explanation: "Eine IPv4-Adresse gehört zur typischen DHCP-Konfiguration." },
  { id: "mask", label: "Subnetzmaske", explanation: "Die Subnetzmaske kann dem Client per DHCP mitgeteilt werden." },
  { id: "gateway", label: "Standardgateway", explanation: "Ein Router für entfernte Netze kann als DHCP-Option verteilt werden." },
  { id: "dns", label: "DNS-Server", explanation: "DNS-Serverinformationen können per DHCP verteilt werden." },
  { id: "mac", label: "MAC-Adresse der Netzwerkkarte ändern", explanation: "DHCP ändert nicht die vorhandene Link-Layer-Adresse einer Schnittstelle." },
  { id: "password", label: "Benutzerpasswort vergeben", explanation: "Benutzerkonten und Passwörter liegen außerhalb der Aufgabe von DHCP." },
  { id: "disk", label: "Festplatte partitionieren", explanation: "Datenträgerverwaltung ist keine DHCP-Funktion." },
  { id: "encryption", label: "Netzwerkverkehr automatisch verschlüsseln", explanation: "DHCP verteilt Konfiguration, stellt aber keine automatische Verkehrsverschlüsselung bereit." },
];

export function DhcpIntroductionLesson() {
  return <div className="space-y-10 text-base leading-7 text-slate-700 sm:text-lg sm:leading-8">
    <LearningObjectives context="lesson" objectives={["DHCP als Dynamic Host Configuration Protocol ausschreiben", "den grundlegenden Zweck von DHCP erklären", "automatische und manuelle IP-Konfiguration unterscheiden", "typische durch DHCP verteilte IPv4-Parameter nennen", "erklären, wie zentrale Konfiguration den Verwaltungsaufwand reduziert", "verstehen, dass DHCP ein Gerät nicht dauerhaft identifiziert", "DHCP und DNS unterscheiden"]} />

    <section aria-labelledby="dhcp-purpose"><h2 id="dhcp-purpose" className="text-2xl font-bold tracking-tight text-slate-950">Was ist DHCP?</h2><div className="mt-4 space-y-4"><p><strong>DHCP</strong> steht für <strong>Dynamic Host Configuration Protocol</strong>. Das Protokoll stellt Clients Netzwerkkonfiguration automatisch bereit. So müssen passende Werte nicht an jedem Endgerät einzeln eingetragen werden.</p><p>Typische Informationen sind eine <strong>IPv4-Adresse</strong>, eine <strong>Subnetzmaske</strong> beziehungsweise passende Präfixinformation, ein <strong>Standardgateway</strong>, <strong>DNS-Server</strong> und die <strong>Lease-Dauer</strong>. Welche Informationen tatsächlich geliefert werden, hängt von Serverkonfiguration und Netzdesign ab.</p></div><DhcpConfigurationVisualization /></section>

    <section aria-labelledby="manual-auto"><h2 id="manual-auto" className="text-2xl font-bold tracking-tight text-slate-950">Manuell oder automatisch konfigurieren?</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><ConfigCard title="Manuell / statisch"><dl className="space-y-2"><Value label="IP" value="192.168.10.25" /><Value label="Maske" value="255.255.255.0" /><Value label="Gateway" value="192.168.10.1" /><Value label="DNS" value="192.168.10.5" /></dl><p className="mt-4 text-sm leading-6">Eine Administration trägt die Werte direkt am Gerät ein und muss sie koordiniert dokumentieren.</p></ConfigCard><ConfigCard title="Automatisch per DHCP"><p>Der Client fordert Konfiguration an. Ein zentral verwalteter DHCP-Dienst kann passende Werte aus dem vorgesehenen Netz bereitstellen.</p><p className="mt-3 text-sm leading-6">Der Client bleibt dabei für seine IP-Konfiguration auf DHCP eingestellt.</p></ConfigCard></div><p className="mt-5">Beide Verfahren haben berechtigte Einsatzfälle. Router, Infrastruktursysteme, manche Server, Drucker oder Appliances brauchen häufig vorhersehbare Adressen. Diese können lokal statisch konfiguriert oder – wenn es zum Design passt – über eine DHCP-Reservierung zuverlässig zugewiesen werden.</p></section>

    <section aria-labelledby="useful"><h2 id="useful" className="text-2xl font-bold tracking-tight text-slate-950">Warum ist DHCP nützlich?</h2><ul className="mt-5 grid gap-3 sm:grid-cols-2">{["weniger manuelle Konfiguration", "weniger Tipp- und Konfigurationsfehler", "zentrale Adressverwaltung", "einfacheres Onboarding von Clients", "leichtere Änderungen an Netzparametern", "zeitlich begrenzte Zuweisung durch Leases"].map((item) => <li key={item} className="rounded-xl border border-slate-200 bg-white p-4 font-semibold text-slate-900">{item}</li>)}</ul><p className="mt-5">Das ist besonders praktisch für wechselnde Office-Clients, Notebooks, Gastgeräte und Testnetze. Würde jedes Endgerät ausschließlich manuell gepflegt, müssten Adressen einzeln geplant, eingetragen, geändert und auf Doppelbelegungen geprüft werden. Für Dienste mit besonderen Betriebsanforderungen kann eine vorhersehbare Adressierung dennoch sinnvoll sein.</p></section>

    <section aria-labelledby="lease-identity"><h2 id="lease-identity" className="text-2xl font-bold tracking-tight text-slate-950">Eine DHCP-Adresse ist keine permanente Identität</h2><p className="mt-4">DHCP weist Adressen üblicherweise für eine <strong>Lease-Zeit</strong> zu. Ein Client versucht normalerweise, diese Zuweisung zu erneuern und kann dabei dieselbe Adresse behalten. Eine spätere andere Adresse ist jedoch möglich. Deshalb gilt: <strong>DHCP-Adresse ≠ dauerhafte Hardware- oder Geräteidentität.</strong></p></section>

    <MultipleSelectionCheck title="Umfang von DHCP" question="Welche Informationen kann ein DHCP-Server einem IPv4-Client typischerweise bereitstellen?" options={configurationOptions} correctOptionIds={["ip", "mask", "gateway", "dns"]} successMessage="Richtig: DHCP kann dem Client die zentrale IPv4-Netzwerkkonfiguration aus Adresse, Maske, Gateway und DNS-Server bereitstellen." missedCorrectMessage="Gesucht sind die vier typischen Werte der IPv4-Netzwerkkonfiguration; DHCP verwaltet weder Benutzerkonten noch Datenträger oder Verschlüsselung." inputName="dhcp-configuration" />

    <Misconceptions items={[["DHCP ist DNS.", "DHCP verteilt Konfiguration; DNS löst Namen auf."], ["DHCP vergibt MAC-Adressen.", "Die Schnittstelle besitzt bereits ihre Link-Layer-Adresse; DHCP liefert IP-Layer-Konfiguration."], ["Eine per DHCP erhaltene Adresse bleibt immer gleich.", "Lease-Verhalten garantiert keine permanente Identität, auch wenn eine Verlängerung häufig dieselbe Adresse behält."], ["Statische IP-Adressen sind immer besser.", "Die Wahl hängt von Betriebsanforderungen und Netzdesign ab."]]} />

    <section aria-labelledby="dhcp-practice"><h2 id="dhcp-practice" className="text-2xl font-bold tracking-tight text-slate-950">Konfiguration sicher auslesen</h2><p className="mt-4">Ändere nichts. Ermittle nur die aktuelle IPv4-Adresse, Maske beziehungsweise Präfixlänge, das Gateway mit einem passenden Systemwerkzeug und Hinweise auf automatische Konfiguration.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Command system="Windows" value="ipconfig /all" /><Command system="Linux" value="ip addr" /></div><p className="mt-4 text-sm leading-6">Unter Linux zeigt <code>ip route</code> häufig das Standardgateway. Ob und wie DHCP-Informationen angezeigt werden, hängt von Distribution, DHCP-Client und Network Manager ab.</p></section>

    <MemoryAid items={["DHCP = automatische Netzwerkkonfiguration", "Typisch: IP · Maske · Gateway · DNS · Lease", "DHCP ≠ DNS", "DHCP ≠ permanente Geräteidentität"]} />
  </div>;
}

export function DoraLesson() {
  return <div className="space-y-10 text-base leading-7 text-slate-700 sm:text-lg sm:leading-8">
    <LearningObjectives context="lesson" objectives={["DORA ausschreiben", "die vier grundlegenden Schritte in der richtigen Reihenfolge beschreiben", "Sender und Empfänger jeder Nachricht identifizieren", "die Bedeutung von Broadcasts bei der initialen Konfiguration erklären", "UDP-Port 67 dem Server und UDP-Port 68 dem Client zuordnen", "DHCPREQUEST im initialen Auswahlprozess korrekt einordnen", "verstehen, dass DHCPNAK und weitere Nachrichten außerhalb des DORA-Fokus existieren"]} />

    <section aria-labelledby="participants"><h2 id="participants" className="text-2xl font-bold tracking-tight text-slate-950">Client, Server und der schwierige Anfang</h2><p className="mt-4">Ein neu gestarteter <strong>DHCP-Client</strong> kennt möglicherweise weder eine nutzbare eigene IPv4-Adresse noch die Adresse eines <strong>DHCP-Servers</strong>. Deshalb nutzt die initiale Kommunikation häufig Broadcast-Mechanismen. Das bedeutet nicht, dass jedes Paket in jedem DHCP-Zustand immer ein Broadcast ist.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><PortCard name="DHCP-Server" port="UDP 67" /><PortCard name="DHCP-Client" port="UDP 68" /></div><p className="mt-4 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm font-semibold text-slate-900">Merke: Server 67 · Client 68. DNS verwendet dagegen Port 53.</p></section>

    <section aria-labelledby="dora-flow"><h2 id="dora-flow" className="text-2xl font-bold tracking-tight text-slate-950">DORA: der grundlegende initiale Ablauf</h2><DoraSequence /><div className="mt-6 space-y-4"><Step title="D — DHCPDISCOVER"><p>Bei einer typischen initialen Adressvergabe sucht der Client nach DHCP-Servern. Als Quelladresse kann <code>0.0.0.0</code>, als Ziel der Limited Broadcast <code>255.255.255.255</code> verwendet werden; UDP läuft dabei vom Client-Port <code>68</code> zum Server-Port <code>67</code>. Details können je nach Zustand und Implementierung variieren.</p></Step><Step title="O — DHCPOFFER"><p>Ein Server kann eine vorgeschlagene IPv4-Adresse, Subnetzinformationen, Lease-Angaben und weitere Optionen anbieten. Mehrere Server können theoretisch antworten. Das Angebot bedeutet noch keine endgültige Übernahme; die Antwortübertragung ist nicht pauschal immer Broadcast oder immer Unicast.</p></Step><Step title="R — DHCPREQUEST"><p>Im initialen Auswahlprozess zeigt der Client an, welches Angebot und welchen Server er anfordert. Dadurch erkennen andere anbietende Server ebenfalls, dass ihr Angebot nicht gewählt wurde. DHCPREQUEST ist mehr als „noch einmal nach einer IP fragen“ und wird auch in anderen Zuständen, etwa bei Verlängerungen, verwendet.</p></Step><Step title="A — DHCPACK"><p>Der ausgewählte Server bestätigt die angeforderte Konfiguration. Nach erfolgreicher Verarbeitung kann der Client die Parameter entsprechend der Lease verwenden. Ein ACK ist nicht zwingend immer Unicast oder immer Broadcast. In bestimmten Fällen kann ein Server stattdessen mit <strong>DHCPNAK</strong> negativ antworten.</p></Step></div></section>

    <DoraOrderCheck />

    <section aria-labelledby="packet-view"><h2 id="packet-view" className="text-2xl font-bold tracking-tight text-slate-950">DORA in einer Paketaufzeichnung erkennen</h2><p className="mt-4">Suche in einer Wireshark- oder Filius-artigen Aufzeichnung konzeptionell nach DHCPDISCOVER, DHCPOFFER, DHCPREQUEST und DHCPACK. Prüfe für jede Nachricht Reihenfolge, Senderrolle und Zielrolle. Ein verbreiteter Wireshark-Anzeigefilter für DHCP/BOOTP-Verkehr ist <code>bootp</code>; je nach Werkzeugversion können Bezeichnungen abweichen.</p></section>

    <Misconceptions items={[["DORA bedeutet, dass immer genau vier Pakete übertragen werden.", "DORA ist der grundlegende konzeptionelle Austausch; Wiederholungen, mehrere Offers und weitere DHCP-Nachrichten sind möglich."], ["Jeder DHCP-Schritt ist immer Broadcast.", "Broadcast- oder Unicast-Verhalten hängt von Nachricht, Zustand und Client-Fähigkeiten ab."], ["Nach dem Offer gehört die IP schon endgültig dem Client.", "Der initiale Auswahl- und Bestätigungsvorgang ist zu diesem Zeitpunkt noch nicht abgeschlossen."], ["DHCP nutzt TCP.", "IPv4-DHCP verwendet UDP, üblicherweise Server-Port 67 und Client-Port 68."]]} />
    <MemoryAid items={["DORA = Discover · Offer · Request · Acknowledge", "Client 68 → Server 67", "Server 67 → Client 68", "DORA beschreibt den grundlegenden initialen Ablauf – nicht jeden DHCP-Austausch"]} />
  </div>;
}

const poolOptions: readonly MultipleSelectionOption[] = [
  { id: "120", label: "192.168.20.120", explanation: "120 liegt zwischen den konfigurierten Grenzen 100 und 200." },
  { id: "199", label: "192.168.20.199", explanation: "199 liegt zwischen den konfigurierten Grenzen 100 und 200." },
  { id: "50", label: "192.168.20.50", explanation: "Die Adresse ist in diesem /24 eine gewöhnliche Hostadresse, liegt aber außerhalb des geplanten Pools 100–200." },
  { id: "network", label: "192.168.20.0", explanation: "Das ist die Netzadresse des /24 und keine gewöhnliche Hostadresse." },
  { id: "broadcast", label: "192.168.20.255", explanation: "Das ist die Broadcast-Adresse des /24 und keine gewöhnliche Hostadresse." },
];

export function DhcpLeasePoolLesson() {
  return <div className="space-y-10 text-base leading-7 text-slate-700 sm:text-lg sm:leading-8">
    <LearningObjectives context="lesson" objectives={["einen DHCP-Lease erklären", "einen Adresspool beziehungsweise Scope erklären", "dynamisch vergebbare, ausgeschlossene und reservierte Adressen konzeptionell unterscheiden", "die Bedeutung der Lease-Dauer erklären", "Verlängerung auf Einsteigerniveau verstehen", "häufige per DHCP gelieferte Konfigurationswerte nennen", "DHCP-Reservierungen konzeptionell verstehen", "Fehler in der Adresspool-Planung erkennen", "begründen, warum ein Pool zum vorgesehenen Subnetz passen muss"]} />

    <section aria-labelledby="pool"><h2 id="pool" className="text-2xl font-bold tracking-tight text-slate-950">Adresspool oder Scope</h2><p className="mt-4">Ein DHCP-Server braucht einen Bereich, aus dem er Adressen vergeben darf. Im Beispielnetz <code>192.168.10.0/24</code> reicht der konfigurierte DHCP-Pool von <code>192.168.10.100</code> bis <code>192.168.10.200</code>. Das gesamte Subnetz muss nicht dynamisch vergeben werden.</p><DhcpPoolVisualization /><p className="mt-5">Die Netzadresse <code>192.168.10.0</code> und die Broadcast-Adresse <code>192.168.10.255</code> dürfen in einem gewöhnlichen Hostpool nicht vergeben werden. Der Pool muss zum vorgesehenen Subnetz gehören und darf nicht unkoordiniert Adressen überlappen, die bewusst statisch verwendet werden.</p></section>

    <section aria-labelledby="lease"><h2 id="lease" className="text-2xl font-bold tracking-tight text-slate-950">Lease: Nutzung auf Zeit</h2><p className="mt-4">Ein <strong>Lease</strong> ist die zeitlich begrenzte Berechtigung beziehungsweise Konfiguration, mit der ein Client eine zugewiesene Adresse nutzt. Vor Ablauf versucht der Client normalerweise, die Lease zu erneuern. Der Server kann dabei dieselbe Adresse verlängern – Ablauf bedeutet also nicht, dass die Adresse zwingend wechselt.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Scenario title="Gast-WLAN">Kürzere Leases können sinnvoll sein, weil die Menge der Clients häufig wechselt und Adressen früher wieder verfügbar werden sollen. Das erzeugt zugleich mehr Erneuerungsverkehr.</Scenario><Scenario title="Stabile Büroumgebung">Längere Leases können Erneuerungsaufwand reduzieren und zu stabileren Zuweisungen passen. Änderungen an Parametern erreichen Clients dann möglicherweise später.</Scenario></div><p className="mt-4 text-sm leading-6">Die passende Lease-Dauer ist eine administrative Designentscheidung. Diese Einführung verzichtet bewusst auf T1-/T2-Details des DHCP-Zustandsautomaten.</p></section>

    <section aria-labelledby="options"><h2 id="options" className="text-2xl font-bold tracking-tight text-slate-950">DHCP-Optionen liefern zusätzliche Konfiguration</h2><p className="mt-4">Neben der Adresse kann DHCP Optionen für <strong>Subnetzmaske</strong>, <strong>Standardgateway beziehungsweise Router</strong>, <strong>DNS-Server</strong> und <strong>Lease-Zeit</strong> liefern. Je nach Umgebung sind auch Domainname oder NTP-Server möglich. Entscheidend ist hier das Konzept, nicht das Auswendiglernen von Optionsnummern.</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><Role title="Standardgateway">Layer-3-Pfad zu entfernten Netzen.</Role><Role title="DNS-Server">Löst Namen in passende Adressinformationen auf.</Role></div><p className="mt-4">DHCP-Server, Gateway und DNS-Server können in kleinen Netzen Funktionen desselben Geräts sein oder – je nach Design – getrennte Systeme. Ihre Rollen bleiben verschieden.</p></section>

    <section aria-labelledby="reservation"><h2 id="reservation" className="text-2xl font-bold tracking-tight text-slate-950">Reservierung statt lokaler statischer Konfiguration</h2><p className="mt-4">In vielen DHCP-Umgebungen wird eine Reservierung anhand der MAC-Adresse beziehungsweise Client-Identifikation eingerichtet. Der Client verwendet weiterhin DHCP; der Server bietet ihm konsistent eine vorgesehene Adresse an. Eine Identifikation kann implementationsabhängig über mehr als nur die MAC-Adresse erfolgen.</p><dl className="mt-5 grid gap-4 sm:grid-cols-2"><Definition term="Statisch / manuell">Die Netzwerkkonfiguration wird lokal am Gerät eingetragen.</Definition><Definition term="DHCP-Reservierung">Der Client bleibt automatisch konfiguriert; der Server ordnet seiner Identifikation eine vorhersehbare Adresse zu.</Definition></dl></section>

    <MultipleSelectionCheck title="Adresspool prüfen" question="Welche Adressen liegen innerhalb des konfigurierten DHCP-Pools 192.168.20.100–192.168.20.200 im Netz 192.168.20.0/24?" options={poolOptions} correctOptionIds={["120", "199"]} successMessage="Richtig: .120 und .199 liegen innerhalb der konfigurierten Grenzen. .50 ist eine mögliche Hostadresse, aber außerhalb dieses Pools; .0 und .255 sind Netz- beziehungsweise Broadcast-Adresse." missedCorrectMessage="Prüfe die inklusive Spanne von 100 bis 200. Außerhalb des Pools bedeutet nicht automatisch protokollbedingt ungültig." inputName="dhcp-pool" />

    <section aria-labelledby="conflicts"><h2 id="conflicts" className="text-2xl font-bold tracking-tight text-slate-950">Adresskonflikte vermeiden</h2><p className="mt-4">Wird eine Adresse innerhalb des DHCP-Pools zusätzlich manuell vergeben, ohne den DHCP-Server zu koordinieren, <strong>kann</strong> eine doppelte Adressvergabe entstehen. Reservierungen, Ausschlüsse und ein dokumentierter Poolplan helfen, solche Kollisionen zu vermeiden.</p></section>

    <Misconceptions items={[["Der DHCP-Pool muss das gesamte Subnetz umfassen.", "Nur der geplante dynamische Vergabebereich muss im Pool liegen."], ["Ein Lease bedeutet, dass die IP nach Ablauf zwingend wechselt.", "Clients erneuern Leases üblicherweise und können dieselbe Adresse behalten."], ["Gateway und DNS sind dasselbe.", "Das Gateway vermittelt zu entfernten Netzen; DNS löst Namen auf."], ["DHCP-Reservierung und statische IP sind identisch.", "Bei einer Reservierung verwendet der Client weiterhin DHCP."], ["Ich kann beliebig statische Adressen mitten im DHCP-Pool vergeben.", "Unkoordinierte statische und dynamische Vergabe kann Adresskonflikte verursachen."]]} />

    <section aria-labelledby="pool-practice"><h2 id="pool-practice" className="text-2xl font-bold tracking-tight text-slate-950">Praxis: einen Pool planen</h2><p className="mt-4">Plane für <code>192.168.50.0/24</code>: Router <code>192.168.50.1</code>, Server <code>192.168.50.10</code>, dynamische Clients <code>192.168.50.100–192.168.50.200</code>.</p><ul className="mt-4 list-disc space-y-2 pl-6"><li>Netzadresse: <code>192.168.50.0</code></li><li>Broadcast: <code>192.168.50.255</code></li><li>vorgesehener dynamischer Pool: <code>192.168.50.100–192.168.50.200</code></li><li>Router, Server, Netzadresse, Broadcast und alle weiteren Adressen außerhalb der Spanne sind <strong>in diesem Plan nicht Teil des dynamischen Pools</strong>. Nicht alle davon sind deshalb protokollreserviert.</li></ul></section>

    <section aria-labelledby="relay-preview" className="rounded-2xl border border-slate-200 bg-slate-50 p-5 sm:p-6"><p className="text-sm font-semibold text-blue-700">Nächste Lektion</p><h2 id="relay-preview" className="mt-1 text-xl font-bold text-slate-950">DHCP über mehrere Subnetze und Relay</h2><p className="mt-3 text-sm leading-6">Initiale DHCP-Suche stützt sich stark auf lokalen Broadcast. Router leiten solche lokalen Broadcasts normalerweise nicht weiter. Für einen zentralen DHCP-Server in einem anderen Subnetz wird deshalb ein Mechanismus wie DHCP-Relay benötigt. Die Konfiguration folgt erst in Lektion 4.</p></section>
  </div>;
}

function ConfigCard({ title, children }: { title: string; children: React.ReactNode }) { return <article className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-bold text-slate-950">{title}</h3><div className="mt-3">{children}</div></article>; }
function Value({ label, value }: { label: string; value: string }) { return <div className="flex flex-wrap justify-between gap-2"><dt className="font-semibold">{label}</dt><dd><code className="break-all">{value}</code></dd></div>; }
function Command({ system, value }: { system: string; value: string }) { return <div className="overflow-hidden rounded-xl border border-slate-200 bg-slate-950"><p className="bg-slate-800 px-4 py-2 text-sm font-semibold text-slate-200">{system}</p><pre className="overflow-x-auto p-4 text-sm text-blue-100"><code>{value}</code></pre></div>; }
function PortCard({ name, port }: { name: string; port: string }) { return <div className="rounded-xl border border-blue-200 bg-blue-50 p-5"><p className="font-bold text-slate-950">{name}</p><code className="mt-2 block text-xl font-bold text-blue-950">{port}</code></div>; }
function Step({ title, children }: { title: string; children: React.ReactNode }) { return <article className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-bold text-slate-950">{title}</h3><div className="mt-2 text-sm leading-6 sm:text-base sm:leading-7">{children}</div></article>; }
function Scenario({ title, children }: { title: string; children: React.ReactNode }) { return <article className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6">{children}</p></article>; }
function Role({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-xl border border-blue-200 bg-blue-50 p-5"><h3 className="font-bold text-blue-950">{title}</h3><p className="mt-2 text-sm leading-6">{children}</p></div>; }
function Definition({ term, children }: { term: string; children: React.ReactNode }) { return <div className="rounded-xl border border-slate-200 bg-white p-4"><dt className="font-bold text-slate-950">{term}</dt><dd className="mt-2 text-sm leading-6">{children}</dd></div>; }
function Misconceptions({ items }: { items: readonly (readonly [string, string])[] }) { return <section aria-labelledby={`misconceptions-${items.length}`}><h2 id={`misconceptions-${items.length}`} className="text-2xl font-bold tracking-tight text-slate-950">Typische Denkfehler</h2><dl className="mt-5 space-y-4">{items.map(([wrong, correction]) => <div key={wrong} className="rounded-xl border border-slate-200 bg-white p-4"><dt className="font-bold text-slate-950">Falsch: „{wrong}“</dt><dd className="mt-2 text-sm leading-6"><strong>Korrektur:</strong> {correction}</dd></div>)}</dl></section>; }
function MemoryAid({ items }: { items: readonly string[] }) { return <aside aria-label="Merksätze" className="rounded-2xl border border-blue-200 bg-blue-950 p-5 text-white sm:p-6"><h2 className="text-sm font-bold uppercase tracking-[0.12em] text-blue-200">Merksätze</h2><ul className="mt-3 space-y-2 font-semibold">{items.map((item) => <li key={item}>{item}</li>)}</ul></aside>; }
