import { LearningObjectives } from "./learning-objectives";
import { SingleChoiceCheck, type SingleChoiceOption } from "./single-choice-check";

const relayOptions: readonly SingleChoiceOption[] = [
  { id: "relay", label: "Relay auf dem Layer-3-Gerät des Clientnetzes einrichten und zum zentralen DHCP-Server weiterleiten.", explanation: "" },
  { id: "dns", label: "Den DNS-Server des Clients ändern.", explanation: "DNS löst Namen auf und transportiert keine DHCP-Anfrage über die Netzgrenze." },
  { id: "broadcast", label: "Auf automatische Broadcast-Weiterleitung jedes Routers vertrauen.", explanation: "Router leiten lokale Broadcasts normalerweise nicht zwischen Subnetzen weiter; Relay ist eine gezielte Funktion." },
  { id: "all", label: "Dem Server 255.255.255.255 zuweisen.", explanation: "Das ist eine begrenzte Broadcast-Adresse, keine gültige Serveradresse." },
  { id: "nat", label: "NAT statt Relay verwenden.", explanation: "NAT übersetzt Adressen und ersetzt kein DHCP Relay." },
];

export function DhcpRelayLesson() { return <Lesson>
  <LearningObjectives context="lesson" objectives={["erklären, warum DHCP an gerouteten Subnetzgrenzen besondere Behandlung benötigt", "Zweck und Ablauf eines DHCP-Relays erklären", "Client, Router, Relay und DHCP-Server unterscheiden", "die Auswahl eines passenden Pools nachvollziehen", "giaddr als möglichen Hinweis auf das Ursprungsnetz einordnen", "Fehler bei Relay-Platzierung und -Konfiguration erkennen"]} />
  <Section id="relay-boundary" title="Lokaler Broadcast trifft geroutete Grenze"><p>Ein neuer Client in <code>192.168.20.0/24</code> besitzt noch keine normal nutzbare IPv4-Konfiguration. Sein DHCP Discover ist zunächst lokal orientiert. Ein Router leitet diesen Broadcast normalerweise nicht nach <code>192.168.10.0/24</code> weiter. Der Server <code>192.168.10.10</code> empfängt ihn daher nicht allein deshalb, weil Routing existiert.</p><p><strong>Präzise:</strong> Die gewöhnliche Broadcast-Suche durchquert eine geroutete Grenze nicht ohne einen Mechanismus wie DHCP Relay – nicht „DHCP kann keine Router überwinden“.</p></Section>
  <RelayFigure />
  <Section id="relay-flow" title="Gezieltes Relay"><ol className="list-decimal space-y-2 pl-6"><li>Client sendet lokales Discover.</li><li>Das Relay am clientseitigen Layer-3-Interface nimmt es entgegen.</li><li>Es leitet die Information gezielt an den bekannten Server.</li><li>Der Server wählt die Konfiguration und antwortet über das Relay.</li><li>Das Relay liefert sie in Richtung Client.</li></ol><p>Das Relay kennt Clientinterface und Serverziel, vergibt aber selbst keine Lease. Ein Router kann Unicast routen, ohne automatisch DHCP zu relayn. Relay bedeutet auch nicht, alle Broadcasts weiterzuleiten.</p></Section>
  <Section id="giaddr" title="Ursprungsnetz, giaddr und Pool"><p>Beim traditionellen Relay-Verhalten kann das Relay <code>giaddr</code> (Gateway IP Address) etwa mit <code>192.168.20.1</code> füllen. Der Server kann diesen Hinweis auf das Ursprungsnetz zur Scope-Auswahl nutzen. Moderne Systeme können weitere Informationen verwenden; hier geht es nicht um Feld-Memorisierung.</p><div className="grid gap-4 sm:grid-cols-2"><Card title="Pool A"><code>192.168.10.100–200</code><br />für <code>192.168.10.0/24</code></Card><Card title="Pool B"><code>192.168.20.100–200</code><br />für <code>192.168.20.0/24</code></Card></div><p>Für den Remote-Client muss Pool B gewählt werden, nicht eine <code>192.168.10.x</code>-Adresse. Produkte konfigurieren Scopes unterschiedlich; die Zuordnung zum Ursprungsnetz bleibt entscheidend.</p></Section>
  <SingleChoiceCheck title="Relay-Design auswählen" question="Client 192.168.20.0/24, Server 192.168.10.0/24: Welches Design ist sinnvoll?" options={relayOptions} correctOptionId="relay" successMessage="Richtig: Das clientnahe Layer-3-Gerät relayed gezielt; der Server bleibt für die Vergabe zuständig." inputName="relay-design" />
  <Misconceptions items={[["DHCP funktioniert grundsätzlich nicht über Router.", "Zentraler DHCP kann Remote-Subnetze über Relay bedienen."], ["Router leiten DHCP-Broadcasts automatisch weiter.", "Relay muss vorhanden und passend konfiguriert sein."], ["Der Relay ist der DHCP-Server.", "Relay transportiert; der Server vergibt."], ["NAT ersetzt DHCP Relay.", "Beide erfüllen verschiedene Aufgaben."], ["Alle entfernten Subnetze bekommen denselben Pool.", "Jedes Clientnetz braucht passende Adressierung."]]} />
  <Section id="relay-practice" title="Planungsaufgabe"><p>Clients A: <code>192.168.10.0/24</code>, Clients B: <code>192.168.20.0/24</code>, Server: <code>192.168.100.10</code>. Notiere, an welchen clientseitigen Layer-3-Interfaces Relay nötig ist, welche zwei Pools benötigt werden und warum der Server das Ursprungsnetz kennen muss. Router-CLI ist nicht erforderlich.</p></Section>
  </Lesson>; }

function RelayFigure() { return <figure aria-labelledby="relay-caption" className="rounded-2xl border border-blue-200 bg-blue-50 p-5 sm:p-7"><div className="grid gap-3 text-center md:grid-cols-[1fr_auto_1fr_auto_1fr] md:items-center"><Card title="Client"><code>192.168.20.x</code><br />Ursprungsnetz <code>192.168.20.0/24</code></Card><Arrow /><Card title="Router / Relay"><code>192.168.20.1</code><br />kennt Serverziel</Card><Arrow /><Card title="DHCP-Server"><code>192.168.10.10</code><br />Pool <code>192.168.20.100–200</code></Card></div><figcaption id="relay-caption" className="mt-5 text-sm leading-6 text-blue-950">Textablauf: lokaler Client-Broadcast → gezielte Relay-Weiterleitung durchs geroutete Netz → Serverantwort über Relay. Rollen und Sender sind damit auch ohne visuelle Pfeile verständlich.</figcaption></figure>; }
function Arrow() { return <span aria-hidden="true" className="font-bold text-blue-800"><span className="md:hidden">↓</span><span className="hidden md:inline">→</span></span>; }

const diagnosticOptions: readonly SingleChoiceOption[] = [
  { id: "evidence", label: "DHCP-Konfiguration fehlt wahrscheinlich; Link, Client, Netzpfad und DHCP-Verfügbarkeit systematisch prüfen.", explanation: "" },
  { id: "dns", label: "DNS ist definitiv die Ursache.", explanation: "DNS ist keine Voraussetzung für DHCP-Adressvergabe." },
  { id: "server", label: "Der DHCP-Server ist definitiv defekt.", explanation: "169.254 ist ein Hinweis, beweist aber keine einzelne Ursache." },
  { id: "normal", label: "Die Adresse gehört normal zu 192.168.50.0/24.", explanation: "169.254.23.18 ist Link-Local, nicht Teil des erwarteten Netzes." },
];

export function DhcpTroubleshootingLesson() { const steps = ["Aktuelle Clientkonfiguration feststellen", "Link und Interface prüfen", "DHCP am Client prüfen", "erwartetes Subnetz/VLAN prüfen", "Weg zu Server oder Relay prüfen", "passenden Scope/Pool prüfen", "freie Adressen prüfen", "Ausschlüsse/Reservierungen prüfen", "Relay prüfen, falls nötig", "Logs und Paketfluss gezielt auswerten"]; return <Lesson>
  <LearningObjectives context="lesson" objectives={["DHCP-Fehlersymptome erkennen", "169.254.x.x als Link-Local-Hinweis einordnen", "Client-, Netzpfad-, Relay-, Server- und Poolursachen unterscheiden", "Pool-Erschöpfung und falsche Scopes erkennen", "Konflikte und unerwartete DHCP-Server untersuchen", "vom Client nach außen systematisch diagnostizieren"]} />
  <Section id="method" title="Vom Client nach außen prüfen"><ol className="grid gap-3 sm:grid-cols-2">{steps.map((step, index) => <li key={step} className="flex gap-3 rounded-xl border border-slate-200 bg-white p-4"><strong className="text-blue-800">{index + 1}.</strong>{step}</li>)}</ol></Section>
  <Section id="client" title="Clientzustand lesen"><div className="grid gap-4 sm:grid-cols-2"><Card title="Windows"><code>ipconfig /all</code><p>IPv4, Maske, Gateway, DHCP aktiviert, DHCP-Server und Lease-Zeiten prüfen.</p></Card><Card title="Linux"><code>ip addr</code><br /><code>ip route</code><p>Interface, Adresse/Präfix und Routen prüfen. DHCP-/Network-Manager-Werkzeuge unterscheiden sich je Distribution.</p></Card></div><aside className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm"><code>ipconfig /release</code> gibt eine Lease aktiv frei; <code>ipconfig /renew</code> fordert aktiv eine an. Nicht blind in Produktion einsetzen, sondern kontrolliert im Lab, wenn eine Unterbrechung vertretbar ist.</aside></Section>
  <Section id="symptoms" title="Hinweise statt Beweise"><p><code>169.254.0.0/16</code> ist IPv4 Link-Local. Bei einem typischen Windows-DHCP-Client deutet <code>169.254.23.18</code> stark darauf hin, dass erwartete DHCP-Konfiguration fehlt. Mögliche Ursachen: Client, Link/VLAN, Netzpfad, Relay, Server oder Pool.</p><ul className="list-disc space-y-2 pl-6"><li>keine nutzbare oder eine alte Konfiguration</li><li>falsche Adresse oder Maske</li><li>korrekte IP, aber Gateway/DNS fehlt</li><li>Adresskonflikt</li><li>Konfiguration eines unerwarteten DHCP-Servers</li></ul></Section>
  <SingleChoiceCheck title="Link-Local-Szenario" question="169.254.23.18 statt 192.168.50.0/24; weitere Clients am Switch scheitern. Was ist gerechtfertigt?" options={diagnosticOptions} correctOptionId="evidence" successMessage="Richtig: Link-Local ist ein DHCP-Hinweis; mehrere Ursachen bleiben möglich." inputName="dhcp-diagnostic" />
  <Section id="pool" title="Adresspool, Scope und Konflikte"><p>Der inklusive Adresspool <code>192.168.10.100–110</code> enthält nur <strong>11</strong> Adressen. Sind alle geleast, ausgeschlossen oder nicht verfügbar, scheitern neue Clients – selbst wenn das ganze <code>/24</code> noch Kapazität hat.</p><p>Ein Client in <code>192.168.20.0/24</code> benötigt einen passenden Scope; ein Scope nur für <code>192.168.10.0/24</code> genügt nicht. Prüfe außerdem Ausschlüsse, Reservierungen und Überschneidungen mit manuellen Adressen.</p></Section>
  <Section id="remote" title="Nur das entfernte Netz fällt aus"><p>Funktioniert DHCP lokal, aber nicht im gerouteten <code>192.168.20.0/24</code>, verdienen Relay, Serverziel, clientseitiges Interface, Routing/Firewall/ACL und Remote-Scope besondere Aufmerksamkeit. Das Muster beweist keine einzelne Ursache.</p></Section>
  <Section id="rogue" title="Unerwarteter DHCP-Server"><p>Ein unbeabsichtigt aktiver Server kann falschen Adressbereich, Gateway oder DNS verteilen. Vergleiche Serveranzeige und Optionen mit dem Soll. Dies ist defensive Fehlersuche, keine Anleitung zum Rogue-DHCP-Aufbau.</p></Section>
  <Misconceptions items={[["169.254 beweist einen defekten Server.", "Es zeigt fehlende erwartete Konfiguration, nicht die genaue Ursache."], ["Ping schließt DHCP-Probleme aus.", "Alte oder manuelle Adressen können weiter funktionieren."], ["Ein voller Pool bedeutet ein volles Subnetz.", "Pool und Subnetzkapazität unterscheiden sich."], ["DHCP-Fehler sind immer Clientfehler.", "Auch Pfad, Relay, Server und Pool kommen infrage."], ["DNS muss für DHCP funktionieren.", "DHCP und DNS sind getrennte Dienste."]]} />
  <Section id="checklist" title="Kompakte Checkliste"><div className="grid gap-4 sm:grid-cols-3"><Card title="Client">Link · DHCP aktiv · Adresse · Maske · Gateway · Lease/Server</Card><Card title="Netz">Subnetz/VLAN · Layer 2 · Routing · Relay · Firewall/ACL</Card><Card title="Server">Dienst · Scope · freie Leases · Ausschlüsse · Reservierungen · Logs</Card></div></Section>
  </Lesson>; }

const poolOptions: readonly SingleChoiceOption[] = [
  { id: "valid", label: "192.168.50.100–192.168.50.150", explanation: "" },
  { id: "network", label: "192.168.50.0–192.168.50.150", explanation: "Enthält Netzadresse .0." },
  { id: "infra", label: "192.168.50.1–192.168.50.150", explanation: "Überlappt Router .1 und Server .10." },
  { id: "wrong", label: "192.168.60.100–192.168.60.150", explanation: "Liegt im falschen Subnetz." },
  { id: "broadcast", label: "192.168.50.200–192.168.50.255", explanation: "Enthält Broadcast .255." },
];

export function DhcpFiliusLesson() { const phases = [["Planen", "Netz, Infrastruktur und Pool dokumentieren."], ["Topologie bauen", "DHCP-Server und zwei oder drei PCs über einen Switch verbinden; Vermittlungsrechner optional."], ["Infrastruktur", "Gateway .1 und Server .10 statisch mit /24 konfigurieren."], ["DHCP-Server", "Pool .100–.150, Maske 255.255.255.0 und Gateway .1 konfigurieren; DNS ist für dieses IP-Lab nicht nötig."], ["Clients", "Automatische Netzwerkkonfiguration aktivieren; keine dynamische Adresse manuell vorbelegen."], ["Verifizieren", "Je Client eine beliebige freie .100–.150, Maske /24 und Gateway .1 prüfen; keine feste Reihenfolge erwarten."], ["Konnektivität", "Client–Client, Server und optional Gateway testen; IP-Erreichbarkeit von DNS trennen."], ["DORA", "Falls Filius Verkehr zeigt, konzeptionell Discover, Offer, Request, ACK zuordnen; keine nicht sichtbaren Paketdetails erfinden."], ["Fehler", "DHCP-Dienst vorübergehend deaktivieren und das Verhalten eines neu anfragenden Lab-Clients beobachten."], ["Beheben", "Client, Automatik und Server prüfen; Dienst aktivieren, Konfiguration mit der verfügbaren Filius-Funktion neu beziehen, erneut testen und dokumentieren."]] as const; return <Lesson>
  <LearningObjectives context="lesson" objectives={["eine DHCP-Topologie in Filius planen", "Server, Pool, Maske und Gateway konfigurieren", "Clients automatisch konfigurieren und prüfen", "DORA vorsichtig mit Beobachtungen vergleichen", "einen kontrollierten Fehler untersuchen", "Befund und Fix dokumentieren"]} />
  <Section id="design" title="Labordesign"><dl className="grid gap-3 sm:grid-cols-2"><Data label="Netz" value="192.168.50.0/24" /><Data label="Maske" value="255.255.255.0" /><Data label="Gateway" value="192.168.50.1" /><Data label="DHCP-Server" value="192.168.50.10" /><Data label="Pool" value="192.168.50.100–150" /><Data label="Broadcast" value="192.168.50.255" /></dl><p>Router und Server liegen außerhalb des Pools; <code>.0</code> und <code>.255</code> werden nicht an Hosts vergeben.</p></Section>
  <SingleChoiceCheck title="Adresspool planen" question="Welcher Pool ist mit Router .1 und Server .10 gültig?" options={poolOptions} correctOptionId="valid" successMessage="Richtig: .100–.150 liegt im /24 und überlappt weder Sonder- noch Infrastrukturadressen." inputName="filius-pool" />
  <Section id="phases" title="Zehn Arbeitsphasen"><ol className="space-y-4">{phases.map(([title, text], index) => <li key={title} className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-sm font-bold text-blue-700">Phase {index + 1}</p><h3 className="font-bold text-slate-950">{title}</h3><p className="text-sm">{text}</p></li>)}</ol><aside className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm">Filius-Menüs und Beobachtung unterscheiden sich nach Version. Relay ist nicht Teil des Basislabs, weil keine versionsübergreifend verlässliche Funktion vorausgesetzt wird.</aside></Section>
  <Section id="fault-two" title="Optionale zweite Fehlerkarte"><p>Verteile testweise Gateway <code>192.168.60.1</code>. Es ist für Clients in <code>192.168.50.0/24</code> nicht lokal erreichbar. Korrigiere auf <code>192.168.50.1</code> und teste erneut.</p></Section>
  <Section id="docs" title="Dokumentation"><div className="overflow-x-auto"><table className="min-w-[46rem] border-collapse text-left text-sm"><thead><tr>{["Gerät", "Quelle", "IPv4", "Maske", "Gateway", "DHCP/Pool", "Test", "Problem/Fix"].map((h) => <th key={h} className="border border-slate-300 bg-slate-100 p-3">{h}</th>)}</tr></thead><tbody><tr>{Array.from({ length: 8 }, (_, i) => <td key={i} className="h-14 border border-slate-300 p-3">…</td>)}</tr></tbody></table></div></Section>
  </Lesson>; }

function Lesson({ children }: { children: React.ReactNode }) { return <div className="space-y-10 text-base leading-7 text-slate-700 sm:text-lg sm:leading-8">{children}</div>; }
function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) { return <section aria-labelledby={id} className="space-y-4"><h2 id={id} className="text-2xl font-bold tracking-tight text-slate-950">{title}</h2>{children}</section>; }
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <div className="min-w-0 rounded-xl border border-slate-200 bg-white p-4"><h3 className="font-bold text-slate-950">{title}</h3><div className="mt-2 break-words text-sm">{children}</div></div>; }
function Data({ label, value }: { label: string; value: string }) { return <div className="flex min-w-0 flex-wrap justify-between gap-2 rounded-xl border border-slate-200 bg-white p-4"><dt className="font-bold text-slate-950">{label}</dt><dd className="break-all"><code>{value}</code></dd></div>; }
function Misconceptions({ items }: { items: readonly (readonly [string, string])[] }) { return <section><h2 className="text-2xl font-bold text-slate-950">Typische Fehlvorstellungen</h2><dl className="mt-5 space-y-4">{items.map(([wrong, correction]) => <div key={wrong} className="rounded-xl border border-slate-200 bg-white p-4"><dt className="font-bold text-slate-950">Falsch: „{wrong}“</dt><dd className="mt-2 text-sm"><strong>Korrektur:</strong> {correction}</dd></div>)}</dl></section>; }
