import { LearningObjectives } from "./learning-objectives";
import { MultipleSelectionCheck, type MultipleSelectionOption } from "./multiple-selection-check";
import { DnsRecordMatchingCheck, DnsResolutionOrderCheck } from "./dns-checks";
import { DnsNameVisualization, DnsPurposeFlow, DnsRecordOverview, DnsResolutionFlow } from "./dns-visualizations";

const dnsOptions: readonly MultipleSelectionOption[] = [
  { id: "address", label: "DNS kann Namen mit IP-Adressinformationen verknüpfen.", explanation: "Das ist eine zentrale, aber nicht die einzige Aufgabe von DNS." },
  { id: "multiple", label: "Ein DNS-Name kann mehrere Adressen besitzen.", explanation: "Mehrere A-Records sowie A- und AAAA-Records sind möglich." },
  { id: "different", label: "DNS und DHCP erfüllen unterschiedliche Aufgaben.", explanation: "DHCP liefert Clientkonfiguration; DNS liefert Namensinformationen." },
  { id: "records", label: "DNS kann unterschiedliche Record-Typen speichern.", explanation: "Neben A und AAAA gibt es beispielsweise MX, NS, TXT und SRV." },
  { id: "dhcp", label: "DNS vergibt automatisch die IP-Konfiguration eines Clients.", explanation: "Das ist eine Aufgabe von DHCP, nicht von DNS." },
  { id: "hardware", label: "Ein DNS-Name gehört für immer genau zu einer physischen Netzwerkkarte.", explanation: "Records können sich ändern; Namen sind keine permanente Hardware-Identität und DNS ändert auch keine MAC-Adresse." },
  { id: "routing", label: "DNS ersetzt Routing.", explanation: "DNS löst Namen auf. Routing transportiert IP-Pakete zwischen Netzen." },
  { id: "unique", label: "Jede IP-Adresse darf nur genau einen DNS-Namen besitzen.", explanation: "Mehrere Namen können über Adress-Records oder Aliase denselben Dienst beziehungsweise dieselbe Adresse erreichen." },
];

export function DnsIntroductionLesson() { return <Lesson>
  <LearningObjectives context="lesson" objectives={["DNS als Domain Name System ausschreiben", "den grundlegenden Zweck von DNS erklären", "erklären, dass DNS Namen mit Informationen wie IP-Adressen verknüpft", "Namen von IPv4- und IPv6-Adressen unterscheiden", "DNS von DHCP unterscheiden", "DNS-Namen nicht als permanente Geräteidentität missverstehen", "mehrere Adressen für einen Namen und mehrere Namen für einen Dienst einordnen", "grundlegende DNS-Begriffe der Administration erkennen"]} />
  <Section id="dns-purpose" title="Was ist DNS?"><p><strong>DNS</strong> bedeutet <strong>Domain Name System</strong>. Menschen und Administratoren verwenden Namen wie <code>server01.firma.test</code> oder <code>www.example.test</code> leichter als Zahlenfolgen. DNS ist ein verteiltes Namenssystem, das Namen mit unterschiedlichen Informationen verknüpfen kann.</p><p>Als Einsteiger-Zusammenfassung hilft „Name → IP-Adresse“. Vollständig ist sie nicht: DNS speichert viele <strong>Resource-Record-Typen</strong>, etwa für Mailserver, Nameserver oder Dienste.</p><DnsPurposeFlow /></Section>
  <Section id="name-address" title="Name und Adresse erfüllen andere Aufgaben"><dl className="grid gap-3 sm:grid-cols-3"><Data label="DNS-Name" value="server01.example.test" /><Data label="IPv4-Adresse" value="192.168.10.20" /><Data label="IPv6-Adresse" value="2001:db8::20" /></dl><p>Der Name ist ein menschlicher und administrativer Bezeichner im DNS-Namensraum. Für IP-Kommunikation wird eine IP-Adresse verwendet. Ein Record kann geändert werden: Der Name ist daher nicht dauerhaft an genau eine IP oder ein physisches Gerät gebunden.</p></Section>
  <Section id="fqdn" title="Host-Label, Domain und FQDN"><p>DNS-Namen bestehen aus durch Punkte getrennten, hierarchischen Labels. Bei <code>pc01.schulung.example</code> ist <code>pc01</code> das Host-Label, <code>schulung.example</code> die Domain und der vollständige Name ein <strong>Fully Qualified Domain Name (FQDN)</strong>. „Hostname“ wird in der Praxis je nach Kontext vereinfacht verwendet; wichtig ist, Label und vollständigen DNS-Namen unterscheiden zu können.</p><DnsNameVisualization /></Section>
  <Section id="dns-dhcp" title="DNS ist nicht DHCP"><Compare title="DHCP">Versorgt Clients mit Netzwerkkonfiguration, etwa Adresse, Maske, Gateway und der Adresse eines DNS-Resolvers.</Compare><Compare title="DNS">Beantwortet Anfragen nach Namensinformationen. DHCP kann einem Client sagen: „Nutze DNS-Server <code>192.168.10.5</code>.“ Erst DNS beantwortet anschließend die Namensanfrage.</Compare><p>Ein Heimrouter kann beide Funktionen anbieten. Die Protokolle und Aufgaben bleiben dennoch verschieden; DHCP löst Namen nicht selbst auf.</p></Section>
  <Section id="roles" title="Was macht ein DNS-Server?"><p>„DNS-Server“ kann verschiedene Rollen meinen. Ein Client fragt meist einen konfigurierten <strong>rekursiven Resolver</strong>. Dieser antwortet aus seinem Cache oder beschafft Informationen über die DNS-Hierarchie. Ein <strong>autoritatives DNS-System</strong> liefert maßgebliche Daten für seine Zone. Lektion 2 trennt diese Rollen genauer.</p></Section>
  <Section id="relationships" title="Ein Name, mehrere Adressen – und umgekehrt"><p><code>service.example.test</code> kann einen, mehrere <strong>A-Records</strong> für IPv4 sowie <strong>AAAA-Records</strong> für IPv6 besitzen. Wie ein Client die Antworten nutzt, hängt von Client und Anwendung ab; mehrere Adressen garantieren allein kein bestimmtes Lastverteilungsverhalten.</p><p>Umgekehrt können mehrere Namen durch eigene Adress-Records oder einen <strong>CNAME</strong>-Alias letztlich denselben Dienst oder dieselbe Adresse erreichen. Die Gleichung „ein Gerät = ein Name = eine IP“ ist keine allgemeine DNS-Regel.</p></Section>
  <MultipleSelectionCheck title="DNS-Grundverständnis" question="Welche Aussagen über DNS sind richtig?" options={dnsOptions} correctOptionIds={["address", "multiple", "different", "records"]} successMessage="Richtig: DNS verknüpft Namen mit verschiedenen Informationen, erlaubt mehrere Antworten und bleibt von DHCP getrennt." missedCorrectMessage="Gesucht sind alle Aussagen zu Namensinformationen, mehreren Adressen, getrennten Aufgaben und Record-Typen." inputName="dns-basics" />
  <Misconceptions items={[["DNS ist einfach ein Telefonbuch Name → eine IP.", "Die Analogie hilft, aber DNS ist verteilt, enthält viele Record-Typen und kann mehrere Antworten liefern."], ["DNS und DHCP sind dasselbe.", "DHCP liefert Netzwerkkonfiguration; DNS liefert Namensinformationen."], ["Ein DNS-Name ist permanent mit einem Gerät verbunden.", "Records können wechseln; Namen bezeichnen Namensraum- oder Dienstkonzepte und keine ewige Hardware-Identität."], ["Wenn DNS kaputt ist, funktioniert das Netzwerk gar nicht mehr.", "IP-Kommunikation kann per Adresse noch funktionieren, obwohl Namensauflösung ausfällt. Viele Anwendungen sind dennoch auf DNS angewiesen."]]} />
  <Section id="practice-one" title="Beobachten statt konfigurieren"><Command command="nslookup server01.example.test" text="Eine DNS-spezifische Anfrage unter Windows und in vielen anderen Umgebungen. Nutze im eigenen Lab einen vorhandenen Namen; die Übung benötigt für die App-Validierung kein Internet." /><Command command="getent hosts server01.example.test" text="Unter Linux nutzt getent die konfigurierte Namensauflösung. Optional sind host oder dig geeignet, falls bereits installiert." /><p>Vergleiche konzeptionell <code>ping &lt;hostname&gt;</code> und <code>ping &lt;bekannte IP&gt;</code>. Ein fehlgeschlagener Ping beweist keinen DNS-Fehler: Firewallregeln oder deaktiviertes ICMP können ebenfalls die Ursache sein.</p></Section>
  <Memory items={["DNS = Domain Name System", "Name ≠ IP-Adresse", "DNS ≠ DHCP", "Ein Name kann mehrere Adressen besitzen.", "DNS enthält mehr als nur A-Records."]} />
  <Preview title="So funktioniert eine DNS-Auflösung">Als Nächstes verfolgst du die Anfrage vom Client über Resolver und Cache bis zu Root-, TLD- und autoritativen Servern.</Preview>
 </Lesson>; }

export function DnsResolutionLesson() { return <Lesson>
  <LearningObjectives context="lesson" objectives={["die Rolle des Clients beziehungsweise Stub-Resolvers erklären", "die Rolle eines rekursiven DNS-Resolvers erklären", "rekursive und iterative Auflösung konzeptionell unterscheiden", "Root-, TLD- und autoritative Serverrollen nennen", "einen typischen ungespeicherten Auflösungsablauf beschreiben", "DNS-Caching und TTL erklären", "erkennen, dass Cache-Antworten Hierarchieabfragen vermeiden können", "UDP und TCP auf Port 53 als klassische DNS-Transporte einordnen", "vermeiden, normale Clientanfragen als direkte Root-Anfragen darzustellen"]} />
  <Section id="stub" title="Vom Programm zum Resolver"><p>Eine Anwendung bittet gewöhnlich den lokalen Resolver des Betriebssystems – oft <strong>Stub-Resolver</strong> genannt – um die Auflösung eines Namens. Der Host kennt einen oder mehrere konfigurierte DNS-Resolver und sendet die Anfrage typischerweise dorthin. Normale Anwendungen fragen nicht für jede Webseite selbst Root-Server ab.</p></Section>
  <Section id="recursive" title="Der rekursive Resolver"><p>Der rekursive Resolver soll dem Client eine abschließende Antwort liefern. Er kann sie <strong>aus seinem Cache</strong> beantworten oder weitere DNS-Anfragen durchführen. Solche Resolver gibt es in Unternehmen, beim Internetanbieter, im Heimnetz oder als öffentliche Dienste; hier wird kein Anbieter empfohlen.</p><p>Client → Resolver ist konzeptionell eine Anfrage nach dem Endergebnis. Der Resolver arbeitet Richtung DNS-Hierarchie typischerweise <strong>iterativ</strong>: Eine Zwischenstelle kann statt der finalen Antwort sinngemäß sagen „Frage als Nächstes diese Nameserver“.</p></Section>
  <Section id="hierarchy" title="Root → TLD → autoritativ"><p>Für <code>www.example.com</code> verweist ein Root-Server auf die Nameserver der Top-Level-Domain <code>.com</code>. Ein TLD-Server verweist auf autoritative Nameserver für <code>example.com</code>. Der zuständige autoritative Server liefert den relevanten Record oder eine passende autoritative Antwort.</p><p>Root-Server speichern nicht die IP jeder Webseite, und TLD-Server müssen nicht die finalen A-/AAAA-Records jedes Hosts enthalten.</p><DnsResolutionFlow /></Section>
  <Section id="steps" title="Zehn Schritte als ungespeichertes Lehrbeispiel"><ol className="list-decimal space-y-2 pl-6">{["Client fragt den konfigurierten rekursiven Resolver.", "Resolver prüft den Cache.", "Falls nötig fragt er einen Root-Server.", "Root verweist auf .com-Server.", "Resolver fragt einen .com-TLD-Server.", "TLD verweist auf autoritative Server für example.com.", "Resolver fragt einen autoritativen Server.", "Resolver erhält die relevante Antwort.", "Resolver speichert sie gemäß TTL zwischen.", "Resolver gibt die Antwort an den Client zurück."].map((step) => <li key={step}>{step}</li>)}</ol><aside className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm"><strong>Lehrmodell:</strong> Reale Resolver kennen oft bereits Antworten oder Delegationen im Cache und müssen dann nicht alle Schritte ausführen.</aside></Section>
  <Section id="cache-ttl" title="Cache, TTL und DNS-Änderungen"><p>Temporäres Caching macht Folgeantworten schneller, senkt DNS-Verkehr und entlastet autoritative Infrastruktur. Ein Cache ist nicht dauerhaft und nicht jede Information bleibt gleich lang gespeichert.</p><p><strong>TTL</strong> bedeutet <strong>Time To Live</strong>. Die TTL eines Resource Records beziehungsweise RRsets gibt an, wie lange ein Caching-Resolver die Information normalerweise behalten darf, bevor sie abläuft und erneut abgefragt werden muss. Sie löscht nicht den autoritativen Record.</p><p>Nach einer Änderung können alte Cache-Daten bis zum Ablauf der relevanten TTL sichtbar bleiben. Es gibt keine universelle Regel „DNS dauert immer 24 oder 48 Stunden“; Cache, TTL und Betriebsumgebung bestimmen das Verhalten mit.</p></Section>
  <Section id="ports" title="Klassisches DNS: UDP und TCP Port 53"><div className="grid gap-3 sm:grid-cols-2"><Data label="Häufige normale Anfragen" value="UDP 53" /><Data label="DNS bei Bedarf" value="TCP 53" /></div><p>UDP ist für viele gewöhnliche Anfragen verbreitet. TCP gehört ebenfalls zu DNS und wird unter anderem bei größeren Antworten, Truncation/Fallback und Zonentransfers verwendet. TCP 53 ist daher nicht ausschließlich für Zonentransfers reserviert. Moderne verschlüsselte Transporte wie DoT und DoH existieren, sind aber nicht Kern dieser Lektion.</p></Section>
  <DnsResolutionOrderCheck />
  <Misconceptions items={[["Mein PC fragt bei jeder Webseite zuerst einen Root-Server.", "Üblicherweise fragt der Client seinen konfigurierten rekursiven Resolver."], ["Root-Server kennen die IP-Adresse jeder Webseite.", "Sie liefern hauptsächlich Verweise zur passenden TLD-Infrastruktur."], ["DNS benutzt immer UDP.", "Klassisches DNS nutzt UDP und TCP auf Port 53."], ["TTL sagt, wann ein DNS-Eintrag gelöscht wird.", "TTL steuert die Cache-Lebensdauer, nicht die Existenz des autoritativen Eintrags."], ["DNS-Änderungen brauchen immer 24 oder 48 Stunden.", "Es gibt keine feste Universalzeit; relevante Cache- und TTL-Werte wirken sich aus."]]} />
  <Section id="practice-two" title="Antwort und befragten Resolver beobachten"><Command command="nslookup www.example.com" text="Achte auf den verwendeten DNS-Server und die zurückgegebenen Adressinformationen. Die Ausgabe beweist allein nicht zuverlässig, ob ein Cache getroffen wurde." /><Command command="nslookup -type=ns example.com" text="Zeigt konzeptionell NS-Informationen; genaue Ausgabe kann je nach Betriebssystem variieren. dig ist optional, falls bereits vorhanden." /></Section>
  <Memory items={["Client → Resolver", "Resolver → Cache oder DNS-Hierarchie", "Root → TLD → autoritativ", "TTL = Cache-Lebensdauer", "DNS klassisch: UDP und TCP Port 53"]} />
  <Preview title="DNS-Records verstehen">Als Nächstes lernst du, welche Informationen A, AAAA, CNAME, MX, NS, PTR, TXT und SRV ausdrücken.</Preview>
 </Lesson>; }

export function DnsRecordsLesson() { return <Lesson>
  <LearningObjectives context="lesson" objectives={["einen DNS Resource Record erklären", "wichtige DNS-Record-Typen unterscheiden", "A und AAAA erklären", "CNAME und MX korrekt erklären", "NS einordnen", "PTR und Reverse-Lookup konzeptionell erklären", "TXT konzeptionell erklären", "SRV als Record zur Dienstsuche erkennen", "für typische Szenarien einen passenden Record wählen", "häufige CNAME-, MX- und PTR-Fehler vermeiden"]} />
  <Section id="rr" title="Resource Records sind die DNS-Datensätze"><p>DNS-Zonen enthalten <strong>Resource Records (RR)</strong>. Vereinfacht besitzt ein Record einen <strong>Namen</strong>, einen <strong>Typ</strong>, einen <strong>Wert beziehungsweise Daten</strong> und eine <strong>TTL</strong>.</p><dl className="grid gap-3 sm:grid-cols-4"><Data label="Name" value="www.example.test" /><Data label="Typ" value="A" /><Data label="Wert" value="192.168.10.20" /><Data label="TTL" value="Cache-Dauer" /></dl><p>Die genaue Schreibweise einer Zonendatei folgt in einer späteren Lektion.</p><DnsRecordOverview /></Section>
  <Section id="a-aaaa" title="A und AAAA: Adressinformationen"><p><strong>A</strong> ordnet einen DNS-Namen einer IPv4-Adresse zu, zum Beispiel <code>server01.example.test → 192.168.10.20</code>. Ein Name kann mehrere A-Records besitzen.</p><p><strong>AAAA</strong> ordnet einen Namen einer IPv6-Adresse zu. <code>server01.example.test → 2001:db8::20</code> nutzt den reservierten IPv6-Dokumentationspräfix und ist kein behaupteter Produktivendpunkt.</p></Section>
  <Section id="cname" title="CNAME: Alias auf einen anderen Namen"><p><code>www.example.test CNAME web01.example.test</code> macht <code>www</code> zum Alias des kanonischen DNS-Namens. Erst <code>web01.example.test A 192.168.10.20</code> enthält die IPv4-Adresse.</p><p>CNAME enthält keine IP-Adresse und ist kein HTTP-Redirect. Ein Name mit CNAME sollte nach den DNS-Regeln im Allgemeinen keine anderen Datensätze daneben besitzen.</p></Section>
  <Section id="mx-ns" title="MX und NS: Mail und Autorität"><p><strong>MX</strong> legt Mail-Exchanger als <em>Hostnamen</em> fest: <code>example.test MX 10 mail.example.test</code>. Der Zielname benötigt wiederum Adress-Records. Niedrigere Preference-Zahlen bedeuten die höhere Präferenz.</p><p><strong>NS</strong> identifiziert autoritative Nameserver einer Zone beziehungsweise Delegation, etwa <code>example.test NS ns1.example.test</code>. Das ist weder ein A-Record noch automatisch der rekursive DNS-Server, den ein Client als <code>192.168.x.x</code> konfiguriert hat.</p></Section>
  <Section id="ptr" title="PTR: Reverse DNS"><p><strong>PTR</strong> ordnet im Reverse-DNS-Namensraum eine Adresse konzeptionell einem Namen zu: <code>192.0.2.25 → host.example.test</code>. IPv4 verwendet dafür den besonderen Namensraum <code>in-addr.arpa</code>; der genaue Zonenaufbau folgt später.</p><p>Reverse DNS ist nicht automatisch die Umkehrung jedes A-Records. Forward- und Reverse-DNS werden separat konfiguriert.</p></Section>
  <Section id="txt-srv" title="TXT und SRV"><p><strong>TXT</strong> speichert Textdaten zu einem Namen, etwa für Domain-Verifikation, E-Mail-Richtlinien oder Dienstmetadaten. Solche Daten sind im jeweiligen DNS-Geltungsbereich abfragbar und kein sicherer Ablageort für Geheimnisse.</p><p><strong>SRV</strong> beschreibt, wo ein Dienst erreichbar ist: Dienst, Protokoll, Zielhost und Port sowie Priority-/Weight-Konzepte. Das unterstützt etwa Dienstsuche bei Active Directory und anderen Anwendungen; den vollständigen Auswahlalgorithmus brauchst du hier noch nicht.</p></Section>
  <DnsRecordMatchingCheck />
  <Section id="multiple-records" title="Mehrere Records und TTL"><p><code>www.example.test</code> kann beispielsweise die A-Records <code>192.0.2.10</code> und <code>192.0.2.11</code> sowie den AAAA-Record <code>2001:db8::10</code> besitzen. DNS allein garantiert dadurch keine bestimmte Lastverteilung; Clients und Anwendungen können die Antworten unterschiedlich nutzen.</p><p>Records beziehungsweise RRsets tragen TTL-Werte für ihre Cache-Dauer. Es gibt keinen universell besten Zahlenwert, den du auswendig lernen musst.</p></Section>
  <Misconceptions items={[["CNAME enthält direkt eine IP-Adresse.", "CNAME verweist auf einen anderen DNS-Namen; A beziehungsweise AAAA enthalten Adressinformationen."], ["MX zeigt direkt auf eine IP.", "Das MX-Ziel ist ein Hostname, der seinerseits über Adress-Records aufgelöst wird."], ["PTR entsteht automatisch aus jedem A-Record.", "Reverse DNS wird separat konfiguriert."], ["NS ist der DNS-Server, den ich auf meinem PC eintrage.", "NS kennzeichnet autoritative Nameserver einer Zone; der Client nutzt gewöhnlich einen rekursiven Resolver."], ["TXT-Einträge sind geheim.", "Exponierte DNS-Daten sind im jeweiligen Geltungsbereich abfragbar und nicht privat."]]} />
  <Section id="practice-three" title="Record-Typen beobachten"><div className="grid gap-3 sm:grid-cols-2">{["nslookup -type=A example.com", "nslookup -type=AAAA example.com", "nslookup -type=MX example.com", "nslookup -type=NS example.com"].map((command) => <Command key={command} command={command} text="Die Ausgabe hängt von Umgebung und aktuellen DNS-Daten ab." />)}</div><p>Für PTR kann <code>nslookup &lt;IP-Adresse&gt;</code> konzeptionell einen Reverse-Lookup zeigen. Unter Linux ist <code>dig example.com A</code> optional, aber nicht vorausgesetzt.</p></Section>
  <Section id="design" title="Kleine DNS-Planungsübung für firma.test"><p>Gefordert sind Webserver <code>192.168.10.20</code>, Mailserver <code>192.168.10.30</code> und DNS-Server <code>192.168.10.5</code>. Eine konzeptionelle Lösung:</p><dl className="grid gap-3 sm:grid-cols-2"><Data label="www.firma.test A" value="192.168.10.20" /><Data label="mail.firma.test A" value="192.168.10.30" /><Data label="firma.test MX" value="mail.firma.test" /><Data label="firma.test NS" value="dns.firma.test" /><Data label="dns.firma.test A" value="192.168.10.5" /></dl><p><code>.test</code> ist für Lehrbeispiele geeignet. <code>.local</code> wird hier bewusst nicht als allgemeines privates DNS-Suffix verwendet, weil es reale Multicast-DNS-Semantik besitzt.</p></Section>
  <Memory items={["A → IPv4; AAAA → IPv6", "CNAME → anderer DNS-Name", "MX → Mailserver-Hostname", "NS → autoritative Nameserver", "PTR → Reverse DNS", "TXT ist nicht geheim; SRV beschreibt Dienste"]} />
  <Preview title="DNS-Zonen, autoritative Server und Delegation">In der nächsten, noch geplanten Lektion geht es darum, was eine DNS-Zone ist, warum Domain und Zone nicht immer identisch sind, wie autoritative Server und NS-Records zusammenspielen und wie Delegation sowie Primary-/Secondary-Autorität grundlegend funktionieren.</Preview>
 </Lesson>; }

function Lesson({ children }: { children: React.ReactNode }) { return <div className="space-y-10 text-base leading-7 text-slate-700 sm:text-lg sm:leading-8">{children}</div>; }
function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) { return <section aria-labelledby={id} className="space-y-4"><h2 id={id} className="text-2xl font-bold tracking-tight text-slate-950">{title}</h2>{children}</section>; }
function Data({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-xl border border-slate-200 bg-white p-4"><dt className="text-sm font-semibold text-slate-500">{label}</dt><dd className="mt-1 break-all"><code className="font-bold text-blue-950">{value}</code></dd></div>; }
function Compare({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6">{children}</p></div>; }
function Command({ command, text }: { command: string; text: string }) { return <div className="min-w-0 rounded-xl border border-slate-200 bg-slate-950 p-4 text-white"><code className="block break-all font-bold text-blue-200">{command}</code><p className="mt-2 text-sm leading-6 text-slate-200">{text}</p></div>; }
function Misconceptions({ items }: { items: readonly (readonly [string, string])[] }) { return <section><h2 className="text-2xl font-bold text-slate-950">Typische Fehlvorstellungen</h2><dl className="mt-5 space-y-4">{items.map(([wrong, correction]) => <div key={wrong} className="rounded-xl border border-slate-200 bg-white p-4"><dt className="font-bold text-slate-950">Falsch: „{wrong}“</dt><dd className="mt-2 text-sm"><strong>Korrektur:</strong> {correction}</dd></div>)}</dl></section>; }
function Memory({ items }: { items: readonly string[] }) { return <aside className="rounded-2xl border border-blue-200 bg-blue-950 p-5 text-white sm:p-6"><h2 className="text-sm font-bold uppercase tracking-[0.12em] text-blue-200">Merksätze</h2><ul className="mt-3 space-y-2 font-semibold">{items.map((item) => <li key={item}>{item}</li>)}</ul></aside>; }
function Preview({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-slate-50 p-5 sm:p-6"><p className="text-sm font-semibold text-blue-700">Nächste Lektion</p><h2 className="mt-1 text-xl font-bold text-slate-950">{title}</h2><p className="mt-3 text-sm leading-6">{children}</p></section>; }
