import { LearningObjectives } from "./learning-objectives";
import { DnsFiliusCheck, DnsTroubleshootingCheck } from "./dns-advanced-checks";
import { SingleChoiceCheck } from "./single-choice-check";

const roleOptions = [
  { id: "authority", label: "Rekursiver Resolver → Clientanfragen auflösen; autoritativer Server → maßgebliche Zonendaten liefern; NS → autoritativen Nameserver nennen; SOA → Zonenautorität und Metadaten beschreiben; Delegation → Autorität für einen Child-Namensraum zuweisen", explanation: "Diese Zuordnung trennt Clientauflösung, Zonenautorität, Records und Autoritätsgrenze korrekt." },
  { id: "all-resolvers", label: "Rekursiver Resolver und autoritativer Server sind immer dieselbe Rolle; NS ist die Resolveradresse des PCs", explanation: "Rollen können technisch auf einem System zusammenkommen, bleiben aber konzeptionell verschieden. NS bezeichnet autoritative Nameserver." },
  { id: "copy", label: "Delegation kopiert alle Records; SOA ist ein IPv4-Record; NS ist nur ein Backup", explanation: "Delegation setzt eine Autoritätsgrenze, SOA enthält Zonenmetadaten und mehrere NS können regulär antworten." },
] as const;

export function DnsZonesLesson() { return <Lesson>
  <LearningObjectives context="lesson" objectives={["eine DNS-Zone erklären und vom Domain-Namensraum unterscheiden", "autoritative und rekursive Serverrollen unterscheiden", "Primary und Secondary als regulär antwortende autoritative Server einordnen", "NS und SOA erklären", "Delegation zwischen Parent- und Child-Zone beschreiben", "Glue Records konzeptionell erklären", "Forward- und Reverse-Zonen unterscheiden"]} />
  <Section id="domain-zone" title="Domain und Zone sind verwandt – aber nicht identisch"><p>Eine <strong>Domain</strong> ist ein Name beziehungsweise Teil des hierarchischen DNS-Namensraums. Eine <strong>DNS-Zone</strong> ist der administrativ verwaltete Teil dieses Namensraums, für den ein Satz autoritativer Server verantwortlich ist.</p><p><code>example.test</code> kann zunächst eine Zone sein, die auch Namen unter <code>training.example.test</code> enthält. Wird <code>training.example.test</code> delegiert, ist es weiterhin eine Subdomain und zugleich der <strong>Zone Apex</strong> – der oberste Name – einer eigenen Child-Zone. Nicht jede Subdomain ist automatisch eine Zone.</p></Section>
  <Section id="authority" title="Autoritative Server, Primary und Secondary"><p>Ein <strong>rekursiver Resolver</strong> beschafft Antworten für Clients. Ein <strong>autoritatives DNS-System</strong> antwortet aus den maßgeblichen Zonendaten der Zonen, die es bedient. Ein Server kann technisch mehrere Rollen übernehmen; die Rollen bleiben getrennt.</p><div className="grid gap-4 sm:grid-cols-2"><Card title="Primary">Hält traditionell die ursprünglichen beziehungsweise editierbaren Zonendaten.</Card><Card title="Secondary">Übernimmt replizierte Zonendaten, traditionell per Zonentransfer. Er ist nicht nur ein Notfallserver.</Card></div><p>Beide können im Normalbetrieb autoritativ antworten. Mehrere Server verbessern Redundanz, Verfügbarkeit und verteilte Bereitstellung; exakt zwei sind nicht vorgeschrieben.</p></Section>
  <Section id="soa-ns" title="SOA und NS"><Record type="SOA" value="example.test SOA ns1.example.test … serial …" text="Start of Authority: kennzeichnet Zonenautorität und enthält administrative Zeit-/Synchronisationsmetadaten, eine Seriennummer sowie das Primary-Nameserver-Konzept. Nicht jedes Feld muss auswendig gelernt werden." /><div className="grid gap-3 sm:grid-cols-2"><Record type="NS" value="example.test NS ns1.example.test" text="Nennt einen autoritativen Nameserver." /><Record type="NS" value="example.test NS ns2.example.test" text="Ein weiterer regulär antwortender autoritativer Nameserver." /></div></Section>
  <Section id="delegation" title="Delegation schafft eine Autoritätsgrenze"><p>Die Parent-Zone <code>example.test</code> veröffentlicht NS-Delegationsinformationen für <code>training.example.test</code>. Resolver erfahren so, dass die Child-Zone von <code>ns1.training.example.test</code> und <code>ns2.training.example.test</code> autoritativ bedient wird. Das ist keine Kopie aller Records: Die Child-Zone kann unabhängig verwaltet werden.</p><DelegationVisual /></Section>
  <Section id="glue" title="Glue löst eine Startabhängigkeit"><p>Liegt der Nameservername innerhalb des delegierten Namensraums – etwa <code>ns1.training.example.test</code> für <code>training.example.test</code> –, benötigt ein Resolver dessen Adresse, bevor er die Child-Zone fragen kann. Parent-seitige <strong>Glue-Adressdaten</strong> liefern diesen Startpunkt.</p><p>Diese Situation heißt auch <em>in-bailiwick</em>: Der Nameservername liegt „innerhalb“ der Delegation. Glue ist besonders dann nötig, aber nicht für jede Delegation und nicht für jede DNS-Adresse.</p></Section>
  <Section id="forward-reverse" title="Forward- und Reverse-Zonen"><div className="grid gap-4 sm:grid-cols-2"><Card title="Forward-Zone"><code>server.firma.test A 192.168.10.20</code>: Name führt zu Records wie A oder AAAA.</Card><Card title="Reverse-Zone"><code>20.10.168.192.in-addr.arpa PTR server.firma.test</code>: Reverse-Namensraum führt per PTR zum Namen. IPv4 nutzt <code>in-addr.arpa</code>, IPv6 <code>ip6.arpa</code>.</Card></div><p>Forward und Reverse werden getrennt administriert; ein A-Record erzeugt nicht automatisch PTR.</p></Section>
  <SingleChoiceCheck title="Rollen und Records zuordnen" question="Welche Zuordnung ist vollständig richtig?" options={roleOptions} correctOptionId="authority" successMessage="Richtig: Resolver, Autorität, NS, SOA und Delegation erfüllen unterschiedliche Aufgaben." inputName="dns-zone-roles" />
  <Misconceptions items={[["Domain und Zone sind immer dasselbe.", "Eine Zone ist eine administrative Teilmenge des Namensraums; Delegationen können Grenzen schaffen."], ["Jede Subdomain ist automatisch eine Zone.", "Erst eine Delegation kann die Subdomain zur eigenständigen Child-Zone machen."], ["Ein Secondary antwortet nur bei Ausfall des Primary.", "Beide können regulär autoritativ antworten."], ["NS ist der DNS-Server meines PCs.", "NS nennt autoritative Nameserver, nicht automatisch den rekursiven Clientresolver."], ["Delegation bedeutet, alle Records zu kopieren.", "Delegation weist Autorität für einen Child-Namensraum zu."], ["Glue ist für jede DNS-Adresse zwingend.", "Glue löst insbesondere die Abhängigkeit bei Nameservernamen innerhalb der delegierten Zone."]]} />
  <Section id="practice" title="Übung: azubi.firma.test"><ol className="list-decimal space-y-2 pl-6"><li>Parent-Namensraum ist <code>firma.test</code>.</li><li><code>azubi.firma.test</code> wird durch Delegation zur eigenständigen Zone.</li><li>Die Parent-Zone veröffentlicht dafür <strong>NS</strong>-Informationen.</li><li>Die benannten Server bedienen die Child-Zone autoritativ.</li></ol></Section>
  <Preview title="DNS-Fehleranalyse">Als Nächstes grenzt du Resolver-, Antwort-, Cache-, Zonen- und Delegationsfehler anhand von Belegen ein.</Preview>
 </Lesson>; }

export function DnsTroubleshootingLesson() { const steps = ["Ist grundlegende IP-Konnektivität vorhanden?", "Welcher DNS-Resolver ist konfiguriert?", "Ist dieser Resolver erreichbar?", "Liefert die gezielte Abfrage eine Antwort?", "Ist der zurückgegebene Record korrekt?", "Antwortet ein anderer Resolver anders?", "Können Cache und TTL alte Daten erklären?", "Stimmen autoritative Zone und Record?", "Ist die Delegation korrekt?", "Sind Forward und Reverse dort konsistent, wo es benötigt wird?"]; return <Lesson>
  <LearningObjectives context="lesson" objectives={["DNS- von allgemeinen Netzwerkfehlern unterscheiden", "Resolverkonfiguration und DNS-Records gezielt prüfen", "NXDOMAIN, SERVFAIL, Timeout und leere Antworten unterscheiden", "falsche oder alte Daten anhand Cache und TTL untersuchen", "rekursive von autoritativen Problemen trennen", "Forward-/Reverse-Abweichungen erkennen", "nslookup und optional dig sinnvoll einsetzen"]} />
  <Section id="method" title="Erst Belege sammeln, dann verändern"><ol className="grid gap-3 sm:grid-cols-2">{steps.map((step, index) => <li key={step} className="rounded-xl border border-slate-200 bg-white p-4"><strong className="text-blue-700">{index + 1}.</strong> {step}</li>)}</ol><p>Beginne nicht mit zufälligem Cache-Leeren. Jeder Schritt soll eine Hypothese prüfen.</p></Section>
  <Section id="ip-vs-dns" title="IP funktioniert, Name nicht"><p>Die Anwendung erreicht <code>192.168.10.20</code>, aber nicht <code>server.firma.test</code>. Das ist starke Evidenz für eine Untersuchung der Namensauflösung, beweist aber nicht, dass DNS die einzig mögliche Ursache ist: Anwendungen können Namen und Dienste zusätzlich anders behandeln.</p></Section>
  <Section id="outcomes" title="Antworttypen unterscheiden"><div className="grid gap-3 sm:grid-cols-2"><Card title="NXDOMAIN">Eine gültige DNS-Antwort: Der abgefragte Name existiert im Antwortkontext nicht.</Card><Card title="SERVFAIL">Resolver/Server konnte die Anfrage nicht erfolgreich abschließen, etwa wegen Upstream-, Autoritäts-, Delegations-, Server- oder in realen Netzen DNSSEC-Validierungsproblemen.</Card><Card title="Timeout / keine Antwort">Mögliche Ursachen: unerreichbarer Server, Firewall/Pfad, Dienst lauscht nicht, Ausfall, Paketverlust. Das ist nicht NXDOMAIN.</Card><Card title="Leere Antwort">Der Name kann existieren, aber keinen Record des abgefragten Typs besitzen. A, AAAA, MX, NS und PTR bewusst wählen.</Card></div></Section>
  <Section id="tools" title="DNS gezielt abfragen"><div className="grid gap-3 sm:grid-cols-2"><Command value="nslookup server.firma.test">Fragt typischerweise den konfigurierten/default Resolver und zeigt dessen DNS-Antwort. Das bildet nicht zwingend den gesamten Resolverpfad jeder Anwendung ab.</Command><Command value="dig server.firma.test A">Optional auf Linux/Unix-artigen Systemen; keine Installation erforderlich.</Command><Command value="dig firma.test MX">Fragt bewusst Mail-Records.</Command><Command value="dig firma.test NS">Prüft Nameserverinformation.</Command></div></Section>
  <Section id="resolver-config" title="Konfigurierten Resolver prüfen"><div className="grid gap-3 sm:grid-cols-2"><Command value="ipconfig /all">Zeigt unter Windows unter anderem konfigurierte DNS-Server.</Command><Command value="ipconfig /displaydns">Kann den lokalen Windows-Resolvercache anzeigen.</Command><Command value="cat /etc/resolv.conf">Hinweis unter Linux; die Datei kann von systemd-resolved, NetworkManager oder anderer Software erzeugt sein und ist nicht immer allein maßgeblich.</Command><Command value="resolvectl status">Optional, falls die jeweilige Linux-Umgebung systemd-resolved nutzt.</Command></div><aside className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm"><code>ipconfig /flushdns</code> verändert den lokalen Resolvercache. Auf Kunden-/Produktivsystemen nicht blind und niemals als ersten Diagnoseschritt verwenden; vorher Belege sichern.</aside></Section>
  <Section id="stale" title="Falsche oder alte Antwort"><p><code>server.firma.test</code> soll nun <code>192.168.10.30</code> liefern, der Client sieht aber <code>192.168.10.20</code>. Vergleiche konfigurierten Resolver und – falls bekannt – autoritativen Server, prüfe TTL und kontrolliere den autoritativen Record. Ein Cache innerhalb der TTL ist möglich; eine fehlerhafte Zonendatei ebenso.</p><p>Cache-Schichten können in Anwendung/Browser, Betriebssystem/Stub, lokalem rekursivem Resolver oder Upstream liegen; nicht jedes System besitzt alle. Darum können zwei Clients zeitweise unterschiedliche Antworten erhalten.</p></Section>
  <Section id="wrong-resolver" title="Falscher Resolver durch DHCP"><p>Erhält ein Client <code>192.168.10.5</code> statt des vorgesehenen Firmenresolvers <code>192.168.10.10</code>, können interne Namen ausfallen oder anders beantwortet werden, obwohl externe Auflösung noch klappt. DHCP kann eine falsche DNS-Serveradresse verteilen, obwohl die Adressvergabe selbst erfolgreich ist. Gateway und DNS bleiben verschiedene Angaben.</p></Section>
  <Section id="reverse-mismatch" title="Forward und Reverse getrennt prüfen"><p><code>server.firma.test A 192.168.10.20</code>, aber der PTR liefert <code>oldserver.firma.test</code>. A und PTR werden getrennt gepflegt. Die Abweichung kann Administration, Logs oder bestimmte Richtlinien/Dienste betreffen, ist aber nicht für jede Anwendung zwingend fatal.</p></Section>
  <DnsTroubleshootingCheck />
  <Section id="two-clients" title="Zwei Clients, zwei Antworten"><p>Client A erhält die alte, Client B die neue Adresse. <strong>Ein möglicher, naheliegender Prüfpunkt ist</strong> der jeweilige Resolverpfad mit Cache und TTL. Das ist eine Hypothese, keine garantierte Ursache.</p></Section>
  <Misconceptions items={[["Wenn ping per Name nicht klappt, ist DNS definitiv kaputt.", "Ping hängt auch von ICMP und Zielverhalten ab; nutze DNS-spezifische Werkzeuge."], ["NXDOMAIN bedeutet, der DNS-Server ist nicht erreichbar.", "NXDOMAIN ist eine negative DNS-Antwort; Unerreichbarkeit zeigt sich eher als Timeout."], ["DNS-Cache löschen ist immer der erste Schritt.", "Erst Zustand und Antworten dokumentieren."], ["Wenn eine IP erreichbar ist, funktioniert automatisch DNS.", "IP-Kommunikation und Namensauflösung sind getrennte Funktionen."], ["A und PTR sind automatisch gekoppelt.", "Forward und Reverse werden separat konfiguriert."], ["SERVFAIL bedeutet immer, der Name existiert nicht.", "SERVFAIL ist eine andere Fehlerklasse ohne eindeutige Einzelursache."]]} />
  <Checklist />
  <Preview title="Praxis: DNS mit Filius">Im Abschlusslab konfigurierst, testest und störst du eine kleine DNS-Umgebung kontrolliert.</Preview>
 </Lesson>; }

export function DnsFiliusLesson() { const phases = [["Adressierung planen", "Netz, Infrastruktur, Client und Namen dokumentieren."], ["Topologie bauen", "DNS-Server, Client und Anwendungsserver über einen Switch verbinden; Router nur ergänzen, wenn der Gateway-Kontext benötigt wird."], ["Infrastruktur konfigurieren", "Gateway optional .1, DNS-Server .10 und Anwendungsserver .20 statisch im /24 konfigurieren."], ["DNS-Dienst konfigurieren", "Domain/Zone firma.test und den A-Eintrag server → 192.168.50.20 anlegen; daraus entsteht server.firma.test."], ["Client konfigurieren", "192.168.50.100/24 und DNS-Server 192.168.50.10 eintragen; Gateway .1 nur bei vorhandenem Router."], ["IP zuerst testen", "Zuerst direkte Erreichbarkeit von 192.168.50.20 mit einer verfügbaren Filius-Funktion prüfen."], ["Namen testen", "Danach server.firma.test auflösen beziehungsweise den Dienst per Name verwenden."], ["DNS-Verkehr beobachten", "Falls Filius Verkehrsanalyse anbietet: Anfrage Client → DNS-Server, Antwort, Namen und sichtbare Zieladresse identifizieren; keine nicht angezeigten Felder annehmen."], ["Fehler einbauen", "Client-DNS kontrolliert auf unbenutzte 192.168.50.99 ändern und IP- gegenüber Namensfunktion vergleichen."], ["Diagnostizieren", "Resolveradresse korrigieren; danach optional A-Record auf falsche .30 setzen und zwischen antwortendem DNS-Dienst und falschen Daten unterscheiden."], ["Dokumentieren", "Sollwerte, Beobachtung, Ursache, Fix und erneuten Test festhalten."]] as const; return <Lesson>
  <LearningObjectives context="lesson" objectives={["eine kleine DNS-Umgebung in Filius planen", "DNS-Server, Clientresolver und A-Record korrekt konfigurieren", "IP-Konnektivität vor Namensauflösung prüfen", "DNS-Verkehr vorsichtig beobachten", "zwei kontrollierte DNS-Fehler diagnostizieren", "Ergebnisse strukturiert dokumentieren"]} />
  <Section id="lab-network" title="Das sichere Lab-Netz"><dl className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Data label="Netz" value="192.168.50.0/24" /><Data label="Maske" value="255.255.255.0" /><Data label="Gateway (optional)" value="192.168.50.1" /><Data label="DNS-Server" value="192.168.50.10" /><Data label="Anwendungsserver" value="192.168.50.20" /><Data label="Client" value="192.168.50.100" /></dl><p>Gewöhnliche Hosts reichen von <code>192.168.50.1</code> bis <code>192.168.50.254</code>; <code>.0</code> ist Netz- und <code>.255</code> Broadcast-Adresse. Alle geplanten Hosts sind gültig und konfliktfrei.</p></Section>
  <Section id="lab-records" title="Zone und Record"><Record type="A" value="server.firma.test → 192.168.50.20" text="Falls Filius in einer Zone nur ein Host-Label erwartet, trage server innerhalb von firma.test ein. Das Ergebnis bleibt der FQDN server.firma.test." /><p>Optional kann <code>www.firma.test</code> als weiterer A-Record dieselbe Adresse erhalten. CNAME oder MX sind nicht erforderlich, weil ihre zuverlässige Unterstützung nicht vorausgesetzt wird. <code>.test</code> wird bewusst statt <code>.local</code> verwendet.</p></Section>
  <Section id="lab-phases" title="Elf Arbeitsphasen"><ol className="space-y-3">{phases.map(([title, text], index) => <li key={title} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-sm font-bold text-blue-700">Phase {index + 1}</p><h3 className="font-bold text-slate-950">{title}</h3><p className="text-sm">{text}</p></li>)}</ol><p className="rounded-xl bg-slate-50 p-4 text-sm">Filius-Versionen können Menüs und Beobachtungen unterschiedlich darstellen. Arbeite aufgabenorientiert und behaupte keine Paketdetails, die das Werkzeug nicht zeigt. Das Lab benötigt kein Internet.</p></Section>
  <Section id="faults" title="Was die kontrollierten Fehler zeigen"><div className="grid gap-4 sm:grid-cols-2"><Card title="Resolver auf .99">Direkte IP-Kommunikation kann weiter funktionieren, während Namensauflösung scheitert: falsche DNS-Serverkonfiguration.</Card><Card title="A-Record auf .30">DNS kann erfolgreich antworten und dennoch falsche Daten liefern. Prüfe Antwortwert und anschließend den adressierten Dienst.</Card></div><p>Optional kann <code>doesnotexist.firma.test</code> eine negative Antwort demonstrieren. Erwarte den Begriff NXDOMAIN nur, wenn die Filius-Version ihn tatsächlich anzeigt.</p></Section>
  <DnsFiliusCheck />
  <Section id="documentation" title="Dokumentationsvorlage"><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead><tr>{["Gerät", "IPv4", "Maske", "Gateway", "DNS-Server", "DNS-Name", "Record/ Wert", "Testergebnis", "Problem", "Fix"].map((heading) => <th key={heading} className="border-b p-3">{heading}</th>)}</tr></thead><tbody><tr>{Array.from({ length: 10 }, (_, index) => <td key={index} className="border-b p-3">—</td>)}</tr></tbody></table></div><p>Die Vorlage wird nicht gespeichert und verändert keinen Lernfortschritt.</p></Section>
 </Lesson>; }

function DelegationVisual() { return <figure className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><figcaption className="font-bold text-blue-950">Parent- und Child-Zone mit Delegation</figcaption><div className="mt-4 grid gap-3 text-center md:grid-cols-[1fr_auto_1fr_auto_1fr] md:items-center"><Flow title="Parent-Zone" value="example.test" /><Arrow text="Delegation per NS" /><Flow title="Child-Zone" value="training.example.test" /><Arrow text="autoritative Server" /><Flow title="Namen der Child-Zone" value="pc01… / server01…" /></div><p className="mt-4 text-sm">Die Parent-Zone delegiert die Child-Zone an <code>ns1.training.example.test</code> und <code>ns2.training.example.test</code>; diese bedienen Namen wie <code>pc01.training.example.test</code> autoritativ.</p></figure>; }
function Flow({ title, value }: { title: string; value: string }) { return <div className="min-w-0 rounded-xl border border-slate-200 bg-white p-4"><strong>{title}</strong><code className="mt-1 block break-all">{value}</code></div>; }
function Arrow({ text }: { text: string }) { return <div className="text-sm font-bold text-blue-800"><span className="md:hidden">↓ </span><span className="hidden md:inline">→ </span>{text}</div>; }
function Checklist() { const groups = [["Client", "IP/Gateway okay? · DNS-Server konfiguriert? · Resolver erreichbar?"], ["Query", "Name und RR-Typ korrekt? · Antwort, Timeout, NXDOMAIN oder SERVFAIL?"], ["Resolver", "Cache/TTL? · Upstream? · passende interne Umgebung/Ansicht, falls vorhanden?"], ["Autoritativ", "Record und Zone korrekt? · Delegation? · TTL?"]] as const; return <Section id="checklist" title="Praktische Checkliste"><dl className="grid gap-3 sm:grid-cols-2">{groups.map(([title, text]) => <div key={title} className="rounded-xl border border-slate-200 bg-white p-4"><dt className="font-bold text-slate-950">{title}</dt><dd className="mt-2 text-sm">{text}</dd></div>)}</dl></Section>; }
function Lesson({ children }: { children: React.ReactNode }) { return <div className="space-y-10 text-base leading-7 text-slate-700 sm:text-lg sm:leading-8">{children}</div>; }
function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) { return <section aria-labelledby={id} className="space-y-4"><h2 id={id} className="text-2xl font-bold tracking-tight text-slate-950">{title}</h2>{children}</section>; }
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <article className="min-w-0 rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6">{children}</p></article>; }
function Record({ type, value, text }: { type: string; value: string; text: string }) { return <article className="min-w-0 rounded-xl border border-blue-200 bg-blue-50 p-4"><h3><code className="font-bold text-blue-950">{type}</code></h3><code className="mt-2 block break-all text-sm">{value}</code><p className="mt-2 text-sm">{text}</p></article>; }
function Command({ value, children }: { value: string; children: React.ReactNode }) { return <article className="min-w-0 rounded-xl bg-slate-950 p-4 text-white"><code className="block break-all font-bold text-blue-200">{value}</code><p className="mt-2 text-sm leading-6 text-slate-200">{children}</p></article>; }
function Data({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-xl border border-slate-200 bg-white p-4"><dt className="text-sm font-semibold text-slate-500">{label}</dt><dd className="mt-1"><code className="break-all font-bold text-blue-950">{value}</code></dd></div>; }
function Misconceptions({ items }: { items: readonly (readonly [string, string])[] }) { return <section><h2 className="text-2xl font-bold text-slate-950">Typische Fehlvorstellungen</h2><dl className="mt-5 space-y-3">{items.map(([wrong, correction]) => <div key={wrong} className="rounded-xl border border-slate-200 bg-white p-4"><dt className="font-bold text-slate-950">Falsch: „{wrong}“</dt><dd className="mt-2 text-sm"><strong>Korrektur:</strong> {correction}</dd></div>)}</dl></section>; }
function Preview({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><p className="text-sm font-semibold text-blue-700">Nächste Lektion</p><h2 className="mt-1 text-xl font-bold text-slate-950">{title}</h2><p className="mt-3 text-sm">{children}</p></section>; }
