const box = "min-w-0 rounded-xl border border-slate-200 bg-white p-4 text-center shadow-sm";

export function DnsNameVisualization() {
  return <figure className="mt-5 rounded-2xl border border-blue-200 bg-blue-50 p-5 sm:p-6"><figcaption className="font-bold text-blue-950">Ein DNS-Name besteht aus hierarchischen Labels</figcaption><div className="mt-4 grid gap-3 sm:grid-cols-3"><Label value="pc01" meaning="Host-Label" /><Label value="schulung" meaning="untergeordnete Domain" /><Label value="example" meaning="übergeordnete Domain" /></div><p className="mt-4 break-words text-sm leading-6 text-blue-950"><code>pc01.schulung.example.</code> ist die absolute Schreibweise. Der abschließende Punkt steht für das unsichtbare Root-Label und wird im Alltag meist weggelassen.</p></figure>;
}
function Label({ value, meaning }: { value: string; meaning: string }) { return <div className={box}><code className="font-bold text-blue-950">{value}</code><p className="mt-1 text-xs text-slate-600">{meaning}</p></div>; }

export function DnsPurposeFlow() {
  return <figure className="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-5 sm:p-6"><figcaption className="font-bold text-slate-950">Vereinfachtes Anfrageprinzip – noch ohne DNS-Hierarchie</figcaption><div className="mt-5 grid items-center gap-3 text-center sm:grid-cols-[1fr_auto_1fr_auto_1fr]"><FlowBox label="Name" value="server01.example.test" /><Arrow label="Anfrage" /><FlowBox label="Resolver" value="DNS-Auflösung" /><Arrow label="Antwort" /><FlowBox label="Adressinformation" value="192.168.10.20" /></div></figure>;
}
function FlowBox({ label, value }: { label: string; value: string }) { return <div className={box}><p className="text-xs font-bold uppercase tracking-wide text-blue-700">{label}</p><code className="mt-1 block break-all font-bold text-slate-950">{value}</code></div>; }
function Arrow({ label }: { label: string }) { return <div className="text-sm font-semibold text-slate-600"><span className="sm:hidden">↓ </span><span className="hidden sm:inline">→ </span>{label}</div>; }

export function DnsResolutionFlow() {
  const hierarchy = [["Root-Server", "Verweis zu .com"], [".com-TLD-Server", "Verweis zu example.com"], ["Autoritativer Server", "Antwort für www.example.com"]] as const;
  return <figure className="mt-5 rounded-2xl border border-blue-200 bg-blue-50 p-5 sm:p-7"><figcaption className="font-bold text-blue-950">Typischer ungespeicherter Lehrbuchablauf</figcaption><div className="mt-5 grid gap-3 lg:grid-cols-[1fr_auto_1.35fr_auto_1fr] lg:items-center"><FlowBox label="Client-Anfrage" value="www.example.com" /><Arrow label="rekursiv gewünscht" /><div className={box}><p className="font-bold text-slate-950">Rekursiver Resolver</p><p className="mt-1 text-sm">1. Cache prüfen</p><p className="text-sm">2. bei Bedarf iterativ fragen</p></div><Arrow label="iterative Anfragen" /><ol className="space-y-2">{hierarchy.map(([title, text], index) => <li key={title} className={box}><p className="text-xs font-bold text-blue-700">{index + 1}</p><p className="font-bold text-slate-950">{title}</p><p className="text-xs text-slate-600">{text}</p></li>)}</ol></div><div className="mt-4 rounded-xl bg-blue-950 p-4 text-sm text-white"><strong>Finale Antwort:</strong> Autoritative Information → Resolver-Cache (gemäß TTL) → Client. Ein Cache-Treffer überspringt die Hierarchie.</div></figure>;
}

const recordRows = [
  ["A", "Name → IPv4", "www.example.test → 192.0.2.10"], ["AAAA", "Name → IPv6", "www.example.test → 2001:db8::10"], ["CNAME", "Alias → kanonischer Name", "www → web01.example.test"], ["MX", "Domain → Mailserver-Hostname", "example.test → mail.example.test"], ["NS", "Zone → autoritativer Nameserver", "example.test → ns1.example.test"], ["PTR", "Reverse-Namensraum → Name", "192.0.2.25 → host.example.test"], ["TXT", "Name → Textdaten", "Verifikation oder Richtlinieninformation"], ["SRV", "Dienst → Ziel und Port", "Dienstsuche für Anwendungen"],
] as const;
export function DnsRecordOverview() { return <figure className="mt-5"><figcaption className="font-bold text-slate-950">Wichtige Resource Records im Vergleich</figcaption><div className="mt-4 grid gap-3 sm:grid-cols-2">{recordRows.map(([type, purpose, example]) => <article key={type} className="min-w-0 rounded-xl border border-slate-200 bg-white p-4"><h3><code className="rounded bg-blue-100 px-2 py-1 font-bold text-blue-950">{type}</code></h3><p className="mt-3 font-semibold text-slate-950">{purpose}</p><p className="mt-1 break-words text-sm text-slate-600"><code className="break-all">{example}</code></p></article>)}</div></figure>; }
