import type { ReactNode } from "react";
import { calculatePaybackMonths, calculateProcurementPrice, calculateProfitabilityPercent, calculateTco, calculateWeightedUtility } from "../../lib/economic-calculations";
import { FundamentalsLesson, ResponsiveTable, TextFlow, type LessonSection } from "./fundamentals-lesson-elements";
import { SingleChoiceCheck } from "./single-choice-check";

type LessonContent = { objectives: readonly string[]; intro: ReactNode; sections: readonly LessonSection[]; visual?: ReactNode; scenario: { title: string; situation: ReactNode; tasks: readonly ReactNode[]; solution: ReactNode }; takeaway: readonly ReactNode[]; relatedLinks?: readonly { href: string; label: string }[] };

const priceExample = calculateProcurementPrice({ listPriceNet: 10_000, discountPercent: 10, cashDiscountPercent: 2, vatPercent: 19 });
const tcoExample = calculateTco({ acquisitionCost: 12_000, oneTimeCosts: 1_000, annualOperatingCost: 3_000, years: 3 });
const paybackExample = calculatePaybackMonths(18_000, 7_200);
const utilityExample = calculateWeightedUtility([{ weightPercent: 40, rating: 8 }, { weightPercent: 35, rating: 6 }, { weightPercent: 25, rating: 9 }]);

const lessons: Record<string, LessonContent> = {
  "kosten-erloes-und-wirtschaftlichkeit": {
    objectives: ["fixe und variable Kosten unterscheiden", "Erlös und Gewinn berechnen", "Deckungsbeitrag grundlegend bestimmen", "Rentabilität einordnen"],
    intro: <p>Wirtschaftliche Entscheidungen vergleichen Nutzen und Ressourcen über einen klaren Zeitraum. Niedrigster Kaufpreis und höchste Wirtschaftlichkeit sind nicht automatisch dasselbe.</p>,
    sections: [
      { title: "Kosten, Erlös und Gewinn", paragraphs: [<>Fixe Kosten bleiben innerhalb des betrachteten Bereichs zunächst unabhängig von der Menge, etwa eine monatliche Grundlizenz. Variable Kosten verändern sich mit Leistung oder Stückzahl.</>, <>Erlös = Menge × Verkaufspreis. Gewinn = Erlös − Gesamtkosten. Der Stückdeckungsbeitrag ist Verkaufspreis minus variable Stückkosten und trägt zur Deckung fixer Kosten bei.</>], activity: <SingleChoiceCheck title="Deckungsbeitrag" question="Ein Service kostet 80 € pro Vorgang; variable Kosten sind 30 €. Wie hoch ist der Stückdeckungsbeitrag?" inputName="economics-contribution" correctOptionId="fifty" successMessage="80 € − 30 € = 50 €." options={[{id:"thirty",label:"30 €",explanation:"Das sind die variablen Kosten."},{id:"fifty",label:"50 €",explanation:"Preis minus variable Stückkosten."},{id:"eighty",label:"80 €",explanation:"Das ist der Erlös pro Vorgang."},{id:"hundred",label:"110 €",explanation:"Kosten werden nicht addiert."}]} /> },
      { title: "Rentabilität braucht Bezugsgröße", paragraphs: [<>Eine einfache Rentabilität kann als Jahresgewinn ÷ eingesetztes Kapital × 100 % berechnet werden. Bei 4.000 € Gewinn und 20.000 € Kapital sind es {calculateProfitabilityPercent(4_000, 20_000).toLocaleString("de-DE")} %.</>, <>Kennzahlen sind nur vergleichbar, wenn Zeitraum, Kostenumfang und Bezugsgröße gleich definiert sind. Nicht messbarer Nutzen darf transparent ergänzt, aber nicht als beliebige Zahl versteckt werden.</>] },
    ],
    visual: <ResponsiveTable caption="Grundrechnungen" headers={["Kennzahl", "vereinfachte Rechnung", "Aussage"]} rows={[["Gewinn", "Erlös − Gesamtkosten", "Überschuss im Zeitraum"],["Deckungsbeitrag", "Erlös − variable Kosten", "Beitrag zu fixen Kosten/Gewinn"],["Rentabilität", "Gewinn ÷ Kapital × 100 %", "Verzinsung der Bezugsgröße"]]} />,
    scenario: { title: "Interner Service", situation: <p>100 Vorgänge bringen je 80 € Verrechnungserlös. Variable Kosten betragen je 30 €, fixe Kosten 4.000 €.</p>, tasks: ["Berechne Gesamtdeckungsbeitrag.", "Berechne den Gewinn."], solution: <p>Deckungsbeitrag: 100 × (80 − 30) = 5.000 €. Gewinn: 5.000 − 4.000 = 1.000 €.</p> },
    takeaway: ["Fixe und variable Kosten reagieren unterschiedlich auf Mengen.", "Deckungsbeitrag deckt fixe Kosten und danach Gewinn.", "Rentabilität braucht klaren Zeitraum und Kapitalbezug."],
  },
  "rabatt-skonto-netto-und-brutto": {
    objectives: ["Rabatt und Skonto unterscheiden", "Reihenfolge korrekt anwenden", "Netto und Brutto berechnen", "auf Cent runden"],
    intro: <p>Rabatt reduziert den vereinbarten Preis; Skonto ist ein zusätzlicher Nachlass bei Zahlung unter festgelegten Bedingungen. Umsatzsteuer wird im Übungsfall nach den Nachlässen auf den zahlbaren Nettobetrag berechnet.</p>,
    sections: [
      { title: "Eindeutige Rechenkette", paragraphs: [<>Ausgehend vom Nettolistenpreis wird zuerst der vereinbarte Rabatt abgezogen. Skonto bezieht sich in dieser Übung auf den rabattierten Nettobetrag. Danach werden Umsatzsteuer und Bruttobetrag berechnet.</>, <>Jede Aufgabe muss Preisbasis, Prozentsätze und Skontobedingung nennen. In diesen Übungen werden Geldbeträge nach jedem Nachlass auf Cent gerundet, damit das Ergebnis reproduzierbar bleibt.</>], activity: <SingleChoiceCheck title="Reihenfolge" question="Worauf werden 2 % Skonto nach 10 % Rabatt in dieser Aufgabe angewendet?" inputName="economics-discounts" correctOptionId="discounted" successMessage="Skonto folgt auf den Rabatt und nutzt den rabattierten Nettobetrag." options={[{id:"list",label:"auf den ursprünglichen Listenpreis",explanation:"Dann würde die vorgegebene Reihenfolge ignoriert."},{id:"discounted",label:"auf den rabattierten Nettobetrag",explanation:"Das ist die definierte Rechenbasis."},{id:"vat",label:"nur auf die Umsatzsteuer",explanation:"Skonto ist kein Steuernachlass."},{id:"gross-first",label:"vor Rabatt auf einen unbekannten Bruttobetrag",explanation:"Die Übung startet netto."}]} /> },
      { title: "Netto und Brutto", paragraphs: [<>Netto enthält die Umsatzsteuer nicht, Brutto enthält sie. Bei 19 % gilt im einfachen Fall Brutto = Netto × 1,19; umgekehrt ist Netto = Brutto ÷ 1,19.</>, <>Steuersätze und rechtliche Einordnung werden in einer realen Beschaffung geprüft. Die Übung verwendet den ausdrücklich genannten Satz und ersetzt keine steuerliche Beratung.</>] },
    ],
    visual: <ResponsiveTable caption="Preisrechnung für 10.000 € netto" headers={["Schritt", "Rechnung", "Ergebnis"]} rows={[["10 % Rabatt", "10.000,00 € − 1.000,00 €", `${priceExample.discountedNet.toLocaleString("de-DE", {minimumFractionDigits:2})} €`],["2 % Skonto", `9.000,00 € − ${priceExample.cashDiscountAmount.toLocaleString("de-DE", {minimumFractionDigits:2})} €`, `${priceExample.payableNet.toLocaleString("de-DE", {minimumFractionDigits:2})} €`],["19 % USt.", `${priceExample.payableNet.toLocaleString("de-DE", {minimumFractionDigits:2})} € + ${priceExample.vatAmount.toLocaleString("de-DE", {minimumFractionDigits:2})} €`, `${priceExample.payableGross.toLocaleString("de-DE", {minimumFractionDigits:2})} € brutto`]]} />,
    scenario: { title: "Serverangebot", situation: <p>10.000 € Nettolistenpreis, 10 % Rabatt, anschließend 2 % Skonto, danach 19 % Umsatzsteuer.</p>, tasks: ["Berechne den zahlbaren Nettobetrag.", "Berechne den Bruttobetrag nach der Übungsregel."], solution: <p>Nach Rabatt 9.000,00 €, Skonto 180,00 €, zahlbar netto {priceExample.payableNet.toLocaleString("de-DE", {minimumFractionDigits:2})} €. Umsatzsteuer {priceExample.vatAmount.toLocaleString("de-DE", {minimumFractionDigits:2})} €, brutto {priceExample.payableGross.toLocaleString("de-DE", {minimumFractionDigits:2})} €.</p> },
    takeaway: ["Rabatt und Skonto wirken nacheinander auf definierte Basen.", "Netto und Brutto unterscheiden sich durch Umsatzsteuer.", "Explizite Rundungsregeln verhindern Mehrdeutigkeit."],
  },
  "tco-und-amortisation": {
    objectives: ["TCO-Zeitraum festlegen", "Einmal- und Betriebskosten einbeziehen", "Amortisationsdauer berechnen", "Annahmen dokumentieren"],
    intro: <p>Total Cost of Ownership (TCO) betrachtet mehr als den Kaufpreis: Einführung, Betrieb, Lizenzen, Energie, Wartung, Support und mögliche Ablösung gehören je nach Vergleich dazu.</p>,
    sections: [
      { title: "Gleiche Grenzen vergleichen", paragraphs: [<>Für einen fairen Vergleich brauchen Varianten denselben Zeitraum, Mengenbezug, Leistungsumfang und Kostenstand. Nicht jeder schwer messbare Nutzen darf ignoriert werden; er wird getrennt dokumentiert.</>, <>Beispiel: 12.000 € Anschaffung, 1.000 € Einführung und 3.000 € jährlicher Betrieb über drei Jahre ergeben {tcoExample.toLocaleString("de-DE")} € TCO.</>] },
      { title: "Amortisation", paragraphs: [<>Einfache Amortisationsdauer = Investition ÷ jährliche Nettoeinsparung. 18.000 € Investition bei 7.200 € jährlicher Einsparung amortisieren sich rechnerisch nach {paybackExample.toLocaleString("de-DE")} Monaten.</>, <>Die einfache Rechnung berücksichtigt unter anderem Zinsen, zeitlich schwankende Einsparungen und Restwerte nicht. Diese Grenze muss zur Entscheidung passen.</>], activity: <SingleChoiceCheck title="Amortisation" question="Wann amortisieren sich 12.000 € bei 6.000 € jährlicher Nettoeinsparung?" inputName="economics-payback" correctOptionId="two-years" successMessage="12.000 ÷ 6.000 = 2 Jahre." options={[{id:"half",label:"nach 6 Monaten",explanation:"Dann wären erst 3.000 € eingespart."},{id:"one",label:"nach 1 Jahr",explanation:"Dann fehlen noch 6.000 €."},{id:"two-years",label:"nach 2 Jahren",explanation:"Die kumulierte Einsparung erreicht 12.000 €."},{id:"six",label:"nach 6 Jahren",explanation:"Das wäre 36.000 € Einsparung."}]} /> },
    ],
    visual: <TextFlow caption="TCO-Vergleich vorbereiten" steps={["Zeitraum und Umfang", "Anschaffung/Einführung", "laufender Betrieb", "Risiken und Restwert", "Varianten vergleichen"]} />,
    scenario: { title: "Zwei Clientmodelle", situation: <p>A kostet 900 € und 350 € Betrieb pro Jahr, B 1.150 € und 230 € Betrieb pro Jahr. Zeitraum: vier Jahre.</p>, tasks: ["Berechne die vereinfachte TCO beider Varianten.", "Welche weiteren Kriterien fehlen?"], solution: <p>A: 900 + 4 × 350 = 2.300 €. B: 1.150 + 4 × 230 = 2.070 €. Zusätzlich zählen Leistung, Ausfall, Service, Restwert, Nutzbarkeit und Risiken.</p> },
    takeaway: ["TCO nutzt gleiche Vergleichsgrenzen.", "Amortisation misst Zeit bis zum Rückfluss.", "Kennzahlen dokumentieren Annahmen und ersetzen keine Risikoanalyse."],
  },
  "beschaffung-und-angebotsvergleich": {
    objectives: ["Muss- und Kann-Kriterien trennen", "technische und wirtschaftliche Kriterien verbinden", "Angebote vergleichbar machen", "Gewährleistung und Garantie grundlegend unterscheiden"],
    intro: <p>Beschaffung beginnt mit Anforderungen, nicht mit Produktnamen. Das bestehende Hardware-Modul behandelt die technische Arbeitsplatzwahl; hier geht es um den nachvollziehbaren wirtschaftlichen Angebotsvergleich.</p>,
    sections: [
      { title: "Vergleichbare Angebote", paragraphs: [<>Muss-Kriterien schließen ungeeignete Varianten aus. Kann-Kriterien differenzieren verbleibende Angebote. Preis, Betrieb, Lizenzen, Wartung, Lieferzeit, Service, Skalierbarkeit, Barrierefreiheit und Nachhaltigkeit werden auf denselben Umfang bezogen.</>, <>Qualitative Kriterien brauchen nachvollziehbare Bewertungsmaßstäbe. „Support gut“ wird etwa durch Reaktionszeit, Servicefenster, Laufzeit und Eskalationsweg konkret.</>] },
      { title: "Gewährleistung und Garantie", paragraphs: [<>Gewährleistung bezeichnet gesetzliche Mängelrechte gegenüber der Verkäuferseite. Eine Garantie ist eine zusätzliche freiwillige Zusage des Garantiegebers nach ihren Bedingungen und verdrängt die gesetzlichen Ansprüche nicht.</>, <>Für echte Verträge werden Zielgruppe, Vertragsart, Leistungsbeschreibung und aktuelle Rechtslage fachkundig geprüft. Hier genügt die begriffliche Trennung ohne Fristenlernen.</>], activity: <SingleChoiceCheck title="Muss-Kriterium" question="Welche Behandlung ist für ein echtes Muss-Kriterium korrekt?" inputName="economics-must" correctOptionId="exclude" successMessage="Ein nicht erfülltes Muss macht das Angebot für diesen Bedarf ungeeignet." options={[{id:"points",label:"Nur einen kleinen Punktabzug geben.",explanation:"Dann wäre es kein echtes Muss."},{id:"exclude",label:"Angebot als nicht geeignet ausschließen.",explanation:"Muss-Kriterien sind zwingend."},{id:"ignore",label:"Kriterium nach Angebotsöffnung entfernen.",explanation:"Das macht den Vergleich beliebig."},{id:"cheapest",label:"Beim billigsten Angebot nicht prüfen.",explanation:"Auch dort gelten Anforderungen."}]} /> },
    ],
    visual: <ResponsiveTable caption="Angebotskriterien" headers={["Art", "Beispiel", "Bewertung"]} rows={[["Muss", "benötigte Schnittstelle", "erfüllt/nicht erfüllt"],["quantitativ", "TCO über 4 Jahre", "einheitliche Rechnung"],["qualitativ", "Supportqualität", "definierte Skala/Evidenz"],["Risiko", "Lieferzeit/Herstellerbindung", "Auswirkung und Maßnahme"]]} />,
    scenario: { title: "30 barrierearme Arbeitsplätze", situation: <p>Drei Angebote unterscheiden sich bei Preis, Lieferzeit, höhenverstellbaren Monitoren, Vor-Ort-Service und Energiebedarf.</p>, tasks: ["Formuliere Muss- und Kann-Kriterien.", "Warum reicht der Kaufpreis nicht?"], solution: <p>Erforderliche Bedienhilfen und Anschlüsse können Muss sein; Lieferzeit, Service und Energie werden messbar bewertet. Betrieb, Ausfall und Nutzbarkeit beeinflussen TCO und Zielerreichung.</p> },
    takeaway: ["Anforderungen machen Angebote vergleichbar.", "Muss-Kriterien werden vor der Nutzwertbewertung geprüft.", "Garantie ergänzt gesetzliche Mängelrechte nach ihren Bedingungen."],
    relatedLinks: [{ href: "/lernen/arbeitsplatz-hardware/arbeitsplatz-auswaehlen", label: "Hardware: Arbeitsplätze technisch auswählen" }],
  },
  "nutzwertanalyse": {
    objectives: ["Kriterien und Gewichte festlegen", "Bewertungen begründen", "gewichtete Punkte berechnen", "Subjektivität und Sensitivität erklären"],
    intro: <p>Eine Nutzwertanalyse vergleicht mehrere geeignete Varianten anhand gewichteter Kriterien. Sie strukturiert Prioritäten, erzeugt aber keine objektive Wahrheit.</p>,
    sections: [
      { title: "Gewichtung mal Bewertung", paragraphs: [<>Die Gewichte ergeben zusammen 100 %. Je Kriterium wird jede Variante auf derselben Skala bewertet. Gewichteter Beitrag = Gewicht × Bewertung; die Summe ist der Nutzwert.</>, <>Bei 40 % × 8, 35 % × 6 und 25 % × 9 ergibt sich auf einer 0-bis-10-Skala ein Gesamtnutzwert von {utilityExample.toLocaleString("de-DE")}.</>], activity: <SingleChoiceCheck title="Gewichteter Beitrag" question="Kriterium Service wiegt 30 %, Angebot erhält 8 von 10 Punkten. Welcher Beitrag entsteht?" inputName="economics-utility" correctOptionId="two-four" successMessage="0,30 × 8 = 2,4 Punkte." options={[{id:"twenty-four",label:"24 Punkte auf der 0-bis-10-Skala",explanation:"30 % werden als 0,30 eingesetzt."},{id:"two-four",label:"2,4 Punkte",explanation:"Das ist der gewichtete Beitrag."},{id:"thirty-eight",label:"38 Punkte",explanation:"Gewicht und Bewertung werden nicht addiert."},{id:"zero",label:"0 Punkte",explanation:"Das Kriterium ist gewichtet und bewertet."}]} /> },
      { title: "Ergebnis hinterfragen", paragraphs: [<>Gewichte spiegeln gewählte Prioritäten; Bewertungen hängen von Daten und Skalen ab. Kleine Änderungen können Rangfolgen verändern. Deshalb werden Begründungen und Sensitivität geprüft.</>, <>Muss-Kriterien werden vorher geprüft. Ein Angebot mit fehlender zwingender Anforderung darf nicht durch viele Komfortpunkte „gewinnen“.</>] },
    ],
    visual: <ResponsiveTable caption="Beispiel für Angebot A" headers={["Kriterium", "Gewicht", "Bewertung 0–10", "Beitrag"]} rows={[["TCO", "40 %", "8", "3,20"],["Service", "35 %", "6", "2,10"],["Nachhaltigkeit", "25 %", "9", "2,25"],["Gesamt", "100 %", "–", utilityExample.toLocaleString("de-DE")]]} />,
    scenario: { title: "Notebookangebote vergleichen", situation: <p>Nach Muss-Prüfung bleiben A und B. A ist günstiger, B bietet besseren Service und niedrigeren Energiebedarf.</p>, tasks: ["Lege drei Kriterien mit 100 % Gesamtgewicht fest.", "Warum muss die Bewertung begründet werden?"], solution: <p>Beispiel: TCO 50 %, Service 30 %, Energie/Nachhaltigkeit 20 %. Datenquellen und Skala müssen feststehen; andere legitime Prioritäten können ein anderes Ergebnis liefern.</p> },
    takeaway: ["Gewichte summieren sich zu 100 %.", "Bewertungen brauchen dieselbe Skala und Evidenz.", "Nutzwertanalyse unterstützt Entscheidungen, sie beweist keine Wahrheit."],
  },
  "kauf-miete-leasing-und-make-or-buy": {
    objectives: ["Kauf, Miete und Leasing vergleichen", "Make-or-Buy strukturieren", "Risiken und Flexibilität berücksichtigen", "keine Variante pauschal bevorzugen"],
    intro: <p>Bezugsmodelle verteilen Zahlung, Eigentum, Flexibilität, Wartung und Risiko unterschiedlich. Die passende Wahl folgt Nutzungsdauer und Anforderungen.</p>,
    sections: [
      { title: "Kauf, Miete und Leasing", paragraphs: [<>Kauf kann bei langer stabiler Nutzung und eigener Betriebsfähigkeit passen, bindet aber Kapital und Restwertrisiko. Miete kann flexibel sein und Services bündeln, verursacht aber laufende Kosten.</>, <>Leasing folgt Vertragsbedingungen zu Laufzeit, Raten, Nutzung, Rückgabe und möglichen Restwerten. Es ist nicht automatisch günstiger oder bilanziell immer gleich zu behandeln; Verträge werden fachlich geprüft.</>] },
      { title: "Make-or-Buy", paragraphs: [<>Make-or-Buy vergleicht Eigenleistung mit externem Bezug. Neben Kosten zählen Kompetenzen, Kapazität, Kontrollbedarf, Abhängigkeit, Sicherheit, Datenschutz, Skalierung und Exit-Möglichkeit.</>, <>Eine Kernkompetenz kann für Make sprechen, fehlende Spezialkenntnis für Buy. Beides braucht Steuerung: Eigenbetrieb ist nicht kostenlos, Outsourcing überträgt nicht jede Verantwortung.</>], activity: <SingleChoiceCheck title="Entscheidung begründen" question="Welche Aussage ist fachlich angemessen?" inputName="economics-sourcing" correctOptionId="context" successMessage="Bedarf, Zeitraum, Vertrag, Risiken und TCO bestimmen die Wahl." options={[{id:"buy",label:"Kauf ist immer am günstigsten.",explanation:"Nutzungsdauer und Betriebskosten variieren."},{id:"lease",label:"Leasing ist grundsätzlich risikofrei.",explanation:"Vertrags-, Nutzungs- und Rückgaberisiken bleiben."},{id:"outsource",label:"Outsourcing überträgt jede Verantwortung.",explanation:"Steuerungs- und Schutzpflichten bleiben relevant."},{id:"context",label:"Die Wahl hängt von TCO, Flexibilität, Fähigkeiten und Risiken ab.",explanation:"Das ist die notwendige Kontextentscheidung."}]} /> },
    ],
    visual: <ResponsiveTable caption="Bezugsmodelle abwägen" headers={["Modell", "mögliche Stärke", "mögliche Grenze"]} rows={[["Kauf", "Eigentum/lange Nutzung", "Kapitalbindung/Restwert"],["Miete", "Flexibilität/Service", "laufende Kosten/Abhängigkeit"],["Leasing", "planbare Raten", "Vertrags- und Rückgabebedingungen"],["externer Service", "Spezialwissen/Skalierung", "Steuerung/Lock-in/Schutzbedarf"]]} />,
    scenario: { title: "Temporäres Projektteam", situation: <p>Für zwölf Monate werden 20 standardisierte Notebooks benötigt; danach ist der Bedarf unsicher.</p>, tasks: ["Welche Modelle sind plausibel?", "Welche Daten braucht der Vergleich?"], solution: <p>Miete oder Leasing können wegen begrenzter Dauer plausibel sein; Kauf bleibt als Vergleich. Benötigt werden Gesamtraten, Services, Schäden/Rückgabe, TCO, Restwert, Lieferfähigkeit und Sicherheitsprozess.</p> },
    takeaway: ["Kein Bezugsmodell ist universell überlegen.", "Make-or-Buy umfasst Kosten, Fähigkeiten und Risiken.", "Vertragsumfang und Exit müssen vergleichbar sein."],
  },
};

export function EconomicsLesson({ lessonSlug }: { lessonSlug: string }) {
  const lesson = lessons[lessonSlug];
  if (!lesson) return null;
  return <FundamentalsLesson lessonId={`economics-${lessonSlug}`} {...lesson} relatedLinks={lesson.relatedLinks}>{lesson.visual}</FundamentalsLesson>;
}
