import { LearningObjectives } from "./learning-objectives";
import {
  LinuxAdministrationMatchingCheck,
  LinuxFileOperationMatchingCheck,
  LinuxInventoryClassificationCheck,
  LinuxPermissionMatchingCheck,
} from "./linux-checks";

function LessonBody({ children }: { children: React.ReactNode }) {
  return <div className="space-y-10 [overflow-wrap:anywhere] text-base leading-7 text-slate-700 sm:text-lg sm:leading-8">{children}</div>;
}

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return <section aria-labelledby={id}><h2 id={id} className="text-2xl font-bold tracking-tight text-slate-950">{title}</h2><div className="mt-4 space-y-4">{children}</div></section>;
}

function Command({ value, children }: { value: string; children: React.ReactNode }) {
  return <div className="min-w-0 rounded-xl border border-slate-200 bg-slate-50 p-4"><code className="block overflow-x-auto whitespace-pre py-1 font-bold text-blue-950">{value}</code><p className="mt-2 text-sm leading-6">{children}</p></div>;
}

function Misconceptions({ items }: { items: readonly (readonly [string, string])[] }) {
  return <dl className="space-y-4">{items.map(([wrong, correction]) => <div key={wrong} className="rounded-xl border border-amber-200 bg-amber-50 p-4"><dt className="font-bold text-slate-950">Falsch: „{wrong}“</dt><dd className="mt-2 text-sm leading-6"><strong>Korrektur:</strong> {correction}</dd></div>)}</dl>;
}

function SafetyBox({ children }: { children: React.ReactNode }) {
  return <aside className="rounded-2xl border-2 border-amber-400 bg-amber-50 p-5 text-slate-900 sm:p-7"><h2 className="text-xl font-bold">Sicherheitsregel</h2><div className="mt-3 space-y-3 text-sm leading-6 sm:text-base">{children}</div></aside>;
}

export function LinuxFileManagementLesson() {
  return <LessonBody>
    <LearningObjectives context="lesson" objectives={["Verzeichnisse und leere Dateien erstellen", "Textdateien sicher untersuchen", "Dateien und Verzeichnisse kopieren", "Dateien und Verzeichnisse verschieben oder umbenennen", "Dateien und Verzeichnisse bewusst löschen", "rekursive Operationen verstehen", "einfache Glob-Muster verwenden", "Dateityp und Metadaten untersuchen", "destruktive Befehle erkennen", "Pfade vor Löschen oder Überschreiben verifizieren"]} />
    <SafetyBox><p><strong>Alle verändernden und löschenden Beispiele dieser Lektion gelten ausschließlich für das wegwerfbare Übungsverzeichnis <code>~/linux-uebung</code>.</strong></p><p>Übe niemals in <code>/</code>, <code>/etc</code>, <code>/usr</code>, <code>/var</code>, deinen echten Dokumenten, eingebundenen Kundendaten oder Produktionspfaden. Prüfe vor einer Löschung mit <code>pwd</code> den Ort und mit <code>ls -la</code> das Ziel.</p></SafetyBox>
    <Section id="linux-create" title="Verzeichnisse und Dateien anlegen">
      <Command value="mkdir ~/linux-uebung">Erstellt das isolierte Übungsverzeichnis. <code>mkdir test</code> erstellt entsprechend ein einzelnes Verzeichnis am aktuellen Ort.</Command>
      <Command value="mkdir -p ~/linux-uebung/projekt/doku"><code>-p</code> legt bei Bedarf fehlende Elternverzeichnisse mit an. Für ein vorhandenes Elternverzeichnis ist die Option nicht immer nötig.</Command>
      <Command value="touch ~/linux-uebung/notizen.txt"><code>touch</code> erstellt eine leere Datei, falls sie noch nicht existiert. Sonst aktualisiert es Zeitstempel – es garantiert keine neue Datei.</Command>
      <p>Dateien enthalten Daten; Verzeichnisse organisieren Namen und Einträge. Befehle behandeln beide deshalb nicht immer gleich.</p>
    </Section>
    <Section id="linux-read" title="Inhalte, Typ und Metadaten untersuchen">
      <div className="grid gap-3 sm:grid-cols-2"><Command value="cat file.txt">Geeignet für kurze Textdateien; bei sehr großen Dateien wird die Ausgabe schnell unübersichtlich.</Command><Command value="less file.txt">Interaktive Ansicht, sofern verfügbar.</Command><Command value="head file.txt">Zeigt standardmäßig den Anfang der Datei.</Command><Command value="tail file.txt">Zeigt standardmäßig das Ende der Datei.</Command><Command value="file example.txt">Schätzt den Dateityp anhand des Inhalts und weiterer Merkmale; die Endung allein ist kein zuverlässiger Typnachweis.</Command><Command value="stat example.txt">Zeigt Metadaten wie Größe, Modus und Zeitstempel.</Command></div>
    </Section>
    <Section id="linux-copy-move" title="Kopieren, verschieben und umbenennen">
      <Command value="cp quelle.txt kopie.txt">Erstellt eine Kopie unter neuem Namen.</Command><Command value="cp quelle.txt zielordner/">Kopiert eine Datei in ein Verzeichnis.</Command><Command value="cp -r quelle-dir ziel-dir"><code>-r</code> verarbeitet einen Verzeichnisbaum rekursiv. Kopiere nicht unüberlegt Systemverzeichnisse.</Command>
      <Command value="mv alt.txt neu.txt">Benennt einen Eintrag am selben Ort um.</Command><Command value="mv datei.txt zielordner/"><code>mv</code> dient sowohl zum Verschieben als auch zum Umbenennen. Ein vorhandenes Ziel kann abhängig von Pfad, Implementierung und Optionen überschrieben werden; <code>mv</code> fragt nicht zuverlässig immer nach.</Command>
    </Section>
    <Section id="linux-delete" title="Löschen: bewusst und kontrolliert">
      <Command value="rm ~/linux-uebung/test.txt">Entfernt diese Übungsdatei normalerweise direkt und nicht über den Desktop-Papierkorb.</Command><Command value="rmdir ~/linux-uebung/leerer-ordner">Entfernt nur ein leeres Verzeichnis.</Command><Command value="rm -r ~/linux-uebung/testordner">Entfernt den Übungs-Verzeichnisbaum rekursiv. Vorher <code>pwd</code>, Zielpfad und Inhalt prüfen; rekursiv bedeutet, dass enthaltene Einträge mitverarbeitet werden.</Command>
      <p><strong>Auch ohne sudo ist <code>rm -r</code> nicht harmlos:</strong> Alle Einträge, für die der Benutzer ausreichende Rechte besitzt, können verloren gehen.</p>
    </Section>
    <Section id="linux-globs" title="Einfache Glob-Muster">
      <Command value="ls *.txt"><code>*</code> passt auf null oder mehr Zeichen; hier listet die Shell passende Namen mit <code>.txt</code>.</Command><Command value="ls ?.txt"><code>?</code> passt auf genau ein Zeichen vor <code>.txt</code>.</Command>
      <p>Globbing wird gewöhnlich von der Shell <em>vor</em> dem Start des Befehls expandiert. Das Muster ist dann nicht Teil eines gespeicherten Dateinamens. Diese Expansion macht Kombinationen mit destruktiven Befehlen besonders mächtig; deshalb bleibt die Übung beim lesenden <code>ls</code>.</p>
    </Section>
    <LinuxFileOperationMatchingCheck />
    <Section id="linux-file-practice" title="Praxis im wegwerfbaren Verzeichnis">
      <pre className="overflow-x-auto rounded-xl bg-slate-950 p-5 text-sm leading-7 text-slate-100"><code>{`mkdir -p ~/linux-uebung/doku
cd ~/linux-uebung
touch notizen.txt
cp notizen.txt kopie.txt
mv kopie.txt doku/
ls -la
file notizen.txt
stat notizen.txt`}</code></pre>
      <p>Eine spätere Bereinigung ist optional: zuerst <code>pwd</code> ausführen, ausdrücklich <code>/home/DEIN-NAME/linux-uebung</code> im Ergebnis bestätigen und nur dann <code>rm -r ~/linux-uebung</code> verwenden. Keine anderen Pfade einsetzen.</p>
    </Section>
    <Section id="linux-file-errors" title="Typische Denkfehler"><Misconceptions items={[["rm legt Dateien im Papierkorb ab.", "rm entfernt Inhalte normalerweise ohne Desktop-Papierkorb."], ["touch erstellt immer garantiert eine neue Datei.", "Bei vorhandenen Dateien aktualisiert touch Zeitstempel."], ["mv kann nur Dateien verschieben, nicht umbenennen.", "mv kann verschieben und umbenennen."], ["Die Dateiendung bestimmt zuverlässig den Dateityp.", "file untersucht den Typ heuristisch; Name und Inhalt können voneinander abweichen."], ["* ist Teil des Dateinamens.", "Oft expandiert die Shell das Glob-Muster vor dem Befehlsstart."], ["rm -r ist harmlos, solange kein sudo davor steht.", "Eigene oder anderweitig beschreibbare Daten können trotzdem rekursiv verloren gehen."]]} /></Section>
  </LessonBody>;
}

export function LinuxPermissionsLesson() {
  return <LessonBody>
    <LearningObjectives context="lesson" objectives={["aktuellen Benutzer und Gruppen bestimmen", "UID und GID konzeptionell erklären", "Eigentümer und Rechte in ls -l lesen", "Owner, Group und Others unterscheiden", "r, w und x interpretieren", "Datei- und Verzeichnisrechte unterscheiden", "gängige rwx-Kombinationen in Oktalwerte übertragen", "chmod verstehen", "Eigentümerwechsel konzeptionell einordnen", "root und sudo verantwortungsvoll erklären", "Least Privilege begründen"]} />
    <Section id="users-groups" title="Benutzer, Gruppen, UID und GID"><div className="grid gap-3 sm:grid-cols-3"><Command value="whoami">Zeigt den effektiven Benutzernamen.</Command><Command value="id">Zeigt UID, primäre GID und Gruppeninformationen.</Command><Command value="groups">Listet Gruppenmitgliedschaften des Benutzers.</Command></div><p>Der Kernel ordnet Identitäten numerisch zu: Die <strong>UID</strong> ist die Benutzerkennung, eine <strong>GID</strong> eine Gruppenkennung. Lesbare Namen werden diesen Kennungen zugeordnet; der Benutzername allein ist nicht die einzige interne Identität.</p></Section>
    <Section id="permission-output" title="Eine lange Auflistung lesen"><pre className="overflow-x-auto rounded-xl bg-slate-950 p-5 text-sm text-slate-100"><code>-rw-r----- 1 azubi support … bericht.txt</code></pre><dl className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded-xl border p-4"><dt className="font-bold">Typ</dt><dd><code>-</code> = reguläre Datei</dd></div><div className="rounded-xl border p-4"><dt className="font-bold">Owner: azubi</dt><dd><code>rw-</code></dd></div><div className="rounded-xl border p-4"><dt className="font-bold">Group: support</dt><dd><code>r--</code></dd></div><div className="rounded-xl border p-4"><dt className="font-bold">Others</dt><dd><code>---</code></dd></div></dl></Section>
    <Section id="permission-semantics" title="rwx bedeutet bei Dateien und Verzeichnissen Unterschiedliches"><div className="grid gap-4 md:grid-cols-2"><article className="rounded-xl border border-blue-200 bg-blue-50 p-5"><h3 className="font-bold text-blue-950">Reguläre Datei</h3><ul className="mt-3 list-disc space-y-2 pl-6 text-sm"><li><strong>r:</strong> Inhalt lesen</li><li><strong>w:</strong> Inhalt verändern</li><li><strong>x:</strong> als Programm/Skript ausführen, sofern Format, Interpreter und weitere Bedingungen passen</li></ul></article><article className="rounded-xl border border-slate-200 p-5"><h3 className="font-bold text-slate-950">Verzeichnis</h3><ul className="mt-3 list-disc space-y-2 pl-6 text-sm"><li><strong>r:</strong> Verzeichniseinträge/Namen lesen</li><li><strong>w:</strong> Einträge erstellen, löschen oder umbenennen, abhängig von weiteren Regeln</li><li><strong>x:</strong> Verzeichnis durchsuchen/durchlaufen und Einträge darüber erreichen</li></ul></article></div><p>Das x-Bit allein garantiert weder, dass eine Datei erfolgreich läuft, noch bedeutet es „Verzeichnis als Programm ausführen“. Leserechte am Verzeichnis garantieren auch keine Leserechte an jeder enthaltenen Datei.</p></Section>
    <Section id="permission-octal" title="Oktale Schreibweise"><p><code>r = 4</code>, <code>w = 2</code>, <code>x = 1</code>. Pro Dreiergruppe werden Werte addiert: <code>4 + 2 + 1 → 7 → rwx</code>.</p><div className="grid gap-3 sm:grid-cols-3"><Command value="644 → rw-r--r--">Owner darf lesen/schreiben, Group und Others lesen.</Command><Command value="755 → rwxr-xr-x">Owner rwx, Group und Others r-x.</Command><Command value="750 → rwxr-x---">Others erhalten keine Rechte.</Command></div><p><code>chmod 777</code> ist keine generische Fehlerbehebung: Es vergibt weitreichende Rechte an alle drei Klassen.</p></Section>
    <Section id="permission-tools" title="chmod, chown und chgrp"><Command value="chmod u+x ~/linux-uebung/script.sh">Fügt dem Owner-Ausführungsrecht für eine eigene Übungsdatei hinzu.</Command><Command value="chmod 640 ~/linux-uebung/bericht.txt">Setzt Rechte auf <code>rw-r-----</code>. Für eigene Übungsdateien ist kein sudo erforderlich.</Command><Command value="chown BENUTZER DATEI   # nur Demonstration">Ändert Eigentümerschaft und erfordert je nach Änderung Privilegien. Nicht ausführen.</Command><Command value="chgrp GRUPPE DATEI   # nur Demonstration">Ändert Gruppeneigentümerschaft; mögliche Gruppen und Rechte sind systemabhängig. Nicht Teil der Praxis.</Command></Section>
    <Section id="root-sudo" title="root, sudo, Least Privilege und umask"><p><code>root</code> ist ein stark privilegierter Benutzer. <code>sudo</code> kann einen konkreten Befehl mit erhöhten Rechten ausführen, wenn die Richtlinie es erlaubt. Nicht jeder Administrationsbefehl braucht sudo – und sudo macht einen schlechten Befehl nicht sicher. Erst lesen, Wirkung und Ziel prüfen, dann nur die minimal nötigen Rechte einsetzen.</p><p><code>umask</code> beeinflusst konzeptionell die Standardrechte neu angelegter Dateien und Verzeichnisse zusammen mit dem vom Prozess angeforderten Erstellungsmodus. Sie „setzt“ nicht einfach pauschal einen einzigen endgültigen Modus.</p></Section>
    <LinuxPermissionMatchingCheck />
    <Section id="permission-errors" title="Typische Denkfehler"><Misconceptions items={[["777 behebt Berechtigungsprobleme korrekt.", "Es öffnet oft unnötig Rechte und verschleiert die Ursache."], ["x bedeutet bei Verzeichnissen, dass das Verzeichnis ausgeführt wird.", "x erlaubt Durchlaufen/Suchen."], ["sudo muss vor jeden Administrationsbefehl.", "Viele Untersuchungen und Arbeiten an eigenen Dateien brauchen keine Erhöhung."], ["Der Benutzername ist intern die einzige Benutzer-ID.", "UID und GID sind die numerischen Kennungen."], ["Leserechte auf ein Verzeichnis bedeuten automatisch, dass jede Datei darin gelesen werden kann.", "Dateirechte und Durchlaufrechte müssen ebenfalls passen."], ["chmod 644 und chmod 755 sind fast dasselbe.", "755 setzt Ausführungsrechte und andere Schreib-/Lesekombinationen als 644."]]} /></Section>
  </LessonBody>;
}

export function LinuxAdministrationLesson() {
  return <LessonBody>
    <LearningObjectives context="lesson" objectives={["Prozess und PID erklären", "Prozesse sicher untersuchen", "Eltern-/Kindprozesse konzeptionell verstehen", "Prozess und Dienst unterscheiden", "systemd-Dienstzustand untersuchen, wo anwendbar", "start, stop, restart und enable unterscheiden", "Paketmanager und Repositories erklären", "Metadatenaktualisierung und Paketupgrade unterscheiden", "distributionsspezifische Werkzeuge erkennen", "installierte Pakete sicher untersuchen", "Prozesse oder Produktionssysteme nicht blind verändern"]} />
    <Section id="processes" title="Prozesse und Signale"><p>Ein <strong>Prozess</strong> ist eine laufende Instanz eines Programms oder Workloads. Seine <strong>PID</strong> ist die Prozesskennung. Prozesse können Eltern-/Kindbeziehungen haben.</p><div className="grid gap-3 sm:grid-cols-2"><Command value="ps">Zeigt typischerweise Prozesse der aktuellen Sitzung.</Command><Command value="ps aux">Verbreitete Kombination unterschiedlicher <code>ps</code>-Syntaxstile für eine breite Momentaufnahme.</Command><Command value="ps -ef">Alternative verbreitete vollständige Auflistung, einschließlich PPID-Spalte.</Command><Command value="top">Interaktive Prozessansicht, sofern vorhanden; <code>htop</code> ist nicht erforderlich.</Command></div><p>Prozesse können Signale erhalten. <code>kill PID</code> sendet auf üblichen Linux-Systemen standardmäßig SIGTERM und bedeutet nicht automatisch sofortiges hartes Beenden. SIGKILL beziehungsweise <code>kill -9</code> ist nur ein letzter Ausweg, nicht der erste Schritt. In dieser Lektion wird kein realer Prozess beendet.</p></Section>
    <Section id="services" title="Prozess, Dienst und systemd"><p>Ein Dienst ist eine nach System-/Dienstkonventionen verwaltete, oft länger laufende Hintergrundfunktion und kann einen oder mehrere Prozesse umfassen. Prozess und Dienst sind keine Synonyme.</p><Command value="systemctl status &lt;dienst&gt;">Nur lesende Statusprüfung auf einem systemd-System. Viele moderne Distributionen nutzen systemd, aber nicht jedes Linux.</Command><div className="grid gap-3 sm:grid-cols-2"><Command value="systemctl start &lt;dienst&gt;   # Konzept">Startet für die aktuelle Laufzeit.</Command><Command value="systemctl stop &lt;dienst&gt;   # Konzept">Stoppt für die aktuelle Laufzeit.</Command><Command value="systemctl restart &lt;dienst&gt;   # Konzept">Stoppt und startet neu; kann Unterbrechungen auslösen.</Command><Command value="systemctl enable &lt;dienst&gt;   # Konzept">Konfiguriert Autostart gemäß Unit-Installation/Targets; bedeutet nicht einfach „jetzt starten“.</Command></div><p><code>disable</code> nimmt diese Autostart-Konfiguration zurück. Alle verändernden Varianten sind hier nur konzeptionell und keine Übung.</p><Command value="journalctl -u &lt;dienst&gt;">Untersucht das systemd-Journal für eine Unit, soweit systemd/journald, Berechtigungen und Konfiguration es zulassen. <code>journalctl --help</code> ist eine sichere Hilfeansicht.</Command></Section>
    <Section id="packages" title="Pakete, Repositories und Werkzeuge"><p>Pakete bündeln verwaltete Software und Metadaten. Repositories liefern Paketmetadaten und -inhalte. Der Paketmanager kann je nach Werkzeug suchen, installieren, aktualisieren, entfernen und Abhängigkeiten behandeln.</p><div aria-label="Paketfluss" className="grid gap-2 text-center sm:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] sm:items-center"><span className="rounded-xl border p-4 font-bold">Repository</span><span aria-hidden="true">↓</span><span className="rounded-xl border p-4 font-bold">Paketmanager</span><span aria-hidden="true">↓</span><span className="rounded-xl border p-4 font-bold">Paket</span><span aria-hidden="true">↓</span><span className="rounded-xl border p-4 font-bold">installierte Dateien/Software</span></div><div className="grid gap-4 md:grid-cols-3"><article className="rounded-xl border p-5"><h3 className="font-bold">Debian/Ubuntu</h3><p>APT + dpkg</p><code className="mt-2 block text-sm">apt list --installed<br/>apt show &lt;paket&gt;<br/>dpkg -l</code></article><article className="rounded-xl border p-5"><h3 className="font-bold">Fedora/RHEL</h3><p>DNF + RPM</p><code className="mt-2 block text-sm">dnf list installed<br/>dnf info &lt;paket&gt;<br/>rpm -qa</code></article><article className="rounded-xl border p-5"><h3 className="font-bold">Arch</h3><p>pacman</p><code className="mt-2 block text-sm">pacman -Q<br/>pacman -Qi &lt;paket&gt;</code></article></div><p>Die Familien sind nicht austauschbar. Zufällige Installationsskripte aus dem Internet sind nicht gleichwertig mit verwalteter Paketinstallation.</p></Section>
    <Section id="package-changes" title="Systemänderungen nur konzeptionell"><p><code>apt install</code>, <code>dnf install</code> und <code>pacman -S</code> verändern das System und können erhöhte Rechte verlangen. Sie sind keine Pflichtübung. <code>apt update</code> aktualisiert Paketindizes beziehungsweise Metadaten; erst ein getrenntes Upgrade verändert installierte Pakete. Auf Produktionssystemen werden Änderungen geplant, autorisiert und geprüft.</p></Section>
    <section aria-labelledby="service-flow" className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><h2 id="service-flow" className="text-xl font-bold text-blue-950">Dienstbeziehung</h2><p className="mt-4 flex flex-wrap items-center gap-3 font-bold"><span>Dienstmanager</span><span aria-hidden="true">→</span><span>Dienst</span><span aria-hidden="true">→</span><span>Prozess(e)</span></p></section>
    <LinuxAdministrationMatchingCheck />
    <Section id="admin-errors" title="Typische Denkfehler"><Misconceptions items={[["Prozess und Dienst sind dasselbe.", "Ein Dienst kann einen oder mehrere Prozesse umfassen."], ["kill bedeutet immer sofortiges hartes Beenden.", "kill sendet standardmäßig üblicherweise SIGTERM."], ["kill -9 ist die normale erste Lösung.", "SIGKILL ist ein letzter Ausweg."], ["systemctl enable startet einen Dienst einfach nur sofort.", "enable konfiguriert den Autostart; Start ist eine getrennte Laufzeitaktion."], ["Jedes Linux verwendet systemd.", "Andere Init-/Dienstsysteme existieren."], ["apt update aktualisiert automatisch alle installierten Programme.", "Es aktualisiert Paketindizes, nicht automatisch alle installierten Pakete."], ["Alle Distributionen verwenden apt.", "DNF/RPM und pacman sind Beispiele anderer Ökosysteme."]]} /></Section>
  </LessonBody>;
}

export function LinuxInventoryLesson() {
  const phases = [
    ["1. System identifizieren", "uname -a · cat /etc/os-release · hostname (oder hostnamectl, falls vorhanden)"],
    ["2. Benutzerkontext", "whoami · id · groups"],
    ["3. Dateisystem", "pwd · ls -la · ls -ld / /home /etc /var /usr"],
    ["4. Berechtigungen", "Typ, Owner, Group und rwx einer ausgewählten Datei lesen"],
    ["5. Speicher", "df -h · free -h"],
    ["6. Prozesse", "ps aux · optional top"],
    ["7. Dienste", "systemctl --type=service --state=running, falls systemd vorhanden"],
    ["8. Pakete", "passendes read-only Werkzeug der erkannten Distribution"],
    ["9. Netzwerk und DNS", "ip addr · ip route · optional ss -ltn · Resolverzustand lesen"],
    ["10. Dokumentation", "Beobachtung, Bedeutung, mögliche Auffälligkeit und nächsten Check notieren"],
  ] as const;
  return <LessonBody>
    <LearningObjectives context="lesson" objectives={["Distribution, Kernel und Hostname bestimmen", "Benutzer, UID und Gruppen erfassen", "Arbeitsverzeichnis und Dateisystemhierarchie untersuchen", "ausgewählte Dateirechte lesen", "Dateisystembelegung und Speicherzustand einordnen", "Prozesse untersuchen", "Dienststatus systemabhängig lesen", "Paketökosystem erkennen", "IP-Adressen und Routing beobachten", "DNS-Konfiguration systemabhängig einordnen", "lauschende TCP-Sockets sicher auflisten", "Befunde evidenzbasiert dokumentieren"]} />
    <SafetyBox><p><strong>Bestandsaufnahme vor Veränderung:</strong> lesen, dokumentieren, Hypothese bilden – und erst danach nur bei Bedarf und mit Autorisierung ändern.</p><p>Dieses Lab benötigt weder sudo noch Paketupdates, Dienstneustarts, Rechte-/Benutzeränderungen oder Löschungen.</p></SafetyBox>
    <Section id="inventory-scenario" title="Auftrag: unbekannten Rechner inventarisieren"><p>Du bekommst einen unbekannten Linux-Rechner zur Bestandsaufnahme. Du darfst nichts verändern. Ermittle Distribution, Kernel, Hostname, Benutzer, IP-Adresse, Standardroute, Speicherbelegung, Arbeitsspeicher, laufende Prozesse und – soweit erkennbar – den Dienstmanager.</p></Section>
    <Section id="inventory-phases" title="Zehn Untersuchungsphasen"><ol className="space-y-3">{phases.map(([title, commands]) => <li key={title} className="rounded-xl border border-slate-200 p-4"><h3 className="font-bold text-slate-950">{title}</h3><code className="mt-2 block overflow-x-auto whitespace-nowrap text-sm">{commands}</code></li>)}</ol></Section>
    <Section id="inventory-identity" title="System und Benutzerkontext"><div className="grid gap-3 sm:grid-cols-2"><Command value="uname -a">Kernel- und Systeminformationen; nicht gleichbedeutend mit dem Distributionsnamen.</Command><Command value="cat /etc/os-release">Übliche Distributionsmetadaten.</Command><Command value="hostname">Liest den Hostnamen. <code>hostnamectl</code> kann auf passenden Systemen zusätzliche Angaben zeigen.</Command><Command value="whoami · id · groups">Liest Benutzername, UID, GID und Gruppen. Keine Benutzer werden verändert.</Command></div><p>Dokumentiere: Welche Distribution? Welcher Kernel? Welcher Hostname? Welche UID, primäre und zusätzliche Gruppen?</p></Section>
    <Section id="inventory-resources" title="Dateisystem, Storage und Memory"><div className="grid gap-3 sm:grid-cols-2"><Command value="pwd · ls -la">Liest aktuellen Ort und Einträge.</Command><Command value="ls -ld / /home /etc /var /usr">Untersucht die Verzeichniseinträge selbst und ihre Rechte.</Command><Command value="df -h">Zeigt Kapazität und Belegung eingebundener Dateisysteme, nicht die Größe einzelner Verzeichnisse.</Command><Command value="du -sh ~/linux-uebung">Optional nur für das eigene sichere Übungsverzeichnis; nicht den ganzen Wurzelbaum scannen.</Command><Command value="free -h">Zeigt Speicherstatistiken, einschließlich Cache-/Buffer-Konzepten. „used“ bedeutet nicht einfach „dauerhaft unverfügbar“.</Command><Command value="ps aux">Zeigt unter anderem Benutzer, PID, Ressourcenindikatoren und Befehl. Nichts beenden.</Command></div></Section>
    <Section id="inventory-services" title="Dienste und Pakete"><Command value="systemctl --type=service --state=running">Listet laufende Dienste auf systemd-Systemen read-only. Auf einem Nicht-systemd-System unterscheidet sich dieser Schritt.</Command><p>Für einen bekannten vorhandenen Dienst ist <code>systemctl status &lt;dienst&gt;</code> geeignet. Vermeide die Annahme, dass ein bestimmter Dienst überall existiert. Erkenne danach aus <code>/etc/os-release</code>, ob APT/dpkg, DNF/RPM, pacman oder ein anderes Paketökosystem plausibel ist, und nutze nur die in Lektion 6 gezeigten lesenden Abfragen.</p></Section>
    <Section id="inventory-network" title="Netzwerk und DNS"><div className="grid gap-3 sm:grid-cols-2"><Command value="ip addr">Zeigt Schnittstellen, Zustände und IP-Adressinformationen; DHCP ist nur ein möglicher Ursprung dieser Konfiguration.</Command><Command value="ip route">Zeigt Routingtabelle und gegebenenfalls eine Default-Route/Gateway.</Command><Command value="ss -ltn">Listet lauschende TCP-Sockets numerisch. Ein Listening-Socket beweist noch keine korrekte Anwendung.</Command><Command value="cat /etc/resolv.conf">Liest Resolverangaben. Die Datei kann generiert sein oder auf einen lokalen Resolvermechanismus verweisen.</Command></div><p><code>resolvectl status</code> kann auf passenden systemd-resolved-Systemen weitere Resolverdetails zeigen; nicht jede Installation nutzt diese Architektur. Es werden weder Adressen, Routen noch DNS-Einstellungen verändert.</p></Section>
    <Section id="inventory-documentation" title="Befunde dokumentieren"><div className="overflow-x-auto"><table className="min-w-[44rem] w-full border-collapse text-left text-sm"><thead><tr>{["Kategorie", "Befehl", "Beobachtung", "Bedeutung", "Mögliche Auffälligkeit", "Nächster Check"].map((heading) => <th key={heading} className="border-b p-3 font-bold text-slate-950">{heading}</th>)}</tr></thead><tbody><tr>{["System", "uname -a", "…", "…", "…", "…"].map((cell, index) => <td key={`${cell}-${index}`} className="border-b p-3">{cell}</td>)}</tr><tr>{["Netzwerk", "ip route", "…", "…", "…", "…"].map((cell, index) => <td key={`${cell}-${index}`} className="border-b p-3">{cell}</td>)}</tr></tbody></table></div><p>Nutze dieselben Spalten für System, User, Filesystem, Storage, Memory, Prozesse, Dienste, Pakete, Netzwerk und DNS. Die Vorlage wird nicht gespeichert.</p></Section>
    <LinuxInventoryClassificationCheck />
    <Section id="inventory-conclusion" title="Abschlusscheck"><ul className="list-disc space-y-2 pl-6"><li>Jede Aussage ist durch eine Beobachtung belegt.</li><li><code>df</code> und <code>du</code> werden nicht verwechselt.</li><li>Prozess, Dienst, Socket und Anwendungserfolg bleiben getrennte Konzepte.</li><li>IP-Adresse, Default-Route und Resolverbeobachtung werden separat dokumentiert.</li><li>Keine Änderung wurde ohne Bedarf und Autorisierung vorgenommen.</li></ul></Section>
  </LessonBody>;
}
