import { LearningObjectives } from "./learning-objectives";
import { LinuxCommandMatchingCheck, LinuxDirectoryMatchingCheck, LinuxPathClassificationCheck } from "./linux-checks";
import { DistributionOverview, FilesystemHierarchyOverview, LinuxSystemLayers, TerminalSessionExample } from "./linux-visualizations";
import { MultipleSelectionCheck, type MultipleSelectionOption } from "./multiple-selection-check";

const linuxOptions: readonly MultipleSelectionOption[] = [
  { id: "kernel", label: "Der Linux-Kernel verwaltet zentrale Systemressourcen.", explanation: "Dazu zählen unter anderem Prozesse, Speicher, Geräte, Dateisysteme und Netzwerkzugriffe." },
  { id: "distribution", label: "Eine Distribution kombiniert Kernel und weitere Software.", explanation: "Sie integriert eine kuratierte Systemumgebung; die genaue Zusammenstellung unterscheidet sich." },
  { id: "bash", label: "Bash ist eine Shell.", explanation: "Bash interpretiert Befehle und ist nicht das Terminalfenster selbst." },
  { id: "headless", label: "Ein Linux-System kann ohne grafische Desktop-Oberfläche betrieben werden.", explanation: "Viele Server werden ohne Desktop lokal oder remote über eine Kommandozeile verwaltet." },
  { id: "ubuntu", label: "Ubuntu und Linux sind exakt dasselbe.", explanation: "Ubuntu ist eine von vielen Distributionen rund um den Linux-Kernel." },
  { id: "terminal", label: "Ein Terminal ist immer Bash.", explanation: "Ein Terminal kann unterschiedliche Shells ausführen; Shell und Terminal sind getrennte Konzepte." },
  { id: "root", label: "root ist ein normaler Benutzer ohne besondere Rechte.", explanation: "root ist traditionell der stark privilegierte Superuser." },
  { id: "packages", label: "Jede Linux-Distribution verwendet denselben Paketmanager.", explanation: "Distributionen verwenden unterschiedliche Paketumgebungen, etwa APT/dpkg, DNF/RPM oder pacman." },
];

export function LinuxIntroductionLesson() {
  return <LessonBody><LearningObjectives context="lesson" objectives={["die Rolle des Linux-Kernels erklären", "Linux-Kernel und Linux-Distribution unterscheiden", "typische Bestandteile einer Distribution nennen", "Shell und Terminal unterscheiden", "grafischen Desktop und Betriebssystemkernel unterscheiden", "root konzeptionell erklären", "unterschiedliche Distributionswerkzeuge bei übertragbaren Linux-Grundkonzepten einordnen", "Linux-Einsatz auf Servern, Desktops und eingebetteten Systemen erkennen", "Ubuntu nicht mit Linux als Ganzem gleichsetzen"]} />
    <Section title="Was ist Linux?"><p>Im engeren technischen Sinn ist <strong>Linux der Kernel</strong>. Im Alltag meint „Linux“ oft ein vollständiges Betriebssystem rund um diesen Kernel. Diese alltagssprachliche Verwendung ist sinnvoll, solange die Ebenen klar bleiben.</p><Formula items={["Linux-Kernel", "Systemwerkzeuge und Bibliotheken", "Paketverwaltung", "Anwendungen", "optionaler grafischer Desktop"]} result="Linux-Distribution / vollständige Systemumgebung" /><p>Nicht jede Distribution enthält exakt dieselben Komponenten. Linux läuft auf Servern, Desktops, eingebetteten Geräten und vielen weiteren Systemen; Ubuntu ist nur eine Distribution.</p><LinuxSystemLayers /></Section>
    <Section title="Kernel und User Space"><p>Der Kernel plant Prozesse, verwaltet Speicher, vermittelt Hardware- und Gerätezugriffe, stellt Dateisystem- und Netzwerkfunktionen bereit und bietet Systemschnittstellen für User-Space-Software. Er ist nicht allein das vollständige Betriebssystem.</p><p>Im <strong>User Space</strong> laufen normale Anwendungen, Shells, Dienste und viele Systemwerkzeuge. Vereinfacht gilt: Anwendungen, Shell und Dienste → Systemschnittstellen → Linux-Kernel → Hardware.</p></Section>
    <Section title="Distributionen und Paketverwaltung"><p>Distributionen kombinieren den Kernel mit einer kuratierten Softwareumgebung. Unterschiede betreffen etwa Paketmanager, Release-Modell, Standard-Desktop, Konfigurationswerkzeuge, Softwarestände und Support. Pfade, Benutzer, Prozesse und Berechtigungen bleiben breit übertragbare Konzepte.</p><DistributionOverview /><p className="mt-4">Als Vorschau: Debian/Ubuntu nutzen das APT/dpkg-Ökosystem, Fedora/RHEL DNF/RPM und Arch <code>pacman</code>. Installationsbefehle folgen erst in Lektion 6; der Paketmanager allein definiert keine Distribution.</p></Section>
    <Section title="Shell, Terminal und Desktop"><Definition term="Terminalemulator">Die grafische oder textuelle Oberfläche beziehungsweise das Fenster für eine Kommandozeilensitzung.</Definition><Definition term="Shell">Der Befehlsinterpreter, zum Beispiel bash, zsh oder fish. Ein Terminal kann unterschiedliche Shells starten; Shells können auch ohne grafischen Terminalemulator laufen.</Definition><Definition term="Desktop-Umgebung">Eine optionale grafische Arbeitsumgebung wie GNOME oder KDE Plasma. Server arbeiten häufig ohne Desktop. Kommandozeile und GUI sind Werkzeuge für unterschiedliche Aufgaben; keine ist grundsätzlich überlegen.</Definition><p>Die Kommandozeile ist besonders für Administration, Automation, Fernverwaltung und Fehlersuche wichtig.</p></Section>
    <Section title="root und offene Zusammenarbeit"><p><code>root</code> ist der traditionelle Superuser mit weitreichenden Privilegien. Normale tägliche Arbeit sollte nicht dauerhaft als root erfolgen. Mechanismen wie <code>sudo</code> können autorisierten Benutzern gezielt erhöhte Rechte geben; deren Nutzung ist hier bewusst keine Übung.</p><p>Linux und viele Bestandteile seines Ökosystems werden als Open Source entwickelt: Quellcode kann unter den jeweiligen Lizenzen eingesehen, geprüft und gemeinschaftlich weiterentwickelt werden.</p></Section>
    <MultipleSelectionCheck title="Linux-Grundverständnis" question="Welche Aussagen über Linux sind korrekt?" options={linuxOptions} correctOptionIds={["kernel", "distribution", "bash", "headless"]} successMessage="Richtig: Kernel, Distribution, Shell und optionale grafische Oberfläche sind sauber voneinander getrennt." missedCorrectMessage="Gesucht sind vier Aussagen zu Kernelaufgaben, Distribution, Bash und Systemen ohne GUI." inputName="linux-basics" />
    <Misconceptions items={[["Linux = Ubuntu.", "Ubuntu ist eine Linux-Distribution, nicht Linux als Ganzes."], ["Kernel und Distribution sind dasselbe.", "Der Kernel stellt zentrale Systemdienste bereit; eine Distribution integriert ihn mit weiterer Software."], ["Terminal und Shell sind dasselbe.", "Das Terminal ist die Oberfläche einer Sitzung, die Shell der Befehlsinterpreter."], ["Linux braucht immer eine grafische Oberfläche.", "Ein Desktop ist optional; viele Server laufen ohne ihn."], ["root sollte für normale Arbeit dauerhaft verwendet werden.", "Alltagsarbeit erfolgt mit normalen Rechten; erhöhte Rechte werden nur gezielt eingesetzt."]]} />
    <Section title="Sicher beobachten"><Command value="uname -a">Zeigt Kernel- und Systeminformationen. Nicht jedes Feld beschreibt die Distribution.</Command><Command value="cat /etc/os-release">Liest Distributionsmetadaten, die Linux-Distributionen üblicherweise in <code>/etc/os-release</code> bereitstellen.</Command></Section>
    <Memory items={["Linux = Kernel im engeren Sinn.", "Distribution = Kernel + Systemumgebung + Softwareverwaltung.", "Shell = Befehlsinterpreter.", "Terminal = Oberfläche für die Kommandozeilensitzung.", "root = stark privilegierter Benutzer."]} />
  </LessonBody>;
}

export function LinuxTerminalLesson() {
  return <LessonBody><LearningObjectives context="lesson" objectives={["Befehl, Option und Argument unterscheiden", "pwd, ls, cd und whoami sicher verwenden", "Befehlshilfe untersuchen", "das aktuelle Arbeitsverzeichnis erklären", "einen Shell-Prompt konzeptionell lesen", "stdout und stderr grundlegend unterscheiden", "Exit-Status konzeptionell einordnen", "History und Tab-Vervollständigung konzeptionell nutzen", "privilegierte oder destruktive Befehle nicht blind kopieren"]} />
    <Section title="Aufbau eines Befehls"><Command value="ls -la /etc"><code>ls</code> ist der Befehl, <code>-la</code> sind hier Optionen und <code>/etc</code> ist ein Pfadargument.</Command><p>Kurze Optionen verwenden häufig <code>-a</code>, lange Optionen häufig <code>--all</code>. Die genaue Syntax hängt vom Befehl ab; nicht jedes Werkzeug folgt denselben Konventionen.</p></Section>
    <Section title="Prompt und Arbeitsverzeichnis"><p>Ein Prompt wie <code>azubi@linux:~$</code> kann Benutzer, Host, aktuelles Verzeichnis und Promptzeichen zeigen. Sein Aussehen ist konfigurierbar. <code>$</code> und <code>#</code> sind verbreitete Konventionen, aber kein unfehlbarer Sicherheitsnachweis.</p><Command value="pwd">„Print Working Directory“: gibt etwa <code>/home/azubi</code> als aktuelles Arbeitsverzeichnis aus.</Command><TerminalSessionExample /></Section>
    <Section title="Auflisten, wechseln, Benutzer prüfen"><Command value="ls">Listet den normalen Verzeichnisinhalt.</Command><Command value="ls -l">Erzeugt eine lange Auflistung; Berechtigungsdetails folgen in Lektion 5.</Command><Command value="ls -a">Nimmt auch Namen mit führendem Punkt einschließlich versteckter Einträge auf.</Command><Command value="ls -la">Kombiniert lange Darstellung und versteckte Einträge.</Command><Command value="cd /etc">Wechselt zu einem absoluten Ziel.</Command><Command value="cd ..">Wechselt ins Elternverzeichnis.</Command><Command value="cd ~">Wechselt in üblichen Shells durch Tilde-Expansion ins Home-Verzeichnis.</Command><Command value="cd">Kehrt in typischen Shells ebenfalls ins Home-Verzeichnis zurück.</Command><Command value="cd -">Wechselt in verbreiteten Shells wie bash zum vorherigen Verzeichnis.</Command><Command value="whoami">Zeigt den effektiven Benutzernamen: als welcher Benutzer Befehle aktuell laufen.</Command></Section>
    <Section title="Hilfe, History und Vervollständigung"><Command value="ls --help">Viele Befehle bieten so Kurzreferenz; das Verhalten ist nicht universell.</Command><Command value="man ls">Öffnet die Handbuchseite, sofern sie installiert ist. Shell-Built-ins können eigene Hilfefunktionen haben.</Command><p>Tab-Vervollständigung kann abhängig von Shell und Konfiguration Tippfehler bei Befehlen und Pfaden reduzieren. Eine History erlaubt die Wiederverwendung früherer Befehle; die Pfeil-nach-oben-Taste ist dafür verbreitet, aber nicht universell. Vor unbekannten Optionen zuerst Dokumentation lesen.</p></Section>
    <Section title="Ausgabe und Exit-Status"><Definition term="stdout">Normale Ausgabe eines Befehls.</Definition><Definition term="stderr">Fehler- oder Diagnoseausgabe. Beide können im Terminal ähnlich erscheinen.</Definition><p>Befehle liefern einen Exit-Status: <code>0</code> steht konventionell für Erfolg, ein anderer Wert für eine vom jeweiligen Befehl definierte Fehler- oder Alternativbedingung. In üblichen POSIX-artigen Shells zeigt <code>echo $?</code> den Status des vorherigen Befehls. Ein stiller Befehl kann trotzdem erfolgreich sein.</p></Section>
    <LinuxCommandMatchingCheck />
    <Section title="Sichere Befehlsgewohnheiten"><aside className="rounded-xl border-2 border-amber-300 bg-amber-50 p-5"><strong>Vor einem unbekannten Befehl:</strong><ul className="mt-3 list-disc space-y-2 pl-6"><li>Wirkung und Optionen verstehen.</li><li>aktuelles Verzeichnis prüfen.</li><li>klären, ob erhöhte Rechte wirklich erforderlich sind.</li><li>bei rekursiven oder destruktiven Operationen besonders vorsichtig sein.</li><li>nichts blind aus unbekannten Quellen einfügen.</li></ul></aside></Section>
    <Misconceptions items={[["Jeder Linux-Befehl braucht sudo.", "Normale Navigation und viele Untersuchungen benötigen keine erhöhten Rechte."], ["ls zeigt automatisch auch alle versteckten Dateien.", "Dafür ist üblicherweise die Option -a erforderlich."], ["cd verändert Dateien.", "cd ändert nur das Arbeitsverzeichnis der aktuellen Shell."], ["Keine Ausgabe bedeutet Fehlschlag.", "Manche erfolgreichen Befehle bleiben still; der Exit-Status liefert zusätzliche Information."], ["Internetbefehle kann man gefahrlos kopieren.", "Quelle, Wirkung, Optionen, Arbeitsverzeichnis und benötigte Rechte müssen geprüft werden."]]} />
    <Section title="Praxis: sicher orientieren"><ol className="list-decimal space-y-2 pl-6"><li>Benutzer mit <code>whoami</code> bestimmen.</li><li>Arbeitsverzeichnis mit <code>pwd</code> bestimmen.</li><li>Inhalt mit <code>ls</code> auflisten.</li><li>Versteckte Einträge mit <code>ls -a</code> einbeziehen.</li><li>Mit <code>cd</code> in ein bekanntes vorhandenes Verzeichnis wechseln.</li><li>Mit <code>cd ~</code> oder <code>cd</code> nach Hause zurückkehren.</li><li>Mit <code>ls --help</code> oder <code>man ls</code> Hilfe ansehen.</li></ol></Section>
    <Memory items={["pwd → Wo bin ich?", "ls → Was ist hier?", "cd → Verzeichnis wechseln", "whoami → Als welcher Benutzer arbeite ich?", "man / --help → Dokumentation prüfen"]} />
  </LessonBody>;
}

export function LinuxFilesystemLesson() {
  return <LessonBody><LearningObjectives context="lesson" objectives={["den einzelnen, bei / beginnenden Dateisystembaum erklären", "Dateisystemwurzel / und Benutzer root unterscheiden", "absolute und relative Pfade unterscheiden", "., .. und ~ korrekt einordnen", "versteckte Punktdateien verstehen", "wichtige Linux-Verzeichnisse erkennen", "Einhängepunkte konzeptionell erklären", "übliche Groß-/Kleinschreibung einordnen", "Windows-Laufwerksbuchstaben nicht auf Linux übertragen", "sicher durch Pfade navigieren"]} />
    <Section title="Eine Wurzel, drei verschiedene Begriffe"><Definition term="/">Das Wurzelverzeichnis des gesamten Dateisystembaums.</Definition><Definition term="root">Der traditionelle privilegierte Benutzer.</Definition><Definition term="/root">Das übliche Home-Verzeichnis dieses Benutzers. Es ist nicht dasselbe wie <code>/</code>.</Definition><p>Linux zeigt eingebundene Dateisysteme normalerweise nicht als <code>C:</code> oder <code>D:</code>. Sie werden an Verzeichnissen eines gemeinsamen Baums eingehängt.</p><FilesystemHierarchyOverview /></Section>
    <Section title="Absolute und relative Pfade"><p><code>/home/azubi/Dokumente/notizen.txt</code> ist absolut: Der Pfad beginnt bei <code>/</code> und hängt nicht vom Arbeitsverzeichnis ab.</p><p><code>Dokumente/notizen.txt</code> ist relativ. Bei <code>pwd</code> → <code>/home/azubi</code> bezeichnet er dieselbe Datei.</p><Definition term=".">Aktuelles Verzeichnis; <code>./script.sh</code> referenziert eine Datei darin, ohne sie hier auszuführen.</Definition><Definition term="..">Elternverzeichnis; aus <code>/home/azubi/Projekte</code> bezeichnet <code>../Dokumente</code> den Pfad <code>/home/azubi/Dokumente</code>.</Definition><Definition term="~">Shell-Erweiterung, die in üblichen Shells praktisch für das Home-Verzeichnis steht. <code>~/Projekte</code> ist vor der Expansion kein literal gespeicherter absoluter Pfad.</Definition><p><code>./test.txt</code> bedeutet <code>test.txt</code> im aktuellen Verzeichnis.</p></Section>
    <Section title="Punktdateien und Groß-/Kleinschreibung"><p>Namen wie <code>.bashrc</code> und <code>.config</code> werden wegen des führenden Punkts von normalem <code>ls</code> konventionell ausgeblendet. Das ist Namens- und Werkzeugverhalten, kein Windows-artiges Hidden-Attribut.</p><p>Typische Linux-Dateisysteme unterscheiden Groß- und Kleinschreibung: <code>Datei.txt</code> und <code>datei.txt</code> können verschiedene Namen sein. Das konkrete Verhalten hängt vom Dateisystem und Einhängen ab; case-sensitive ist die normale Erwartung.</p></Section>
    <Section title="Wichtige Verzeichnisse"><DirectoryList /></Section>
    <Section title="Einhängepunkte"><p>Ein Mount hängt ein Dateisystem an ein Verzeichnis im vorhandenen Baum. Wird eine SSD-Partition konzeptionell bei <code>/mnt/daten</code> eingehängt, erscheinen ihre Dateien darunter. <code>/mnt</code> ist eine Konvention für temporäres/manuelles Einhängen; <code>/media</code> wird auf manchen Desktop-Systemen für Wechselmedien genutzt. Beides ist nicht zwingend.</p></Section>
    <LinuxPathClassificationCheck /><LinuxDirectoryMatchingCheck />
    <Misconceptions items={[["/root ist dasselbe wie /.", "/ ist die Dateisystemwurzel; /root ist üblicherweise das Home-Verzeichnis von root."], ["/usr enthält alle Benutzer-Homes.", "Diese liegen üblicherweise unter /home; /usr enthält zentrale User-Space-Software und Daten."], ["Linux verwendet grundsätzlich C: und D:.", "Dateisysteme werden in einen gemeinsamen, bei / beginnenden Baum eingehängt."], ["Eine Punktdatei besitzt ein besonderes Hidden-Attribut.", "Das Verbergen ist Konvention und Verhalten von Werkzeugen wie ls."], ["Relative Pfade beginnen immer mit ../.", "Auch Dokumente/datei.txt oder ./datei.txt sind relativ."], ["/bin muss physisch separat sein.", "Beim modernen usr-merge ist /bin häufig ein Symlink nach /usr/bin; beide Darstellungen müssen berücksichtigt werden."]]} />
    <Section title="Praxis: nur lesen und navigieren"><ol className="list-decimal space-y-2 pl-6"><li><code>pwd</code> ausführen.</li><li><code>ls /</code> und danach <code>ls /etc</code> ausführen.</li><li>Das eigene Home-Verzeichnis mit <code>ls ~</code> untersuchen.</li><li>Mit <code>ls -a</code> versteckte Einträge erkennen.</li><li>Mit <code>cd /etc</code> einen absoluten Pfad nutzen.</li><li>Mit <code>cd ..</code> einen relativen Pfad nutzen.</li><li>Mit <code>cd ~</code> oder <code>cd</code> zurückkehren.</li><li>Mit <code>ls -ld /bin /sbin /usr/bin</code> beobachten, ob Pfade Verzeichnisse oder symbolische Links sind.</li></ol></Section>
    <Section title="Als Nächstes: Dateien und Verzeichnisse verwalten"><p>Die nächste Lektion behandelt <code>mkdir</code>, <code>touch</code>, <code>cp</code>, <code>mv</code>, <code>rm</code>, Dateiinspektion, sichere Löschgewohnheiten und Globbing auf Einsteigerniveau. Diese Operationen werden hier noch nicht ausgeführt.</p></Section>
  </LessonBody>;
}

function DirectoryList() { const entries = [["/home", "Home-Verzeichnisse normaler Benutzer"], ["/root", "Home-Verzeichnis von root"], ["/etc", "systemweite Konfiguration"], ["/var", "veränderliche Daten wie Logs, Caches, Spools und Dienstdaten"], ["/tmp", "temporäre Dateien; Fortbestand nach Neustart ist nicht versprochen"], ["/usr", "wesentliche User-Space-Programme, Bibliotheken und geteilte Daten"], ["/bin", "historisch essenzielle Befehle; heute oft Symlink nach /usr/bin"], ["/sbin", "historisch Administrationsprogramme; heute oft in /usr zusammengeführt"], ["/dev", "Geräteknoten und -schnittstellen"], ["/proc", "virtuelle Prozess- und Kernelinformationen"], ["/sys", "virtuelle Kernel- und Geräteinformationen"], ["/boot", "startbezogene Dateien"], ["/mnt", "konventioneller temporärer/manueller Einhängeort"], ["/media", "auf manchen Desktops Einhängepunkte für Wechselmedien"]] as const; return <dl className="mt-5 grid gap-3 sm:grid-cols-2">{entries.map(([path, text]) => <div key={path} className="rounded-xl border border-slate-200 bg-white p-4"><dt><code className="font-bold">{path}</code></dt><dd className="mt-2 text-sm leading-6">{text}</dd></div>)}</dl>; }
function LessonBody({ children }: { children: React.ReactNode }) { return <div className="space-y-10 text-base leading-7 text-slate-700 sm:text-lg sm:leading-8">{children}</div>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="text-2xl font-bold tracking-tight text-slate-950">{title}</h2><div className="mt-4 space-y-4">{children}</div></section>; }
function Definition({ term, children }: { term: string; children: React.ReactNode }) { return <div className="rounded-xl border border-slate-200 bg-white p-4"><strong className="text-slate-950">{term}</strong><p className="mt-1 text-sm leading-6">{children}</p></div>; }
function Command({ value, children }: { value: string; children: React.ReactNode }) { return <article className="min-w-0 rounded-xl border border-slate-700 bg-slate-950 p-4 text-white"><code className="block overflow-x-auto font-bold text-blue-200">{value}</code><p className="mt-2 text-sm leading-6 text-slate-200">{children}</p></article>; }
function Formula({ items, result }: { items: readonly string[]; result: string }) { return <div className="rounded-xl border border-blue-200 bg-blue-50 p-5 text-sm"><div className="flex flex-wrap items-center gap-2">{items.map((item, index) => <span key={item} className="contents">{index > 0 && <span aria-hidden="true">+</span>}<span className="rounded-lg bg-white px-3 py-2 font-semibold">{item}</span></span>)}</div><p className="mt-3 font-bold">= {result}</p></div>; }
function Misconceptions({ items }: { items: readonly (readonly [string, string])[] }) { return <section><h2 className="text-2xl font-bold text-slate-950">Typische Fehlvorstellungen</h2><dl className="mt-5 space-y-3">{items.map(([wrong, correction]) => <div key={wrong} className="rounded-xl border border-slate-200 bg-white p-4"><dt className="font-bold text-slate-950">Falsch: „{wrong}“</dt><dd className="mt-2 text-sm"><strong>Korrektur:</strong> {correction}</dd></div>)}</dl></section>; }
function Memory({ items }: { items: readonly string[] }) { return <aside className="rounded-2xl border border-blue-200 bg-blue-50 p-5"><h2 className="text-xl font-bold text-blue-950">Merksätze</h2><ul className="mt-3 list-disc space-y-2 pl-6 text-sm leading-6">{items.map((item) => <li key={item}>{item}</li>)}</ul></aside>; }
