import type { ReactNode } from "react";
import { CodeBlock, FundamentalsLesson, ResponsiveTable, TextFlow, type LessonSection } from "./fundamentals-lesson-elements";
import { SingleChoiceCheck } from "./single-choice-check";

type LessonContent = { objectives: readonly string[]; intro: ReactNode; sections: readonly LessonSection[]; visual?: ReactNode; scenario: { title: string; situation: ReactNode; tasks: readonly ReactNode[]; solution: ReactNode }; takeaway: readonly ReactNode[] };

const lessons: Record<string, LessonContent> = {
  "uml-und-modelle-einordnen": {
    objectives: ["Modell und Realität unterscheiden", "UML als Notationsfamilie einordnen", "Diagrammzweck erkennen", "Detailtiefe passend wählen"],
    intro: <p>Ein Modell hebt für eine Fragestellung wichtige Aspekte hervor und lässt anderes bewusst weg. UML bietet mehrere Diagrammarten; kein einzelnes Diagramm beschreibt automatisch das gesamte System.</p>,
    sections: [
      { title: "Sichten statt vollständiger Kopie", paragraphs: [<>Ein Use-Case-Diagramm zeigt Nutzungssichten, ein Klassendiagramm Struktur und ein Aktivitätsdiagramm Abläufe. Dieselbe Fachlichkeit kann in mehreren Sichten erscheinen, ohne dass die Symbole austauschbar sind.</>, <>Zielgruppe und Entscheidung bestimmen den Detailgrad. Ein grobes Gesprächsmodell und eine technische Spezifikation dürfen unterschiedlich detailliert sein.</>] },
      { title: "Notation verständlich nutzen", paragraphs: [<>Ein Diagramm braucht Titel, konsistente Begriffe und eine Legende, wenn eigene vereinfachte Darstellungsmittel verwendet werden. Pfeile oder Linien erhalten nur die Bedeutung, die die gewählte Notation festlegt.</>], activity: <SingleChoiceCheck title="Passende Sicht" question="Welches Diagramm eignet sich primär, um einen Entscheidungsablauf zu verfolgen?" inputName="modeling-view" correctOptionId="activity" successMessage="Aktivitätsdiagramme zeigen Handlungen und Kontrollfluss." options={[{id:"usecase",label:"Use-Case-Diagramm",explanation:"Es zeigt Akteure und Anwendungsfälle."},{id:"class",label:"Klassendiagramm",explanation:"Es zeigt statische Struktur."},{id:"activity",label:"Aktivitätsdiagramm",explanation:"Es visualisiert Ablauf und Entscheidungen."},{id:"er",label:"ER-Modell",explanation:"Es modelliert Datenbeziehungen."}]} /> },
    ],
    visual: <ResponsiveTable caption="Modelle nach Fragestellung" headers={["Modell", "Kernfrage", "typische Elemente"]} rows={[["Use Case", "Wer nutzt welche Funktion?", "Akteur, Anwendungsfall, Systemgrenze"],["Klasse", "Welche Struktur und welches Verhalten?", "Klasse, Attribut, Methode, Beziehung"],["Aktivität", "Wie läuft ein Prozess?", "Aktion, Entscheidung, Fluss"],["ER", "Welche Daten hängen zusammen?", "Entität, Attribut, Beziehung, Kardinalität"]]} />,
    scenario: { title: "Helpdesk modellieren", situation: <p>Ein Team möchte zuerst Rollen und angebotene Systemfunktionen klären, nicht technische Klassen.</p>, tasks: ["Welche Diagrammart passt?", "Welche Details bleiben zunächst außen vor?"], solution: <p>Ein Use-Case-Diagramm passt. Datenbanktabellen, Methoden und konkrete Bildschirmabläufe gehören nicht zwingend in diese erste Sicht.</p> },
    takeaway: ["Modelle sind zweckgebundene Vereinfachungen.", "Diagrammarten beantworten unterschiedliche Fragen.", "Konsistente Begriffe sind wichtiger als Dekoration."],
  },
  "use-case-diagramme": {
    objectives: ["Akteure erkennen", "Anwendungsfälle formulieren", "Systemgrenze erklären", "Nutzung von internen Abläufen trennen"],
    intro: <p>Ein Use-Case-Diagramm zeigt, welche externen Rollen mit welchen fachlichen Funktionen eines betrachteten Systems interagieren.</p>,
    sections: [
      { title: "Akteur, Use Case und Grenze", paragraphs: [<>Ein Akteur ist eine Rolle außerhalb der betrachteten Systemgrenze, etwa „Lernender“ oder ein externes Identitätssystem. Eine konkrete Person ist nicht automatisch ein eigener Akteurstyp.</>, <>Use Cases werden als fachliche Ziele benannt, etwa „Ticket erfassen“. Die Systemgrenze zeigt, welche Funktionen zum betrachteten System gehören.</>], activity: <SingleChoiceCheck title="Akteur bestimmen" question="Wer ist im Helpdesk-System ein plausibler Akteur?" inputName="modeling-actor" correctOptionId="role" successMessage="Ein Akteur beschreibt eine externe Rolle." options={[{id:"role",label:"die Rolle Support-Mitarbeiter",explanation:"Sie interagiert von außen mit dem System."},{id:"table",label:"die interne Tabelle tickets",explanation:"Eine Tabelle ist kein externer Akteur."},{id:"method",label:"die Methode save()",explanation:"Eine Methode gehört zur internen Struktur."},{id:"button",label:"die Farbe der Speichern-Schaltfläche",explanation:"Das ist ein UI-Detail."}]} /> },
      { title: "Nicht zum Ablaufdiagramm machen", paragraphs: [<>Die Verbindung zwischen Akteur und Use Case bedeutet Teilnahme, nicht automatisch zeitliche Reihenfolge. Interne Einzelschritte werden in anderen Modellen beschrieben.</>, <>Systemgrenzen hängen vom Betrachtungsgegenstand ab: Ein E-Mail-Dienst kann außerhalb eines Ticketsystems liegen, obwohl beide technisch zusammenarbeiten.</>] },
    ],
    visual: <CodeBlock caption="Strukturierte Use-Case-Skizze">{"Akteur: Lernender\nSystem: Azubi Lab\n  (Lernmodul öffnen)\n  (Quiz bearbeiten)\n  (Fortschritt ansehen)"}</CodeBlock>,
    scenario: { title: "Geräteausgabe", situation: <p>Ein Mitarbeitender beantragt ein Gerät; der IT-Support prüft und dokumentiert die Ausgabe.</p>, tasks: ["Nenne zwei Akteure.", "Formuliere zwei fachliche Use Cases."], solution: <p>Akteure: Mitarbeitender, IT-Support. Use Cases: „Gerät beantragen“ und „Geräteausgabe dokumentieren“. Interne Tabellen sind keine Akteure.</p> },
    takeaway: ["Akteure sind externe Rollen.", "Use Cases beschreiben fachliche Ziele.", "Assoziationen zeigen keine Ablaufreihenfolge."],
  },
  "klassendiagramme": {
    objectives: ["Klasse und Objekt unterscheiden", "Attribute und Methoden lesen", "Sichtbarkeit grundlegend deuten", "einfache Beziehungen interpretieren"],
    intro: <p>Ein Klassendiagramm beschreibt statische Typen, ihre Eigenschaften, ihr Verhalten und Beziehungen. Ein Objekt ist eine konkrete Instanz und nicht dasselbe wie die Klasse.</p>,
    sections: [
      { title: "Drei Bereiche einer Klasse", paragraphs: [<>Der Klassenname steht typischerweise oben, Attribute in der Mitte und Methoden unten. <code>+ public</code> und <code>- private</code> sind gebräuchliche Sichtbarkeitszeichen.</>, <>Attribute halten modellierten Zustand, Methoden beschreiben angebotene Operationen. Ein Datenbankfeld und ein UML-Attribut können zusammenhängen, sind aber nicht automatisch identisch.</>], activity: <SingleChoiceCheck title="Element zuordnen" question="Was beschreibt status: Text in der Klasse Ticket?" inputName="modeling-class-element" correctOptionId="attribute" successMessage="Name und Typ kennzeichnen ein Attribut." options={[{id:"object",label:"ein konkretes Objekt",explanation:"Es fehlt eine konkrete Instanz."},{id:"attribute",label:"ein Attribut",explanation:"Es beschreibt eine Eigenschaft der Klasse."},{id:"method",label:"eine Methode",explanation:"Eine Methode hätte typischerweise eine Operationsschreibweise."},{id:"actor",label:"einen Akteur",explanation:"Akteure gehören zur Use-Case-Sicht."}]} /> },
      { title: "Beziehungen vorsichtig lesen", paragraphs: [<>Eine Linie kann eine Assoziation darstellen; Rollenname und Kardinalität präzisieren sie. Aggregation und Komposition haben speziellere Lebenszyklusaussagen und sollten nicht ohne fachlichen Grund verwendet werden.</>, <>Vererbung ist nicht Schwerpunkt dieses Moduls. Für einfache Prüfungsfälle genügen Klassen, Attribute, Methoden, Sichtbarkeit und klar beschriftete Beziehungen.</>] },
    ],
    visual: <CodeBlock caption="Vereinfachte Klasse">{"Ticket\n----------------\n- nummer: Ganzzahl\n- status: Text\n----------------\n+ schliessen(): Boolesch"}</CodeBlock>,
    scenario: { title: "Inventarsystem", situation: <p>Die Klasse Gerät besitzt Inventarnummer und Status; die Methode reservieren() ändert den Zustand.</p>, tasks: ["Was ist Klasse, Attribut und Methode?", "Ist Gerät-4711 Klasse oder Objekt?"], solution: <p>Gerät ist die Klasse, Inventarnummer/Status sind Attribute, reservieren() ist eine Methode. Gerät-4711 ist ein konkretes Objekt.</p> },
    takeaway: ["Klassen sind Typen, Objekte konkrete Instanzen.", "Attribute beschreiben Zustand, Methoden Verhalten.", "Beziehungssymbole brauchen fachlich passende Bedeutung."],
  },
  "aktivitaetsdiagramme": {
    objectives: ["Start und Ende erkennen", "Aktionen verfolgen", "Entscheidungen und Guards lesen", "resultierenden Pfad bestimmen"],
    intro: <p>Aktivitätsdiagramme zeigen Kontrollfluss. Ein Ablauf beginnt, führt Aktionen aus, verzweigt an Bedingungen und endet an einem Endknoten.</p>,
    sections: [
      { title: "Entscheidung mit Bedingungen", paragraphs: [<>Eine Raute kann einen Entscheidungs- oder Zusammenführungsknoten darstellen. Ausgehende Zweige erhalten eindeutige Bedingungen, oft Guards wie <code>[genehmigt]</code> und <code>[abgelehnt]</code>.</>, <>Bedingungen sollten sich für den betrachteten Fall nicht widersprechen. Eine reine Reihenfolge von Tätigkeiten braucht keine Entscheidung.</>], activity: <SingleChoiceCheck title="Pfad verfolgen" question="Nach 'Antrag prüfen' gilt genehmigt = FALSCH. Welcher Zweig folgt?" inputName="modeling-activity-path" correctOptionId="reject" successMessage="Der Guard [nicht genehmigt] bestimmt den Ablehnungszweig." options={[{id:"approve",label:"Gerät ausgeben",explanation:"Dieser Zweig verlangt genehmigt."},{id:"reject",label:"Ablehnung mitteilen",explanation:"Der negative Guard trifft zu."},{id:"both",label:"beide gleichzeitig",explanation:"Die Entscheidung wählt hier genau einen Zweig."},{id:"start",label:"zum Start zurück",explanation:"Dafür ist kein Rückfluss modelliert."}]} /> },
      { title: "Parallelität nicht erraten", paragraphs: [<>Balken können parallele Pfade aufteilen oder synchronisieren. Ein gewöhnlicher Entscheidungsknoten bedeutet keine parallele Ausführung.</>, <>Das Diagramm zeigt modelliertes Verhalten, nicht automatisch Laufzeit, Verantwortlichkeit oder Datenstruktur.</>] },
    ],
    visual: <TextFlow caption="Einfacher Entscheidungsablauf" steps={["Start", "Antrag prüfen", "[genehmigt?]", "ausgeben oder ablehnen", "Ende"]} />,
    scenario: { title: "Passwort-Reset", situation: <p>Nach Identitätsprüfung wird bei Erfolg ein Reset gestartet, sonst an den Support eskaliert.</p>, tasks: ["Formuliere beide Guards.", "Welcher Pfad gilt bei fehlgeschlagener Prüfung?"], solution: <p>Guards etwa [Identität bestätigt] und [Identität nicht bestätigt]. Bei Fehlschlag folgt die Eskalation, nicht der Reset.</p> },
    takeaway: ["Aktionen und Kontrollfluss bilden einen Ablauf.", "Guards entscheiden über Zweige.", "Entscheidung und Parallelität sind verschiedene Konstrukte."],
  },
  "er-modell-und-kardinalitaeten": {
    objectives: ["Entitäten und Attribute bestimmen", "Beziehungen benennen", "Kardinalitäten lesen", "n:m-Beziehungen erkennen"],
    intro: <p>Ein ER-Modell beschreibt fachliche Datenobjekte und ihre Beziehungen. Es bleibt zunächst unabhängig von konkreten SQL-Abfragen.</p>,
    sections: [
      { title: "Entität, Attribut, Beziehung", paragraphs: [<>Kunde und Ticket können Entitätstypen sein; Kundennummer oder Betreff Attribute. „Kunde erstellt Ticket“ ist eine Beziehung.</>, <>Kardinalitäten beschreiben, wie viele Ausprägungen beteiligt sein dürfen oder müssen. Bei „ein Kunde erstellt viele Tickets; jedes Ticket gehört genau einem Kunden“ liegt Kunde 1:n Ticket vor.</>], activity: <SingleChoiceCheck title="Kardinalität" question="Viele Benutzer können viele Gruppen besitzen. Welche Beziehung ist das fachlich?" inputName="modeling-cardinality" correctOptionId="many" successMessage="Auf beiden Seiten sind mehrere Zuordnungen möglich." options={[{id:"one",label:"1:1",explanation:"Das würde je Seite höchstens eine Zuordnung erlauben."},{id:"one-many",label:"1:n",explanation:"Hier können auch Benutzer mehrere Gruppen haben."},{id:"many",label:"n:m",explanation:"Beide Seiten können mehrfach zugeordnet sein."},{id:"none",label:"keine Beziehung",explanation:"Mitgliedschaften sind eine Beziehung."}]} /> },
      { title: "Fachregeln entscheiden", paragraphs: [<>Kardinalitäten werden nicht geraten, sondern aus Regeln abgeleitet. „Kann“ deutet auf optionale Teilnahme, „muss genau“ auf verpflichtende Eindeutigkeit.</>, <>Eine n:m-Beziehung wird bei relationaler Umsetzung typischerweise durch eine Zuordnungstabelle aufgelöst. Das ist Modellierung, noch kein SQL-Kurs.</>] },
    ],
    visual: <CodeBlock caption="ER-Skizze in Textform">{"KUNDE (kundennummer, name)\n  1 ─── erstellt ─── n\nTICKET (ticketnummer, betreff)"}</CodeBlock>,
    scenario: { title: "Geräte und Standorte", situation: <p>Jedes Gerät steht aktuell an genau einem Standort; an einem Standort stehen viele Geräte.</p>, tasks: ["Nenne Entitäten und Beziehung.", "Welche Kardinalität gilt?"], solution: <p>Entitäten Gerät und Standort, Beziehung „steht an“. Standort 1:n Gerät beziehungsweise Gerät n:1 Standort.</p> },
    takeaway: ["Entitäten sind fachliche Datenobjekte.", "Kardinalitäten folgen Geschäftsregeln.", "n:m benötigt relational meist eine Zuordnung."],
  },
  "relationale-tabellen-und-schluessel": {
    objectives: ["Tabellen und Zeilen einordnen", "Primärschlüssel auswählen", "Fremdschlüssel konzeptionell verstehen", "Redundanzprobleme erkennen"],
    intro: <p>Im relationalen Modell werden gleichartige Datensätze in Tabellen dargestellt. Ein Primärschlüssel identifiziert jede Zeile eindeutig und stabil.</p>,
    sections: [
      { title: "Schlüssel statt Zufall", paragraphs: [<>Eine Kundennummer eignet sich eher als Primärschlüssel als ein nicht eindeutiger Name. Ein Fremdschlüssel verweist auf den Schlüssel einer anderen Tabelle und bildet Beziehungen ab.</>, <>Technische Schlüssel können sinnvoll sein; fachliche Eindeutigkeit kann zusätzlich durch Regeln abgesichert werden. „Eindeutig heute“ reicht nicht, wenn sich der Wert später ändert.</>], activity: <SingleChoiceCheck title="Primärschlüssel" question="Welches Attribut eignet sich für Geräte am besten als Primärschlüssel?" inputName="modeling-primary-key" correctOptionId="inventory" successMessage="Eine eindeutige stabile Inventar-ID identifiziert die Zeile." options={[{id:"model",label:"Modellname",explanation:"Viele Geräte können dasselbe Modell haben."},{id:"room",label:"Raumnummer",explanation:"Mehrere Geräte stehen im selben Raum und können umziehen."},{id:"inventory",label:"eindeutige Inventar-ID",explanation:"Sie ist für die Identifikation gedacht."},{id:"color",label:"Gehäusefarbe",explanation:"Sie ist weder eindeutig noch stabil."}]} /> },
      { title: "Redundanz verursacht Pflegeprobleme", paragraphs: [<>Wird derselbe Standortname in jeder Gerätezeile wiederholt, können Schreibvarianten und widersprüchliche Änderungen entstehen. Eine eigene Standorttabelle reduziert diese Redundanz.</>, <>Normalisierung wird hier nur als Grundidee behandelt: Fakten werden so strukturiert, dass sie nicht unnötig mehrfach gepflegt werden. SQL-Syntax ist nicht Teil dieses Moduls.</>] },
    ],
    visual: <ResponsiveTable caption="Einfache relationale Abbildung" headers={["Tabelle", "Primärschlüssel", "weitere Attribute/Verweis"]} rows={[["Standort", "standort_id", "name"],["Gerät", "geraet_id", "modell, standort_id → Standort"]]} />,
    scenario: { title: "Doppelte Standortdaten", situation: <p>In 200 Gerätezeilen stehen Standortname und Adresse. Eine Adresse ändert sich.</p>, tasks: ["Welches Problem entsteht?", "Wie verbessert eine Standorttabelle das Modell?"], solution: <p>Viele Zeilen müssten konsistent geändert werden; vergessene Zeilen widersprechen sich. Eine Standorttabelle speichert die Adresse einmal, Geräte verweisen per standort_id darauf.</p> },
    takeaway: ["Primärschlüssel identifizieren Zeilen stabil.", "Fremdschlüssel bilden Beziehungen ab.", "Weniger Redundanz reduziert Änderungsanomalien."],
  },
};

export function ModelingLesson({ lessonSlug }: { lessonSlug: string }) {
  const lesson = lessons[lessonSlug];
  if (!lesson) return null;
  return <FundamentalsLesson lessonId={`modeling-${lessonSlug}`} {...lesson}>{lesson.visual}</FundamentalsLesson>;
}
