import { LearningObjectives } from "./learning-objectives";
import { NetworkAddressClassificationCheck } from "./network-troubleshooting-checks";
import { EvidenceComparison, LocalNetworkDiagnosticOverview, RouteTableOverview, RoutingDecisionVisualization, TroubleshootingMethodFlow } from "./network-troubleshooting-visualizations";
import { SingleChoiceCheck, type SingleChoiceOption } from "./single-choice-check";

const firstResponseOptions: readonly SingleChoiceOption[] = [
  { id: "clarify", label: "Das konkrete Symptom, den Umfang und reproduzierbare Beobachtungen klären", explanation: "Das trennt den vagen Bericht von technischen Fakten und liefert eine Diagnosebasis." },
  { id: "reboot", label: "Den Server sofort neu starten", explanation: "Ein Neustart verändert Zustand, erklärt aber keine Grundursache und kann Evidenz beseitigen." },
  { id: "dns", label: "Den DNS-Server des Clients ändern", explanation: "Für einen DNS-Fehler gibt es noch keinen Beleg." },
  { id: "firewall", label: "Die Firewall deaktivieren", explanation: "Das wäre eine unbegründete und sicherheitsrelevante Änderung." },
  { id: "adapter", label: "Den Netzwerkadapter neu installieren", explanation: "Das Fehlerbild wurde noch nicht eingegrenzt." },
];

const linkLocalOptions: readonly SingleChoiceOption[] = [
  { id: "investigate", label: "IPv4 Link-Local erkannt; automatische Konfiguration, Verbindung und DHCP-Pfad untersuchen", explanation: "169.254.0.0/16 ist ein Hinweis auf einen Konfigurationszustand, aber kein Beweis für eine einzelne Ursache." },
  { id: "dns", label: "DNS ist definitiv ausgefallen", explanation: "DNS erklärt nicht allein, warum die erwartete IPv4-Konfiguration fehlt." },
  { id: "router", label: "Der Internetrouter ist definitiv defekt", explanation: "Mehrere lokale, Client-, VLAN-, Relay- oder DHCP-Ursachen bleiben möglich." },
  { id: "lease", label: "Der PC besitzt damit eine korrekte Firmen-DHCP-Lease", explanation: "Link-Local ist gerade nicht die erwartete Firmenadresse." },
  { id: "static", label: "Sofort irgendeine statische IP setzen", explanation: "Eine Zufallsadresse ist keine Diagnose und kann Konflikte verursachen." },
];

const routingDiagnosticOptions: readonly SingleChoiceOption[] = [
  { id: "path", label: "Routing ab dem lokalen Gateway zum Netz 192.168.20.0/24 und den Rückweg untersuchen", explanation: "Gateway und DNS liefern bereits Evidenz; der nächste Bereich ist der weiterführende Hin- und Rückpfad." },
  { id: "dhcp", label: "Die DHCP-Lease ist definitiv abgelaufen", explanation: "Die Client- und Gateway-Kommunikation liefern dafür keinen Beleg." },
  { id: "dns", label: "DNS ist definitiv defekt", explanation: "Der Name wurde im Szenario bereits korrekt aufgelöst." },
  { id: "mask", label: "Die Clientmaske zufällig ändern", explanation: "Unbelegte Änderungen verschlechtern die Diagnose." },
  { id: "browser", label: "Den Browser neu installieren", explanation: "Das IP-Pfadproblem ist nicht browserspezifisch belegt." },
];

const routeSelectionOptions: readonly SingleChoiceOption[] = [
  { id: "b", label: "Gateway B über 192.168.20.0/24", explanation: "Die /24-Route ist das spezifischste passende Präfix." },
  { id: "a", label: "Gateway A über 0.0.0.0/0", explanation: "Die Default Route passt, ist aber weniger spezifisch als /24." },
  { id: "both", label: "Immer gleichzeitig an beide Gateways", explanation: "Longest Prefix Match wählt zunächst die spezifischere Route." },
  { id: "none", label: "Keine Route passt", explanation: "Sowohl /24 als auch /0 passen; /24 ist spezifischer." },
];

export function TroubleshootingMethodLesson() {
  const layers = ["Physical/Link", "lokale Schnittstelle und Konfiguration", "lokales Subnetz", "Gateway und Routing", "DHCP, DNS und unterstützende Dienste", "Transport und Dienstport", "Anwendung"];
  return <Lesson>
    <LearningObjectives context="lesson" objectives={["ein Problem präzise formulieren", "Benutzerbeschreibung und beobachtete Fakten trennen", "Umfang, Häufigkeit und letzte Änderungen erfassen", "eine Known-Good-Baseline vergleichen", "eine testbare Hypothese bilden", "jeweils eine begründete Änderung durchführen", "Lösung durch erneuten Test verifizieren", "Diagnose und Ergebnis dokumentieren", "Bestätigungsfehler und zufälliges Trial-and-Error vermeiden"]} />
    <Section title="Symptom ist nicht Ursache"><p>„<strong>Internet geht nicht.</strong>“ ist ein Benutzerbericht und zunächst nur eine Symptombeschreibung. Dahinter können getrenntes WLAN, eine unpassende IP-Adresse, ein fehlendes Default Gateway, ein DNS-Problem, nur eine ausgefallene Website, ein Proxy-/Dienstproblem oder eine reine Browserstörung stehen.</p><p>Übersetze einen Bericht nie direkt in eine Grundursache. Formuliere stattdessen eine überprüfbare Beobachtung, zum Beispiel: „PC01 ist per WLAN verbunden; <code>nslookup portal.firma.test</code> liefert einen Timeout, ein bekannter IP-Endpunkt ist jedoch erreichbar.“</p></Section>
    <Section title="Umfang und Reproduzierbarkeit"><QuestionList items={["Ein Benutzer oder viele?", "Ein Gerät oder viele?", "Eine Anwendung oder alle?", "Ein Hostname oder jeder Name?", "Nur das lokale Netz oder auch entfernte Ziele?", "Kabel oder WLAN – und das richtige Netz/SSID?", "Ständig oder zeitweise?", "Seit wann?", "Was wurde zuletzt geändert?"]} /><p>Diese Fragen grenzen den Fehlerraum ein. Ein reproduzierbares Fehlerbild lässt sich gezielt testen; bei sporadischen Fehlern werden Zeitpunkt, Häufigkeit und Begleitumstände besonders wichtig.</p></Section>
    <Section title="Known Good ist Vergleich, keine Kopiervorlage"><p>Der betroffene PC nutzt <code>192.168.10.50/24</code>, ein funktionierender Nachbar <code>192.168.10.60/24</code>. Vergleiche IP, Maske, Gateway, DNS, Netz/VLAN, DHCP oder statische Konfiguration sowie Routen.</p><p>Die Baseline liefert Evidenz über erwarteten Zustand. Sie erlaubt nicht, fremde IP- oder DNS-Werte blind zu kopieren: Geräte können bewusst andere Rollen, Reservierungen oder Routen besitzen.</p></Section>
    <EvidenceComparison />
    <Section title="Die evidenzbasierte Methode"><ol className="grid gap-3 sm:grid-cols-2">{["Beobachten", "Problem präzise definieren", "Evidenz sammeln", "betroffene Schicht eingrenzen", "testbare Hypothese bilden", "Hypothese testen", "nur begründet ändern", "erneut verifizieren", "Befund und Ergebnis dokumentieren"].map((step, index) => <li key={step} className="rounded-xl border border-slate-200 bg-white p-4"><strong className="text-blue-700">{index + 1}.</strong> {step}</li>)}</ol><p>Eine Hypothese muss durch einen erwartbaren Test bestätigt oder widerlegt werden können. Suche auch nach Beobachtungen, die deiner Vermutung widersprechen – das reduziert Confirmation Bias.</p></Section>
    <TroubleshootingMethodFlow />
    <Section title="Schichtweise denken, nicht starr auswendig lernen"><ol className="list-decimal space-y-2 pl-6">{layers.map((layer) => <li key={layer}>{layer}</li>)}</ol><p>Dieses Modell hilft bei der Auswahl des nächsten Tests. Es ist keine Behauptung, jeder reale Vorfall müsse streng und vollständig von oben nach unten abgearbeitet werden.</p></Section>
    <Section title="Werkzeuge passend zur Frage wählen"><div className="grid gap-4 sm:grid-cols-2"><ToolList title="Windows" tools={["ipconfig /all", "ping", "tracert", "route print", "nslookup", "Test-NetConnection"]} /><ToolList title="Linux" tools={["ip addr", "ip route", "ping", "traceroute oder tracepath", "getent, nslookup oder dig", "ss", "curl"]} /></div><Safety>Alle genannten Anwendungen werden hier nur lesend eingesetzt. Verfügbarkeit und Ausgabe hängen von Betriebssystem und Installation ab; kein einzelnes Werkzeug ist überall Pflicht.</Safety></Section>
    <Section title="Ping ist kein universeller Gesundheitstest"><aside className="rounded-xl border-2 border-amber-300 bg-amber-50 p-5"><p><strong>ping</strong> prüft ICMP-Echo-Verhalten, sofern Ziel und Netz dies zulassen. Erfolg ist Evidenz für einen Teil der IP-Erreichbarkeit.</p><p className="mt-3">Ein Fehlschlag beweist weder, dass der Host offline ist, noch dass Route oder Dienst defekt sind – ICMP kann gefiltert werden. Ein Erfolg beweist weder DNS, HTTP, Anwendung noch einen lauschenden TCP-Port.</p></aside></Section>
    <SingleChoiceCheck title="Erster sinnvoller Schritt" question="Ein Benutzer sagt: „Der Server geht nicht.“ Was ist die beste erste Reaktion?" options={firstResponseOptions} correctOptionId="clarify" successMessage="Richtig: Zuerst das genaue Fehlerbild, den Umfang und technische Beobachtungen klären." inputName="troubleshooting-first-step" />
    <Section title="Vier Änderungen, keine klare Erkenntnis"><p>Du änderst gleichzeitig IP, DNS, Gateway und Firewall; danach verschwindet das Symptom. Das ist schlechte Diagnose: Du weißt nicht, welche Änderung relevant war, ob die Hypothese stimmte oder welche unnötigen Abweichungen und Sicherheitsrisiken entstanden sind.</p><p>Besser: Beobachtung → Hypothese → eine kontrollierte, autorisierte Änderung → gleicher Retest → Dokumentation.</p></Section>
    <Section title="Praxis: Vage Berichte präzisieren"><p>Formuliere für jeden Bericht testbare Fragen: „Internet geht nicht“, „Server nicht erreichbar“, „Drucker geht nicht“, „Website lädt nicht“ und „Netzlaufwerk weg“.</p><p>Beispiel Website: Löst der Name auf? Funktioniert eine andere Website? Ist der Ziel-IP-/Dienstpfad erreichbar? Kommt eine HTTP-Antwort? Betrifft es einen Browser oder mehrere Clients?</p></Section>
    <Misconceptions items={[["Der Benutzer sagt DNS ist kaputt, also beginne ich bei DNS.", "Der Bericht ist eine Hypothese; Umfang und technische Evidenz bestimmen den Einstieg."], ["Ping funktioniert = Netzwerk komplett okay.", "ICMP-Erfolg prüft weder DNS noch Port oder Anwendung."], ["Ping funktioniert nicht = Gerät definitiv offline.", "ICMP kann gefiltert sein oder anders behandelt werden."], ["Viele Änderungen gleichzeitig sparen Zeit.", "Sie verhindern eine eindeutige Zuordnung von Ursache und Wirkung."], ["Neustart ist eine Diagnose.", "Ein Neustart kann Zustand verändern, erklärt aber allein keine Grundursache."], ["Wenn es nach einer Änderung funktioniert, war die Vermutung automatisch korrekt.", "Korrelation, Seiteneffekte und mehrere gleichzeitige Änderungen müssen ausgeschlossen werden."]]} />
    <Memory items={["Symptom ≠ Ursache", "Beobachten vor Ändern", "Eine Hypothese muss testbar sein", "Nur eine begründete Änderung gleichzeitig", "Nach jeder Änderung erneut testen", "Dokumentieren"]} />
  </Lesson>;
}

export function ClientIpLocalNetworkLesson() {
  return <Lesson>
    <LearningObjectives context="lesson" objectives={["Schnittstellen- und Linkzustand untersuchen", "IPv4-Adresse, Maske beziehungsweise Präfix, Gateway und DNS unterscheiden", "DHCP-Hinweise in der Clientkonfiguration erkennen", "169.254.0.0/16 als IPv4 Link-Local einordnen", "Loopback und Netzwerkschnittstellenadresse unterscheiden", "gleiches und unterschiedliches Subnetz bestimmen", "auffällige Masken und Adressen erkennen", "ARP-/Neighbor-Zustand konzeptionell einordnen", "Duplicate-IP-Symptome verstehen", "lokale Evidenz vor Router- oder DNS-Vermutungen sammeln"]} />
    <Section title="Zuerst Interface und Link"><QuestionList items={["Kabel verbunden?", "WLAN mit dem erwarteten SSID verbunden?", "Interface aktiviert beziehungsweise up?", "Link vorhanden?", "korrektes Switch-/Funknetz?", "passt der beobachtete Zustand zur Baseline?"]} /><p>Eine Link-LED ist ein Hinweis, aber kein Beweis für Ende-zu-Ende-IP-Kommunikation. Lokale Firewallregeln können Tests beeinflussen; sie werden nicht als Erstmaßnahme deaktiviert.</p></Section>
    <Section title="Clientkonfiguration lesen"><div className="grid gap-4 sm:grid-cols-2"><Command value="ipconfig /all">Windows: Adapter, IPv4-Adresse, Subnetzmaske, Default Gateway, „DHCP aktiviert“, angezeigten DHCP-Server und DNS-Server unterscheiden.</Command><Command value="ip addr">Linux: Schnittstellenzustand sowie Adressen und Präfixe lesen.</Command><Command value="ip route">Linux: Routingtabelle und gegebenenfalls Default Route lesen.</Command><Command value="arp -a · ip neigh">Windows beziehungsweise Linux: lokalen IPv4-Neighbor-/ARP-Cache beobachten.</Command></div><p>Linux-DNS-Konfiguration ist distributions- und dienstabhängig; NetworkManager oder systemd-resolved werden nicht als universal vorausgesetzt. DHCP-Server, Gateway und DNS-Server sind drei verschiedene Rollen, auch wenn ein Gerät mehrere davon übernehmen kann.</p></Section>
    <Section title="Plausibles Konfigurationsbeispiel"><dl className="grid gap-3 sm:grid-cols-2"><Data label="IPv4-Adresse" value="192.168.10.50" text="Identifiziert die Schnittstelle im Beispielnetz." /><Data label="Maske / Präfix" value="255.255.255.0 · /24" text="Trennt lokalen Netz- und Hostanteil." /><Data label="Default Gateway" value="192.168.10.1" text="Next Hop für nicht spezifischer behandelte entfernte Ziele." /><Data label="DNS-Server" value="192.168.10.10" text="Beantwortet beziehungsweise vermittelt Namensauflösung." /></dl><p>Diese Adressen sind für das Beispiel gültig, aber keine universell vorgeschriebenen Gateway- oder DNS-Adressen.</p></Section>
    <Section title="Link-Local und Loopback"><p><code>169.254.0.0/16</code> ist IPv4 <strong>Link-Local</strong>. Windows weist häufig eine solche APIPA-Adresse zu, wenn automatische IPv4-Konfiguration über DHCP keine nutzbare konfigurierte Adresse ergibt. Das ist Evidenz für einen Konfigurationszustand – kein Beweis, dass der DHCP-Server ausgeschaltet ist.</p><p>Mögliche Untersuchungsbereiche sind Link, Client, VLAN/Pfad, Relay, Server, Pool oder andere Konfigurationsprobleme. <code>127.0.0.0/8</code> ist der Loopbackbereich; <code>127.0.0.1</code> bezeichnet häufig den lokalen Host und ist keine Firmen-LAN-Adresse.</p></Section>
    <Section title="Gleiches Subnetz oder Routing?"><p><code>192.168.10.50/24</code> und <code>192.168.10.60/24</code> gehören zu <code>192.168.10.0/24</code> und kommunizieren gewöhnlich lokal, ohne Same-Subnet-Verkehr zum Default Gateway zu senden. <code>192.168.20.60/24</code> liegt in einem anderen Netz und benötigt einen passenden Route-/Gateway-Pfad.</p></Section>
    <LocalNetworkDiagnosticOverview />
    <Section title="Falsche Maske und doppelte Adresse"><p>PC A mit <code>192.168.10.50/24</code> und PC B mit <code>192.168.10.60/16</code> können unterschiedliche Entscheidungen darüber treffen, welche Ziele lokal sind. Das kann verwirrendes oder asymmetrisches Verhalten verursachen, bedeutet aber nicht in jedem Fall Totalausfall.</p><p>Zwei Hosts mit derselben IPv4-Adresse können wechselnde ARP-/Neighbor-Zuordnungen, intermittierende Erreichbarkeit, Verkehr zum falschen Gerät oder Betriebssystemwarnungen verursachen. Verschiedene Gerätenamen verhindern keinen IP-Konflikt.</p></Section>
    <Section title="ARP und lokale Nachbarn"><p>In einem Ethernet-artigen lokalen IPv4-Netz ordnet <strong>ARP</strong> lokale IPv4-Adressen Link-Layer-Adressen zu. <code>arp -a</code> und <code>ip neigh</code> zeigen Cache-/Neighbor-Zustand. Ein vorhandener Eintrag ist historische Evidenz und kein dauerhafter Gesundheitsbeweis für das Ziel.</p><p>Praktische Reihenfolge, sofern passend: Interface/Link → eigene IP-Konfiguration → lokaler Stack/Loopback → bekannter Same-Subnet-Peer → Gateway. Ziele müssen bekannt sein und dürfen ICMP ablehnen; Ping bleibt nur ein Evidenzbaustein.</p></Section>
    <SingleChoiceCheck title="Link-Local richtig einordnen" question="Ein Client zeigt 169.254.44.21 mit 255.255.0.0. Welche Schlussfolgerung ist am besten?" options={linkLocalOptions} correctOptionId="investigate" successMessage="Richtig: Link-Local grenzt die Untersuchung auf automatische Konfiguration und den lokalen DHCP-/Netzpfad ein, beweist aber keine Einzelursache." inputName="link-local-conclusion" />
    <NetworkAddressClassificationCheck />
    <Section title="Praxis: Drei Befunde vergleichen"><ConfigCase title="A · plausibel" values={["192.168.10.50/24", "Gateway 192.168.10.1", "DNS 192.168.10.10"]}>Die Felder sind im Beispielnetz plausibel; daraus folgt noch keine Dienstgesundheit.</ConfigCase><ConfigCase title="B · auffällig" values={["169.254.20.12/16", "kein erwartetes Firmengateway"]}>Link-Local verlangt Untersuchung von automatischer Konfiguration und Pfad. Der exakte Auslöser ist noch offen.</ConfigCase><ConfigCase title="C · Maske prüfen" values={["192.168.10.200/16", "Gateway 192.168.10.1"]}>Die Hostadresse ist syntaktisch gültig, doch das <code>/16</code> kann von der erwarteten <code>/24</code>-Baseline abweichen. Nicht blind korrigieren: Sollzustand belegen.</ConfigCase></Section>
    <Misconceptions items={[["169.254.x.x beweist, dass der DHCP-Server ausgeschaltet ist.", "Link-Local lässt mehrere Client-, Pfad-, Relay-, Server- oder Poolursachen offen."], ["Default Gateway und DNS-Server sind dieselbe Rolle.", "Routing und Namensauflösung sind getrennte Funktionen."], ["127.0.0.1 ist eine nutzbare Firmen-LAN-Adresse.", "Sie gehört zum Loopbackbereich des lokalen Hosts."], ["Verschiedene IP-Adressen können nie in Konflikt stehen.", "Konflikte entstehen insbesondere, wenn zwei Hosts dieselbe Adresse verwenden."], ["Link-LED an bedeutet Layer 3 funktioniert.", "Linkstatus beweist keine gültige IP-Konfiguration oder Ende-zu-Ende-Kommunikation."], ["Same-Subnet-Verkehr geht immer durchs Gateway.", "Gewöhnlicher lokaler Verkehr wird direkt über das lokale Netz zugestellt."], ["Ein ARP-Eintrag beweist, dass der Host jetzt gesund ist.", "Neighbor-Caches sind zeitabhängige Evidenz, keine permanente Wahrheit."]]} />
  </Lesson>;
}

export function GatewayRoutingReachabilityLesson() {
  return <Lesson>
    <LearningObjectives context="lesson" objectives={["die Rolle eines Default Gateways erklären", "lokale und entfernte Ziele unterscheiden", "Routingtabellen konzeptionell lesen", "0.0.0.0/0 als Default Route einordnen", "Longest Prefix Match verstehen", "Windows- und Linux-Routen lesend untersuchen", "tracert und traceroute vorsichtig interpretieren", "fehlende oder falsche Gatewaysymptome erkennen", "Routing und DNS trennen", "Hin- und Rückweg konzeptionell berücksichtigen"]} />
    <Section title="Default Gateway als Next Hop"><p>Ein <strong>Default Gateway</strong> ist der Next-Hop-Router, den ein Host nutzt, wenn keine spezifischere lokale oder andere Route das Ziel behandelt. PC <code>192.168.10.50/24</code> erkennt Server <code>192.168.20.25</code> als entfernt und sendet gewöhnlich zu einem passenden Router, etwa <code>192.168.10.1</code>.</p><p>Für normale Kommunikation mit <code>192.168.10.80/24</code> ist kein Gateway nötig. In einer gewöhnlichen direkt verbundenen Konfiguration wäre Gateway <code>192.168.20.1</code> für PC <code>192.168.10.50/24</code> ohne Sonderroute/on-link-Verfahren verdächtig, weil es nicht über das lokale <code>/24</code> erreichbar ist.</p></Section>
    <RoutingDecisionVisualization />
    <Section title="Routingtabelle und Default Route"><p>Eine Routingtabelle enthält Zielpräfixe und Entscheidungen über Interface oder Next Hop. <code>0.0.0.0/0</code> ist die am wenigsten spezifische IPv4-Route und behandelt Ziele, für die keine spezifischere Route passt. Sie bedeutet nicht universell „Internet“.</p><div className="grid gap-4 sm:grid-cols-3"><Command value="route print">Windows: Routingtabelle lesen.</Command><Command value="Get-NetRoute">PowerShell, optional: Routeninformationen lesen.</Command><Command value="ip route">Linux: Routingtabelle lesen.</Command></div></Section>
    <Section title="Longest Prefix Match"><p>Passen mehrere Routen, wird grundsätzlich das spezifischste passende Präfix bevorzugt. Bei <code>0.0.0.0/0 → Gateway A</code> und <code>192.168.20.0/24 → Gateway B</code> nutzt Ziel <code>192.168.20.25</code> die <code>/24</code>-Route über Gateway B.</p><aside className="rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm"><strong>Vorschau:</strong> Haben passende Routen dieselbe Präfixlänge, können Metriken oder weitere Präferenzen die Auswahl beeinflussen. Diese Lektion verändert keine Metriken.</aside></Section>
    <RouteTableOverview />
    <Section title="Pfad mit tracert oder traceroute beobachten"><div className="grid gap-4 sm:grid-cols-2"><Command value="tracert 203.0.113.10">Windows: sichtbare Teile des Pfads beobachten.</Command><Command value="traceroute 203.0.113.10 · tracepath 203.0.113.10">Linux: je nach vorhandener Installation; kein Zusatzwerkzeug ist Pflicht.</Command></div><p>Ein fehlender Hop oder <code>*</code> beweist nicht, dass dort keine Weiterleitung stattfindet. Router und Firewalls können Pakete weiterleiten, ohne auf Diagnoseprobes zu antworten.</p></Section>
    <Section title="Gateway, weiterführender Pfad oder Dienst?"><ul className="list-disc space-y-2 pl-6"><li>Known-Good-Same-Subnet-Peer erreichbar, Gateway nicht: Gatewayadresse, VLAN/lokales Netz, Routerinterface, Filterung, Neighbor-Auflösung und physischen Pfad untersuchen.</li><li>Gateway erreichbar, entferntes Netz nicht: Routing/Pfad nach dem ersten Hop und Rückweg untersuchen.</li><li>Remote-IP erreichbar, Hostname nicht: DNS ist ein sinnvoller nächster Bereich.</li><li>IP und Name funktionieren, TCP-Dienst scheitert: Port/Dienst untersuchen.</li></ul><p>Diese Aussagen nennen nächste Untersuchungsbereiche, keine absoluten Grundursachen. Ein Gateway-Ping beweist weder Internet-, DNS- noch Dienstverfügbarkeit.</p></Section>
    <Section title="Routing und DNS sind unabhängig"><p><code>nslookup server.firma.test</code> kann korrekt <code>192.168.20.20</code> liefern, während der Client keinen funktionierenden Route-/Rückpfad dorthin hat. Umgekehrt kann IP-Routing funktionieren, obwohl Namensauflösung scheitert.</p><p>Hin- und Rückweg müssen nicht identisch sein. Wenn Client → Router A → Server funktioniert, dem Server aber eine Route zurück zu <code>192.168.10.0/24</code> fehlt, kann der Client trotz bestehendem Hinweg einen Timeout beobachten.</p></Section>
    <SingleChoiceCheck title="Nächsten Untersuchungsbereich wählen" question="192.168.10.50/24 erreicht Gateway 192.168.10.1, aber nicht Server 192.168.20.20; DNS löst korrekt auf. Was untersuchst du als Nächstes?" options={routingDiagnosticOptions} correctOptionId="path" successMessage="Richtig: Untersuche den weiterführenden Route-/Netzpfad und den Rückweg statt DNS oder Clientwerte zufällig zu ändern." inputName="routing-next-area" />
    <SingleChoiceCheck title="Spezifischste Route wählen" question="0.0.0.0/0 führt zu Gateway A, 192.168.20.0/24 zu Gateway B. Wohin geht 192.168.20.25?" options={routeSelectionOptions} correctOptionId="b" successMessage="Richtig: Die passende /24-Route über Gateway B ist spezifischer als /0." inputName="longest-prefix-route" />
    <Section title="Praxis: Drei Ziele, drei Entscheidungen"><p>Client: <code>192.168.10.50/24</code>, Gateway <code>192.168.10.1</code>, DNS <code>192.168.10.10</code>. Routen: <code>192.168.10.0/24 → on-link</code>, <code>192.168.20.0/24 → 192.168.10.254</code>, <code>0.0.0.0/0 → 192.168.10.1</code>.</p><ul className="list-disc space-y-2 pl-6"><li><code>192.168.10.80</code> → on-link</li><li><code>192.168.20.40</code> → Next Hop <code>192.168.10.254</code></li><li><code>203.0.113.10</code> → Default Route über <code>192.168.10.1</code></li></ul><p><code>203.0.113.10</code> stammt aus einem Dokumentationsnetz und ist kein empfohlener DNS- oder Testdienst.</p></Section>
    <Misconceptions items={[["Default Gateway ist für jeden Hostkontakt nötig.", "Gewöhnlicher Same-Subnet-Verkehr bleibt lokal."], ["0.0.0.0/0 bedeutet speziell das Internet.", "Es ist schlicht die am wenigsten spezifische IPv4-Route."], ["Wenn das Gateway antwortet, muss Internet funktionieren.", "Der restliche Hin-/Rückpfad und Zieldienst bleiben ungeprüft."], ["Jeder Traceroute-Stern bedeutet, dass Pakete dort stoppen.", "Zwischengeräte können weiterleiten, ohne auf Probes zu antworten."], ["DNS-Auflösung beweist funktionierendes Routing.", "Namensauflösung und IP-Pfad sind getrennte Funktionen."], ["Wenn eine Anfrage den Server erreicht, ist der Rückweg korrekt.", "Eine fehlende Rückroute kann trotzdem zum Timeout führen."], ["Eine Routingtabelle kann nur eine Route enthalten.", "Mehrere Präfixe und Next Hops sind normal."]]} />
    <Preview title="DHCP- und DNS-Fehler eingrenzen">Als Nächstes untersuchst du Lease und APIPA, DHCP-Pfad, falsche Optionen, Pool-Erschöpfung sowie NXDOMAIN, SERVFAIL, Timeout, Cache und Resolverunterschiede.</Preview>
  </Lesson>;
}

function Lesson({ children }: { children: React.ReactNode }) { return <div className="space-y-10 text-base leading-7 text-slate-700 [&_code]:break-words sm:text-lg sm:leading-8">{children}</div>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="text-2xl font-bold tracking-tight text-slate-950">{title}</h2><div className="mt-4 space-y-4">{children}</div></section>; }
function QuestionList({ items }: { items: readonly string[] }) { return <ul className="grid gap-3 sm:grid-cols-2">{items.map((item) => <li key={item} className="rounded-xl border border-slate-200 bg-white p-4"><span aria-hidden="true" className="mr-2 font-bold text-blue-700">?</span>{item}</li>)}</ul>; }
function ToolList({ title, tools }: { title: string; tools: readonly string[] }) { return <section className="rounded-xl border border-slate-200 bg-white p-4"><h3 className="font-bold text-slate-950">{title}</h3><ul className="mt-3 space-y-2">{tools.map((tool) => <li key={tool}><code>{tool}</code></li>)}</ul></section>; }
function Command({ value, children }: { value: string; children: React.ReactNode }) { return <article className="min-w-0 rounded-xl border border-slate-200 bg-white p-4"><code className="block overflow-x-auto whitespace-pre-wrap break-words font-bold text-blue-900">{value}</code><p className="mt-2 text-sm leading-6">{children}</p></article>; }
function Data({ label, value, text }: { label: string; value: string; text: string }) { return <div className="min-w-0 rounded-xl border border-blue-200 bg-blue-50 p-4"><dt className="text-sm font-bold text-blue-800">{label}</dt><dd className="mt-1"><code className="break-words font-bold text-blue-950">{value}</code><span className="mt-2 block text-sm leading-6">{text}</span></dd></div>; }
function ConfigCase({ title, values, children }: { title: string; values: readonly string[]; children: React.ReactNode }) { return <article className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-bold text-slate-950">{title}</h3><p className="mt-2"><code>{values.join(" · ")}</code></p><p className="mt-2 text-sm leading-6">{children}</p></article>; }
function Safety({ children }: { children: React.ReactNode }) { return <aside className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950"><strong>Sicherheit:</strong> {children}</aside>; }
function Misconceptions({ items }: { items: readonly (readonly [string, string])[] }) { return <section><h2 className="text-2xl font-bold text-slate-950">Typische Fehlvorstellungen</h2><dl className="mt-5 space-y-3">{items.map(([wrong, correction]) => <div key={wrong} className="rounded-xl border border-slate-200 bg-white p-4"><dt className="font-bold text-slate-950">Falsch: „{wrong}“</dt><dd className="mt-2 text-sm"><strong>Korrektur:</strong> {correction}</dd></div>)}</dl></section>; }
function Memory({ items }: { items: readonly string[] }) { return <aside className="rounded-2xl bg-blue-950 p-5 text-white"><h2 className="text-xl font-bold">Merksätze</h2><ul className="mt-3 list-disc space-y-2 pl-6 text-sm">{items.map((item) => <li key={item}>{item}</li>)}</ul></aside>; }
function Preview({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-slate-50 p-5 sm:p-6"><p className="text-sm font-semibold text-blue-700">Nächste Lektion</p><h2 className="mt-1 text-xl font-bold text-slate-950">{title}</h2><p className="mt-3 text-sm leading-6">{children}</p></section>; }
