import type { ReactNode } from "react";
import { networkDeviceExerciseDefinitions } from "../../data/learning-exercises/network-devices";
import { FundamentalsLesson, ResponsiveTable, TextFlow, type LessonSection } from "./fundamentals-lesson-elements";
import { PracticeExercise } from "./practice-exercise";

type DeviceLesson = {
  objectives: readonly string[];
  intro: ReactNode;
  sections: readonly LessonSection[];
  visual?: ReactNode;
  scenario: { title: string; situation: ReactNode; tasks: readonly ReactNode[]; solution: ReactNode };
  takeaway: readonly ReactNode[];
};

const deviceRows = [
  ["Repeater", "typisch Layer 1", "Signal/Bitstrom", "regeneriert beziehungsweise wiederholt", "Spezialfälle; klassische Ethernet-Repeater historisch"],
  ["Hub", "Layer 1", "keine Adressen", "Bits an alle anderen Ports", "weitgehend historisch"],
  ["Bridge/Switch", "typisch Layer 2", "Ziel-MAC, VLAN", "Frames innerhalb einer Broadcast-Domäne", "Switch sehr verbreitet"],
  ["Router", "Layer 3", "Ziel-IP und Routingtabelle", "Pakete zwischen IP-Netzen", "zentral in LAN/WAN/Internet"],
  ["Access Point", "typisch Layer 2 plus Funkfunktionen", "MAC/SSID/Sicherheitskontext", "Frames zwischen WLAN und LAN", "sehr verbreitet"],
] as const;

const lessons: Record<string, DeviceLesson> = {
  "warum-netzwerke-gekoppelt-werden": {
    objectives: ["Koppelelemente nach ihrer Weiterleitungsinformation unterscheiden", "Layer-1-, Layer-2- und Layer-3-Funktionen einordnen", "Segmentierung von reiner Reichweitenverlängerung trennen", "ein Gerät anhand einer Anforderung auswählen"],
    intro: <><p>Ein Netz wird nicht einfach durch „irgendeine Box“ verbunden. Geräte regenerieren Signale, verbinden lokale Segmente, leiten zwischen IP-Netzen oder übersetzen Zugangs- und Anwendungsprotokolle.</p><p>Für die Auswahl zählen die benötigte Reichweite, die betrachtete Adresse, Broadcast-Grenzen, Medien, Leistung, Verfügbarkeit und Sicherheitsanforderungen.</p></>,
    sections: [
      { title: "Drei grundlegende Entscheidungen", paragraphs: [<>Layer-1-Geräte behandeln Signale, ohne MAC- oder IP-Ziele zu verstehen. Layer-2-Geräte werten Frames und typischerweise MAC-Adressen aus. Layer-3-Geräte treffen Entscheidungen für IP-Pakete anhand von Netzen und Routen.</>, <>Multifunktionsgeräte können mehrere Rollen vereinen. Ein „WLAN-Router“ für kleine Standorte enthält häufig Router, Switch, Access Point, Firewall und eventuell Modem in einem Gehäuse.</>], points: ["Signal weitertragen", "Frames lokal gezielt weiterleiten", "Pakete zwischen IP-Netzen routen", "Medien oder Protokolle an einer Grenze anpassen"] },
      { title: "Domänen statt nur Ports zählen", paragraphs: [<>Eine Kollisionsdomäne beschreibt den Bereich, in dem gleichzeitige Übertragungen auf einem gemeinsam genutzten Medium kollidieren können. Eine Broadcast-Domäne beschreibt, welche Layer-2-Teilnehmer einen Broadcast erhalten.</>, <>Moderne Full-Duplex-Switchports vermeiden klassische Ethernet-Kollisionen pro Link. Broadcasts bleiben jedoch innerhalb desselben VLANs sichtbar, bis ein Layer-3-Gerät die Domäne begrenzt.</>] },
      { title: "Gerätenamen sind keine vollständige Architektur", paragraphs: [<>Ein Layer-3-Switch kann routen, ein Router kann Switchports enthalten und ein Access Point kann zusätzliche Routerfunktionen besitzen. Entscheidend ist die aktiv genutzte Funktion im Szenario.</>, <>Dokumentiere Schnittstellen, VLANs, IP-Netze und Rollen. Eine Produktbezeichnung allein beantwortet nicht, wie der Datenverkehr tatsächlich läuft.</>] },
    ],
    visual: <ResponsiveTable caption="Koppelelemente nach ihrer Hauptfunktion" headers={["Gerät", "typische Ebene", "ausgewertete Information", "Weiterleitung", "heutige Einordnung"]} rows={deviceRows} />,
    scenario: { title: "Zwei Anforderungen, zwei Funktionen", situation: <p>Ein Büro benötigt mehr Ethernet-Ports im selben VLAN und außerdem Kommunikation zum Servernetz <code>192.168.20.0/24</code>.</p>, tasks: ["Welche Funktion erweitert das lokale Layer-2-Netz?", "Welche Funktion verbindet die IP-Netze?"], solution: <p>Ein Switch stellt weitere Ports und lokale Frameweiterleitung bereit. Für die Verbindung verschiedener IP-Netze ist eine Router- beziehungsweise Layer-3-Funktion mit passenden Routen erforderlich. Beide Funktionen können in getrennten oder kombinierten Geräten stecken.</p> },
    takeaway: ["Wähle nach Funktion, nicht nur nach Produktnamen.", "MAC-basierte und IP-basierte Weiterleitung lösen unterschiedliche Aufgaben.", "Collision- und Broadcast-Domains helfen, die Wirkung eines Geräts zu beschreiben."],
  },
  "repeater-und-hub": {
    objectives: ["Repeater und Hub erklären", "ihre fehlende Adressauswertung erkennen", "Kollisions- und Broadcast-Verhalten beschreiben", "historische und aktuelle Einsätze unterscheiden"],
    intro: <><p>Repeater und Hubs arbeiten auf der Bitübertragungsschicht. Sie kennen weder MAC- noch IP-Adressen und treffen keine zielbezogene Weiterleitungsentscheidung.</p></>,
    sections: [
      { title: "Repeater: Signal regenerieren", paragraphs: [<>Ein Repeater empfängt ein Signal, bereitet es innerhalb seiner technischen Spezifikation auf und sendet es weiter. Er verlängert einen Übertragungsabschnitt, filtert aber keine Frames.</>, <>Repeater-Funktionen gibt es weiterhin in verschiedenen Medien und Funkszenarien. Der klassische Ethernet-Repeater aus Koax-/Twisted-Pair-Grundkursen ist im modernen geswitchten LAN kaum noch üblich.</>] },
      { title: "Hub: Multiport-Repeater", paragraphs: [<>Ein Hub wiederholt eingehende Bits an alle anderen Ports. Alle angeschlossenen Stationen teilen sich die verfügbare Übertragungsumgebung und historisch eine Kollisionsdomäne.</>, <>Ein Hub lernt keine MAC-Tabelle. Er kann weder unbekannten Unicast noch Broadcast unterscheiden, weil er den Frameinhalt nicht als Switch auswertet.</>] },
      { title: "Warum der Hub verschwand", paragraphs: [<>Switches stellen jedem Port einen eigenen Punkt-zu-Punkt-Link bereit, können Vollduplex nutzen und Frames gezielt weiterleiten. Das verbessert nutzbare Bandbreite, Skalierung und Isolation gegenüber einem Hub.</>, <>Der Wechsel verhindert jedoch nicht alle Broadcasts und ersetzt keine Layer-3-Segmentierung oder Sicherheitsrichtlinie.</>], note: <><strong>Historisch wichtig:</strong> CSMA/CD und klassische Kollisionen erklären Shared-Ethernet mit Hubs. Auf modernen Full-Duplex-Switchlinks treten diese Kollisionen nicht auf.</> },
    ],
    visual: <ResponsiveTable caption="Hub und Switch im Vergleich" headers={["Merkmal", "Hub", "Switch"]} rows={[["Ebene", "Layer 1", "typisch Layer 2"], ["Adressauswertung", "keine", "MAC-Adresse/VLAN"], ["Weiterleitung", "an alle anderen Ports", "gezielt oder bei Bedarf Flooding"], ["Kollisionsbereiche", "gemeinsam", "pro Port/Link getrennt"], ["Broadcast-Domäne", "eine", "eine pro VLAN, sofern kein Routing"]]} />,
    scenario: { title: "Hub wird durch Switch ersetzt", situation: <p>Acht ältere PCs teilen sich einen Hub. Dieser wird ohne VLAN- oder Routeränderung durch einen Switch ersetzt.</p>, tasks: ["Was ändert sich bei Kollisionen und gezielter Weiterleitung?", "Wird automatisch eine neue Broadcast-Domäne pro Port erzeugt?"], solution: <p>Jeder Switchport bildet einen eigenen Link/Kollisionsbereich und bekannte Unicasts werden gezielt weitergeleitet. Alle Ports im selben VLAN bleiben jedoch Teil derselben Broadcast-Domäne. Eine Broadcast-Trennung entsteht erst durch VLAN-/Layer-3-Grenzen.</p> },
    takeaway: ["Repeater und Hub werten keine Zieladressen aus.", "Der Hub ist im modernen Ethernet weitgehend historisch.", "Ein Switch reduziert Kollisionsbereiche, nicht automatisch die Broadcast-Domäne."],
  },
  "bridge-und-switch": {
    objectives: ["Bridge und Switch als Layer-2-Geräte erklären", "Gemeinsamkeiten und Unterschiede benennen", "MAC-basierte Weiterleitung beschreiben", "VLANs als getrennte Layer-2-Domänen einordnen"],
    intro: <><p>Eine Bridge verbindet Layer-2-Segmente und filtert Frames anhand gelernter MAC-Adressen. Ein moderner Switch lässt sich konzeptionell als schnelle Multiport-Bridge verstehen.</p></>,
    sections: [
      { title: "Bridge", paragraphs: [<>Klassische Bridges hatten wenige Ports und verbanden LAN-Segmente. Sie lernten, hinter welchem Port welche Quell-MAC erschien, und filterten lokale Frames, die nicht in das andere Segment mussten.</>, <>Der Begriff bleibt wichtig für das Verständnis sowie in Software-, Virtualisierungs- und WLAN-Bridging. Als separates Gerät wurde die Bridge weitgehend durch Switches ersetzt.</>] },
      { title: "Switch", paragraphs: [<>Ein Layer-2-Switch verarbeitet viele Ports, pflegt eine MAC-/Forwarding-Tabelle und leitet bekannte Unicast-Frames zum passenden Port. Broadcast und noch unbekannter Unicast werden innerhalb des VLANs geflutet.</>, <>Ein Switch verändert nicht automatisch das IP-Subnetz. VLAN-fähige Switches können mehrere logische Layer-2-Domänen tragen; Kommunikation zwischen ihnen benötigt Layer 3.</>], activity: <PracticeExercise exercise={networkDeviceExerciseDefinitions.typicalLayer} /> },
      { title: "Schleifen und Redundanz", paragraphs: [<>Redundante Layer-2-Verbindungen können ohne Schleifenschutz Broadcast-Stürme und instabile MAC-Tabellen verursachen. Protokolle wie Spanning Tree schaffen kontrollierte, schleifenfreie aktive Pfade.</>, <>Das ist eine konzeptionelle Vorschau: Redundanz erfordert Design und Protokolle; zwei Kabel beliebig parallel zu stecken macht ein Netz nicht automatisch ausfallsicher.</>] },
    ],
    visual: <TextFlow caption="Layer-2-Weiterleitung" steps={["Frame kommt an", "Quell-MAC wird gelernt", "Ziel-MAC wird gesucht", "gezielt senden oder fluten"]} />,
    scenario: { title: "Server und Clients im selben VLAN", situation: <p>Ein Switch kennt die Server-MAC an Port 12. Ein Client an Port 3 sendet einen Unicast-Frame an diese MAC.</p>, tasks: ["Wohin leitet der Switch den Frame?", "Welcher Tabelleninhalt wird zusätzlich gelernt?"], solution: <p>Der bekannte Ziel-Unicast geht nur an Port 12. Zugleich lernt beziehungsweise aktualisiert der Switch die Quell-MAC des Clients an Port 3. Er entscheidet dabei nicht anhand der Ziel-IP.</p> },
    takeaway: ["Bridge und Switch nutzen dieselbe grundlegende Layer-2-Logik.", "Der Switch ist die verbreitete Multiport-Ausprägung.", "VLANs segmentieren Layer 2; Routing verbindet die entstehenden Netze."],
  },
  "wie-ein-switch-lernt": {
    objectives: ["MAC-Lernen aus Quelladressen erklären", "bekannten und unbekannten Unicast unterscheiden", "Broadcast-Flooding einordnen", "Alterung und Schleifenprobleme konzeptionell verstehen"],
    intro: <><p>Ein Switch benötigt keine manuell eingetragene Route zu jedem Endgerät. Er baut dynamisch eine Zuordnung aus MAC-Adresse, VLAN und Eingangsport auf.</p></>,
    sections: [
      { title: "Lernen aus der Quelle", paragraphs: [<>Bei jedem gültigen Frame betrachtet der Switch die Quell-MAC und merkt sich, an welchem Port sie in diesem VLAN erreichbar war. Vorhandene Einträge werden aktualisiert.</>, <>Er lernt nicht aus der Ziel-MAC. Die Ziel-MAC wird für die Weiterleitungsentscheidung in der bereits aufgebauten Tabelle gesucht.</>] },
      { title: "Forwarding, Filtering und Flooding", paragraphs: [<>Ist die Ziel-MAC an einem anderen Port bekannt, sendet der Switch gezielt dorthin. Liegt Quelle und Ziel hinter demselben Port, kann er den Frame für andere Ports filtern.</>, <>Ist ein Unicast-Ziel noch unbekannt, flutet der Switch den Frame an die anderen Ports desselben VLANs. Broadcasts werden ebenfalls innerhalb des VLANs geflutet; ein Router leitet sie gewöhnlich nicht in andere Netze weiter.</>], activity: <PracticeExercise exercise={networkDeviceExerciseDefinitions.switchForwarding} /> },
      { title: "Dynamischer Zustand", paragraphs: [<>MAC-Einträge altern nach einer geräteabhängigen Zeit aus, damit Änderungen der Topologie berücksichtigt werden. Die Tabelle ist Betriebsevidenz, keine dauerhafte Inventarliste.</>, <>Viele wechselnde Einträge, MAC-Flapping oder unerwartete Ports können auf Schleifen, fehlerhafte Verkabelung oder legitime Mobilität/Virtualisierung hindeuten. Der Kontext entscheidet.</>] },
    ],
    visual: <ResponsiveTable caption="Beispiel einer MAC-Tabelle" headers={["VLAN", "MAC-Adresse", "Port", "Art"]} rows={[["10", <code key="a">02:00:5e:10:00:01</code>, "Gi1/0/3", "dynamisch"], ["10", <code key="b">02:00:5e:10:00:20</code>, "Gi1/0/12", "dynamisch"], ["20", <code key="c">02:00:5e:20:00:05</code>, "Gi1/0/18", "dynamisch"]]} />,
    scenario: { title: "Erster Frame an einen neuen Drucker", situation: <p>Der Drucker wurde gerade angeschlossen. Seine Ziel-MAC ist dem Switch im VLAN 10 noch unbekannt.</p>, tasks: ["Wie behandelt der Switch den ersten Unicast?", "Wie kann spätere Weiterleitung gezielter werden?"], solution: <p>Der Switch flutet den Unknown-Unicast innerhalb des VLANs an die anderen geeigneten Ports. Sobald der Drucker selbst sendet, lernt der Switch dessen Quell-MAC am Eingangsport und kann spätere Frames gezielt weiterleiten.</p> },
    takeaway: ["Switches lernen Quell-MAC-Adressen.", "Bekannter Unicast wird gezielt, unbekannter Unicast innerhalb des VLANs geflutet.", "Die MAC-Tabelle ist dynamisch und VLAN-bezogen."],
  },
  "router": {
    objectives: ["Router als Layer-3-Gerät erklären", "Routingentscheidung anhand von Ziel-IP und Präfix beschreiben", "Broadcast-Domänen abgrenzen", "Router und Layer-2-Switch unterscheiden"],
    intro: <><p>Ein Router verbindet IP-Netze. Er entscheidet für ein eingehendes IP-Paket anhand der Zieladresse und seiner Routingtabelle, über welchen nächsten Hop oder welche Ausgangsschnittstelle es weitergeht.</p></>,
    sections: [
      { title: "Routingtabelle und spezifischste Route", paragraphs: [<>Routen enthalten Zielpräfix, Ausgang und gegebenenfalls Next Hop. Passen mehrere Einträge, wird grundsätzlich die spezifischste passende Route ausgewählt (Longest Prefix Match).</>, <>Eine Default Route <code>0.0.0.0/0</code> ist der unspezifische Rückfall für Ziele ohne bessere Route. Sie bedeutet nicht technisch zwingend „Internet“.</>] },
      { title: "Grenze der Broadcast-Domäne", paragraphs: [<>Ein gewöhnlicher Layer-2-Broadcast wird nicht einfach durch den Router in das nächste IP-Netz kopiert. Jede Router-Schnittstelle beziehungsweise jedes geroutete VLAN gehört zu einer eigenen Broadcast-Domäne.</>, <>Bestimmte Dienste wie DHCP können über konfigurierte Relay-Funktionen vermittelt werden. Das ist eine bewusste Layer-3-Funktion, kein allgemeines Broadcast-Forwarding.</>] },
      { title: "Mehr als nur Weiterleitung", paragraphs: [<>Routerprodukte können zusätzlich Firewall, NAT, VPN, Quality of Service oder WAN-Zugang anbieten. Diese Zusatzfunktionen sind nicht identisch mit der Kernaufgabe Routing.</>, <>Ein Layer-3-Switch kann ebenfalls routen. Die Gerätewahl hängt von Schnittstellen, Leistung, Funktionen, Betrieb und Design ab, nicht nur vom Namen.</>] },
    ],
    visual: <TextFlow caption="Routingentscheidung" steps={["Ziel-IP lesen", "passende Präfixe suchen", "spezifischste Route wählen", "neuen lokalen Frame senden"]} />,
    scenario: { title: "Clientnetz zum Servernetz", situation: <p><code>192.168.10.0/24</code> soll mit <code>192.168.20.0/24</code> kommunizieren.</p>, tasks: ["Welche Funktion ist erforderlich?", "Welche Angaben brauchen die Hosts?", "Was passiert mit Broadcasts?"], solution: <p>Es braucht Layer-3-Routing und erreichbare Routeradressen beziehungsweise passende Routen. Hosts verwenden für entfernte Ziele typischerweise ihr Default Gateway. Normale Layer-2-Broadcasts bleiben auf ihre jeweilige Domäne begrenzt.</p> },
    takeaway: ["Router verbinden IP-Netze anhand von Routinginformationen.", "Sie begrenzen Layer-2-Broadcast-Domänen.", "Routing, NAT und Firewalling sind unterscheidbare Funktionen."],
  },
  "gateway": {
    objectives: ["Default Gateway und Router unterscheiden", "Gateway als allgemeinen Übergang erklären", "Protokoll-Gateways einordnen", "den passenden Gatewaybegriff im Kontext verwenden"],
    intro: <><p>„Gateway“ ist ein kontextabhängiger Begriff. In der IP-Konfiguration ist das <strong>Default Gateway</strong> meist die Routeradresse für Ziele ohne spezifischere lokale Route. Allgemeiner kann ein Gateway zwischen unterschiedlichen Systemen oder Protokollen vermitteln.</p></>,
    sections: [
      { title: "Default Gateway", paragraphs: [<>Ein Host vergleicht Ziel-IP und Präfix mit seinen Routen. Ist das Ziel nicht lokal und keine spezifischere Route vorhanden, sendet er das Paket an den nächsten Hop der Default Route.</>, <>Das Default Gateway muss aus Sicht des Hosts über einen direkt erreichbaren Link beziehungsweise das passende lokale Netz erreichbar sein. Seine Konfiguration garantiert noch keinen vollständigen Weg zum Ziel.</>] },
      { title: "Router ist nicht immer gleich Gateway", paragraphs: [<>Ein Router kann viele Netze verbinden, ohne für jeden Host das Default Gateway zu sein. Umgekehrt bezeichnet „Gateway“ häufig die Rolle dieses Routers aus Sicht eines bestimmten Netzes.</>, <>„Gateway“ wird außerdem für Anwendungs- oder Protokollübergänge genutzt, etwa Mail-Gateway, API-Gateway oder VoIP-Gateway. Dort geht es nicht bloß um IP-Routing.</>] },
      { title: "Herstellerbegriffe prüfen", paragraphs: [<>Ein Internet-Gateway-Gerät kann Modem, Router, NAT, Firewall, Switch und Access Point kombinieren. Für Planung und Fehlersuche müssen die Rollen getrennt betrachtet werden.</>, <>Frage daher: Übergang wovon wohin, auf welcher Ebene und mit welcher Entscheidung?</>] },
    ],
    visual: <ResponsiveTable caption="Gateway-Begriffe im Kontext" headers={["Begriff", "Aufgabe", "Beispiel", "nicht automatisch"]} rows={[["Default Gateway", "Next Hop der Default Route", "192.168.10.1", "DNS-Server"], ["Router", "IP-Pakete zwischen Netzen weiterleiten", "LAN ↔ Servernetz", "Protokollübersetzer"], ["Protokoll-/Application-Gateway", "zwischen Protokollen oder Diensten vermitteln", "Mail- oder VoIP-Gateway", "physischer Internetanschluss"]]} />,
    scenario: { title: "Gateway erreichbar, Internet nicht", situation: <p>Ein Client kann sein Default Gateway anpingen, aber ein entferntes Ziel nicht erreichen.</p>, tasks: ["Was ist damit bestätigt?", "Was bleibt zu untersuchen?"], solution: <p>Der lokale Pfad zum Gateway funktioniert zumindest für den Test. Upstream-Routing, Rückweg, Filter, NAT, Zielerreichbarkeit und gegebenenfalls DNS bleiben offen. „Gateway erreichbar“ beweist nicht den gesamten Ende-zu-Ende-Pfad.</p> },
    takeaway: ["Default Gateway ist eine Routenrolle aus Sicht eines Hosts.", "Gateway kann auch Protokollvermittlung bedeuten.", "Kombigeräte müssen funktional statt nur nach Produktname analysiert werden."],
  },
  "access-point-modem-medienkonverter": {
    objectives: ["Access Point, Modem und Medienkonverter unterscheiden", "ihre typischen Ebenen und Informationen einordnen", "Access Point und Router auseinanderhalten", "Kombigeräte funktional analysieren"],
    intro: <><p>Nicht jedes Koppelelement entscheidet zwischen MAC- oder IP-Netzen. Manche Geräte stellen einen Funkzugang bereit, passen Signale an ein Zugangsnetz an oder setzen ein physisches Medium um.</p></>,
    sections: [
      { title: "Wireless Access Point", paragraphs: [<>Ein Access Point verbindet WLAN-Teilnehmer mit einer kabelgebundenen Layer-2-Infrastruktur und koordiniert Funkzugriff, SSID und WLAN-Sicherheitsmechanismen. Er ist typischerweise eine Bridge mit zusätzlichen Funkfunktionen.</>, <>Ein eigenständiger Access Point muss nicht routen oder NAT durchführen. Dass Heimgeräte diese Funktionen kombinieren, macht „Access Point“ und „Router“ nicht synonym.</>], activity: <PracticeExercise exercise={networkDeviceExerciseDefinitions.accessPointRole} /> },
      { title: "Modem beziehungsweise Netzabschluss", paragraphs: [<>Ein Modem beziehungsweise modernes Zugangsgerät passt Signale und Übertragungsverfahren an das Medium oder Providerzugangsnetz an, etwa Kabel-, DSL- oder Mobilfunkzugang. Je nach Technik ist „Modem“ eine vereinfachende Produktbezeichnung.</>, <>Bridge-/Modem-Modus und Routermodus sind zu unterscheiden. Im Routermodus übernimmt das Gerät zusätzliche Layer-3- und häufig Firewall-/NAT-Funktionen.</>] },
      { title: "Medienkonverter", paragraphs: [<>Ein Medienkonverter setzt beispielsweise Kupfer-Ethernet in Glasfaser-Ethernet um. Dabei soll die höhere Kommunikationslogik grundsätzlich erhalten bleiben; das Medium und die physische Darstellung ändern sich.</>, <>Er erzeugt nicht automatisch ein neues IP-Netz, filtert keine Sicherheitsrichtlinie und ersetzt keinen Router.</>] },
    ],
    visual: <ResponsiveTable caption="Spezialisierte Koppelelemente" headers={["Gerät", "Hauptzweck", "wertet typischerweise aus", "häufige Verwechslung"]} rows={[["Access Point", "WLAN-Zugang/Bridging", "Frames, WLAN-Kontext, MAC", "ist nicht automatisch Router"], ["Modem/Zugangsgerät", "Anpassung an Zugangsmedium/-verfahren", "Signal-/Linkverfahren", "Kombigerät kann zusätzlich routen"], ["Medienkonverter", "Medium umsetzen", "Signal/Frame-Transport je nach Gerät", "erzeugt nicht automatisch IP-Segmentierung"]]} />,
    scenario: { title: "WLAN im bestehenden VLAN", situation: <p>Mobilgeräte sollen im bestehenden Client-VLAN dieselben Layer-3-Dienste nutzen wie kabelgebundene PCs.</p>, tasks: ["Welche Gerätefunktion stellt den Funkzugang bereit?", "Ist zwingend ein zusätzlicher Router nötig?"], solution: <p>Ein passend konfigurierter Access Point kann WLAN und vorhandenes VLAN auf Layer 2 verbinden. Ein zusätzlicher Router ist dafür nicht zwingend; Routing ist erst für Übergänge in andere IP-Netze nötig.</p> },
    takeaway: ["Ein Access Point stellt Funkzugang bereit und ist nicht automatisch ein Router.", "Modems/Zugangsgeräte passen an das Anschlussverfahren an.", "Medienkonverter ändern das Medium, nicht automatisch die Netzlogik."],
  },
  "collision-und-broadcast-domains": {
    objectives: ["Kollisions- und Broadcast-Domäne definieren", "Hub, Switch, Router und VLAN zuordnen", "Full-Duplex-Verbindungen einordnen", "Domänen in einfachen Skizzen bestimmen"],
    intro: <><p>Domänen beschreiben, welche Teilnehmer ein bestimmtes gemeinsames Verhalten teilen. Kollisions- und Broadcast-Domäne sind unterschiedliche Begriffe und dürfen nicht anhand der Zahl sichtbarer Geräte gleichgesetzt werden.</p></>,
    sections: [
      { title: "Kollisionsdomäne", paragraphs: [<>Im klassischen gemeinsam genutzten Half-Duplex-Ethernet konnten gleichzeitige Sendungen kollidieren. Ein Hub erweiterte diesen gemeinsamen Bereich.</>, <>Ein Switch trennt die Bereiche portweise. Auf modernen Full-Duplex-Punkt-zu-Punkt-Links gibt es keine klassischen CSMA/CD-Kollisionen, auch wenn der Begriff „eine Kollisionsdomäne pro Switchport“ als Vergleich weiter genutzt wird.</>], activity: <PracticeExercise exercise={networkDeviceExerciseDefinitions.collisionDomains} /> },
      { title: "Broadcast-Domäne", paragraphs: [<>Layer-2-Broadcasts werden von Bridges und Switches innerhalb desselben VLANs weitergeleitet. Daher bilden alle passenden Ports eines VLANs grundsätzlich eine gemeinsame Broadcast-Domäne.</>, <>Router beziehungsweise geroutete Schnittstellen begrenzen diese Domäne. Auch VLANs schaffen getrennte Layer-2-Broadcast-Domänen; die Kommunikation dazwischen benötigt Routing.</>], activity: <PracticeExercise exercise={networkDeviceExerciseDefinitions.broadcastBoundary} /> },
      { title: "Zählen mit klaren Annahmen", paragraphs: [<>Gib bei Aufgaben an, ob Links Full- oder Half-Duplex sind, welche Ports zu welchem VLAN gehören und ob Layer-3-Routing aktiv ist. Ohne diese Angaben kann eine reine Portzählung irreführen.</>, <>WLAN nutzt andere Medienzugriffsmechanismen als klassisches Ethernet. Übertrage Ethernet-Kollisionsbegriffe nicht unkritisch auf Funk.</>] },
    ],
    visual: <ResponsiveTable caption="Wirkung typischer Geräte auf Domänen" headers={["Gerät/Funktion", "Kollisionsbereich", "Broadcastbereich"]} rows={[["Hub", "gemeinsam erweitert", "gemeinsam erweitert"], ["Layer-2-Switch, ein VLAN", "pro Port/Link getrennt", "bleibt ein gemeinsamer Bereich"], ["VLAN-Grenze", "Ports getrennt", "trennt Layer-2-Broadcasts"], ["Router/Layer-3-Interface", "getrennte Links", "trennt Broadcast-Domänen"]]} />,
    scenario: { title: "24-Port-Switch mit zwei VLANs", situation: <p>Zwölf Ports gehören zu VLAN 10, zwölf zu VLAN 20. Jeder Endgeräteport arbeitet Full-Duplex; Routing ist separat vorhanden.</p>, tasks: ["Wie viele Layer-2-Broadcast-Domänen gibt es?", "Teilen alle Endgeräte eine klassische Kollisionsdomäne?"], solution: <p>Es gibt zwei Broadcast-Domänen, je eine pro VLAN. Jeder Full-Duplex-Switchlink ist separat; alle Endgeräte teilen nicht den Kollisionsbereich eines Hubs. Routing verbindet die VLANs nur nach Layer-3-Regeln.</p> },
    takeaway: ["Switches trennen Kollisionsbereiche portweise.", "VLANs und Routergrenzen trennen Broadcast-Domänen.", "Full-Duplex und WLAN benötigen eine vorsichtige, technologiebezogene Einordnung."],
  },
  "welches-geraet-fuer-welchen-zweck": {
    objectives: ["Koppelelemente aus Anforderungen ableiten", "Multifunktionsgeräte in Rollen zerlegen", "Layer-2- und Layer-3-Anforderungen trennen", "eine Auswahl technisch begründen"],
    intro: <><p>Die richtige Gerätewahl beginnt nicht bei einem Produktkatalog, sondern bei der Aufgabe: Müssen Signale überbrückt, Ports erweitert, WLAN bereitgestellt, IP-Netze verbunden oder Zugangsmedien angepasst werden?</p></>,
    sections: [
      { title: "Anforderung → Funktion", paragraphs: [<>Weitere Endgeräte im selben VLAN benötigen typischerweise Switchports. Kommunikation zwischen Subnetzen benötigt Routing. WLAN-Zugang benötigt Access-Point-Funktion. Ein Glasfaserabschnitt kann passende Transceiver oder Medienumsetzung erfordern.</>, <>Ein Gateway für eine Anwendung ist nicht durch ein Default Gateway ersetzt. Ebenso löst ein stärkerer Access Point keine fehlende Route zwischen Netzen.</>], activity: <PracticeExercise exercise={networkDeviceExerciseDefinitions.purposeSelection} /> },
      { title: "Betriebliche Kriterien", paragraphs: [<>Berücksichtige Portgeschwindigkeit und -medien, PoE, VLANs, Routingkapazität, Redundanz, Verwaltung, Monitoring, Updates und Support. Ein technisch möglicher Aufbau kann betrieblich ungeeignet sein.</>, <>Sicherheitsfunktionen müssen explizit geplant werden. Ein VLAN-fähiger Switch oder Router ist nicht automatisch sicher konfiguriert.</>] },
      { title: "Dokumentierte Entscheidung", paragraphs: [<>Halte Zweck, Schnittstellen, logische Netze, Ausfallfolgen und Abhängigkeiten fest. So kann ein anderer Administrator nachvollziehen, warum ein Gerät an dieser Stelle steht.</>, <>Nutze Begriffe präzise: „Der Layer-3-Switch routet zwischen VLAN 10 und 20“ ist aussagekräftiger als „der Switch macht das Netzwerk“.</>] },
    ],
    visual: <ResponsiveTable caption="Schnelle Auswahlhilfe" headers={["Anforderung", "passende Funktion", "typisches Gerät", "wichtige Prüfung"]} rows={[["mehr Ports im selben VLAN", "Layer-2-Forwarding", "Switch", "VLAN, Geschwindigkeit, PoE"], ["zwei IP-Netze verbinden", "Routing", "Router/Layer-3-Switch", "Routen, Rückweg, Richtlinien"], ["WLAN bereitstellen", "Funkzugang/Bridging", "Access Point", "Abdeckung, Kanal, Authentisierung"], ["Kupfer zu Glasfaser", "Medienumsetzung", "Transceiver/Medienkonverter", "Standard, Wellenlänge, Datenrate"], ["Providerzugang", "Zugangsverfahren", "Modem/ONT/Zugangsgerät", "Anschlussart und Betriebsmodus"]]} />,
    scenario: { title: "Neue Etage und Servernetz", situation: <p>Eine neue Büroetage benötigt 30 kabelgebundene Clients, WLAN und Zugriff auf ein getrenntes Server-VLAN.</p>, tasks: ["Welche Funktionen werden benötigt?", "Welche Angaben fehlen noch für eine konkrete Auswahl?"], solution: <p>Benötigt werden ausreichend verwaltete Switchports, Access Points samt passender Anbindung und Layer-3-Routing zum Servernetz. Zu klären sind unter anderem Bandbreite, PoE, Funkplanung, Uplinks, Redundanz, VLAN-/Security-Vorgaben, Monitoring und Budget.</p> },
    takeaway: ["Leite Gerätefunktionen aus technischen und betrieblichen Anforderungen ab.", "Ein Gehäuse kann mehrere klar trennbare Rollen enthalten.", "Eine gute Auswahl nennt Grenzen, Abhängigkeiten und Ausfallfolgen."],
  },
};

export function NetworkDeviceLesson({ lessonSlug }: { lessonSlug: string }) {
  const lesson = lessons[lessonSlug];
  if (!lesson) return null;
  return <FundamentalsLesson lessonId={`devices-${lessonSlug}`} {...lesson} relatedLinks={[{ href: "/lernen/osi-tcp-ip-modell", label: "OSI- & TCP/IP-Modell" }, { href: "/lernen/subnetting", label: "Subnetting" }]}>{lesson.visual}</FundamentalsLesson>;
}

export const networkDeviceLessonSlugs = Object.freeze(Object.keys(lessons));
