import { LearningObjectives } from "./learning-objectives";
import { TroubleshootingSymptomClassificationCheck } from "./network-troubleshooting-checks";
import { DhcpDnsComparison, DhcpDnsDiagnosticFlow, FullTroubleshootingDecisionTree, PracticeEvidenceMatrix, PracticeTopology, ServiceLayerPath, ServiceSymptomComparison } from "./network-troubleshooting-visualizations";
import { SingleChoiceCheck, type SingleChoiceOption } from "./single-choice-check";

const dhcpLinkLocalOptions: readonly SingleChoiceOption[] = [
  { id: "dhcp-path", label: "Lokalen Link sowie DHCP-Bezugspfad, VLAN und erreichbare Infrastruktur untersuchen", explanation: "Link-Local belegt den fehlenden erwarteten IPv4-Zustand, aber noch keine einzelne Ursache." },
  { id: "dns-record", label: "Den DNS-Record der Website ändern", explanation: "Ein Website-Record erklärt den fehlenden normalen Client-Adressbezug nicht." },
  { id: "port", label: "HTTP-Port 443 testen", explanation: "Ohne plausible Clientkonfiguration ist ein Anwendungstest noch nicht der stärkste nächste Schritt." },
  { id: "browser", label: "Den Browser neu installieren", explanation: "Das Symptom liegt vor der Browserschicht." },
  { id: "gateway-dead", label: "Das Gateway ist damit definitiv ausgefallen", explanation: "Die Link-Local-Adresse beweist keinen Ausfall des Gateways." },
];

const dnsNxdomainOptions: readonly SingleChoiceOption[] = [
  { id: "dns", label: "DNS-Namensauflösung und die Daten für server.firma.test untersuchen", explanation: "Der Zielhost ist per IP erreichbar; NXDOMAIN lenkt die Untersuchung auf Namespace und Resolverdaten." },
  { id: "routing", label: "Die Routingtabelle zufällig ändern", explanation: "Die IP-Erreichbarkeit belegt einen ausreichend funktionierenden Pfad zum bekannten Ziel." },
  { id: "dhcp", label: "Den DHCP-Pool vergrößern", explanation: "Eine vorhandene IP-Erreichbarkeit und NXDOMAIN liefern dafür keinen Beleg." },
  { id: "firewall", label: "Die Clientfirewall deaktivieren", explanation: "Das wäre unbegründet und sicherheitsrelevant." },
];

const wrongDnsAnswerOptions: readonly SingleChoiceOption[] = [
  { id: "unexpected", label: "DNS antwortet, aber die Antwort ist für den beabsichtigten Dienst unerwartet", explanation: "Erreichbarkeit des Resolvers und Korrektheit der gelieferten Daten sind getrennte Fragen." },
  { id: "down", label: "Der DNS-Server ist vollständig ausgefallen", explanation: "Er hat eine Antwort geliefert." },
  { id: "correct", label: "Jede DNS-Antwort ist automatisch fachlich korrekt", explanation: "Records, Cache, Resolver oder Sicht können unerwartete Daten liefern." },
  { id: "routing", label: "Das beweist einen Routingfehler zum Webserver", explanation: "Die Namensantwort allein prüft den Pfad zum gelieferten oder erwarteten Ziel nicht." },
];

const tcpSuccess503Options: readonly SingleChoiceOption[] = [
  { id: "application", label: "Webdienst, Anwendung und Backend-Abhängigkeiten untersuchen", explanation: "DNS und TCP funktionieren ausreichend; HTTP 503 ist Evidenz aus der Anwendungsschicht." },
  { id: "mask", label: "Die Client-Subnetzmaske ändern", explanation: "Der erfolgreiche TCP-Aufbau widerspricht einem unbelegten Maskenwechsel." },
  { id: "dhcp", label: "Den DHCP-Pool erweitern", explanation: "Dafür gibt es keine Evidenz." },
  { id: "dns", label: "Den DNS-Namen löschen", explanation: "Der Name wurde bereits erfolgreich aufgelöst." },
];

const refusedOptions: readonly SingleChoiceOption[] = [
  { id: "endpoint", label: "Zielendpunkt, Listener, Dienst, Port und ablehnende Policy untersuchen", explanation: "Die Verbindung wurde für den angefragten TCP-Endpunkt aktiv abgelehnt." },
  { id: "dhcp", label: "Den DHCP-Pool untersuchen", explanation: "Die erfolgreiche Namensauflösung und TCP-Ablehnung liefern dafür keinen Hinweis." },
  { id: "dns", label: "Den DNS-Record neu anlegen", explanation: "DNS löst im Szenario korrekt auf." },
  { id: "path", label: "Den HTTP-Pfad /index.html ändern", explanation: "Vor einer TCP-Verbindung wurde noch keine HTTP-Ressource angefragt." },
];

const unresolvedNameOptions: readonly SingleChoiceOption[] = [
  { id: "name-first", label: "Nein – zuerst Namensauflösung untersuchen oder eine dokumentierte Ziel-IP als Evidenz beschaffen", explanation: "Ohne aufgelöstes oder bekanntes Ziel ist ein HTTP-Statustest nicht sauber definiert." },
  { id: "status", label: "Ja – HTTP 404 und 503 lassen sich ohne Ziel testen", explanation: "HTTP benötigt einen erreichbaren Zielendpunkt." },
  { id: "scan", label: "Ja – zuerst das gesamte Subnetz nach Webservern scannen", explanation: "Ungezieltes Scannen ist weder erforderlich noch Teil dieser Übung." },
  { id: "firewall", label: "Ja – vorher die Firewall vollständig deaktivieren", explanation: "Das wäre eine unbegründete Sicherheitsänderung." },
];

const finalCaseOptions: readonly SingleChoiceOption[] = [
  { id: "server-app", label: "Anwendung, Dienstverfügbarkeit und Backend auf der Serverseite", explanation: "Bis einschließlich TCP 80 ist der Pfad belegt; HTTP 503 stammt aus der Anwendungsschicht." },
  { id: "client-ip", label: "Client-IP-Adresse und Subnetzmaske neu konfigurieren", explanation: "Die korrekte Konfiguration und der funktionierende Ende-zu-Ende-Pfad sprechen dagegen." },
  { id: "dns", label: "DNS-Record ersetzen", explanation: "DNS liefert bereits die dokumentierte Serveradresse." },
  { id: "gateway", label: "Default Gateway austauschen", explanation: "Gateway und Route funktionieren im Szenario." },
];

export function DhcpDnsTroubleshootingLesson() {
  return <Lesson>
    <LearningObjectives context="lesson" objectives={["DHCP- und statische Clientkonfiguration unterscheiden", "Lease-Vorhandensein und Lease-Korrektheit trennen", "IPv4 Link-Local/APIPA als Evidenz einordnen", "falsche DHCP-Optionen für Gateway oder DNS erkennen", "Pool-Erschöpfung und Relay-Pfade konzeptionell einordnen", "IP-Erreichbarkeit von DNS-Auflösung trennen", "NXDOMAIN, SERVFAIL, Timeout und leere Antworten vorsichtig interpretieren", "Resolverergebnisse kontrolliert vergleichen", "falsche oder zwischengespeicherte DNS-Daten erkennen", "eine DNS-Antwort von einer korrekten DNS-Antwort unterscheiden", "lesende DHCP-/DNS-Werkzeuge einsetzen", "Flush- und Reset-first-Troubleshooting vermeiden"]} />

    <Section title="DHCP konfiguriert – DNS löst Namen auf"><p><strong>DHCP</strong> und <strong>DNS</strong> sind getrennte Dienste. DHCP kann einem Client unter anderem IPv4-Adresse, Präfix, Gateway und die Adresse eines DNS-Resolvers mitteilen. DNS beantwortet anschließend namensbezogene Anfragen. Ein DHCP-Fehler kann also die DNS-Konfiguration des Clients betreffen, ohne dass beide Dienste identisch wären.</p><DhcpDnsComparison /></Section>

    <Section title="DHCP systematisch untersuchen"><Numbered items={["Ist DHCP aktiviert oder ist die Konfiguration statisch?", "Hat der Client eine IPv4-Adresse erhalten?", "Passt sie zum erwarteten Netz?", "Stimmen Maske oder Präfix?", "Ist das Default Gateway plausibel?", "Sind die DNS-Server plausibel?", "Sind Lease-Zeitpunkte und DHCP-Server sichtbar?", "Ist erwartete lokale Infrastruktur erreichbar?", "Sind ein oder mehrere Clients betroffen?", "Sind VLAN, Relay, Pfad oder Server als nächster Bereich plausibel?"]} /><DhcpDnsDiagnosticFlow /></Section>

    <Section title="Clientseitige DHCP-Evidenz"><div className="grid gap-4 lg:grid-cols-2"><Command value="ipconfig /all" label="A · lesend">Windows zeigt je nach Kontext unter anderem „DHCP aktiviert“, IPv4-Adresse, Subnetzmaske, Default Gateway, DHCP-Server, DNS-Server sowie Lease erhalten/ablaufend. Diese Rollen nicht verwechseln.</Command><Command value="ip addr · ip route" label="A · lesend">Linux zeigt Adressen/Präfixe und Routen. Optional können vorhandene Werkzeuge wie <code>nmcli</code> oder <code>networkctl</code> weitere Evidenz liefern; NetworkManager oder systemd-networkd sind nicht überall eingesetzt.</Command></div><p>Ein Lease-Eintrag beweist nur, dass Konfiguration bezogen wurde. Er beweist nicht, dass jede Option fachlich richtig ist.</p></Section>

    <Section title="APIPA, falsche Optionen, Pool und Relay"><Case title="Link-Local / APIPA"><code>169.254.32.18/16</code> zeigt, dass aktuell nicht die erwartete Firmenkonfiguration vorliegt. Link, Client, VLAN, DHCP-Pfad, Relay, Server und Pool bleiben mögliche Untersuchungsbereiche; weder Serverausfall noch Pool-Erschöpfung sind damit allein bewiesen.</Case><Case title="Lease vorhanden, Gateway falsch">Client <code>192.168.10.50/24</code>, geliefert <code>Gateway 192.168.10.254</code>, erwartet <code>192.168.10.1</code>, DNS <code>192.168.10.10</code>. Untersuche Scope, Optionen und Quelle der Konfiguration – überschreibe das Gateway nicht einfach manuell.</Case><Case title="Endlicher Adresspool">Bestehende Clients können gültige Leases behalten, während neue Clients zeit- oder geräteabhängig keine normale Adresse erhalten. Das ist mit Pool-Erschöpfung vereinbar, aber APIPA allein beweist sie nicht.</Case><Case title="Relay über Subnetzgrenzen">Funktioniert DHCP in Subnetz A, nicht aber in Subnetz B, obwohl derselbe zentrale Server vorgesehen ist, sind VLAN, Relay/Helper und der Pfad für Subnetz B plausible Bereiche. Router leiten DHCP-Broadcasts nicht automatisch wie normalen gerichteten Verkehr weiter.</Case></Section>

    <SingleChoiceCheck title="Link-Local eingrenzen" question="PC01 hat 169.254.32.18/16 und kein erwartetes Firmengateway; Nachbarn im selben VLAN erhalten 192.168.10.x/24 per DHCP. Was untersuchst du als Nächstes?" options={dhcpLinkLocalOptions} correctOptionId="dhcp-path" successMessage="Richtig: Die vorhandene Evidenz grenzt auf lokale Konfiguration und den DHCP-Bezugspfad ein." inputName="troubleshooting-dhcp-link-local" />

    <Section title="DNS systematisch untersuchen"><Numbered items={["Ist grundlegende IP-Erreichbarkeit plausibel?", "Welcher Resolver ist konfiguriert?", "Ist dieser Resolver erreichbar?", "Welcher exakte Name und Record-Typ wird abgefragt?", "Welche Antwort oder welcher Fehler tritt auf?", "Löst ein Known-Good-Name auf?", "Liefert ein gezielt abgefragter Resolver ein anderes Ergebnis?", "Ist die Antwort korrekt oder nur vorhanden?", "Sind Cache, TTL und Änderungszeit relevant?", "Ist die autoritative Datenquelle ein plausibler nächster Bereich?"]} /><div className="grid gap-4 lg:grid-cols-2"><Command value="nslookup server.firma.test" label="A · lesend">Zeigt je nach Plattform den verwendeten Resolver, Antworten oder Fehler. Das Ausgabeformat ist nicht überall identisch.</Command><Command value="nslookup server.firma.test 192.168.10.10" label="A · lesend">Fragt gezielt den dokumentierten Resolver ab und erlaubt einen kontrollierten Vergleich.</Command><Command value="dig server.firma.test" label="A · lesend, optional">Fragt DNS direkt; das Werkzeug muss installiert sein.</Command><Command value="getent hosts server.firma.test" label="A · lesend, optional">Nutzt unter Linux den konfigurierten Systempfad für Namensdienste, nicht zwingend ausschließlich einen direkten DNS-Query.</Command></div></Section>

    <Section title="DNS-Ergebnisse richtig lesen"><dl className="grid gap-4 md:grid-cols-2"><Definition term="NXDOMAIN">DNS meldet, dass der abgefragte Name im relevanten Namespace nicht existiert.</Definition><Definition term="SERVFAIL">Resolver oder Server konnte die Auflösung nicht erfolgreich abschließen.</Definition><Definition term="Timeout">Innerhalb der Wartezeit kam keine erwartete DNS-Antwort.</Definition><Definition term="Keine passende Antwort">Die Abfrage kann erfolgreich sein, ohne einen Record des angefragten Typs zurückzugeben.</Definition></dl><p>Keines dieser Ergebnisse identifiziert allein eine einzige Grundursache.</p></Section>

    <Section title="Antwort vorhanden – Daten trotzdem falsch"><p>Dokumentiert ist <code>server.firma.test → 192.168.10.20</code>, der verwendete Resolver liefert aber <code>192.168.10.30</code>. DNS ist erreichbar und antwortet; Record, Cache, Resolverauswahl, Split-DNS/View oder Datenquelle können dennoch falsch beziehungsweise unerwartet sein.</p><p>DNS-Antworten können entsprechend ihrer TTL zwischengespeichert werden. Nach einer Änderung können Resolver zeitweise verschiedene Daten liefern. Beobachte zuerst Resolver, Antwort, TTL-/Cache-Kontext und Änderungszeit. Implementierungen wählen mehrere konfigurierte Resolver nicht nach einer universellen Regel „primär bis aus, dann sekundär“ aus.</p></Section>

    <SingleChoiceCheck title="IP funktioniert, Name nicht" question="192.168.10.20 ist vom Client erreichbar, aber nslookup server.firma.test liefert NXDOMAIN. Welche Schicht untersuchst du als Nächstes?" options={dnsNxdomainOptions} correctOptionId="dns" successMessage="Richtig: IP-Pfad und Namensauflösung sind getrennt; NXDOMAIN lenkt auf DNS." inputName="troubleshooting-dns-nxdomain" />
    <SingleChoiceCheck title="Unerwartete DNS-Antwort" question="nslookup liefert 192.168.10.30, dokumentiert ist 192.168.10.20. Was ist damit bewiesen?" options={wrongDnsAnswerOptions} correctOptionId="unexpected" successMessage="Richtig: Der Resolver antwortet, doch fachliche Richtigkeit der Daten ist nicht belegt." inputName="troubleshooting-dns-wrong-answer" />

    <Section title="Sichere Praxis: drei Befunde"><Case title="A · plausibler Ausgangszustand"><code>192.168.10.44/24 · GW 192.168.10.1 · DNS 192.168.10.10 · DHCP: ja</code>. Bekannt: Die Felder entsprechen der Baseline. Offen: Dienstgesundheit. Nächster lesender Test richtet sich nach dem konkreten Symptom.</Case><Case title="B · erwartete Firmenkonfiguration fehlt"><code>169.254.15.42/16</code>. Verdächtig: Link-Local statt Firmenlease. Offen: genaue Client-, Link-, VLAN-, Relay-, Pool- oder Serverursache. Nächster Test: Link und <code>ipconfig /all</code> beziehungsweise <code>ip addr</code>/<code>ip route</code> vergleichen.</Case><Case title="C · unerwarteter Resolver">IP und Gateway sind gültig, DNS zeigt jedoch einen nicht dokumentierten Resolver. Bekannt: Konfiguration weicht ab. Offen: ob sie statisch oder per DHCP kam und welches Ergebnis dieser Resolver liefert. Nächster Test: Resolverquelle und gezielte Namensantwort lesend vergleichen.</Case></Section>

    <Misconceptions items={[["DHCP-Lease vorhanden = Netzwerkkonfiguration garantiert korrekt.", "Optionen können trotz Lease falsch oder unpassend sein."], ["169.254.x.x beweist, dass der DHCP-Server ausgeschaltet ist.", "Link-Local lässt mehrere Client-, Link-, VLAN-, Relay-, Pool- und Serverursachen offen."], ["DHCP und DNS sind derselbe Dienst.", "DHCP verteilt Konfiguration; DNS beantwortet Namensfragen."], ["NXDOMAIN bedeutet Netzwerkweg zum DNS-Server kaputt.", "NXDOMAIN ist gerade eine DNS-Antwort über den Namen."], ["Wenn DNS antwortet, ist der Wert automatisch richtig.", "Eine erreichbare Quelle kann falsche oder veraltete Daten liefern."], ["DNS-Cache immer zuerst leeren.", "Erst Resolver, Antwort und Cache-/TTL-Kontext dokumentieren."], ["Der zweite DNS-Server wird nur benutzt, wenn der erste ausgeschaltet ist.", "Resolverauswahl variiert nach Betriebssystem und Clientimplementierung."]]} />
    <CommandSafety />
    <Preview title="Ports, Dienste und typische Fehlersymptome">Als Nächstes trennst du DNS, Transportendpunkt, Listener, Dienst und Anwendung anhand von Refused, Timeout und HTTP-Antworten.</Preview>
  </Lesson>;
}

export function PortsServicesSymptomsLesson() {
  return <Lesson>
    <LearningObjectives context="lesson" objectives={["Portnummern als Transportendpunkte erklären", "IP-Adresse und Port unterscheiden", "TCP und UDP konzeptionell unterscheiden", "Listener, Prozess und Dienst einordnen", "Connection Refused vorsichtig interpretieren", "Timeout vorsichtig interpretieren", "TCP-Erfolg von Anwendungszustand trennen", "DNS-, Transport- und Anwendungsfehler unterscheiden", "lokale Listener lesend untersuchen", "einen bekannten TCP-Dienst sicher testen", "Portkonventionen korrekt einordnen", "die nächste Diagnoseschicht auswählen"]} />

    <Section title="IP-Adresse, Port und Transport"><p>Die IP-Adresse adressiert eine Schnittstelle beziehungsweise einen Endpunkt im IP-Netz. Ein <strong>Port</strong> bezeichnet einen Kommunikationsendpunkt im TCP-/UDP-Kontext eines Hosts. Bei <code>192.168.10.20:443</code> ist <code>192.168.10.20</code> die IP und <code>443</code> der Port.</p><p>Ein Port identifiziert nicht in jeder Architektur dauerhaft genau ein Programm: Proxies, NAT, Multiplexing und andere Bindungsmodelle können dazwischenliegen. TCP bietet verbindungsorientierte, UDP datagrammorientierte Transportsemantik. Das macht UDP nicht „schlecht“ und TCP garantiert keinen Anwendungserfolg.</p></Section>

    <Section title="Portkonventionen sind Hinweise"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Port value="53 UDP/TCP" service="DNS" /><Port value="67/68 UDP" service="DHCP" /><Port value="80 TCP" service="HTTP, häufig HTTP/1.x/2 unverschlüsselt" /><Port value="443 TCP" service="HTTPS, häufig HTTP/1.1/2 über TLS" /><Port value="443 UDP" service="HTTP/3 über QUIC, häufig" /><Port value="22 TCP" service="SSH" /><Port value="3389 TCP/UDP" service="RDP je nach Funktion/Nutzung" /><Port value="445 TCP" service="SMB, häufig" /></div><p>Dienste können anders konfiguriert sein; eine Portnummer beweist nicht, welches Anwendungsprotokoll tatsächlich läuft.</p></Section>

    <Section title="Listener und lokaler Endpunkt"><p>Ein Serverprozess oder Dienst kann einen lokalen Transportendpunkt binden und dort lauschen, etwa <code>0.0.0.0:443</code> auf relevanten lokalen Interfaces oder <code>192.168.10.20:443</code> auf einer bestimmten Adresse. <strong>LISTENING</strong> belegt einen Listener – nicht die fachliche Gesundheit der Anwendung oder ihrer Backends.</p><div className="grid gap-4 lg:grid-cols-2"><Command value="netstat -ano" label="A · lesend">Windows: lokale/entfernte Adressen, Zustände und PID je nach Zeile.</Command><Command value="Get-NetTCPConnection" label="A · lesend, optional">PowerShell: TCP-Endpunkte; nicht in jeder Minimalumgebung verfügbar.</Command><Command value="ss -ltn" label="A · lesend">Linux: <code>-l</code> listening, <code>-t</code> TCP, <code>-n</code> numerisch. Prozessbesitz kann zusätzliche Rechte/Optionen brauchen.</Command><Command value="Test-NetConnection server.firma.test -Port 443" label="A · lesend">PowerShell: bekannten, autorisierten TCP-Endpunkt testen. Erfolg belegt weder Zertifikat noch HTTP, Login oder Backend.</Command></div></Section>

    <Section title="Bis zur HTTP-Schicht testen"><div className="grid gap-4 lg:grid-cols-2"><Command value="curl -I https://server.firma.test/" label="A · lesend">Fordert mit HEAD-Verhalten Header an, soweit Server und Werkzeug dies sinnvoll unterstützen.</Command><Command value="curl -i http://server.firma.test/" label="A · lesend">Zeigt HTTP-Header und Inhalt einer bekannten, autorisierten Ressource. Keine Zugangsdaten verwenden.</Command></div><p><code>404</code> bedeutet Ressource nicht gefunden, <code>500</code> serverseitige Verarbeitung fehlgeschlagen, <code>502</code> Gateway/Proxy erhielt keine brauchbare Upstream-Antwort, <code>503</code> Dienst nicht verfügbar und <code>504</code> Upstream-Timeout. In allen Fällen fand HTTP-Kommunikation statt; dies sind keine reinen Netzwerkschichtfehler.</p></Section>

    <ServiceLayerPath />
    <ServiceSymptomComparison />

    <Section title="Refused, Timeout und erfolgreicher TCP-Aufbau"><Case title="Connection refused">Der Versuch erreichte einen Punkt, der die TCP-Verbindung aktiv ablehnen konnte. Untersuche falschen Port, fehlenden Listener, gestoppten Dienst, Bindung an eine andere Adresse oder eine ablehnende Policy. Das bedeutet weder „DNS kaputt“ noch zwingend „Server aus“.</Case><Case title="Timeout">Innerhalb der Wartezeit kam kein erwarteter Verbindungs-/Antwortausgang. Drop/Filterung, Routing oder Rückweg, Hostausfall, Zwischenpfad, Überlastung und bei UDP fehlende Antwortsemantik bleiben möglich. Timeout beweist keine Firewall.</Case><Case title="TCP erfolgreich, HTTP 503">IP-Pfad und TCP-Endpunkt funktionieren ausreichend. Jetzt sind Frontend-Dienst, Anwendung, Wartungs-/Lastzustand und Backend-Abhängigkeiten sinnvoll. Eine zufällige Änderung der Clientmaske wäre nicht begründet.</Case></Section>

    <Section title="Dienste haben Abhängigkeiten"><p>Ein realistischer Pfad lautet: Client → DNS → IP-Routing → TCP-Endpunkt → Frontend-Dienst → Backend. Ein Proxy kann auf <code>443</code> lauschen, während Datenbank oder Anwendung fehlen; der Client erhält dann möglicherweise <code>502</code>, <code>503</code> oder <code>504</code>. Das ist nicht automatisch ein Clientnetzfehler.</p><Safety>Firewalls können je nach Produkt und Policy erlauben, verwerfen oder aktiv ablehnen. Deaktiviere sie nicht pauschal. Sammle Evidenz und prüfe die relevante Regel nur mit Autorisierung.</Safety></Section>

    <SingleChoiceCheck title="TCP erfolgreich, HTTP 503" question="DNS liefert 192.168.10.20, Test-NetConnection auf 443 ist erfolgreich, der Browser erhält 503 Service Unavailable. Welcher Bereich folgt?" options={tcpSuccess503Options} correctOptionId="application" successMessage="Richtig: Die Evidenz grenzt auf Webdienst, Anwendung oder Backend ein." inputName="troubleshooting-http-503" />
    <SingleChoiceCheck title="TCP-Verbindung abgelehnt" question="DNS löst korrekt auf, aber TCP 443 meldet Connection refused. Was untersuchst du als Nächstes?" options={refusedOptions} correctOptionId="endpoint" successMessage="Richtig: Endpunkt, Listener, Dienst, Port und Policy sind der passende Bereich." inputName="troubleshooting-tcp-refused" />
    <SingleChoiceCheck title="Name nicht aufgelöst" question="Für den beabsichtigten Server liegt keine Namensauflösung und keine dokumentierte Ziel-IP vor. Solltest du mit HTTP-Statuscodes beginnen?" options={unresolvedNameOptions} correctOptionId="name-first" successMessage="Richtig: Zuerst Ziel und Namensauflösung belastbar bestimmen." inputName="troubleshooting-unresolved-name" />

    <Section title="Sichere Werkzeugwahl"><dl className="grid gap-4 sm:grid-cols-2"><Definition term="DNS-Ergebnis"><code>nslookup</code>, optional <code>dig</code> oder <code>getent</code></Definition><Definition term="Bekannter Windows-TCP-Endpunkt"><code>Test-NetConnection -Port</code></Definition><Definition term="HTTP-Antwort"><code>curl</code> auf bekannte URL</Definition><Definition term="Linux-Listener"><code>ss -ltn</code></Definition><Definition term="Windows-Endpunkte/PIDs"><code>netstat -ano</code> oder optional <code>Get-NetTCPConnection</code></Definition></dl><Safety>Teste nur bekannte, autorisierte Ziele und Ports. Subnetze oder Portbereiche zu scannen ist weder erforderlich noch Teil dieser Lektion.</Safety></Section>

    <Misconceptions items={[["Port 443 beweist HTTPS.", "443 ist eine Konvention; der tatsächliche Dienst muss geprüft werden."], ["LISTENING bedeutet Anwendung funktioniert.", "Ein Listener belegt weder fachliche Antwort noch Backendgesundheit."], ["TCP-Verbindung erfolgreich = Website komplett gesund.", "TLS, HTTP, Login, Anwendung und Backend bleiben offen."], ["Connection refused bedeutet DNS kaputt.", "Refused ist ein TCP-Endpunktsymptom nach erfolgter Zielbestimmung."], ["Timeout beweist Firewall.", "Mehrere Pfad-, Host-, Drop- und Lastursachen sind möglich."], ["HTTP 404 bedeutet Server nicht erreichbar.", "Der Server hat per HTTP geantwortet; Ressource oder Routing fehlen."], ["Ping erfolgreich bedeutet Port 443 offen.", "ICMP und TCP-Port sind getrennte Tests."], ["Firewall zum Testen einfach komplett deaktivieren.", "Das ist sicherheitsrelevant und ohne Evidenz nicht gerechtfertigt."]]} />
    <CommandSafety />
    <Preview title="Praxis: Netzwerkfehler vollständig analysieren">Zum Abschluss führst du die Schichten in einer Diagnose vom Benutzerbericht bis zur dokumentierten Hypothese zusammen.</Preview>
  </Lesson>;
}

export function NetworkTroubleshootingPracticeLesson() {
  return <Lesson>
    <LearningObjectives context="lesson" objectives={["ein vollständiges Fehlerbild präzisieren", "Link, IP, Subnetz und Gateway nacheinander belegen", "DHCP- und DNS-Evidenz unterscheiden", "Routing und Rückweg berücksichtigen", "TCP-Endpunkt und Anwendung getrennt testen", "acht typische Vorfälle der passenden Schicht zuordnen", "eine Hypothese aus Evidenz ableiten", "nur eine begründete Änderung vorschlagen", "den erwarteten Zustand erneut verifizieren", "Befund, Root Cause und Lösung nachvollziehbar dokumentieren"]} />

    <Safety prominent>Planen und lesend diagnostizieren: zuerst beobachten, dann Schicht eingrenzen, Hypothese prüfen und dokumentieren. Änderungen erfolgen nur nach belastbarer Evidenz und mit Autorisierung.</Safety>

    <Section title="Fiktive Labortopologie"><PracticeTopology /><dl className="grid gap-3 sm:grid-cols-2"><Definition term="Clientnetz"><code>192.168.10.0/24</code> · PC01 <code>192.168.10.50</code> · Gateway <code>192.168.10.1</code></Definition><Definition term="Infrastruktur"><code>192.168.10.10</code> stellt im Szenario DNS und DHCP bereit.</Definition><Definition term="Servernetz"><code>192.168.20.0/24</code> · Webserver <code>192.168.20.20</code></Definition><Definition term="Namens- und Dienstbaseline"><code>portal.firma.test → 192.168.20.20</code> · HTTP auf TCP 80 · <code>http://portal.firma.test/</code></Definition></dl><p>Alle Hostadressen liegen gültig in den jeweiligen <code>/24</code>-Netzen; der Routerpfad verbindet beide Netze.</p></Section>

    <Section title="13 Diagnosephasen"><Numbered items={["Benutzerbericht lesen", "exaktes Symptom definieren", "lokales Interface und Konfiguration prüfen", "lokales oder entferntes Ziel bestimmen", "Gateway und Pfad testen", "DHCP-Evidenz untersuchen", "DNS untersuchen", "Transportendpunkt des Ziels testen", "Anwendungsantwort untersuchen", "Hypothese bilden", "begründete Lösung konzeptionell auswählen", "erwartetes Ergebnis verifizieren", "vollständig dokumentieren"]} /></Section>

    <Section title="Acht Vorfälle, acht begründete Einstiege"><div className="grid gap-4 lg:grid-cols-2"><Incident number="1" title="APIPA / DHCP-Pfad" evidence="PC01: 169.254.35.44/16, kein Firmengateway; andere Clients haben normale Leases." direction="Link, lokale Konfiguration und DHCP-Bezugspfad untersuchen. Link-Local beweist weder Serverausfall noch Pool-Erschöpfung; keine Zufalls-IP setzen." /><Incident number="2" title="Falsche DHCP-DNS-Option" evidence="PC01: 192.168.10.50/24, GW 192.168.10.1, DNS 192.168.10.99 statt 192.168.10.10; IP-Pfad zum Server funktioniert." direction="DNS-Konfiguration und deren statische/DHCP-Quelle untersuchen, nicht Routing beschuldigen." /><Incident number="3" title="Falsche DNS-Antwort" evidence="portal.firma.test liefert 192.168.20.30 statt dokumentierter 192.168.20.20." direction="DNS ist verfügbar; Record, Resolver, Cache, View und Datenquelle untersuchen. Kein Timeout." /><Incident number="4" title="Routingfehler" evidence="Clientwerte korrekt, Gateway erreichbar, DNS liefert 192.168.20.20, Zielnetz nicht erreichbar." direction="Hin- und Rückroute zwischen 192.168.10.0/24 und 192.168.20.0/24 untersuchen, DNS nicht ändern." /><Incident number="5" title="Connection refused" evidence="DNS korrekt, Routing ausreichend, TCP 80 wird aktiv abgelehnt." direction="Listener, Dienst, Port, Bindung und ablehnende Policy untersuchen; DHCP ist nicht der erste Bereich." /><Incident number="6" title="HTTP 404" evidence="TCP-Verbindung steht; GET /azubi erhält 404 Not Found." direction="Ressource, Pfad und Anwendungsrouting untersuchen. Der Server war ausreichend erreichbar." /><Incident number="7" title="HTTP 503" evidence="TCP-Verbindung steht; Frontend antwortet 503 Service Unavailable." direction="Dienst, Anwendung, Backend, Wartung und Last untersuchen; Client-IP nicht ändern." /><Incident number="8" title="Intermittenter IP-Konflikt" evidence="PC01 fällt zeitweise aus; ARP-/Neighbor-Zuordnung wechselt; weiteres Gerät könnte dieselbe IPv4-Adresse nutzen." direction="Adressverwaltung und Duplicate-IP-Hypothese lesend belegen; keine offensiven ARP-Techniken." /></div></Section>

    <PracticeEvidenceMatrix />

    <Section title="Lesender Werkzeugkasten"><div className="grid gap-4 lg:grid-cols-2"><Toolbox title="Windows" commands={["ipconfig /all", "ping", "arp -a", "route print", "tracert", "nslookup", "Test-NetConnection", "netstat -ano", "curl"]} /><Toolbox title="Linux" commands={["ip addr", "ip route", "ip neigh", "ping", "tracepath / traceroute", "dig / nslookup / getent", "ss -ltn", "curl"]} /></div><p>Verfügbarkeit und Ausgabe variieren. Kein Werkzeug ist überall Pflicht; für das Basislabor ist keine Erhöhung erforderlich.</p></Section>

    <FullTroubleshootingDecisionTree />
    <TroubleshootingSymptomClassificationCheck />

    <Section title="Gesamtfall: Schicht für Schicht eingegrenzt"><ol className="space-y-3"><li><Evidence step="1">PC01: <code>192.168.10.50/24</code>, Gateway <code>192.168.10.1</code>, DNS <code>192.168.10.10</code></Evidence></li><li><Evidence step="2">Gateway ist erreichbar.</Evidence></li><li><Evidence step="3"><code>portal.firma.test → 192.168.20.20</code></Evidence></li><li><Evidence step="4">Route und Rückpfad funktionieren ausreichend.</Evidence></li><li><Evidence step="5">TCP 80 ist erfolgreich.</Evidence></li><li><Evidence step="6">HTTP antwortet <code>503 Service Unavailable</code>.</Evidence></li></ol></Section>
    <SingleChoiceCheck title="Stärkster nächster Bereich" question="Wo setzt die weitere Untersuchung nach dieser Evidenz an?" options={finalCaseOptions} correctOptionId="server-app" successMessage="Richtig: Der Pfad ist bis HTTP belegt; Anwendung, Dienst und Backend sind jetzt am stärksten." inputName="troubleshooting-final-case" />

    <Section title="Vorfall dokumentieren"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{["Benutzerbericht", "Beobachtetes Symptom", "Umfang", "Aktuelle Konfiguration", "Test", "Ergebnis", "Interpretation", "Hypothese", "Nächster Test", "Änderung, falls autorisiert", "Verifikation", "Root Cause", "Finale Lösung"].map((field) => <div key={field} className="min-h-20 rounded-xl border border-slate-200 bg-white p-4 text-sm font-semibold text-slate-900">{field}</div>)}</div><p>Die Vorlage ist nicht persistent. Sie macht sichtbar, welche Aussage beobachtet, abgeleitet, verändert und anschließend bestätigt wurde.</p></Section>

    <Misconceptions items={[["Bei Netzwerkfehlern immer zuerst Adapter zurücksetzen.", "Zuerst Symptome und Konfiguration beobachten."], ["169.254 = DHCP-Server definitiv offline.", "Mehrere lokale und serverseitige Ursachen bleiben offen."], ["DNS-Antwort vorhanden = DNS-Daten korrekt.", "Erreichbarkeit und Datenrichtigkeit sind getrennt."], ["Gateway erreichbar = komplette Route funktioniert.", "Weiterer Hin- und Rückweg bleiben ungetestet."], ["Porttest erfolgreich = Anwendung funktioniert.", "Protokoll, Fachlogik und Backend bleiben offen."], ["404 = Netzwerkfehler.", "HTTP hat ausreichend funktioniert, um den Status zu liefern."], ["503 = Client-IP falsch.", "Der Frontend-Dienst meldet fehlende Anwendungsverfügbarkeit."], ["Nach erfolgreicher Änderung muss nichts dokumentiert werden.", "Verifikation und Dokumentation sichern Wissen und Nachvollziehbarkeit."], ["Wenn etwas wieder funktioniert, ist Root Cause automatisch bekannt.", "Korrelation und Seiteneffekte müssen durch kontrollierte Tests ausgeschlossen werden."]]} />
    <CommandSafety />
    <Safety prominent>Keine Pflichtänderungen: keine IP-Änderung, kein DHCP Release/Renew, kein DNS-Flush, keine Route, kein Dienstneustart, keine Firewall-/Adapter-Deaktivierung, kein Reboot, keine Neuinstallation und keine Serveränderung.</Safety>
  </Lesson>;
}

function Lesson({ children }: { children: React.ReactNode }) { return <div className="space-y-10 text-base leading-7 text-slate-700 [&_code]:break-words sm:text-lg sm:leading-8">{children}</div>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="text-2xl font-bold tracking-tight text-slate-950">{title}</h2><div className="mt-4 space-y-4">{children}</div></section>; }
function Numbered({ items }: { items: readonly string[] }) { return <ol className="grid gap-3 sm:grid-cols-2">{items.map((item, index) => <li key={item} className="rounded-xl border border-slate-200 bg-white p-4"><strong className="mr-2 text-blue-700">{index + 1}.</strong>{item}</li>)}</ol>; }
function Command({ value, label, children }: { value: string; label: string; children: React.ReactNode }) { return <article className="min-w-0 rounded-xl border border-slate-200 bg-white p-4"><p className="text-xs font-bold uppercase tracking-wide text-emerald-700">{label}</p><code className="mt-2 block overflow-x-auto whitespace-pre-wrap break-words font-bold text-blue-900">{value}</code><p className="mt-2 text-sm leading-6">{children}</p></article>; }
function Case({ title, children }: { title: string; children: React.ReactNode }) { return <article className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6">{children}</p></article>; }
function Definition({ term, children }: { term: string; children: React.ReactNode }) { return <div className="rounded-xl border border-blue-200 bg-blue-50 p-4"><dt className="font-bold text-blue-950">{term}</dt><dd className="mt-2 text-sm leading-6">{children}</dd></div>; }
function Port({ value, service }: { value: string; service: string }) { return <div className="rounded-xl border border-blue-200 bg-blue-50 p-4"><code className="font-bold text-blue-950">{value}</code><p className="mt-2 text-sm">{service}</p></div>; }
function Incident({ number, title, evidence, direction }: { number: string; title: string; evidence: string; direction: string }) { return <article className="rounded-xl border border-slate-200 bg-white p-5"><p className="text-xs font-bold uppercase tracking-wide text-blue-700">Vorfall {number}</p><h3 className="mt-1 font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6"><strong>Evidenz:</strong> {evidence}</p><p className="mt-2 text-sm leading-6"><strong>Richtung:</strong> {direction}</p></article>; }
function Toolbox({ title, commands }: { title: string; commands: readonly string[] }) { return <section className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-bold text-slate-950">{title}</h3><ul className="mt-3 grid gap-2 sm:grid-cols-2">{commands.map((command) => <li key={command}><code>{command}</code></li>)}</ul></section>; }
function Evidence({ step, children }: { step: string; children: React.ReactNode }) { return <div className="rounded-xl border border-blue-200 bg-blue-50 p-4"><strong className="mr-2 text-blue-800">{step}.</strong>{children}</div>; }
function Safety({ children, prominent = false }: { children: React.ReactNode; prominent?: boolean }) { return <aside className={`rounded-xl border p-5 text-sm leading-6 ${prominent ? "border-2 border-amber-300 bg-amber-50 text-slate-950" : "border-emerald-200 bg-emerald-50 text-emerald-950"}`}><strong>Sicherheitsregel:</strong> {children}</aside>; }
function Misconceptions({ items }: { items: readonly (readonly [string, string])[] }) { return <section><h2 className="text-2xl font-bold text-slate-950">Typische Fehlvorstellungen</h2><dl className="mt-5 space-y-3">{items.map(([wrong, correction]) => <div key={wrong} className="rounded-xl border border-slate-200 bg-white p-4"><dt className="font-bold text-slate-950">Falsch: „{wrong}“</dt><dd className="mt-2 text-sm"><strong>Korrektur:</strong> {correction}</dd></div>)}</dl></section>; }
function CommandSafety() { return <section><h2 className="text-2xl font-bold text-slate-950">Befehlssicherheit</h2><dl className="mt-5 grid gap-4 lg:grid-cols-3"><Definition term="A · lesend / diagnostisch">Erforderlich sind nur bekannte Zieltests und Abfragen wie <code>ipconfig /all</code>, <code>ip addr</code>, <code>ip route</code>, <code>nslookup</code>, <code>dig</code>, <code>getent</code>, <code>Test-NetConnection</code>, <code>netstat -ano</code>, <code>ss -ltn</code> und <code>curl</code>.</Definition><Definition term="B · zustandsändernd, nur konzeptionell">Lease Release/Renew, DNS-Flush, Adapterreset, Route oder Konfiguration ändern und Dienstneustart werden nicht ausgeführt.</Definition><Definition term="C · privilegiert/administrativ, nur konzeptionell">DHCP-/DNS-Server, Relay, Firewall, Dienstbindung oder Serveranwendung ändern erfordert Befund, Freigabe und passende Zuständigkeit.</Definition></dl></section>; }
function Preview({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-slate-50 p-5 sm:p-6"><p className="text-sm font-semibold text-blue-700">Nächste Lektion</p><h2 className="mt-1 text-xl font-bold text-slate-950">{title}</h2><p className="mt-3 text-sm leading-6">{children}</p></section>; }
