import type { ReactNode } from "react";
import { FundamentalsLesson, ResponsiveTable, TextFlow, type LessonSection } from "./fundamentals-lesson-elements";
import { SingleChoiceCheck } from "./single-choice-check";

type Content = { objectives: readonly string[]; intro: ReactNode; sections: readonly LessonSection[]; visual?: ReactNode; scenario: { title: string; situation: ReactNode; tasks: readonly ReactNode[]; solution: ReactNode }; takeaway: readonly ReactNode[] };
const lessons: Record<string, Content> = {
  "personenbezogene-daten-und-rechtsrahmen": {
    objectives: ["personenbezogene Daten erkennen", "besondere Kategorien einordnen", "DSGVO-Zweck erklären", "BDSG als Ergänzung orientierend einordnen"],
    intro: <p>Personenbezogene Daten beziehen sich auf identifizierte oder identifizierbare natürliche Personen. Dazu können Namen, Kennungen, Standort-, Geräte- oder Nutzungsdaten gehören, wenn eine Zuordnung möglich ist.</p>,
    sections: [
      { title: "Kontext entscheidet", paragraphs: [<>Eine IP-Adresse oder Personalnummer kann mit Zusatzwissen eine Person identifizieren. Besondere Kategorien – etwa Gesundheitsdaten – benötigen wegen ihrer Sensibilität besonderen Schutz; auch andere Daten können im Kontext hohe Risiken erzeugen.</>, <>Die DSGVO schafft Grundregeln für die Verarbeitung personenbezogener Daten in ihrem Anwendungsbereich. Das BDSG ergänzt auf nationaler Ebene. Diese Lektion bietet Orientierung, keine Rechtsberatung.</>] },
      { title: "Verarbeitung braucht Grundlage und Zweck", paragraphs: [<>Erheben, Speichern, Lesen, Ändern, Übermitteln und Löschen sind Verarbeitung. Vorher müssen Zweck, Rechtsgrundlage, Verantwortlichkeit, Empfänger, Fristen und Schutz geklärt sein.</>, <>„Wir könnten die Daten später brauchen“ ist kein sauber bestimmter Zweck. Fachstelle beziehungsweise Datenschutzbeauftragte werden bei Unsicherheit früh eingebunden.</>] },
    ],
    visual: <ResponsiveTable caption="Beispiele im Kontext" headers={["Datum", "personenbezogen?", "warum"]} rows={[["Name + Kundennummer", "ja", "direkt/indirekt zuordenbar"], ["Geräte-ID mit Nutzerkonto", "ja", "Zusatzdaten ermöglichen Zuordnung"], ["vollständig aggregierte Statistik", "möglicherweise nein", "nur wenn Re-Identifizierung vernünftigerweise ausgeschlossen"], ["Gesundheitsangabe", "ja, besonders sensibel", "besondere Kategorie"]]} />,
    scenario: { title: "Inventarliste mit Nutzerzuordnung", situation: <p>Eine IT-Liste enthält Gerätenummer, Namen, Abteilung und letzten Login.</p>, tasks: ["Sind das personenbezogene Daten?", "Welche Fragen sind vor der Verarbeitung nötig?"], solution: <p>Ja, die Einträge sind Personen zuordenbar. Zweck, Rechtsgrundlage, Zugriff, Datenminimierung, Aufbewahrung, Transparenz und Schutz müssen geklärt werden.</p> },
    takeaway: ["Identifizierbarkeit kann durch Zusatzwissen entstehen.", "DSGVO und BDSG werden kontextbezogen angewendet.", "Zweck und Rechtsgrundlage gehören vor die Verarbeitung."],
  },
  "datenschutzgrundsaetze": {
    objectives: ["zentrale Grundsätze anwenden", "Datenminimierung und Speicherbegrenzung unterscheiden", "Transparenz und Rechenschaft einordnen", "Zielkonflikte erkennen"],
    intro: <p>Datenschutzgrundsätze lenken den gesamten Lebenszyklus: rechtmäßig, fair und transparent; zweckgebunden; auf das Erforderliche begrenzt; richtig; nicht länger als nötig; angemessen geschützt und nachweisbar verantwortet.</p>,
    sections: [
      { title: "Vom Zweck zur Datenmenge", paragraphs: [<>Zweckbindung fragt, wofür Daten erhoben und verwendet werden. Datenminimierung fragt, welche Daten dafür wirklich nötig sind. Richtigkeit verlangt angemessene Aktualisierung und Korrektur.</>, <>Speicherbegrenzung bedeutet Lösch- oder Prüfkonzepte statt unbegrenzter Vorratshaltung. Gesetzliche Aufbewahrung oder Rechtsansprüche können Fristen beeinflussen; die konkrete Abwägung ist kontextabhängig.</>] },
      { title: "Schutz und Nachweis", paragraphs: [<>Integrität und Vertraulichkeit verlangen geeignete technische und organisatorische Maßnahmen. Transparenz informiert verständlich über Verarbeitung; Rechenschaftspflicht verlangt, Entscheidungen und Umsetzung nachweisen zu können.</>] },
    ],
    visual: <TextFlow caption="Datenschutzgerechte Planung" steps={["Zweck/Rechtsgrundlage", "erforderliche Daten", "Zugriff/Empfänger", "Frist/Löschung", "Schutz/Nachweis"]} />,
    scenario: { title: "Kundendaten unbegrenzt speichern", situation: <p>Eine Anwendung besitzt keine Löschfristen, weil Daten „vielleicht später nützlich“ seien.</p>, tasks: ["Welche Grundsätze sind betroffen?", "Wie wird verbessert?"], solution: <p>Zweckbindung, Datenminimierung und Speicherbegrenzung sind betroffen. Zwecke und Pflichten klären, Fristen/Löschregeln dokumentieren, Ausnahmen kontrollieren und Löschung nachweisbar umsetzen.</p> },
    takeaway: ["Jeder Datensatz braucht Zweck und angemessene Dauer.", "Datensicherheit ist Teil datenschutzgerechter Verarbeitung.", "Rechenschaft verlangt dokumentierte Umsetzung."],
  },
  "betroffenenrechte": {
    objectives: ["wichtige Rechte unterscheiden", "Anfragen sicher bearbeiten", "Identität und Fristen berücksichtigen", "Rechte nicht als absolut darstellen"],
    intro: <p>Betroffenenrechte geben Menschen Kontrolle und Transparenz. Dazu gehören Auskunft, Berichtigung, Löschung, Einschränkung, Widerspruch und Datenübertragbarkeit.</p>,
    sections: [
      { title: "Rechte im Überblick", paragraphs: [<>Auskunft schafft Überblick; Berichtigung korrigiert unrichtige Daten. Löschung und Einschränkung betreffen weitere Nutzung, Widerspruch richtet sich gegen bestimmte Verarbeitungen, Datenübertragbarkeit ermöglicht Daten in einem strukturierten Format unter ihren Voraussetzungen.</>, <>Diese Rechte gelten nicht immer absolut. Rechtsgrundlage, Aufbewahrungspflichten, Rechte anderer, Identitätsprüfung und konkrete Voraussetzungen können Umfang und Ergebnis beeinflussen.</>] },
      { title: "Sicherer Prozess", paragraphs: [<>Anfragen werden erkannt, dokumentiert und an die zuständige Stelle geleitet. Die Identität wird verhältnismäßig geprüft; dabei dürfen nicht unnötig neue Daten gesammelt werden.</>, <>Antwortdaten dürfen nicht an die falsche Person gelangen. Fristen, Systeme, Empfänger, Backups und rechtliche Ausnahmen werden koordiniert statt spontan einzeln geändert.</>] },
    ],
    visual: <ResponsiveTable caption="Betroffenenrechte praktisch" headers={["Recht", "typisches Anliegen", "Kontextfrage"]} rows={[["Auskunft", "Welche Daten werden verarbeitet?", "Identität/Schutz Dritter"], ["Berichtigung", "Adresse ist falsch", "welche Systeme/Empfänger?"], ["Löschung", "Konto entfernen", "Pflichten/Ansprüche?"], ["Einschränkung", "Nutzung vorläufig begrenzen", "Kennzeichnung/Durchsetzung"], ["Widerspruch", "bestimmte Nutzung ablehnen", "Rechtsgrundlage/Gründe"], ["Übertragbarkeit", "Daten maschinenlesbar", "Voraussetzungen/Format"]]} />,
    scenario: { title: "Löschanfrage mit offenen Belegen", situation: <p>Ein ehemaliger Kunde verlangt sofort die Löschung aller Daten; einzelne Buchungsbelege unterliegen möglicherweise Aufbewahrungspflichten.</p>, tasks: ["Warum ist weder ‚alles löschen‘ noch ‚nichts löschen‘ automatisch richtig?", "Wie gehst du vor?"], solution: <p>Die zuständige Stelle prüft Identität, Zwecke, Rechtsgrundlagen und Fristen je Datenart. Nicht mehr benötigte Daten können gelöscht, andere gesperrt oder befristet aufbewahrt werden; die Entscheidung wird transparent erläutert.</p> },
    takeaway: ["Betroffenenrechte benötigen einen verlässlichen Prozess.", "Rechte hängen vom rechtlichen Kontext ab und sind nicht immer absolut.", "Identitätsprüfung darf selbst nicht ausufern."],
  },
  "anonymisierung-und-pseudonymisierung": {
    objectives: ["Anonymisierung definieren", "Pseudonymisierung abgrenzen", "Zusatzinformationen schützen", "Re-Identifizierungsrisiken bewerten"],
    intro: <p>Bei echter Anonymisierung kann eine Person mit vernünftigerweise verfügbaren Mitteln nicht mehr identifiziert werden. Pseudonymisierung ersetzt oder trennt Kennzeichen, lässt eine Zuordnung mit Zusatzinformation aber grundsätzlich zu.</p>,
    sections: [
      { title: "Anonym ist schwerer als namenlos", paragraphs: [<>Nur Namen zu entfernen genügt oft nicht: Kombinationen aus Alter, Ort, Zeit oder seltenen Merkmalen können Personen erneut identifizieren. Anonymisierung berücksichtigt Datensatz, Zusatzquellen, Aufwand und technische Entwicklung.</>, <>Echt anonymisierte Daten werden datenschutzrechtlich anders behandelt als identifizierbare Daten. Ob Anonymität tatsächlich erreicht ist, muss belastbar bewertet werden.</>] },
      { title: "Pseudonyme bleiben personenbezogen", paragraphs: [<>Eine Personalnummer statt Name ist ein Pseudonym, wenn eine getrennte Zuordnungstabelle existiert. Zugriffstrennung, Verschlüsselung und organisatorische Kontrolle reduzieren Risiken.</>, <><strong>Pseudonymisierte Daten bleiben personenbezogene Daten</strong>, weil Re-Identifizierung mit Zusatzinformation möglich ist. Pseudonymisierung ist eine Schutzmaßnahme, keine Befreiung von Datenschutzpflichten.</>], activity: <SingleChoiceCheck title="Anonym oder pseudonym?" question="Ein Datensatz nutzt zufällige Kennungen; eine getrennte Tabelle ordnet sie Kunden zu. Was liegt vor?" inputName="privacy-pseudo" correctOptionId="pseudo" successMessage="Die Zuordnung bleibt mit Zusatzinformation möglich." options={[{ id: "anonymous", label: "Sicher anonym, weil Namen fehlen.", explanation: "Die Zuordnungstabelle ermöglicht Re-Identifizierung." }, { id: "public", label: "Öffentliche Daten ohne Schutzbedarf.", explanation: "Pseudonyme bleiben personenbezogen." }, { id: "pseudo", label: "Pseudonymisierte personenbezogene Daten.", explanation: "Richtig." }, { id: "encrypted", label: "Zwingend asymmetrisch verschlüsselte Daten.", explanation: "Pseudonymisierung sagt nichts über das konkrete Verschlüsselungsverfahren." }]} /> },
    ],
    visual: <ResponsiveTable caption="Abgrenzung" headers={["Merkmal", "anonymisiert", "pseudonymisiert"]} rows={[["Zuordnung", "vernünftigerweise nicht mehr möglich", "mit Zusatzinformation möglich"], ["Zusatzschlüssel", "keiner zur Personenzuordnung", "oft getrennte Tabelle/Schlüssel"], ["Personenbezug", "bei echter Anonymität aufgehoben", "bleibt bestehen"], ["Beispiel", "ausreichend aggregierte Statistik", "Studien-ID mit Zuordnungsliste"]]} />,
    scenario: { title: "Support-Tickets für Analyse", situation: <p>Namen werden entfernt, aber E-Mail-Adressen, genaue Zeitstempel und seltene Fehlertexte bleiben.</p>, tasks: ["Ist der Export automatisch anonym?", "Wie lässt sich das Risiko senken?"], solution: <p>Nein. Direkte und indirekte Merkmale können re-identifizieren. Zweck prüfen, Felder minimieren, Zeit/Details aggregieren, Pseudonyme und getrennte Zuordnung nutzen oder echte Anonymisierung fachlich bewerten.</p> },
    takeaway: ["Namen entfernen bedeutet nicht automatisch anonymisieren.", "Pseudonymisierte Daten bleiben personenbezogen.", "Re-Identifizierbarkeit wird im realistischen Kontext bewertet."],
  },
  "datenschutz-und-datensicherheit": {
    objectives: ["Datenschutz und Datensicherheit unterscheiden", "Überlappungen erklären", "Maßnahmen dem Zweck zuordnen", "Vorfälle korrekt eskalieren"],
    intro: <p>Datenschutz schützt Menschen und die rechtmäßige Verarbeitung ihrer personenbezogenen Daten. Datensicherheit beziehungsweise Informationssicherheit schützt Informationen technisch und organisatorisch – auch wenn sie keinen Personenbezug haben.</p>,
    sections: [
      { title: "Überlappend, nicht identisch", paragraphs: [<>Zugriffskontrolle, Verschlüsselung, Protokollierung und Backups können beide Ziele unterstützen. Ein Geschäftsgeheimnis ohne Personenbezug ist primär Informationssicherheit; eine rechtmäßige, transparente Datennutzung ist eine Datenschutzfrage.</>, <>Eine Maßnahme kann sicher, aber datenschutzwidrig sein: umfassendes Dauerlogging schützt vielleicht Systeme, kann aber unnötige Beschäftigtendaten sammeln. Umgekehrt braucht zulässige Verarbeitung angemessene Sicherheit.</>] },
      { title: "Notebook-Diebstahl", paragraphs: [<>Beim gestohlenen Notebook sind physische Sicherheit und Vertraulichkeit betroffen; bei Kundendaten zusätzlich Datenschutz. Vollverschlüsselung, sichere Anmeldung, Remote-Sperre, minimierte lokale Daten und ein Meldeprozess reduzieren das Risiko.</>, <>Ob eine Datenschutzverletzung gemeldet werden muss, bewertet die zuständige Stelle anhand Kontext und Risiko – Mitarbeitende melden intern schnell, statt selbst abschließend juristisch zu entscheiden.</>] },
    ],
    visual: <ResponsiveTable caption="Ziele unterscheiden" headers={["Frage", "Datenschutz", "Datensicherheit"]} rows={[["Schutzobjekt", "Menschen/personenbezogene Daten", "Informationen und Systeme"], ["Kernfrage", "Ist Verarbeitung rechtmäßig und fair?", "Bleibt Information vertraulich, integer, verfügbar?"], ["Beispiel", "Zweck/Betroffenenrechte", "Firewall/Verschlüsselung/Backup"], ["Schnittmenge", "angemessene TOM", "dieselben TOM schützen Systeme"]]} />,
    scenario: { title: "Notebook mit Kundendaten gestohlen", situation: <p>Das Gerät war gesperrt; der Verschlüsselungsstatus ist unbekannt.</p>, tasks: ["Welche Ziele sind betroffen?", "Welche Sofortmaßnahmen sind angemessen?"], solution: <p>Vertraulichkeit, Geräte-/Kontosicherheit und Datenschutz sind betroffen. Intern melden, Gerät/Token sperren, Verschlüsselung und lokale Daten prüfen, Ereignis dokumentieren und Risiko-/Meldebewertung durch zuständige Stellen durchführen lassen.</p> },
    takeaway: ["Datenschutz und Datensicherheit verfolgen unterschiedliche Hauptziele.", "Technische Maßnahmen können beide unterstützen.", "Datenschutzvorfälle werden schnell intern gemeldet und fachlich bewertet."],
  },
  "datenschutzfaelle-praxis": {
    objectives: ["Praxisfälle strukturiert analysieren", "Grundsätze und Schutzziele zuordnen", "Sofortreaktion und Prävention trennen", "zuständige Rollen einbeziehen"],
    intro: <p>Ein guter Fallablauf lautet: stoppen und sichern, intern melden, Umfang und Betroffene klären, Risiko bewerten, Maßnahmen dokumentieren und Wiederholung verhindern. Details folgen dem betrieblichen Incident-/Datenschutzprozess.</p>,
    sections: [
      { title: "Fehlversand und Altzugänge", paragraphs: [<>Kundendaten an einen falschen Empfänger betreffen Vertraulichkeit und möglicherweise eine Datenschutzverletzung. Rückruf/Löschbitte kann helfen, hebt den Vorfall aber nicht automatisch auf.</>, <>Ein ausgeschiedener Mitarbeiter mit aktivem Konto verletzt Least Privilege und Offboarding. Zugang sperren, Aktivitäten prüfen und Joiner-Mover-Leaver-Prozess verbessern.</>] },
      { title: "Menschen und Technik", paragraphs: [<>Phishing und gemeinsame Adminpasswörter gefährden Authentizität, Zurechenbarkeit und Vertraulichkeit. Unerwartete MFA-Anfragen ablehnen, Vorfälle melden und individuelle privilegierte Konten einsetzen.</>, <>Ungepatchte Arbeitsplätze erhöhen Exploit-Risiken; unbegrenzte Kundendatenhaltung verletzt möglicherweise Zweck-/Speicherbegrenzung. Patch- und Löschprozesse brauchen Verantwortliche und Nachweise.</>] },
    ],
    visual: <ResponsiveTable caption="Praxisfälle analysieren" headers={["Fall", "Problem/Ziel", "Reaktion und Prävention"]} rows={[["falscher Empfänger", "Vertraulichkeit", "melden, begrenzen; Empfängerprüfung"], ["Ransomware", "CIA-Ziele", "isolieren; Patch, Rechte, Backup"], ["gemeinsames Adminpasswort", "Authentizität/Zurechenbarkeit", "individuelle Konten, MFA"], ["ehemaliger Mitarbeiter", "unberechtigter Zugriff", "sperren, prüfen; Offboarding"], ["unbegrenzte Speicherung", "Speicherbegrenzung", "Fristen und Löschkonzept"]]} />,
    scenario: { title: "Kombinierter Vorfall", situation: <p>Ein ehemaliger Mitarbeiter meldet sich mit einem geteilten Adminkonto an und exportiert alte Kundendaten, die ohne Frist gespeichert wurden.</p>, tasks: ["Nenne Sicherheits- und Datenschutzprobleme.", "Welche Sofort- und Präventionsmaßnahmen folgen?"], solution: <p>Zugang beenden, Konto/Token sperren, Beweise sichern, Umfang und Empfänger klären, Incident-/Datenschutzstellen einbeziehen. Individuelle privilegierte Konten, MFA, Offboarding, Least Privilege, Protokollierung sowie Zweck-/Fristen- und Löschkonzept verhindern Wiederholung.</p> },
    takeaway: ["Sofortreaktion begrenzt Schaden; Prävention behebt Ursachen.", "Praktische Fälle betreffen oft mehrere Ziele zugleich.", "Dokumentation und zuständige Rollen gehören zum Prozess."],
  },
};

export function PrivacyLesson({ lessonSlug }: { lessonSlug: string }) {
  const lesson = lessons[lessonSlug];
  if (!lesson) return null;
  return <FundamentalsLesson lessonId={`privacy-${lessonSlug}`} {...lesson}>{lesson.visual}</FundamentalsLesson>;
}
