import type { ReactNode } from "react";
import { calculateProjectNetwork } from "../../lib/project-network";
import { FundamentalsLesson, ResponsiveTable, TextFlow, type LessonSection } from "./fundamentals-lesson-elements";
import { SingleChoiceCheck } from "./single-choice-check";

type LessonContent = { objectives: readonly string[]; intro: ReactNode; sections: readonly LessonSection[]; visual?: ReactNode; scenario: { title: string; situation: ReactNode; tasks: readonly ReactNode[]; solution: ReactNode }; takeaway: readonly ReactNode[] };

const networkExample = calculateProjectNetwork([
  { id: "A", duration: 2, predecessorIds: [] },
  { id: "B", duration: 3, predecessorIds: ["A"] },
  { id: "C", duration: 2, predecessorIds: ["A"] },
  { id: "D", duration: 4, predecessorIds: ["B", "C"] },
  { id: "E", duration: 2, predecessorIds: ["D"] },
]);

const lessons: Record<string, LessonContent> = {
  "projektmerkmale-und-smart-ziele": {
    objectives: ["Projekt und Routine unterscheiden", "Projektauftrag einordnen", "SMART-Ziele prüfen", "Ziel und Maßnahme trennen"],
    intro: <p>Ein Projekt ist zeitlich begrenzt, verfolgt ein konkretes Ziel und besitzt gegenüber Routineaufgaben eine besondere Kombination aus Umfang, Ressourcen, Beteiligten und Risiken.</p>,
    sections: [
      { title: "Projektmerkmale", paragraphs: [<>Ein klarer Start und Abschluss, ein definierter Auftrag, begrenzte Ressourcen und eine geeignete Organisation kennzeichnen ein Projekt. Nicht jede einmalige Aufgabe braucht deshalb ein großes Projektbüro.</>, <>Projektleitung koordiniert Ziel, Plan, Team, Kommunikation, Risiken und Entscheidungen. Fachverantwortung bleibt bei den passenden Rollen.</>] },
      { title: "SMART statt vage", paragraphs: [<>Ein Ziel soll spezifisch, messbar, attraktiv beziehungsweise akzeptiert, realistisch und terminiert sein. Die genaue deutsche Auflösung kann variieren; entscheidend sind Klarheit und Prüfbarkeit.</>, <>„Server verbessern“ ist vage. „Bis 30. November sinkt die gemessene Wiederanlaufzeit des Dienstes im Test von 120 auf höchstens 45 Minuten“ ist überprüfbar.</>], activity: <SingleChoiceCheck title="SMART prüfen" question="Welches Ziel ist am besten überprüfbar?" inputName="project-smart" correctOptionId="measurable" successMessage="Termin, Messgröße und Zielwert machen den Erfolg prüfbar." options={[{id:"better",label:"Das WLAN soll bald besser werden.",explanation:"Zeitpunkt und Messgröße fehlen."},{id:"measurable",label:"Bis 15.12. erreicht der Pilot in den definierten Räumen mindestens −67 dBm.",explanation:"Termin, Bereich und Messwert sind definiert."},{id:"technology",label:"Wir kaufen Access Points.",explanation:"Das ist eine Maßnahme, kein Ergebnisziel."},{id:"perfect",label:"Alle sind immer vollständig zufrieden.",explanation:"Das ist weder realistisch noch messklar."}]} /> },
    ],
    visual: <TextFlow caption="Vom Bedarf zum prüfbaren Ziel" steps={["Ausgangslage", "gewünschter Nutzen", "Messgröße und Zielwert", "Termin und Verantwortlichkeit"]} />,
    scenario: { title: "WLAN-Pilot", situation: <p>In zwei Schulungsräumen brechen Videokonferenzen ab. Bis Jahresende soll eine pilotierte Verbesserung bewertet werden.</p>, tasks: ["Formuliere ein SMARTes Ziel.", "Nenne eine Maßnahme, die nicht mit dem Ziel verwechselt werden darf."], solution: <p>Beispielziel: Bis 15.12. bestehen 95 % definierter Testanrufe in beiden Räumen ohne Abbruch. Eine zusätzliche Funkmessung oder neue Access Points sind mögliche Maßnahmen.</p> },
    takeaway: ["Projekte sind zielgerichtet und begrenzt.", "SMART macht Erfolg überprüfbar.", "Ziele beschreiben Ergebnisse, Maßnahmen den Weg."],
  },
  "magisches-dreieck-und-stakeholder": {
    objectives: ["Zeit, Kosten und Leistung/Qualität abwägen", "Stakeholder analysieren", "Projektrollen unterscheiden", "Risiken priorisieren"],
    intro: <p>Projektentscheidungen verändern häufig mehrere Zielgrößen gleichzeitig. Das magische Dreieck macht den Zusammenhang zwischen Zeit, Kosten und Leistung beziehungsweise Qualität sichtbar.</p>,
    sections: [
      { title: "Zielkonflikte transparent machen", paragraphs: [<>Ein früherer Termin kann zusätzliche Kosten oder geringeren Umfang verursachen. Ein größerer Umfang benötigt meist mehr Zeit, Ressourcen oder andere Prioritäten. Qualität darf nicht stillschweigend auf ein undefiniertes Minimum fallen.</>, <>Änderungen werden bewertet, entschieden und dokumentiert. Das Dreieck liefert keine automatische Entscheidung, sondern strukturiert die Auswirkungen.</>] },
      { title: "Stakeholder und Risiken", paragraphs: [<>Stakeholder beeinflussen das Projekt oder sind betroffen: Auftraggeber, Nutzer, Betrieb, Datenschutz, Einkauf oder externe Anbieter. Interesse, Einfluss, Informationsbedarf und mögliche Konflikte unterscheiden sich.</>, <>Risiken werden mit Ursache, Eintrittswahrscheinlichkeit, Auswirkung, Maßnahme und Verantwortlichkeit beschrieben. Ein hoher Schaden bei geringer Wahrscheinlichkeit kann trotzdem relevant sein.</>], activity: <SingleChoiceCheck title="Dreieck anwenden" question="Der unverrückbare Termin bleibt, der Umfang steigt. Welche Reaktion ist plausibel?" inputName="project-triangle" correctOptionId="tradeoff" successMessage="Kosten, Ressourcen, Umfang oder Qualitätsanforderungen müssen neu bewertet werden." options={[{id:"nothing",label:"Es ändert sich garantiert nichts.",explanation:"Mehr Umfang braucht normalerweise eine Anpassung."},{id:"tradeoff",label:"Ressourcen/Kosten erhöhen oder Umfang und Qualitätsziel neu verhandeln.",explanation:"Das macht den Zielkonflikt transparent."},{id:"hide",label:"Die Änderung nicht dokumentieren.",explanation:"Das verschärft Steuerungsrisiken."},{id:"blame",label:"Stakeholder nicht mehr informieren.",explanation:"Betroffene brauchen passende Kommunikation."}]} /> },
    ],
    visual: <ResponsiveTable caption="Stakeholderanalyse" headers={["Stakeholder", "Interesse", "Einfluss", "Kommunikation"]} rows={[["Auftraggeber", "Nutzen/Budget", "hoch", "Entscheidungen und Status"],["Nutzer", "praktischer Ablauf", "mittel", "Anforderungen und Pilotfeedback"],["Betrieb", "wartbarer Service", "hoch", "Architektur, Übergabe, Risiken"]]} />,
    scenario: { title: "Rollout-Termin bleibt", situation: <p>Eine gesetzte Eröffnung bleibt unverändert, zusätzlich werden 20 Arbeitsplätze gefordert.</p>, tasks: ["Welche Zielgrößen sind betroffen?", "Welche Stakeholder entscheiden beziehungsweise liefern Evidenz?"], solution: <p>Zeit ist fix; Umfang steigt, daher Kosten/Ressourcen und Qualitätsrisiken bewerten. Auftraggeber entscheidet Prioritäten, Technik und Nutzer liefern Aufwand und Abnahmekriterien.</p> },
    takeaway: ["Projektziele beeinflussen einander.", "Stakeholder werden nach Bedarf eingebunden.", "Risiken brauchen Besitzer und Maßnahmen."],
  },
  "phasen-arbeitspakete-und-anforderungen": {
    objectives: ["Projektphasen einordnen", "PSP und Arbeitspakete erklären", "Meilensteine unterscheiden", "Lastenheft und Pflichtenheft trennen"],
    intro: <p>Ein Projekt wird in planbare Teile zerlegt. Phasen strukturieren den Lebenszyklus, ein Projektstrukturplan gliedert den Leistungsumfang und Arbeitspakete machen Verantwortung und Ergebnis greifbar.</p>,
    sections: [
      { title: "Vom Projekt zum Arbeitspaket", paragraphs: [<>Ein Arbeitspaket hat Ergebnis, Umfang, Verantwortlichkeit, Aufwand und Abnahmekriterien. Ein Meilenstein ist ein bedeutender prüfbarer Zustand und hat typischerweise keine eigene Dauer.</>, <>Projektphasen können Initiierung, Planung, Umsetzung, Abnahme/Übergabe und Abschluss umfassen. Das ist ein sinnvolles Modell, keine universelle starre Schablone.</>] },
      { title: "Was und wie", paragraphs: [<>Das Lastenheft beschreibt aus Auftraggebersicht Anforderungen und das „Was/Wofür“. Das Pflichtenheft beschreibt aus Auftragnehmersicht die geplante Umsetzung, also das „Wie/Womit“.</>, <>Die Trennung ist eine hilfreiche Grundregel. Verträge und Organisationen können Dokumentnamen anders verwenden; maßgeblich bleibt der vereinbarte Inhalt.</>], activity: <SingleChoiceCheck title="Dokument zuordnen" question="Wo gehört die geplante technische Umsetzung einer Anforderung typischerweise hin?" inputName="project-specification" correctOptionId="requirements" successMessage="Das Pflichtenheft konkretisiert die Umsetzung." options={[{id:"customer",label:"nur ins Lastenheft als Auftraggeberbedarf",explanation:"Dort steht primär das Was/Wofür."},{id:"requirements",label:"ins Pflichtenheft als Umsetzungskonzept",explanation:"Dort wird das Wie konkretisiert."},{id:"milestone",label:"ausschließlich in einen Meilenstein",explanation:"Ein Meilenstein ist ein Zustand, kein vollständiges Umsetzungskonzept."},{id:"risk",label:"nur in die Risikoliste",explanation:"Risiken und Umsetzung sind verschiedene Artefakte."}]} /> },
    ],
    visual: <TextFlow caption="Ein möglicher Projektablauf" steps={["Auftrag klären", "planen und strukturieren", "umsetzen und steuern", "abnehmen und übergeben", "abschließen und lernen"]} />,
    scenario: { title: "Fileserver-Migration", situation: <p>Der Fachbereich fordert Zugriff, Verfügbarkeit und einen Stichtag. Die IT plant Plattform, Migration und Tests.</p>, tasks: ["Ordne Lasten- und Pflichtenheftanteile.", "Formuliere einen Meilenstein."], solution: <p>Bedarf und Abnahmekriterien gehören ins Lastenheft; technische Lösung und Migrationsverfahren ins Pflichtenheft. Meilenstein: „Pilotmigration fachlich abgenommen“.</p> },
    takeaway: ["PSP gliedert Umfang, Arbeitspakete machen ihn bearbeitbar.", "Meilensteine markieren Ergebnisse ohne Dauer.", "Lastenheft beschreibt das Was, Pflichtenheft das Wie."],
  },
  "gantt-und-projektcontrolling": {
    objectives: ["Gantt-Balken lesen", "Abhängigkeiten erkennen", "Meilensteine einordnen", "Soll und Ist vergleichen"],
    intro: <p>Ein Gantt-Diagramm legt Vorgänge auf eine Zeitachse. Balken zeigen geplanten Start und Dauer; Abhängigkeiten und Meilensteine erklären, was wann möglich oder fällig ist.</p>,
    sections: [
      { title: "Zeitplan interpretieren", paragraphs: [<>Zwei Balken können parallel liegen, wenn keine widersprechende Abhängigkeit oder Ressourcenbegrenzung besteht. Eine Ende-Anfang-Abhängigkeit bedeutet: Der Nachfolger startet erst nach Abschluss des Vorgängers.</>, <>Ein Meilenstein markiert etwa Freigabe oder Abnahme. Er ist keine mehrtägige Tätigkeit und ersetzt kein Arbeitspaket.</>], activity: <SingleChoiceCheck title="Gantt lesen" question="Testen darf erst nach Installation beginnen. Installation endet an Tag 6. Wann ist der früheste Teststart?" inputName="project-gantt" correctOptionId="seven" successMessage="Bei ganzen Arbeitstagen startet der Nachfolger am folgenden Tag 7." options={[{id:"one",label:"Tag 1",explanation:"Die Abhängigkeit wäre verletzt."},{id:"six",label:"parallel an Tag 6 vor Abschluss",explanation:"Der Vorgänger muss abgeschlossen sein."},{id:"seven",label:"Tag 7",explanation:"Das ist der nächste Tag nach dem Ende."},{id:"unknown",label:"grundsätzlich nie bestimmbar",explanation:"Die Abhängigkeit und das Ende sind gegeben."}]} /> },
      { title: "Controlling statt Planablage", paragraphs: [<>Soll-Ist-Vergleiche betrachten Termine, Aufwand, Kosten, Umfang, Qualität und Risiken. Eine Abweichung ist ein Signal zur Analyse, nicht automatisch persönliches Versagen.</>, <>Prognosen werden mit Restaufwand und Risiken aktualisiert. Gegenmaßnahmen erhalten Verantwortlichkeit und Termin; Änderungen brauchen einen nachvollziehbaren Entscheidungsweg.</>] },
    ],
    visual: <ResponsiveTable caption="Kleiner Gantt-Ausschnitt" headers={["Vorgang", "Dauer", "Vorgänger", "geplanter Zeitraum"]} rows={[["Anforderungen", "2 Tage", "–", "Tag 1–2"],["Installation", "4 Tage", "Anforderungen", "Tag 3–6"],["Test", "2 Tage", "Installation", "Tag 7–8"],["Abnahme", "Meilenstein", "Test", "Ende Tag 8"]]} />,
    scenario: { title: "Installation verspätet", situation: <p>Die Installation endet zwei Tage später; Test und Abnahme hängen direkt davon ab.</p>, tasks: ["Welche Folgewirkung ist wahrscheinlich?", "Welche Informationen braucht eine Steuerungsentscheidung?"], solution: <p>Ohne Puffer oder Gegenmaßnahme verschieben sich Test und Abnahme. Benötigt werden Ursache, Restaufwand, verfügbare Ressourcen, Qualitätsrisiko, Puffer und Terminpriorität.</p> },
    takeaway: ["Gantt zeigt Zeitlage und Abhängigkeiten.", "Meilensteine sind prüfbare Zustände.", "Controlling vergleicht, prognostiziert und steuert."],
  },
  "netzplan-und-kritischer-pfad": {
    objectives: ["Vorwärtsrechnung durchführen", "Rückwärtsrechnung durchführen", "Gesamtpuffer bestimmen", "kritischen Pfad korrekt benennen"],
    intro: <p>Der Vorgangsknoten-Netzplan macht logische Abhängigkeiten sichtbar. Die Vorwärtsrechnung liefert früheste, die Rückwärtsrechnung späteste Termine.</p>,
    sections: [
      { title: "Vorwärts und rückwärts", paragraphs: [<>Frühester Anfang FAZ ist das Maximum der frühesten Enden aller Vorgänger; FEZ = FAZ + Dauer. Die Projektdauer ist das maximale FEZ am Ende.</>, <>Rückwärts gilt für Endvorgänge SEZ = Projektdauer. Für andere Vorgänge ist SEZ das Minimum der spätesten Anfänge ihrer Nachfolger; SAZ = SEZ − Dauer.</>] },
      { title: "Puffer und kritischer Pfad", paragraphs: [<>Gesamtpuffer = SAZ − FAZ beziehungsweise SEZ − FEZ. Vorgänge mit Gesamtpuffer 0 sind kritisch: Eine Verzögerung verschiebt ohne Gegenmaßnahme den Projektendtermin.</>, <>Mehrere kritische Pfade sind möglich. Ein nichtkritischer Vorgang darf nur innerhalb seines Puffers verschoben werden, ohne den Endtermin zu verändern.</>], activity: <SingleChoiceCheck title="Netzplan rechnen" question="Vorgang C hat FAZ 2 und SAZ 3. Wie groß ist sein Gesamtpuffer?" inputName="project-network-float" correctOptionId="one" successMessage="Gesamtpuffer = SAZ − FAZ = 1." options={[{id:"zero",label:"0 Tage",explanation:"Dann wäre C kritisch."},{id:"one",label:"1 Tag",explanation:"3 − 2 ergibt 1."},{id:"two",label:"2 Tage",explanation:"Dauer und Puffer sind nicht dasselbe."},{id:"five",label:"5 Tage",explanation:"Das ist keine Differenz der Startzeiten."}]} /> },
    ],
    visual: <ResponsiveTable caption="Berechneter Netzplan (Zeit ab 0)" headers={["Vorgang", "Dauer", "FAZ", "FEZ", "SAZ", "SEZ", "GP", "kritisch"]} rows={networkExample.activities.map((activity) => [activity.id, activity.duration, activity.earliestStart, activity.earliestFinish, activity.latestStart, activity.latestFinish, activity.totalFloat, activity.critical ? "ja" : "nein"])} />,
    scenario: { title: "Kritischen Pfad bestimmen", situation: <p>A(2) verzweigt in B(3) und C(2); D(4) wartet auf beide; E(2) folgt D.</p>, tasks: ["Wie lang ist das Projekt?", "Welcher Pfad ist kritisch?"], solution: <p>Die berechnete Dauer beträgt {networkExample.projectDuration} Tage. Kritisch ist A–B–D–E mit 2+3+4+2 = 11; C besitzt einen Tag Gesamtpuffer.</p> },
    takeaway: ["Vorwärts: Maximum der Vorgänger.", "Rückwärts: Minimum der Nachfolger.", "Gesamtpuffer 0 kennzeichnet kritische Vorgänge."],
  },
  "wasserfall-scrum-und-kanban": {
    objectives: ["Wasserfall einordnen", "Scrum-Rollen und -Artefakte unterscheiden", "Review und Retrospektive trennen", "Kanban-Grundidee erklären"],
    intro: <p>Vorgehensmodelle strukturieren Zusammenarbeit. Die passende Wahl hängt von Veränderlichkeit, Risiko, Regulierung, Lieferbarkeit und Teamkontext ab.</p>,
    sections: [
      { title: "Sequenziell planen", paragraphs: [<>Wasserfallartige Modelle ordnen Phasen weitgehend nacheinander. Das unterstützt planbare Übergaben und Dokumentation, reagiert aber bei späten Erkenntnissen oft teuer.</>, <>Auch sequenzielle Projekte brauchen Feedback und Risikosteuerung; „Wasserfall“ bedeutet nicht, Erkenntnisse bewusst zu ignorieren.</>] },
      { title: "Scrum und Kanban", paragraphs: [<>In Scrum maximiert der Product Owner Produktwert und verantwortet das Product Backlog. Der Scrum Master unterstützt Scrum und beseitigt keine Arbeit stellvertretend. Developers erstellen im Sprint ein nutzbares Inkrement; das Sprint Backlog beschreibt ihren Plan.</>, <>Im Review werden Ergebnis und nächste Produktentscheidungen mit Stakeholdern betrachtet; die Retrospektive verbessert Zusammenarbeit und Prozess. Kanban visualisiert Fluss und begrenzt Work in Progress (WIP), ohne automatisch Scrum-Rollen zu übernehmen.</>], activity: <SingleChoiceCheck title="Scrum-Rolle" question="Wer verantwortet in Scrum die Ordnung des Product Backlogs?" inputName="project-scrum-role" correctOptionId="po" successMessage="Der Product Owner verantwortet Product-Backlog-Management und Wert." options={[{id:"sm",label:"Scrum Master",explanation:"Er unterstützt das Rahmenwerk."},{id:"po",label:"Product Owner",explanation:"Das gehört zu seiner Accountabilität."},{id:"developers",label:"ausschließlich die Developers",explanation:"Sie verantworten unter anderem Sprint Backlog und Inkrement."},{id:"customer",label:"automatisch jeder Kunde",explanation:"Stakeholder geben Input, sind aber nicht automatisch Product Owner."}]} /> },
    ],
    visual: <ResponsiveTable caption="Vorgehensweisen vergleichen" headers={["Ansatz", "Stärke", "Grenze", "passender Kontext"]} rows={[["Wasserfall", "klare Phasen/Übergaben", "späte Änderungen teuer", "stabile, stark dokumentierte Anforderungen"],["Scrum", "kurze Lernzyklen", "braucht fokussiertes Team und Product Goal", "komplexe Produktentwicklung"],["Kanban", "Fluss/WIP sichtbar", "Priorisierung bleibt nötig", "kontinuierliche Servicearbeit"]]} />,
    scenario: { title: "Zwei IT-Vorhaben", situation: <p>Ein gesetzlich festgelegter Hardware-Rollout hat stabile Abnahmekriterien; ein internes Portal benötigt häufiges Nutzerfeedback.</p>, tasks: ["Welche Vorgehensrichtung ist je Fall plausibel?", "Warum ist keine Methode universell überlegen?"], solution: <p>Der Rollout kann stärker sequenziell geplant werden; das Portal profitiert möglicherweise von iterativen Scrum-Zyklen. Team, Risiken, Lieferbarkeit und Änderungsrate entscheiden.</p> },
    takeaway: ["Vorgehensweisen werden kontextbezogen gewählt.", "Scrum-Rollen und Ereignisse haben getrennte Zwecke.", "Kanban fokussiert sichtbaren Fluss und WIP."],
  },
};

export function ProjectManagementLesson({ lessonSlug }: { lessonSlug: string }) {
  const lesson = lessons[lessonSlug];
  if (!lesson) return null;
  return <FundamentalsLesson lessonId={`project-${lessonSlug}`} {...lesson}>{lesson.visual}</FundamentalsLesson>;
}
