import type { ReactNode } from "react";
import { FundamentalsLesson, ResponsiveTable, TextFlow, type LessonSection } from "./fundamentals-lesson-elements";
import { SingleChoiceCheck } from "./single-choice-check";

type LessonContent = { objectives: readonly string[]; intro: ReactNode; sections: readonly LessonSection[]; visual?: ReactNode; scenario: { title: string; situation: ReactNode; tasks: readonly ReactNode[]; solution: ReactNode }; takeaway: readonly ReactNode[]; relatedLinks?: readonly { href: string; label: string }[] };

const lessons: Record<string, LessonContent> = {
  "qualitaet-qa-qm-und-pdca": {
    objectives: ["Qualität relativ zu Anforderungen erklären", "Qualitätssicherung und Qualitätsmanagement unterscheiden", "PDCA auf einen IT-Prozess anwenden"],
    intro: <p>Qualität bedeutet, definierte und berechtigte Anforderungen nachweisbar zu erfüllen. „Fühlt sich gut an“ ist kein prüfbares Qualitätskriterium.</p>,
    sections: [
      { title: "QA und QM", paragraphs: [<>Qualitätsmanagement (QM) umfasst das übergreifende System aus Zielen, Verantwortlichkeiten, Prozessen, Ressourcen und Verbesserung. Qualitätssicherung (QA) umfasst geplante Maßnahmen, die Vertrauen in die Erfüllung von Qualitätsanforderungen schaffen.</>, <>Prüfen und Testen sind wichtige QA-Aktivitäten, aber Qualität entsteht auch durch klare Anforderungen, Reviews, Standards, Schulung und kontrollierte Änderungen.</>], activity: <SingleChoiceCheck title="QA oder QM?" question="Eine Organisation definiert Rollen, Qualitätsziele und einen unternehmensweiten Verbesserungsprozess. Was beschreibt das am ehesten?" inputName="quality-qa-qm" correctOptionId="qm" successMessage="Das übergreifende System gehört zum Qualitätsmanagement." options={[{id:"qa-only",label:"nur einen einzelnen Funktionstest",explanation:"Das Beispiel ist breiter."},{id:"qm",label:"Qualitätsmanagement",explanation:"Richtig."},{id:"incident",label:"einen Incident",explanation:"Ein Incident ist eine Störung."},{id:"acceptance",label:"nur formale Abnahme",explanation:"Abnahme ist ein einzelner Schritt."}]} /> },
      { title: "PDCA als Lernschleife", paragraphs: [<>Plan definiert Problem, Ziel und Maßnahme. Do erprobt die Maßnahme kontrolliert. Check vergleicht Ergebnisse mit Ziel und Daten. Act standardisiert eine wirksame Verbesserung oder passt den Plan an.</>, <>PDCA ist zyklisch. Check ist nicht „fertig“, und Act bedeutet nicht bloß Aktion, sondern Konsequenz aus dem geprüften Ergebnis.</>] },
    ],
    visual: <ResponsiveTable caption="PDCA bei fehlerhaften Arbeitsplatz-Rollouts" headers={["Phase", "Beispiel"]} rows={[["Plan","Fehlerdaten auswerten; Checkliste und Zielquote definieren"],["Do","Checkliste in kleinem Pilot einsetzen"],["Check","Fehlerquote und Rückmeldungen mit Ausgangswert vergleichen"],["Act","wirksame Checkliste standardisieren oder überarbeiten"]]} />,
    scenario: { title: "Wiederholte Rolloutfehler", situation: <p>Bei zwölf neuen Clients fehlen mehrfach Zertifikate. Das Team möchte sofort überall eine neue Checkliste einführen.</p>, tasks: ["Ordne sinnvolle PDCA-Schritte.", "Welche Messgröße macht die Wirkung prüfbar?"], solution: <p>Ursache/Ziel planen, Checkliste im Pilot anwenden, Fehlerrate und Aufwand prüfen, dann standardisieren oder anpassen. Messbar sind etwa fehlende Zertifikate pro Rollout und Nacharbeitszeit.</p> },
    takeaway: ["Qualität bezieht sich auf definierte Anforderungen.", "QA ist Teil eines umfassenderen QM.", "PDCA verbindet geplanten Versuch, Prüfung und Konsequenz."],
  },
  "testfaelle-und-soll-ist": {
    objectives: ["vollständige Testfälle formulieren", "erwartetes Ergebnis vor Ausführung definieren", "Soll, Ist, Abweichung und Evidenz trennen"],
    intro: <p>Ein Testfall macht Erfolg vor der Durchführung entscheidbar. Ohne vorher definiertes Soll kann ein beobachtetes Ist beliebig als passend ausgelegt werden.</p>,
    sections: [
      { title: "Bausteine eines Testfalls", paragraphs: [<>Ein praktischer Testfall enthält Test-ID, Bezug zur Anforderung, Vorbedingungen, Testdaten, Schritte und erwartetes Ergebnis. Nach Ausführung folgen tatsächliches Ergebnis, PASS/FAIL sowie Evidenz oder Kommentar.</>, <>PASS bedeutet, dass das beobachtete Ergebnis das definierte Soll erfüllt. Ein unerwarteter Erfolg oder ein „sieht okay aus“ ersetzt keine Kriterien.</>], activity: <SingleChoiceCheck title="Testfall prüfen" question="Wann wird das erwartete Ergebnis festgelegt?" inputName="quality-expected" correctOptionId="before" successMessage="Das Soll wird vor der Ausführung aus der Anforderung abgeleitet." options={[{id:"after",label:"Erst nach dem Test passend zum beobachteten Ergebnis.",explanation:"Dann wäre die Bewertung beliebig."},{id:"before",label:"Vor der Ausführung.",explanation:"Richtig."},{id:"never",label:"Es ist nicht nötig.",explanation:"Ohne Soll fehlt die Bewertungsbasis."},{id:"customer-only",label:"Nur bei Beschwerden.",explanation:"Jeder prüfbare Test braucht ein Soll."}]} /> },
      { title: "Soll, Ist und Abweichung", paragraphs: [<>Soll beschreibt die erwartete beobachtbare Wirkung; Ist hält die tatsächliche Beobachtung fest. Die Abweichung nennt konkret den Unterschied, ohne bereits eine unbewiesene Ursache zu behaupten.</>, <>Screenshots, Logauszüge oder Messwerte können Evidenz sein. Personen- und Geheimdaten werden minimiert und geschützt; Evidenz muss reproduzierbar und zum Testzeitpunkt zuordenbar sein.</>] },
    ],
    visual: <ResponsiveTable caption="Testfall TC-FS-04" headers={["Feld", "Inhalt"]} rows={[["Anforderung","berechtigte Nutzer öffnen Freigabe innerhalb 2 s"],["Vorbedingung","Testkonto, LAN, definierte Datei vorhanden"],["Schritte","anmelden; Freigabe öffnen; Datei aufrufen"],["Soll","Datei öffnet in höchstens 2 s; Zugriff protokolliert"],["Ist","3,4 s; Zugriff erfolgreich"],["Status","FAIL – Leistungsziel verfehlt"],["Evidenz","Zeitmessung und bereinigter Logverweis"]]} />,
    scenario: { title: "Druckertest", situation: <p>Ein Techniker notiert nach dem Test nur „Drucken geht“.</p>, tasks: ["Welche Felder fehlen?", "Formuliere ein prüfbares Soll."], solution: <p>Test-ID, Anforderung, Vorbedingung, Schritte, Testdaten, Soll, konkretes Ist, Status und Evidenz fehlen. Beispiel-Soll: definierte PDF wird vom Testkonto innerhalb 60 Sekunden einseitig und vollständig am Zielgerät ausgegeben.</p> },
    takeaway: ["Das Soll steht vor dem Test fest.", "Ist beschreibt Beobachtung, nicht Wunsch.", "Abweichung und Evidenz machen Ergebnisse nachvollziehbar."],
  },
  "testarten-und-abnahmetest": {
    objectives: ["Funktions-, Integrations-, System- und Abnahmetest unterscheiden", "Black- und White-Box einordnen", "technischen Test und formale Abnahme trennen"],
    intro: <p>Testarten betrachten unterschiedliche Prüfebenen und Ziele. Sie können sich in einem Projekt ergänzen und sind nicht nur durch den Namen des Werkzeugs bestimmt.</p>,
    sections: [
      { title: "Ebenen und Zweck", paragraphs: [<>Ein Funktionstest prüft eine konkrete Funktion. Ein Integrationstest prüft das Zusammenspiel von Komponenten. Ein Systemtest betrachtet das Gesamtsystem gegen Anforderungen. Ein Abnahmetest liefert Evidenz für vereinbarte Akzeptanzkriterien aus Auftraggeber-/Nutzersicht.</>, <>Ein bestandener interner Systemtest ist noch keine formale Abnahme. Abnahme ist eine Erklärung beziehungsweise ein geregelter Vorgang im vereinbarten Kontext.</>], activity: <SingleChoiceCheck title="Testart wählen" question="ERP und DMS funktionieren einzeln; geprüft wird nun der Dokumentenaustausch über die Schnittstelle. Welche Testart passt?" inputName="quality-test-type" correctOptionId="integration" successMessage="Das Zusammenspiel zweier Systeme ist Gegenstand des Integrationstests." options={[{id:"function",label:"nur Funktionstest einer isolierten Schaltfläche",explanation:"Hier geht es um mehrere Systeme."},{id:"integration",label:"Integrationstest",explanation:"Richtig."},{id:"acceptance",label:"automatisch formale Abnahme",explanation:"Eine Schnittstellenprüfung allein ist keine Abnahme."},{id:"pdca",label:"PDCA-Act",explanation:"PDCA ist ein Verbesserungszyklus."}]} /> },
      { title: "Black Box und White Box", paragraphs: [<>Black-Box-Tests leiten Eingaben und erwartete Ausgaben aus Spezifikation ab, ohne interne Struktur als Testbasis zu benötigen. White-Box-Tests berücksichtigen interne Struktur oder Pfade.</>, <>Beide Sichten können sinnvoll sein. Black Box bedeutet nicht oberflächlich, White Box nicht automatisch vollständig; Auswahl und Abdeckung folgen Risiko und Ziel.</>] },
    ],
    visual: <ResponsiveTable caption="Testarten im Fileservice" headers={["Testart", "Beispiel"]} rows={[["Funktion","berechtigter Upload funktioniert"],["Integration","Identitätsdienst liefert Rollen an Fileservice"],["System","gesamter Dienst erfüllt Sicherheit, Leistung und Recovery-Anforderungen"],["Abnahmetest","vereinbarte Anwenderfälle gegen Akzeptanzkriterien"],["Black Box","Anmeldung anhand Ein-/Ausgabe prüfen"],["White Box","interne Berechtigungspfade gezielt abdecken"]]} />,
    scenario: { title: "Neues Kundenportal", situation: <p>Login, DMS-Schnittstelle und Gesamtsystem wurden intern geprüft. Der Kunde soll nun die vereinbarten Geschäftsabläufe bestätigen.</p>, tasks: ["Welche Tests liegen vor?", "Welcher Schritt folgt und warum ist er nicht identisch mit internem Test?"], solution: <p>Login kann Funktionstest, DMS-Austausch Integrationstest und Gesamtprüfung Systemtest sein. Danach folgt ein vereinbarter Abnahmetest und gegebenenfalls die formale Abnahme durch die zuständige Partei.</p> },
    takeaway: ["Testarten beantworten verschiedene Fragen.", "Black-/White-Box beschreiben die Testsicht.", "Technischer Test und formale Abnahme sind getrennt."],
  },
  "fehlerdokumentation-und-serviceprozess": {
    objectives: ["reproduzierbare Fehlerberichte erstellen", "Service Request, Incident und Problem unterscheiden", "Supportlevel, Auswirkung, Dringlichkeit und Eskalation einordnen"],
    intro: <p>Das bestehende Troubleshooting-Modul vermittelt die technische Diagnose. Hier geht es ergänzend um den organisatorischen Serviceprozess vom Eingang bis zum nachvollziehbaren Abschluss.</p>,
    sections: [
      { title: "Ticket und Fehlerbericht", paragraphs: [<>Ein Ticket hält Melder, Zeit, betroffenen Service, Umgebung, reproduzierbare Schritte, Soll, Ist, Auswirkung, Evidenz, Status und Bearbeitung fest. Ein Service Request ist eine standardisierte Leistungsanfrage; ein Incident ist eine ungeplante Beeinträchtigung.</>, <>Ein Problem bezeichnet die zugrunde liegende Ursache oder Ursachenanalyse zu einem oder mehreren Incidents. Das Symptom wird nicht vorschnell als Root Cause dokumentiert.</>], activity: <SingleChoiceCheck title="Servicefall zuordnen" question="Zwölf Nutzer verlieren wiederholt die Verbindung; die gemeinsame Ursache ist noch unbekannt. Was ist zunächst angemessen?" inputName="quality-service" correctOptionId="incident" successMessage="Die konkrete Servicebeeinträchtigung wird als Incident erfasst; Ursachenanalyse kann als Problem bearbeitet werden." options={[{id:"request",label:"nur Service Request für neue Hardware",explanation:"Es liegt eine Störung vor."},{id:"incident",label:"Incident mit Auswirkung und Evidenz",explanation:"Richtig."},{id:"root",label:"sofort eine unbelegte Root Cause eintragen",explanation:"Ursache ist noch offen."},{id:"close",label:"Ticket ohne Prüfung schließen",explanation:"Wiederherstellung und Abschlusskriterien fehlen."}]} /> },
      { title: "Support und Eskalation", paragraphs: [<>First, Second und Third Level sind organisatorische Konzepte: Annahme/Standardfälle, vertiefte Fachanalyse und spezialisierte Produkt-/Entwicklungsnähe sind typische Richtungen. Exakte Grenzen variieren je Organisation.</>, <>Priorität ergibt sich häufig aus Auswirkung und Dringlichkeit; technische Schwere ist nicht dasselbe. Eskalation kann fachlich oder hierarchisch nötig sein. Fernsupport erfolgt nur autorisiert, transparent und mit sicherem Zugriff.</>] },
    ],
    visual: <TextFlow caption="Serviceprozess" steps={["Meldung/Ticket", "klassifizieren/priorisieren", "First Level", "fachlich eskalieren", "Lösung verifizieren", "Nutzer bestätigen", "dokumentiert schließen"]} />,
    scenario: { title: "Zwei Tickets", situation: <p>A: Vorstandspräsentation in 20 Minuten, einzelner Beamer fällt aus. B: unkritische Testfunktion zeigt bei allen Nutzern einen Darstellungsfehler.</p>, tasks: ["Vergleiche Auswirkung, Dringlichkeit und technische Schwere.", "Welche Information fehlt für die Priorität?"], solution: <p>A hat geringe Nutzerzahl, aber hohe Dringlichkeit; B hat breite Auswirkung, möglicherweise geringe Dringlichkeit. Geschäftsfolgen, Workarounds, SLA und Sicherheitsrisiko bestimmen die Priorität – nicht Nutzerrolle allein.</p> },
    takeaway: ["Ticket ist der nachvollziehbare Datensatz, nicht die Ursache.", "Incident und Problem sind verschieden.", "Supportlevel und Priorität hängen vom Organisationskontext ab."],
    relatedLinks: [{href:"/lernen/netzwerkfehler-systematisch-analysieren/troubleshooting-methode",label:"Troubleshooting: evidenzbasierte Diagnose"}],
  },
  "abnahme-uebergabe-und-einweisung": {
    objectives: ["vereinbarten Umfang und Soll-Ist-Abweichungen prüfen", "technischen Test, Abnahme und Übergabe unterscheiden", "ein Abnahmeprotokoll sinnvoll strukturieren"],
    intro: <p>Am Ende eines Auftrags werden nicht nur Geräte übergeben. Umfang, Prüfergebnis, bekannte Abweichungen, offene Maßnahmen, Dokumentation und Verantwortungswechsel müssen nachvollziehbar sein.</p>,
    sections: [
      { title: "Vom Test zur Abnahme", paragraphs: [<>Zuerst werden vereinbarter Umfang und Kriterien bestätigt, Funktionen geprüft und Abweichungen dokumentiert. Offene Mängel erhalten Status, Verantwortlichkeit und Termin. Die zuständige Partei entscheidet anschließend im vereinbarten Rahmen über den Abnahmestatus.</>, <>Übergabe überträgt System, Dokumentation und Betriebswissen. Einweisung befähigt Nutzer beziehungsweise Betrieb. Diese Schritte können zusammenliegen, sind aber begrifflich nicht identisch.</>], activity: <SingleChoiceCheck title="Reihenfolge bestimmen" question="Ein Abnahmetest findet eine bekannte Abweichung. Was ist angemessen?" inputName="quality-handover" correctOptionId="record" successMessage="Abweichung, Auswirkung, Entscheidung und Folgemaßnahme werden dokumentiert." options={[{id:"hide",label:"Abweichung aus dem Protokoll entfernen.",explanation:"Das verhindert eine nachvollziehbare Entscheidung."},{id:"record",label:"Abweichung dokumentieren und über Status/Folge entscheiden.",explanation:"Richtig."},{id:"auto",label:"Automatisch vollständige Abnahme behaupten.",explanation:"Der vereinbarte Prozess entscheidet."},{id:"delete",label:"Testevidenz löschen.",explanation:"Nachweise müssen angemessen erhalten bleiben."}]} /> },
      { title: "Abnahmeprotokoll", paragraphs: [<>Nützlich sind Projekt-/Auftragsreferenz, Umfang, Datum, Beteiligte, Test-/Ergebniszusammenfassung, bekannte Abweichungen oder Mängel, vereinbarte Folgemaßnahmen und Abnahmestatus.</>, <>Das Lernmuster garantiert keine rechtliche Wirkung. Reale Vorlagen und Zeichnungsberechtigungen folgen Vertrag und Organisation.</>] },
    ],
    visual: <ResponsiveTable caption="Übergabe-Check" headers={["Bereich", "Nachweis"]} rows={[["Umfang","gelieferte Komponenten/Leistungen"],["Prüfung","Testfälle und Ergebnisübersicht"],["Abweichung","Beschreibung, Auswirkung, Entscheidung"],["Betrieb","Dokumentation, Backup, Monitoring, Supportweg"],["Einweisung","Zielgruppe, Inhalte, Fragen"],["Status","angenommen, bedingt/offen nach vereinbartem Prozess"]]} />,
    scenario: { title: "Fileserver-Übergabe", situation: <p>Alle Muss-Tests sind bestanden; ein optionaler Bericht fehlt und soll nächste Woche geliefert werden.</p>, tasks: ["Welche Informationen gehören ins Protokoll?", "Was wird bei der Einweisung gezeigt?"], solution: <p>Umfang, Tests, fehlender Bericht, Verantwortlichkeit/Termin und vereinbarter Abnahmestatus werden festgehalten. Einweisung zeigt Zugriff, sichere Nutzung, Wiederherstellung im Nutzerumfang, Grenzen und Supportweg.</p> },
    takeaway: ["Technischer Test, Abnahme, Übergabe und Einweisung sind verschiedene Schritte.", "Abweichungen werden sichtbar entschieden.", "Das Protokoll dokumentiert, garantiert aber nicht pauschal Rechtswirkung."],
    relatedLinks: [{href:"/lernen/kundenauftrag-kommunikation-und-vertraege/sla-support-und-kundeneinweisung",label:"Kundenauftrag: SLA und Einweisung"}],
  },
  "technische-dokumentation-und-lessons-learned": {
    objectives: ["technischen Ist-Zustand für Dritte nachvollziehbar dokumentieren", "Geheimnisse sicher behandeln", "Plan/Ist-Aufwand und Lessons Learned auswerten"],
    intro: <p>Technische Dokumentation ermöglicht einer anderen Fachkraft, Zweck, Aufbau, Abhängigkeiten und Betrieb zu verstehen. Sie ist aktuell, adressatengerecht und sicher abgelegt.</p>,
    sections: [
      { title: "Betriebsfähige Dokumentation", paragraphs: [<>Typische Inhalte sind Systemzweck, Übersicht/Topologie, Konfiguration, IP-/Servicedaten soweit angemessen, Abhängigkeiten, Rollen, Backup-/Recovery-Verweise, Wartung und Änderungshistorie.</>, <>Passwörter, private Schlüssel und Tokens gehören nicht als Klartext in normale Dokumentation. Stattdessen wird der freigegebene Secret-Speicher, Eigentümer und sichere Zugriffsprozess referenziert.</>], activity: <SingleChoiceCheck title="Geheimnisse dokumentieren" question="Wie wird ein Administratorpasswort in der technischen Dokumentation behandelt?" inputName="quality-secrets" correctOptionId="reference" successMessage="Die Dokumentation verweist auf den kontrollierten Secret-Prozess, ohne das Passwort offenzulegen." options={[{id:"plain",label:"Als Klartext in jede PDF schreiben.",explanation:"Das schafft unnötige Offenlegung."},{id:"reference",label:"Sicheren Secret-Speicher und Zugriffsprozess referenzieren.",explanation:"Richtig."},{id:"public",label:"Im öffentlichen Wiki ablegen.",explanation:"Zugriff wäre unkontrolliert."},{id:"email",label:"An alle Beteiligten mailen.",explanation:"Das ist keine sichere Geheimnisverwaltung."}]} /> },
      { title: "Abweichung und Lernen", paragraphs: [<>Geplanter und tatsächlicher Aufwand, Kosten, Termine und Ergebnis werden verglichen. Gründe und Korrekturmaßnahmen werden sachlich dokumentiert; eine Abweichung ist Information, keine Personenrangliste.</>, <>Lessons Learned halten fest, was wirkte, was nicht, warum und was beim nächsten Mal geändert wird. Eine Scrum-Retrospektive ist ein regelmäßiges Teamereignis im Scrum-Rahmen; Lessons Learned kann projekt- und methodenübergreifend erfolgen.</>] },
    ],
    visual: <ResponsiveTable caption="Dokumentationsstruktur" headers={["Abschnitt", "Beispiel"]} rows={[["Zweck/Scope","bereitgestellter Dateidienst und Nutzerkreis"],["Architektur","Systeme, Netze, Abhängigkeiten"],["Konfiguration","Versionen, Rollen, relevante Parameter"],["Betrieb","Monitoring, Wartung, Backup-/Recovery-Verweis"],["Secrets","nur Referenz auf kontrollierten Speicher"],["Änderungen","Datum, Anlass, Änderung, Verantwortlichkeit"]]} />,
    scenario: { title: "Projektabschluss", situation: <p>Die Migration brauchte 26 statt 18 Stunden, weil Quelldaten inkonsistent waren. Ein Vorabscan hätte das erkannt.</p>, tasks: ["Dokumentiere Plan/Ist und Ursache ohne Schuldzuweisung.", "Formuliere ein Lesson Learned mit nächster Maßnahme."], solution: <p>Plan 18 h, Ist 26 h, Abweichung +8 h; Evidenz: Inkonsistenzen und Nacharbeit. Lesson Learned: Vor künftigen Migrationen automatisierten Datenqualitäts-Scan mit definiertem Ergebnis und Verantwortlichkeit einplanen.</p> },
    takeaway: ["Dokumentation beschreibt den umgesetzten Zustand und Betrieb.", "Secrets werden referenziert, nicht offengelegt.", "Lessons Learned führen aus Evidenz zu einer konkreten Verbesserung."],
    relatedLinks: [{href:"/lernen/projektmanagement/gantt-und-projektcontrolling",label:"Projektmanagement: Soll-Ist-Controlling"},{href:"/lernen/wirtschaftlichkeit-und-beschaffung/kosten-erloes-und-wirtschaftlichkeit",label:"Wirtschaftlichkeit: Kosten einordnen"}],
  },
};

export function QualityHandoverLesson({ lessonSlug }: { lessonSlug: string }) {
  const lesson = lessons[lessonSlug];
  if (!lesson) return null;
  return <FundamentalsLesson lessonId={`quality-${lessonSlug}`} {...lesson} relatedLinks={lesson.relatedLinks}>{lesson.visual}</FundamentalsLesson>;
}
