import type { ReactNode } from "react";
import { FundamentalsLesson, ResponsiveTable, TextFlow, type LessonSection } from "./fundamentals-lesson-elements";
import { SingleChoiceCheck } from "./single-choice-check";

type Content = { objectives: readonly string[]; intro: ReactNode; sections: readonly LessonSection[]; visual?: ReactNode; scenario: { title: string; situation: ReactNode; tasks: readonly ReactNode[]; solution: ReactNode }; takeaway: readonly ReactNode[] };

const lessons: Record<string, Content> = {
  "begriffe-und-schutzziele": {
    objectives: ["Sicherheitsdisziplinen unterscheiden", "CIA-Schutzziele anwenden", "Authentizität einordnen", "Maßnahmen mehreren Zielen zuordnen"],
    intro: <p>Informationssicherheit schützt Informationen unabhängig von ihrer Form. IT-Sicherheit fokussiert informationsverarbeitende Technik; Datenschutz schützt Menschen beim Umgang mit personenbezogenen Daten. Datensicherung stellt wiederherstellbare Kopien bereit.</p>,
    sections: [
      { title: "Vertraulichkeit, Integrität, Verfügbarkeit", paragraphs: [<>Vertraulichkeit bedeutet Zugriff nur für Berechtigte. Integrität schützt Korrektheit und Unverändertheit. Verfügbarkeit bedeutet, dass Systeme und Informationen bei Bedarf nutzbar sind.</>, <>Authentizität unterstützt die Prüfung, ob Identitäten, Nachrichten oder Systeme tatsächlich die behauptete Herkunft besitzen. Sie ergänzt die CIA-Ziele, ersetzt aber keine Autorisierung.</>] },
      { title: "Ziele können konkurrieren", paragraphs: [<>Starke Zugriffskontrolle schützt Vertraulichkeit, darf aber Notfallzugriff nicht unbedacht verhindern. Redundanz erhöht Verfügbarkeit, eine falsche Änderung kann jedoch auf alle Kopien gelangen. Risiken und Geschäftsanforderungen bestimmen die Balance.</>] },
    ],
    visual: <ResponsiveTable caption="Schutzziele im Betrieb" headers={["Ziel", "Beispiel", "Maßnahme"]} rows={[["Vertraulichkeit", "Personalakte nur für HR", "Berechtigung/Verschlüsselung"], ["Integrität", "Paket unverändert", "Hash/Signatur/Prozess"], ["Verfügbarkeit", "Dienst im Störfall", "Redundanz/Backup/Notfallplan"], ["Authentizität", "Serveridentität prüfen", "Zertifikat/Signatur/MFA"]]} />,
    scenario: { title: "Manipulierte Rechnung", situation: <p>Eine Rechnung erreicht die Buchhaltung, aber Bankverbindung und Absenderherkunft sind fraglich.</p>, tasks: ["Welche Schutzziele sind betroffen?", "Welche Prüfungen sind sinnvoll?"], solution: <p>Integrität und Authentizität stehen im Vordergrund, eventuell auch Vertraulichkeit. Absender über einen bekannten Kanal verifizieren, Signatur-/Prozessnachweise prüfen und nicht über Kontaktdaten der verdächtigen Nachricht reagieren.</p> },
    takeaway: ["Datenschutz und IT-Sicherheit überlappen, sind aber nicht identisch.", "CIA plus Authentizität strukturiert Risiken.", "Maßnahmen werden aus dem konkreten Risiko abgeleitet."],
  },
  "schadsoftware-erkennen": {
    objectives: ["Malware-Arten unterscheiden", "Anzeichen vorsichtig bewerten", "sicher reagieren", "Wiederansteckung vermeiden"],
    intro: <p>Malware-Bezeichnungen beschreiben Verbreitung, Tarnung oder Wirkung. Ein Fund kann mehrere Eigenschaften kombinieren; die Klassifikation ersetzt keine technische Analyse.</p>,
    sections: [
      { title: "Verbreitung und Tarnung", paragraphs: [<>Ein Virus hängt sich an andere Dateien/Programme; ein Wurm verbreitet sich selbstständig über Netze oder Schwachstellen. Ein Trojaner tarnt schädliche Funktion als legitime Software.</>, <>Rootkits verbergen oder verankern Angreifer tief im System. Botnetze verbinden kompromittierte Geräte zur Fernsteuerung. Spyware sammelt Informationen; Keylogger erfassen Eingaben.</>] },
      { title: "Erpressung und Reaktion", paragraphs: [<>Ransomware verschlüsselt oder exfiltriert Daten und fordert Lösegeld. Auffällige Dateiendungen, unbekannte Prozesse, Warnmeldungen oder unerklärlicher Verkehr sind Hinweise, aber keine alleinige Diagnose.</>, <>Gerät nach Incident-Plan isolieren, Beweise erhalten, Security-Team informieren, Konten/Token bewerten, Reichweite bestimmen und aus vertrauenswürdigen Quellen wiederherstellen. Nicht hektisch alles löschen oder Lösegeld als sichere Lösung betrachten.</>] },
    ],
    visual: <ResponsiveTable caption="Malware defensiv einordnen" headers={["Typ", "Kennzeichen", "Schwerpunkt der Abwehr"]} rows={[["Virus", "benötigt Wirtsdatei/Ausführung", "Updates, Schutz, sichere Quellen"], ["Wurm", "selbstständige Verbreitung", "Patches, Segmentierung"], ["Trojaner", "Täuschung", "Quellenprüfung, Rechte"], ["Ransomware", "Verschlüsselung/Erpressung", "Isolation, geschützte Backups"], ["Rootkit/Bot", "Tarnung/Fernsteuerung", "EDR, Neuaufbau, Netzsicht"]]} />,
    scenario: { title: "Dateien plötzlich verschlüsselt", situation: <p>Ein Arbeitsplatz zeigt eine Erpressungsnachricht; ein Netzlaufwerk ist erreichbar.</p>, tasks: ["Was ist die erste organisatorisch-technische Reaktion?", "Welche Vorsorge reduziert die Wirkung?"], solution: <p>Nach Plan isolieren, Incident melden und Reichweite samt Identitäten untersuchen; nicht unkoordiniert weiterarbeiten. Segmentierung, Least Privilege, Patches, Endpoint-Schutz und offline/immutable getestete Backups reduzieren Risiko und Auswirkung.</p> },
    takeaway: ["Malware-Kategorien können sich überschneiden.", "Erkennen, isolieren, melden und evidenzbasiert wiederherstellen.", "Backups sind Resilienz, nicht die einzige Schutzmaßnahme."],
  },
  "angriffe-und-social-engineering": {
    objectives: ["Phishing und Social Engineering erkennen", "Spoofing, Sniffing und MITM unterscheiden", "DoS/DDoS einordnen", "Exploit und Zero-Day korrekt erklären"],
    intro: <p>Angriffe zielen auf Menschen, Protokolle und Systeme. Defensive Analyse fragt: Welche Täuschung oder Schwachstelle wird genutzt, welche Wirkung droht und welche Kontrollen begrenzen sie?</p>,
    sections: [
      { title: "Täuschung und Verkehr", paragraphs: [<>Phishing versucht Zugangsdaten, Zahlungen oder Ausführung durch glaubhafte Nachrichten zu erlangen; Social Engineering umfasst weitere Manipulation von Menschen. Spoofing fälscht eine behauptete Quelle.</>, <>Sniffing beobachtet Verkehr; bei einem Man-in-the-Middle-Angriff positioniert sich ein Angreifer zwischen Kommunikationspartnern und kann Verkehr mitlesen oder verändern. Verschlüsselung plus Identitätsprüfung reduziert das Risiko.</>] },
      { title: "Verfügbarkeit und Schwachstellen", paragraphs: [<>DoS überlastet einen Dienst aus einer Quelle oder Methode, DDoS nutzt viele verteilte Systeme. Rate Limits, Filter, Kapazität und spezialisierte Schutzdienste können Wirkung begrenzen.</>, <>Ein Exploit nutzt eine Schwachstelle. Zero-Day bezeichnet eine zuvor unbekannte oder ohne verfügbaren Fix ausnutzbare Lücke im jeweiligen Kontext – nicht automatisch einen bestimmten Malware-Typ.</>] },
    ],
    visual: <TextFlow caption="Verdächtige Nachricht prüfen" steps={["nicht klicken", "Absender/Domain prüfen", "Anforderung über bekannten Kanal verifizieren", "melden", "bei Interaktion Incident-Prozess"]} />,
    scenario: { title: "Dringende MFA-Freigabe", situation: <p>Ein Anrufer gibt sich als IT aus und fordert die sofortige Bestätigung einer unerwarteten MFA-Anfrage.</p>, tasks: ["Welche Angriffsform liegt nahe?", "Wie reagierst du?"], solution: <p>Social Engineering beziehungsweise MFA-Fatigue ist wahrscheinlich. Ablehnen, Gespräch beenden, IT über einen bekannten Kanal kontaktieren und den Vorfall melden; Kontozugriffe prüfen lassen.</p> },
    takeaway: ["Dringlichkeit und Autorität sind häufige Manipulationsmittel.", "MITM umfasst aktive Zwischenposition, Sniffing zunächst Beobachtung.", "Zero-Day beschreibt eine Schwachstellenlage, keine Garantie erfolgreichen Angriffs."],
  },
  "schutzmassnahmen-und-hardening": {
    objectives: ["mehrschichtige Maßnahmen auswählen", "Least Privilege anwenden", "Hardening planen", "sichere Reaktion und Prävention verbinden"],
    intro: <p>Defense in Depth kombiniert technische, organisatorische und physische Kontrollen. Keine Einzelmaßnahme – auch keine Firewall – macht ein System allein sicher.</p>,
    sections: [
      { title: "Angriffsfläche reduzieren", paragraphs: [<>Updates und Patchmanagement priorisieren bekannte Schwachstellen. Unnötige Dienste, Ports, Konten und Standardzugänge werden deaktiviert; sichere Baselines und Konfigurationskontrolle halten den Zustand nachvollziehbar.</>, <>Firewalls beschränken Verbindungen, Netzwerksegmentierung begrenzt Bewegungen, Endpoint-Schutz erkennt Verhalten. Physische Zutrittskontrollen schützen Geräte und Konsolen.</>] },
      { title: "Identitäten und Resilienz", paragraphs: [<>Least Privilege vergibt nur nötige Rechte; getrennte Admin-Konten, MFA und passende Passwortregeln reduzieren Kontoangriffe. Gemeinsame Administratorpasswörter zerstören Zurechenbarkeit.</>, <>Verschlüsselung schützt Daten je Einsatz, Backups unterstützen Wiederherstellung. Beide benötigen Schlüssel-, Rechte-, Monitoring- und Testprozesse.</>] },
    ],
    visual: <ResponsiveTable caption="Risiko und passende Kontrollen" headers={["Risiko", "präventiv", "erkennen/reagieren"]} rows={[["unbenötigter Dienst", "deaktivieren, Firewall", "Port-/Baseline-Prüfung"], ["gestohlene Zugangsdaten", "MFA, Least Privilege", "Login-Alarme, Token sperren"], ["laterale Bewegung", "Segmentierung", "Netz-/Endpoint-Monitoring"], ["Ransomware", "Patchen, Rechte, Filter", "Isolation, Incident-Plan, Restore"]]} />,
    scenario: { title: "Neu installierter Server", situation: <p>Ein Server ist ungepatcht, mehrere ungenutzte Dienste lauschen und alle Administratoren nutzen dasselbe Passwort.</p>, tasks: ["Priorisiere fünf Maßnahmen.", "Wie wird sicherer Fernzugriff gestaltet?"], solution: <p>Inventarisieren, patchen, unnötige Dienste deaktivieren, Firewall auf Bedarf begrenzen, individuelle Least-Privilege-/Admin-Konten mit MFA einrichten. Fernzugriff über freigegebenen administrativen Pfad, bevorzugt SSH statt Telnet, mit Logging und Netzbegrenzung.</p> },
    takeaway: ["Hardening reduziert Angriffsfläche und unnötige Rechte.", "MFA ergänzt, ersetzt aber keine weiteren Kontrollen.", "Backups und Incident-Prozesse erhöhen Resilienz."],
  },
  "kryptografie-und-hashing": {
    objectives: ["Klartext und Chiffretext unterscheiden", "symmetrische und asymmetrische Verfahren vergleichen", "Hashing korrekt einordnen", "digitale Signaturen erklären"],
    intro: <p>Verschlüsselung wandelt Klartext mit Schlüssel in Chiffretext und ist mit dem passenden Schlüssel umkehrbar. Hashing erzeugt einen Einweg-Prüfwert und ist <strong>keine reversible Verschlüsselung</strong>.</p>,
    sections: [
      { title: "Zwei Verschlüsselungsmodelle", paragraphs: [<>Symmetrische Verschlüsselung nutzt denselben geheimen Schlüssel für Ver- und Entschlüsselung und ist effizient für große Datenmengen. Die sichere Schlüsselverteilung ist die zentrale Herausforderung.</>, <>Asymmetrische Kryptografie nutzt ein Schlüsselpaar. Sie unterstützt Schlüsselaustausch und Signaturen, ist rechenaufwendiger und wird in hybriden Protokollen oft mit symmetrischer Verschlüsselung kombiniert.</>] },
      { title: "Hashes und Signaturen", paragraphs: [<>Ein kryptografischer Hash bildet Daten deterministisch auf einen festen Prüfwert ab. Man vergleicht Werte; man „entschlüsselt“ einen Hash nicht. Passwörter benötigen langsame Passwort-Hashverfahren mit Salt.</>, <>Eine digitale Signatur wird mit dem privaten Schlüssel erzeugt und mit dem öffentlichen geprüft. Sie kann Integrität und Herkunftsbezug unterstützen, verschlüsselt den Inhalt aber nicht automatisch.</>], activity: <SingleChoiceCheck title="Hash oder Verschlüsselung?" question="Welche Aussage ist korrekt?" inputName="security-hash" correctOptionId="oneway" successMessage="Hashes werden verglichen, nicht entschlüsselt." options={[{ id: "decrypt", label: "Jeder Hash wird mit dem öffentlichen Schlüssel entschlüsselt.", explanation: "Hashing ist kein Verschlüsselungsverfahren." }, { id: "oneway", label: "Ein kryptografischer Hash ist als Einweg-Prüfwert gedacht.", explanation: "Richtig." }, { id: "identity", label: "Verschlüsselung beweist immer die Identität des Absenders.", explanation: "Dafür sind zusätzliche Authentisierung und Vertrauensprüfung nötig." }, { id: "plain", label: "Chiffretext ist unverschlüsselter Klartext.", explanation: "Chiffretext ist das verschlüsselte Ergebnis." }]} /> },
    ],
    visual: <ResponsiveTable caption="Kryptografische Werkzeuge" headers={["Werkzeug", "Hauptzweck", "wichtige Grenze"]} rows={[["symmetrisch", "Vertraulichkeit effizient", "gemeinsamer Schlüssel"], ["asymmetrisch", "Schlüsselaustausch/Signatur", "Vertrauen in Schlüssel nötig"], ["Hash", "Integritätsvergleich", "keine Verschlüsselung"], ["Signatur", "Integrität/Herkunftsbezug", "kein Geheimhalten"]]} />,
    scenario: { title: "Softwarepaket prüfen", situation: <p>Ein Hersteller veröffentlicht Paket, Hash und digital signierte Metadaten.</p>, tasks: ["Was zeigt der Hash?", "Was ergänzt die Signatur?"], solution: <p>Der Hash zeigt bei vertrauenswürdigem Vergleich, ob die Bytes übereinstimmen. Die gültige Signatur bindet Integrität an einen geprüften privaten Schlüssel; der öffentliche Schlüssel beziehungsweise Zertifikatspfad muss vertrauenswürdig bezogen werden.</p> },
    takeaway: ["Verschlüsselung ist mit Schlüssel umkehrbar, Hashing nicht.", "Hybride Verfahren kombinieren Stärken.", "Signaturen brauchen vertrauenswürdige Schlüsselzuordnung."],
  },
  "zertifikate-tls-und-sichere-administration": {
    objectives: ["Zertifikate und CA erklären", "TLS/HTTPS korrekt bewerten", "SSH und Telnet unterscheiden", "Identität und Verschlüsselung getrennt prüfen"],
    intro: <p>Für sichere Administration greifen Kryptografie, Identitätsprüfung und restriktiver Zugriff ineinander. Die ausführliche HTTPS-/Zertifikatsvalidierung besitzt bereits eine eigene Lektion im Webserver-Modul; hier ordnen wir sie in sichere Administrationswege ein.</p>,
    sections: [
      { title: "TLS im Administrationspfad einordnen", paragraphs: [<>TLS schützt Transportvertraulichkeit und -integrität. Ein Zertifikat bindet einen öffentlichen Schlüssel an geprüfte Angaben; eine Certificate Authority (CA) bestätigt diese Bindung im jeweiligen Vertrauensmodell.</>, <><strong>HTTPS beweist nicht, dass eine Website geschäftlich vertrauenswürdig ist.</strong> Auch eine Phishing-Domain kann ein gültiges Zertifikat besitzen. Für Details zu Kette, Hostname und Gültigkeit verweist diese Lektion bewusst auf „HTTPS und TLS-Grundlagen“ statt den Stoff zu duplizieren.</>] },
      { title: "SSH statt Telnet – und Zugriff begrenzen", paragraphs: [<>Telnet überträgt Sitzungsdaten einschließlich Anmeldedaten typischerweise unverschlüsselt. SSH schützt Transport und Serverauthentisierung; Hostschlüssel müssen beim ersten Kontakt über einen vertrauenswürdigen Kanal geprüft werden.</>, <>Der administrative Dienst sollte nur aus vorgesehenen Netzen erreichbar sein. Individuelle Admin-Konten, MFA wo unterstützt, Least Privilege und Protokollierung ergänzen den geschützten Transport.</>, <>Verschlüsselung allein beweist keine Identität. Falsche Schlüsselannahme oder kompromittierte Endpunkte können eine verschlüsselte Verbindung trotzdem unsicher machen.</>] },
    ],
    visual: <TextFlow caption="Sicherer administrativer Zugriff" steps={["freigegebener Admin-Pfad", "Hostidentität prüfen", "SSH/TLS schützen Transport", "individuell authentisieren", "Rechte/Protokolle begrenzen"]} />,
    scenario: { title: "Admin-Portal mit falscher Domain", situation: <p>Eine angebliche Verwaltungsseite nutzt HTTPS, die Domain weicht aber leicht vom dokumentierten Administrationsnamen ab.</p>, tasks: ["Was bestätigt TLS?", "Welche Admin-Kontrollen fehlen noch?"], solution: <p>TLS kann den Transport zur im Zertifikat genannten Domain schützen, beweist aber nicht den erwarteten Betreiber. Nicht anmelden, Domain und Zertifikat über dokumentierte Wege prüfen und melden. Danach bleiben MFA, individuelle Konten, Netzbegrenzung und Least Privilege erforderlich.</p> },
    takeaway: ["TLS/SSH schützen Transport nur mit korrekter Identitätsprüfung.", "HTTPS beweist keine vertrauenswürdige Geschäftsabsicht.", "Sichere Administration kombiniert geschützte Protokolle, begrenzte Erreichbarkeit und individuelle Rechte."],
  },
};

export function SecurityLesson({ lessonSlug }: { lessonSlug: string }) {
  const lesson = lessons[lessonSlug];
  if (!lesson) return null;
  const relatedLinks = lessonSlug === "zertifikate-tls-und-sichere-administration"
    ? [{ href: "/lernen/webserver-grundlagen/https-und-tls", label: "Webserver: HTTPS, TLS und Zertifikatsprüfung im Detail" }]
    : [];
  return <FundamentalsLesson lessonId={`security-${lessonSlug}`} {...lesson} relatedLinks={relatedLinks}>{lesson.visual}</FundamentalsLesson>;
}
