import type { ReactNode } from "react";
import { FundamentalsLesson, ResponsiveTable, TextFlow, type LessonSection } from "./fundamentals-lesson-elements";
import { SingleChoiceCheck } from "./single-choice-check";

type LessonContent = { objectives: readonly string[]; intro: ReactNode; sections: readonly LessonSection[]; visual?: ReactNode; scenario: { title: string; situation: ReactNode; tasks: readonly ReactNode[]; solution: ReactNode }; takeaway: readonly ReactNode[]; relatedLinks?: readonly { href: string; label: string }[] };

const lessons: Record<string, LessonContent> = {
  "softwarearten-und-geschaeftsanwendungen": {
    objectives: ["System- und Anwendungssoftware unterscheiden", "Standard-, Individual- und Branchensoftware einordnen", "ERP, CRM, CMS und DMS nach Zweck unterscheiden"],
    intro: <p>Software wird nach Aufgabe und Zielgruppe eingeordnet. Kategorien helfen bei der Anforderungsanalyse, ersetzen aber keine Prüfung des konkreten Produkts.</p>,
    sections: [
      { title: "System- und Anwendungssoftware", paragraphs: [<>Systemsoftware stellt grundlegende Funktionen für Hardware und Anwendungen bereit, etwa Betriebssystem, Treiber oder systemnahe Werkzeuge. Anwendungssoftware unterstützt fachliche Aufgaben wie Buchhaltung, Textverarbeitung oder Ticketbearbeitung.</>, <>Standardsoftware richtet sich an viele Nutzer mit ähnlichen Anforderungen. Individualsoftware wird für einen konkreten Bedarf entwickelt; Branchensoftware bündelt typische Abläufe einer Branche. Eine Lösung kann mehrere Merkmale verbinden.</>], activity: <SingleChoiceCheck title="Softwareklasse wählen" question="Welche Zuordnung passt am besten zu einem Betriebssystem?" inputName="software-category" correctOptionId="system" successMessage="Ein Betriebssystem ist grundlegende Systemsoftware." options={[{id:"system",label:"Systemsoftware",explanation:"Richtig."},{id:"crm",label:"CRM",explanation:"CRM unterstützt Kundenbeziehungen."},{id:"dms",label:"DMS",explanation:"Ein DMS verwaltet Dokumente."},{id:"individual",label:"zwingend Individualsoftware",explanation:"Betriebssysteme können Standardsoftware sein."}]} /> },
      { title: "Geschäftsanwendungen nach Zweck", paragraphs: [<>ERP integriert betriebliche Ressourcen und Prozesse, CRM unterstützt Kundenbeziehungen, CMS verwaltet veröffentlichte Inhalte und DMS organisiert Dokumente samt Ablage, Suche und Lebenszyklus.</>, <>Die Kürzel beschreiben Schwerpunkte, keine starren Produktgrenzen. Ein System kann Funktionen mehrerer Bereiche enthalten; entscheidend sind Anforderungen, Datenflüsse und Verantwortlichkeiten.</>] },
    ],
    visual: <ResponsiveTable caption="Typische Geschäftsanwendungen" headers={["Klasse", "Hauptzweck", "Beispielaufgabe"]} rows={[["ERP","integrierte Unternehmensressourcen/-prozesse","Auftrag, Bestand und Buchung verbinden"],["CRM","Kundenbeziehungen","Kontakte und Vertriebsaktivitäten pflegen"],["CMS","digitale Inhalte","Webinhalte redaktionell veröffentlichen"],["DMS","Dokumente","Dokumente versionieren, finden und aufbewahren"]]} />,
    scenario: { title: "Vier Anforderungen", situation: <p>Ein Betrieb möchte Lagerbestände verbinden, Kundenkontakte dokumentieren, Website-Inhalte pflegen und Rechnungen revisionsgeeignet auffindbar halten.</p>, tasks: ["Ordne jedem Bedarf eine passende Anwendungsklasse zu.", "Welche Schnittstellen zwischen den Systemen könnten wichtig sein?"], solution: <p>ERP passt zu Lager/Prozessintegration, CRM zu Kontakten, CMS zu Website-Inhalten und DMS zur Dokumentenverwaltung. Kunden-, Auftrags- und Dokumentreferenzen benötigen abgestimmte Schnittstellen und Zuständigkeiten.</p> },
    takeaway: ["Softwareklassen beschreiben Zwecke.", "Standard, individuell und branchenspezifisch sind keine Qualitätsurteile.", "Produktgrenzen können sich überschneiden."],
  },
  "software-auswaehlen": {
    objectives: ["Auswahlkriterien aus Anforderungen ableiten", "Kompatibilität und Interoperabilität unterscheiden", "Betrieb, Sicherheit, Datenschutz und Lebenszyklus einbeziehen"],
    intro: <p>Eine belastbare Auswahl beginnt mit messbaren Anforderungen und nicht mit einem vertrauten Produktnamen.</p>,
    sections: [
      { title: "Funktionale und nicht-funktionale Passung", paragraphs: [<>Funktionale Kriterien beschreiben benötigte Aufgaben. Nicht-funktionale Kriterien betreffen etwa Bedienbarkeit, Barrierefreiheit, Leistung, Skalierung, Wartbarkeit, Sicherheit und Datenschutz.</>, <>Kompatibilität fragt, ob Software auf der vorgesehenen Plattform und mit vorhandenen Formaten funktioniert. Interoperabilität fragt, ob verschiedene Systeme kontrolliert Daten und Funktionen austauschen können.</>], activity: <SingleChoiceCheck title="Auswahlkriterium erkennen" question="Eine Anwendung muss per dokumentierter API Kundendaten mit dem ERP austauschen. Welches Kriterium steht im Vordergrund?" inputName="software-selection" correctOptionId="interop" successMessage="Der geregelte Austausch zwischen Systemen ist Interoperabilität." options={[{id:"interop",label:"Interoperabilität",explanation:"Richtig."},{id:"color",label:"Farbgestaltung",explanation:"Das beschreibt nicht den Systemaustausch."},{id:"ownership",label:"Eigentumsübergang",explanation:"Das ist kein technisches Integrationskriterium."},{id:"clock",label:"CPU-Takt allein",explanation:"Ein Einzelwert belegt keine Schnittstelle."}]} /> },
      { title: "Lebenszyklus statt Momentaufnahme", paragraphs: [<>Prüfe unterstützte Plattformen, Update- und Supportzeitraum, Migrationsweg, Datenexport, Administrationsaufwand, Kompetenzen und Herstellerabhängigkeit. Ein Pilot liefert Evidenz für reale Arbeitsabläufe.</>, <>Kosten und Lizenzierung gehören in denselben Vergleich, werden aber im bestehenden Wirtschaftsmodul mit TCO, Angebotsvergleich und Nutzwertanalyse vertieft.</>] },
    ],
    visual: <TextFlow caption="Anforderungsbasierte Auswahl" steps={["Bedarf klären", "Muss/Kann definieren", "Marktoptionen prüfen", "Pilot und Risiken", "TCO/Nutzwert", "begründete Entscheidung"]} />,
    scenario: { title: "DMS für 30 Mitarbeitende", situation: <p>Gesucht werden Volltextsuche, rollenbasierter Zugriff, barrierearme Bedienung, ERP-Schnittstelle, dokumentierter Export und fünf Jahre Support.</p>, tasks: ["Welche Kriterien sind funktional, welche nicht-funktional?", "Welche Evidenz sollte ein Pilot liefern?"], solution: <p>Suche und ERP-Austausch sind Funktionen; Zugänglichkeit, Sicherheit, Wartbarkeit und Support sind nicht-funktionale Anforderungen. Der Pilot prüft echte Rollen, Dokumente, Schnittstellen, Export und Bedienhilfen.</p> },
    takeaway: ["Anforderungen steuern die Auswahl.", "Kompatibilität und Interoperabilität sind verschieden.", "Pilot, Lebenszyklus, Risiken und Kosten gehören zusammen."],
    relatedLinks: [{href:"/lernen/wirtschaftlichkeit-und-beschaffung/beschaffung-und-angebotsvergleich",label:"Wirtschaftlichkeit: Angebote vergleichen"},{href:"/lernen/arbeitsplatz-hardware/arbeitsplatz-auswaehlen",label:"Hardware: Arbeitsplatz auswählen"}],
  },
  "open-source-und-proprietaer": {
    objectives: ["Open Source anhand von Lizenzrechten einordnen", "proprietäre Software neutral beschreiben", "Kosten, Sicherheit und Support nicht aus dem Modell ableiten"],
    intro: <p>Open Source und proprietär beschreiben vor allem Zugang zum Quellcode und eingeräumte Nutzungsrechte. Daraus folgt kein automatisches Urteil über Preis, Qualität oder Eignung.</p>,
    sections: [
      { title: "Quelloffen heißt lizenziert", paragraphs: [<>Open-Source-Software bleibt urheberrechtlich geschützt. Die jeweilige Lizenz erlaubt bestimmte Nutzungen, Änderungen und Weitergaben unter Bedingungen. Betrieb, Schulung oder Support können kostenpflichtig sein.</>, <>GPL ist eine Copyleft-Lizenz mit Bedingungen bei Weitergabe abgeleiteter Werke; LGPL ist bei Bibliotheken in bestimmten Konstellationen weniger weitreichend; MIT ist permissiv und verlangt insbesondere den Erhalt von Copyright- und Lizenzhinweisen. Das ist Orientierung, keine Auslegung eines konkreten Lizenztexts.</>] },
      { title: "Proprietär ohne Pauschalurteil", paragraphs: [<>Bei proprietärer Software behält der Rechteinhaber typischerweise stärkere Kontrolle über Quellcode und Nutzung. Sie kann bezahlt, kostenlos bereitgestellt, lokal oder als Cloud-Dienst angeboten werden.</>, <>Weder Modell garantiert Sicherheit noch Support. Prüfe Pflegeprozess, Schwachstellenreaktion, Vertrag, Community/Anbieter, Kompetenzen und Exit-Fähigkeit.</>], activity: <SingleChoiceCheck title="Aussage prüfen" question="Welche Aussage ist korrekt?" inputName="software-open-source" correctOptionId="terms" successMessage="Auch Open Source wird unter konkreten Lizenzbedingungen genutzt." options={[{id:"free",label:"Open Source ist immer kostenlos.",explanation:"Services, Betrieb oder Distribution können Kosten erzeugen."},{id:"no-copyright",label:"Open Source hat kein Urheberrecht.",explanation:"Urheberrecht und Lizenzbedingungen bleiben relevant."},{id:"terms",label:"Open Source gewährt Rechte unter Lizenzbedingungen.",explanation:"Richtig."},{id:"paid",label:"Proprietäre Software ist immer kostenpflichtig.",explanation:"Auch kostenlose proprietäre Angebote existieren."}]} /> },
    ],
    visual: <ResponsiveTable caption="Sachlicher Vergleich" headers={["Aspekt", "Open Source", "proprietär"]} rows={[["Quellcode","gemäß Lizenz zugänglich","typischerweise nicht allgemein zugänglich"],["Kosten","nicht automatisch null","nicht automatisch kostenpflichtig"],["Sicherheit","abhängig von Projekt und Betrieb","abhängig von Anbieter und Betrieb"],["Support","Community und/oder Vertrag","Anbieter/Partner und/oder Vertrag"]]} />,
    scenario: { title: "Bibliothek auswählen", situation: <p>Ein Team möchte eine Bibliothek in einem verteilten Produkt verwenden und findet Varianten unter GPL, LGPL und MIT.</p>, tasks: ["Welche Information reicht noch nicht für die Entscheidung?", "Wer sollte bei Unsicherheit beteiligt werden?"], solution: <p>Lizenzname allein ersetzt nicht die Prüfung von Nutzungsart, Änderung, Kopplung und Weitergabe. Verantwortliche für Architektur, Lizenz-Compliance beziehungsweise Recht werden früh beteiligt.</p> },
    takeaway: ["Open Source bedeutet nicht rechtefrei oder automatisch kostenlos.", "Proprietär bedeutet nicht automatisch bezahlt oder besser unterstützt.", "Der konkrete Lizenztext und Nutzungskontext entscheiden."],
  },
  "lizenzmodelle-und-nutzungsrechte": {
    objectives: ["Lizenz und Eigentum unterscheiden", "Nutzer-, Geräte- und Concurrent-Modelle anwenden", "Abonnement, dauerhaft, Pay-per-Use und Freemium einordnen"],
    intro: <p>Eine Softwarelizenz beschreibt eingeräumte Nutzungsrechte und Bedingungen. Der Kauf eines Datenträgers oder Geräts überträgt nicht automatisch das Urheberrecht an der Software.</p>,
    sections: [
      { title: "Bezugsgröße verstehen", paragraphs: [<>Named User bindet Berechtigungen an benannte Personen, Concurrent User begrenzt typischerweise gleichzeitige Nutzung und gerätebasierte Lizenzierung knüpft an Geräte. OEM-Rechte sind häufig an konkrete Vertrags- oder Hardwarebedingungen gebunden.</>, <>Eine EULA formuliert Nutzungsbedingungen des Anbieters. Ob und wie sie wirksam einbezogen ist, wird im realen Fall fachkundig geprüft; diese Lektion vermittelt keine Rechtsberatung.</>], activity: <SingleChoiceCheck title="30 Personen, 10 gleichzeitig" question="Welches Modell bildet eine Anforderung von höchstens zehn gleichzeitigen Nutzern am direktesten ab?" inputName="software-license-basis" correctOptionId="concurrent" successMessage="Concurrent User bezieht sich auf gleichzeitige Nutzung." options={[{id:"named",label:"30 Named User",explanation:"Das kann passen, bildet aber die Gleichzeitigkeit nicht direkt ab."},{id:"concurrent",label:"10 Concurrent User",explanation:"Richtig, sofern die konkreten Bedingungen dies erlauben."},{id:"device",label:"eine Gerätelizenz",explanation:"Ein Gerät reicht für mehrere Arbeitsplätze nicht automatisch."},{id:"none",label:"keine Lizenz",explanation:"Nutzungsrechte bleiben nötig."}]} /> },
      { title: "Zeit- und Verbrauchsmodelle", paragraphs: [<>Ein Abonnement gewährt Nutzung für einen Zeitraum nach Vertrag; eine dauerhafte Lizenz gewährt ein zeitlich nicht als Abonnement begrenztes Nutzungsrecht, aber nicht automatisch Updates oder Support für immer.</>, <>Pay-per-Use rechnet Nutzung ab. Freemium bietet eine begrenzte kostenlose Stufe und kostenpflichtige Erweiterungen. Kostenmodell und Nutzungsrecht müssen getrennt geprüft werden.</>] },
    ],
    visual: <ResponsiveTable caption="Lizenzmodelle einordnen" headers={["Modell", "Bezugsgröße", "Prüffrage"]} rows={[["Named User","benannte Person","dürfen Konten geteilt werden?"],["Concurrent User","gleichzeitige Nutzung","wie wird Gleichzeitigkeit gemessen?"],["Device","Gerät","welche Installationen/Clients zählen?"],["Subscription","Zeitraum","was endet mit dem Abonnement?"],["Perpetual","dauerhaftes Nutzungsrecht","welche Version, Updates und Pflege?"],["Pay-per-Use","Verbrauch","welche Einheit wird gemessen?"]]} />,
    scenario: { title: "Neue Fachanwendung", situation: <p>30 Beschäftigte greifen wechselnd von 20 Geräten zu; höchstens zehn arbeiten gleichzeitig. Außendienst und Schichtwechsel sind relevant.</p>, tasks: ["Welche Modelle sind vergleichenswert?", "Welche Vertragsdetails müssen vor der Wahl geklärt werden?"], solution: <p>Concurrent kann passen; Named User oder Gerätevarianten bleiben Vergleichsoptionen. Zählweise, Mehrfachgeräte, Offline-Nutzung, Kontoteilung, Spitzenlast, Audit und Skalierung müssen vertraglich geklärt werden.</p> },
    takeaway: ["Lizenz ist Nutzungsrecht, nicht Eigentum am Werk.", "Bezugsgröße und reale Nutzung müssen zusammenpassen.", "Dauerhafte Lizenz garantiert nicht automatisch ewige Updates."],
  },
  "lizenzszenarien-pruefen": {
    objectives: ["Lizenzbedarf aus Nutzung ableiten", "Fehlzuordnungen erkennen", "Abonnement und dauerhafte Lizenz über den Lebenszyklus vergleichen"],
    intro: <p>Lizenz-Compliance beginnt mit einer belastbaren Inventur: Wer nutzt was, auf welchen Geräten, wie gleichzeitig und in welchem Vertragsrahmen?</p>,
    sections: [
      { title: "Nutzung und Bestand abgleichen", paragraphs: [<>Installation, zugewiesenes Konto und tatsächliche Nutzung können unterschiedliche Zählgrößen sein. Deshalb werden Vertrag, Bestellungen, Portalzuweisungen, Inventar und technische Nutzungshinweise abgestimmt.</>, <>Ein einzelner Produktschlüssel für beliebig viele Geräte ist kein plausibler Standard. Ebenso beweist eine deinstallierte Anwendung allein nicht, dass jede Zuweisung oder Cloud-Berechtigung beendet ist.</>], activity: <SingleChoiceCheck title="Mismatch erkennen" question="Eine Named-User-Lizenz ist auf ein geteiltes Teamkonto für zwölf Personen registriert. Was ist der richtige nächste Schritt?" inputName="software-license-mismatch" correctOptionId="check" successMessage="Nutzung und konkrete Bedingungen müssen geprüft und korrekt zugeordnet werden." options={[{id:"ignore",label:"Ignorieren, weil nur ein Konto existiert.",explanation:"Die reale Nutzung kann den Bedingungen widersprechen."},{id:"check",label:"Vertrag prüfen und persönliche beziehungsweise passende Rechte zuordnen.",explanation:"Richtig."},{id:"rename",label:"Das Konto nur umbenennen.",explanation:"Ein Name ändert die Nutzungsweise nicht."},{id:"publish",label:"Den Schlüssel öffentlich dokumentieren.",explanation:"Lizenzschlüssel sind schützenswerte Informationen."}]} /> },
      { title: "Varianten transparent vergleichen", paragraphs: [<>Abonnement und dauerhafte Lizenz werden für denselben Zeitraum, Funktionsumfang, Nutzerbestand, Updates, Support und Exit verglichen. Kurzfristig niedrige Raten beweisen keine niedrigeren TCO.</>, <>Ändert sich der Bedarf stark, können skalierbare Modelle nützlich sein; zugleich zählen Preisrisiko, Anbieterabhängigkeit, Datenexport und Betriebsunterbrechung.</>] },
    ],
    visual: <TextFlow caption="Lizenzprüfung" steps={["Nutzung erfassen", "Vertrag/Entitlement", "Zählregel anwenden", "Abweichung dokumentieren", "Korrektur und Nachweis"]} />,
    scenario: { title: "Mehrgeräte-Nutzung", situation: <p>Zehn Beschäftigte nutzen je Notebook und Smartphone. Das Angebot nennt entweder 10 Named User oder 20 Device-Lizenzen.</p>, tasks: ["Welche Variante könnte passen?", "Warum darf die Entscheidung nicht nur auf der Anzahl beruhen?"], solution: <p>Named User kann Mehrgeräte-Nutzung abdecken, wenn die Bedingungen dies erlauben; Device zählt Geräte. Funktionsumfang, zulässige Geräte, Offline-Nutzung, Kosten und Wachstum müssen geprüft werden.</p> },
    takeaway: ["Vertragliche Zählregel schlägt Vermutung.", "Inventar und Berechtigung werden gemeinsam geprüft.", "TCO und Exit gehören zum Lizenzvergleich."],
    relatedLinks: [{href:"/lernen/wirtschaftlichkeit-und-beschaffung/tco-und-amortisation",label:"Wirtschaftlichkeit: TCO und Amortisation"}],
  },
  "ki-gestuetzte-software": {
    objectives: ["generative und nicht-generative KI-Funktionen unterscheiden", "Ausgaben verifizieren", "Datenschutz, Geheimhaltung und Rechte vor Nutzung prüfen"],
    intro: <p>KI kann Bestandteil lokaler Software oder eines Dienstes sein. Sie liefert Wahrscheinlichkeits- oder Musterergebnisse, keine automatische Garantie für Wahrheit, Rechtmäßigkeit oder Eignung.</p>,
    sections: [
      { title: "Generieren und klassifizieren", paragraphs: [<>Generative Systeme erzeugen etwa Text, Code oder Bilder. Nicht-generative Verfahren können beispielsweise Spam klassifizieren oder Anomalien erkennen. Die konkrete Funktion, Datenbasis und Fehlerart müssen zum Einsatz passen.</>, <>Generierte Ausgaben können plausibel klingen und trotzdem falsch, unvollständig oder erfunden sein. Verantwortliche prüfen Fakten, Rechenwege, Quellen, Sicherheit und fachliche Freigabe.</>], activity: <SingleChoiceCheck title="KI-Ausgabe behandeln" question="Ein Assistent erzeugt eine überzeugende, aber unbelegte Firewallregel. Was ist angemessen?" inputName="software-ai-verification" correctOptionId="verify" successMessage="Ausgaben müssen gegen Anforderungen, Dokumentation und sichere Tests geprüft werden." options={[{id:"apply",label:"Direkt produktiv anwenden.",explanation:"Plausibilität ist kein Nachweis."},{id:"verify",label:"Fachlich prüfen und kontrolliert testen.",explanation:"Richtig."},{id:"secret",label:"Zusätzlich Zugangsdaten eingeben.",explanation:"Geheimnisse dürfen nicht unkontrolliert übertragen werden."},{id:"truth",label:"Als wahr behandeln, weil sie flüssig formuliert ist.",explanation:"Formulierung belegt keine Richtigkeit."}]} /> },
      { title: "Daten und Rechte vorab klären", paragraphs: [<>Vertrauliche Firmen-, Kunden- oder Personendaten werden nur in dafür freigegebenen Systemen und mit geklärtem Zweck verarbeitet. Speicherung, Training, Übermittlung, Löschung und Zugriffsrechte gehören in die Bewertung.</>, <>Bei Ein- und Ausgaben können Lizenz-, Urheber- und Nutzungsfragen offen oder kontextabhängig sein. Unsicherheit wird dokumentiert und an zuständige Stellen gegeben, statt pauschal gelöst zu behaupten.</>] },
    ],
    visual: <ResponsiveTable caption="Prüffragen vor KI-Nutzung" headers={["Bereich", "Prüffrage"]} rows={[["Fachlichkeit","Wie wird die Ausgabe verifiziert?"],["Daten","Welche Informationen verlassen welchen Schutzbereich?"],["Sicherheit","Darf erzeugter Code/Befehl kontrolliert getestet werden?"],["Rechte","Sind Ein- und Ausgabe für den Zweck nutzbar?"],["Verantwortung","Wer entscheidet und dokumentiert?"]]} />,
    scenario: { title: "Support-Zusammenfassung", situation: <p>Ein Cloud-Assistent soll ein Ticket mit Kundennamen, IP-Adressen, Logauszug und internem Passwort zusammenfassen.</p>, tasks: ["Welche Daten sind problematisch?", "Wie kann der Bedarf sicherer gelöst werden?"], solution: <p>Passwort darf nicht eingegeben werden; Personen- und Betriebsdaten brauchen Freigabe und Zweckprüfung. Geheimnisse entfernen, Daten minimieren beziehungsweise pseudonymisieren und nur einen freigegebenen Dienst nutzen; Ergebnis fachlich prüfen.</p> },
    takeaway: ["KI ist eine Software-/Dienstfähigkeit, keine Wahrheitsmaschine.", "Vertrauliche Daten gehören nur in freigegebene Verarbeitung.", "Ausgaben und Rechte werden geprüft."],
    relatedLinks: [{href:"/lernen/it-sicherheit/begriffe-und-schutzziele",label:"IT-Sicherheit: Schutzziele"},{href:"/lernen/datenschutz/datenschutzgrundsaetze",label:"Datenschutz: Grundsätze"}],
  },
};

export function SoftwareLicensingLesson({ lessonSlug }: { lessonSlug: string }) {
  const lesson = lessons[lessonSlug];
  if (!lesson) return null;
  return <FundamentalsLesson lessonId={`software-${lessonSlug}`} {...lesson} relatedLinks={lesson.relatedLinks}>{lesson.visual}</FundamentalsLesson>;
}
