import { LearningObjectives } from "./learning-objectives";
import { AddressCountCheck } from "./subnet-lesson-checks";
import { SubnetReferenceVisualization } from "./subnet-reference-visualization";

export function SubnetLessonThree() {
  return <div className="space-y-10 text-base leading-7 text-slate-700 sm:text-lg sm:leading-8">
    <LearningObjectives context="lesson" objectives={["Hostbits aus einer Präfixlänge bestimmen", "die Gesamtzahl der Adressen mit 2^Hostbits berechnen", "gewöhnliche Hostadressen in traditionellen Subnetzen bestimmen", "die Blockgröße aus dem relevanten Maskenoktett ableiten", "Gesamtadressen, Hostadressen und Blockgröße unterscheiden"]} />

    <section aria-labelledby="hostbits-heading"><h2 id="hostbits-heading" className="text-2xl font-bold tracking-tight text-slate-950">Vom Präfix zu den Adressen</h2><p className="mt-4">Eine IPv4-Adresse hat immer 32 Bit. Die Präfixlänge nennt die Netzbits; der Rest sind Hostbits.</p><div className="mt-5 grid gap-3 sm:grid-cols-2"><Formula title="Hostbits" formula="32 − Präfixlänge" /><Formula title="Adressen gesamt" formula="2^Hostbits" /></div><ul className="mt-5 grid gap-3 sm:grid-cols-2">{[[24,8,256],[25,7,128],[26,6,64],[27,5,32],[28,4,16]].map(([prefix,bits,total]) => <li key={prefix} className="rounded-xl border border-slate-200 bg-white p-4"><code className="font-bold text-blue-950">/{prefix}</code><span> → {bits} Hostbits → </span><code>2^{bits} = {total}</code></li>)}</ul></section>

    <section aria-labelledby="hosts-heading"><h2 id="hosts-heading" className="text-2xl font-bold tracking-tight text-slate-950">Gewöhnliche Hostadressen</h2><p className="mt-4">In einem konventionellen IPv4-Subnetz sind die erste Adresse die Netzadresse und die letzte die Broadcast-Adresse. Für gewöhnliche Hosts bleiben daher typischerweise <code>Gesamtadressen − 2</code>: Ein <code>/26</code> enthält 64 Adressen, davon 62 gewöhnliche Hostadressen.</p><aside className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-slate-900"><strong>Präzisionshinweis:</strong> <code>2^Hostbits − 2</code> ist keine universelle Regel für alle IPv4-Präfixe. <code>/31</code> und <code>/32</code> haben besondere Semantik und werden hier nicht berechnet.</aside></section>

    <section aria-labelledby="block-heading"><h2 id="block-heading" className="text-2xl font-bold tracking-tight text-slate-950">Was bedeutet Blockgröße?</h2><p className="mt-4">Die Blockgröße ist der Abstand möglicher Subnetzgrenzen im <strong>relevanten Maskenoktett</strong> – dem Oktett, in dem die Netz-/Host-Grenze liegt. Für die hier betrachteten Präfixe ist das das vierte Oktett.</p><p className="mt-4 rounded-xl bg-blue-950 p-4 text-center font-bold text-white"><code>Blockgröße = 256 − Maskenwert</code></p><dl className="mt-5 grid gap-3 sm:grid-cols-2">{[[25,128,128],[26,192,64],[27,224,32],[28,240,16]].map(([prefix,mask,size]) => <div key={prefix} className="rounded-xl border border-slate-200 bg-white p-4"><dt><code className="font-bold text-blue-950">/{prefix}</code> · Maskenoktett {mask}</dt><dd className="mt-1"><code>256 − {mask} = {size}</code></dd></div>)}</dl><p className="mt-5">Eine Blockgröße von 64 bedeutet: Mögliche Grenzen treten im relevanten Oktett in 64er-Schritten auf. Die vollständigen Bereiche berechnest du erst in Lektion 4.</p><SubnetReferenceVisualization /></section>

    <AddressCountCheck />

    <section aria-labelledby="l3-misconceptions"><h2 id="l3-misconceptions" className="text-2xl font-bold tracking-tight text-slate-950">Typische Denkfehler</h2><dl className="mt-5 space-y-4"><Mistake wrong="/26 bedeutet 26 Hosts." correction="26 ist die Präfixlänge: Es gibt 26 Netzbits und 6 Hostbits." /><Mistake wrong="Ein /26 hat 26 Adressen." correction="6 Hostbits ergeben 2^6 = 64 Gesamtadressen." /><Mistake wrong="Blockgröße und Hostanzahl sind dasselbe." correction="Die Blockgröße beschreibt den Abstand der Subnetzgrenzen; die Hostanzahl zählt gewöhnlich zuweisbare Hostadressen." /><Mistake wrong="Man zieht bei jedem IPv4-Netz immer zwei Adressen ab." correction="Das beschreibt traditionelle Netz-/Broadcast-Semantik, gilt aber nicht universell für besondere Präfixe." /></dl></section>

    <section aria-labelledby="l3-practice"><h2 id="l3-practice" className="text-2xl font-bold tracking-tight text-slate-950">Kurz üben</h2><ul className="mt-4 list-disc space-y-2 pl-6"><li>Wie viele Adressen enthält ein <code>/27</code>? <strong>32</strong></li><li>Wie viele Hostbits bleiben bei <code>/28</code>? <strong>4</strong></li><li>Welche Blockgröße gehört zu <code>255.255.255.192</code>? <strong>64</strong></li></ul></section>
    <section aria-labelledby="l4-preview" className="rounded-2xl border border-slate-200 bg-slate-50 p-5 sm:p-6"><p className="text-sm font-semibold text-blue-700">Nächste Lektion</p><h2 id="l4-preview" className="mt-1 text-xl font-bold text-slate-950">Netzbereiche bestimmen</h2><p className="mt-3 text-sm leading-6">Dort nutzt du die Blockgröße, um Subnetzgrenzen sowie Netz-, Host- und Broadcast-Adressen vollständig zu bestimmen.</p></section>
  </div>;
}

function Formula({ title, formula }: { title: string; formula: string }) { return <div className="rounded-xl border border-blue-200 bg-blue-50 p-5"><p className="text-sm font-semibold text-blue-800">{title}</p><code className="mt-2 block text-lg font-bold text-blue-950">{formula}</code></div>; }
function Mistake({ wrong, correction }: { wrong: string; correction: string }) { return <div className="rounded-xl border border-slate-200 bg-white p-4"><dt className="font-bold text-slate-950">Falsch: „{wrong}“</dt><dd className="mt-2 text-sm leading-6"><strong>Korrektur:</strong> {correction}</dd></div>; }
