import { FiliusConfigurationCheck } from "./filius-configuration-check";
import { LearningObjectives } from "./learning-objectives";

const devices = [
  ["PC-A1", "Client in Subnetz A", "192.168.10.10/26", "192.168.10.0/26", "192.168.10.1"],
  ["PC-A2", "Client in Subnetz A", "192.168.10.20/26", "192.168.10.0/26", "192.168.10.1"],
  ["Router", "Schnittstelle A", "192.168.10.1/26", "192.168.10.0/26", "—"],
  ["Router", "Schnittstelle B", "192.168.10.65/26", "192.168.10.64/26", "—"],
  ["PC-B1", "Client in Subnetz B", "192.168.10.70/26", "192.168.10.64/26", "192.168.10.65"],
  ["PC-B2", "Client in Subnetz B", "192.168.10.80/26", "192.168.10.64/26", "192.168.10.65"],
] as const;

export function SubnetLessonSix() {
  return <div className="space-y-10 text-base leading-7 text-slate-700 sm:text-lg sm:leading-8">
    <LearningObjectives context="lesson" objectives={["einen Subnetzplan in Gerätekonfigurationen übertragen", "gültige Hostadressen vergeben und Netz- sowie Broadcast-Adressen vermeiden", "Subnetzzugehörigkeit und die Notwendigkeit von Routing erklären", "eine einfache Layer-3-Verbindung in Filius konfigurieren", "Kommunikation systematisch testen und typische Konfigurationsfehler erkennen", "Beobachtungen mit berechneten Netzbereichen vergleichen und den Adressplan dokumentieren"]} />

    <section aria-labelledby="scenario-heading"><p className="text-sm font-semibold text-blue-700">Praxisauftrag</p><h2 id="scenario-heading" className="mt-1 text-2xl font-bold tracking-tight text-slate-950">Zwei Firmennetze aus einem /24 planen</h2><p className="mt-4">Die fiktive Firma Nordwerk erhält den Block <code>192.168.10.0/24</code>. Zwei getrennte Netze sollen jeweils bis zu 50 gewöhnliche Hosts aufnehmen. Dafür verwendest du zwei <code>/26</code>-Subnetze. Der verbleibende Teil des ursprünglichen <code>/24</code> bleibt in dieser Lehrübung bewusst ungenutzt; dies ist kein optimierter Produktionsentwurf.</p></section>

    <Phase number="1" title="Planung"><p>Rechne zuerst auf Papier: Präfix, Maske, Blockgröße, Netzadresse, Broadcast und gewöhnlicher Hostbereich beider Netze. Prüfe danach deine Lösung.</p><details className="mt-5 rounded-xl border border-slate-200 bg-white p-4"><summary className="cursor-pointer font-bold text-slate-950 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-blue-600">Planungslösung anzeigen</summary><div className="mt-4 grid gap-4 sm:grid-cols-2"><SubnetCard name="Subnetz A" network="192.168.10.0/26" range="192.168.10.1–192.168.10.62" broadcast="192.168.10.63" /><SubnetCard name="Subnetz B" network="192.168.10.64/26" range="192.168.10.65–192.168.10.126" broadcast="192.168.10.127" /></div><p className="mt-4 text-sm">Für beide gilt: Maske <code>255.255.255.192</code>, 6 Hostbits, Blockgröße 64, 64 Gesamtadressen und traditionell 62 gewöhnliche Hostadressen.</p></details></Phase>

    <section aria-labelledby="plan-heading"><h2 id="plan-heading" className="text-2xl font-bold tracking-tight text-slate-950">Der verbindliche Adressplan</h2><div className="mt-5 overflow-x-auto rounded-xl border border-slate-200"><table className="w-full min-w-[46rem] border-collapse text-left text-sm"><thead className="bg-slate-100 text-slate-950"><tr><TableHead>Gerät</TableHead><TableHead>Zweck</TableHead><TableHead>IPv4 / Präfix</TableHead><TableHead>Netz</TableHead><TableHead>Gateway</TableHead></tr></thead><tbody>{devices.map((row, index) => <tr key={`${row[0]}-${row[1]}`} className={index % 2 ? "bg-slate-50" : "bg-white"}>{row.map((cell) => <td key={cell} className="border-t border-slate-200 px-4 py-3"><code className="whitespace-nowrap">{cell}</code></td>)}</tr>)}</tbody></table></div><p className="mt-3 text-sm">Auf allen Schnittstellen wird die punktierte Maske <code>255.255.255.192</code> eingetragen. Keine Adresse ist doppelt vergeben.</p></section>

    <Phase number="2" title="Topologie aufbauen"><p>Lege in Filius zwei lokale Segmente an. Verbinde <strong>PC-A1</strong> und <strong>PC-A2</strong> mit <strong>Switch A</strong>, <strong>PC-B1</strong> und <strong>PC-B2</strong> mit <strong>Switch B</strong>. Ein <strong>Vermittlungsrechner</strong> besitzt je eine Verbindung zu beiden Switches.</p><div className="mt-5 grid gap-3 text-center sm:grid-cols-[1fr_auto_1fr] sm:items-center"><TopologyBlock title="Subnetz A" text="PC-A1 · PC-A2 · Switch A" /><p className="font-bold text-blue-800"><span className="sm:hidden">↓</span><span className="hidden sm:inline">↔</span> Vermittlungsrechner <span className="sm:hidden">↓</span><span className="hidden sm:inline">↔</span></p><TopologyBlock title="Subnetz B" text="PC-B1 · PC-B2 · Switch B" /></div><p className="mt-4 text-sm">Die Switches bilden die lokalen Layer-2-Segmente; der Vermittlungsrechner verbindet beide IP-Netze auf Layer 3. Bezeichnungen oder Dialogpositionen können je nach Filius-Version leicht abweichen.</p></Phase>

    <Phase number="3" title="Subnetz A konfigurieren"><ol className="list-decimal space-y-2 pl-6"><li>PC-A1: <code>192.168.10.10</code>, Maske <code>255.255.255.192</code></li><li>PC-A2: <code>192.168.10.20</code>, dieselbe Maske</li><li>Lasse das Gateway zunächst leer und teste PC-A1 ↔ PC-A2.</li></ol><Expected>Der lokale Test soll funktionieren: Beide Adressen liegen im Bereich <code>192.168.10.1–192.168.10.62</code> des Netzes <code>192.168.10.0/26</code>.</Expected></Phase>
    <Phase number="4" title="Subnetz B konfigurieren"><ol className="list-decimal space-y-2 pl-6"><li>PC-B1: <code>192.168.10.70</code>, Maske <code>255.255.255.192</code></li><li>PC-B2: <code>192.168.10.80</code>, dieselbe Maske</li><li>Lasse das Gateway zunächst leer und teste PC-B1 ↔ PC-B2.</li></ol><Expected>Auch dieser lokale Test soll funktionieren: Beide liegen im Hostbereich von <code>192.168.10.64/26</code>.</Expected></Phase>
    <FiliusConfigurationCheck />

    <Phase number="5" title="Vor dem Routing testen"><p>Sende einen Ping von PC-A1 an PC-B1, bevor ein funktionierender Layer-3-Pfad samt Gateways eingerichtet ist. Eine erfolgreiche Kommunikation ist in diesem Zustand nicht zu erwarten.</p><p className="mt-3">PC-A1 vergleicht Zieladresse und Maske und erkennt PC-B1 als nicht lokal. Für dieses Ziel benötigt der Host einen passenden Layer-3-Next-Hop, üblicherweise sein Standardgateway. Ethernet „versteht“ dabei nicht selbst die IP-Subnetze.</p></Phase>

    <Phase number="6" title="Routing hinzufügen"><ol className="list-decimal space-y-2 pl-6"><li>Router-Schnittstelle A: <code>192.168.10.1</code> mit <code>255.255.255.192</code></li><li>Router-Schnittstelle B: <code>192.168.10.65</code> mit <code>255.255.255.192</code></li><li>Gateway auf PC-A1 und PC-A2: <code>192.168.10.1</code></li><li>Gateway auf PC-B1 und PC-B2: <code>192.168.10.65</code></li></ol><p className="mt-3">Der Vermittlungsrechner ist mit je einer Schnittstelle direkt an beide Netze angeschlossen. Für diese zwei direkt verbundenen Netze ist kein dynamisches Routingprotokoll nötig. Das jeweilige Gateway liegt im lokalen Client-Subnetz und ist deshalb direkt erreichbar.</p></Phase>

    <Phase number="7" title="Kommunikation verifizieren"><p>Teste in dieser Reihenfolge: lokales Hostpaar → lokales Gateway → entferntes Subnetz.</p><ul className="mt-4 grid gap-3 sm:grid-cols-2">{["A1 → A2: lokal erfolgreich", "A1 → Router A: erfolgreich", "B1 → B2: lokal erfolgreich", "B1 → Router B: erfolgreich", "A1 → B1: über Router erfolgreich", "A2 → B2: über Router erfolgreich"].map((test) => <li key={test} className="rounded-xl border border-slate-200 bg-white p-4 text-sm font-semibold text-slate-900">{test}</li>)}</ul><p className="mt-4 text-sm">Falls deine Filius-Version den Datenaustausch sichtbar macht, beobachte je einen lokalen und einen netzübergreifenden Test. Beim zweiten durchläuft der IP-Verkehr das Layer-3-Gerät. Dokumentiere nur, was du tatsächlich beobachtest.</p></Phase>

    <Phase number="8" title="Troubleshooting-Challenge"><div className="space-y-5"><Trouble title="Fehler 1: inkonsistente Maske" config="PC-B2 · 192.168.10.80 · 255.255.255.0 · Gateway 192.168.10.65">Die <code>/24</code>-Maske widerspricht dem <code>/26</code>-Plan. PC-B2 kann dadurch Ziele fälschlich als lokal interpretieren. Die konkreten Symptome hängen von der Umgebung ab. Korrekt ist <code>255.255.255.192</code>.</Trouble><Trouble title="Fehler 2: entferntes Gateway" config="PC-A2 · Gateway 192.168.10.65">Dieses Gateway liegt in Subnetz B und damit außerhalb des lokalen <code>192.168.10.0/26</code>. Ein Standardgateway muss lokal erreichbar sein. Korrekt ist <code>192.168.10.1</code>.</Trouble><Trouble title="Ungültige Hostadressen" config="Darf PC-A1 192.168.10.0/26 oder 192.168.10.63/26 nutzen?">Nein. <code>192.168.10.0</code> bezeichnet das Netz, <code>192.168.10.63</code> dessen Broadcast. Beide sind im konventionellen <code>/26</code> nicht als gewöhnliche Hostadresse vorgesehen.</Trouble></div></Phase>

    <Phase number="9" title="Dokumentation und Abschluss"><p>Halte den geprüften Zustand professionell fest. Eine mögliche Vorlage:</p><div className="mt-4 overflow-x-auto rounded-xl border border-slate-200"><table className="w-full min-w-[52rem] text-left text-sm"><thead className="bg-slate-100"><tr>{["Gerät", "Schnittstelle/Zweck", "IPv4-Adresse", "Präfix/Maske", "Netz", "Gateway", "Verbindung", "Notizen"].map((value) => <TableHead key={value}>{value}</TableHead>)}</tr></thead><tbody><tr>{["PC-A1", "Client A", "192.168.10.10", "/26 · 255.255.255.192", "192.168.10.0/26", "192.168.10.1", "lokal/remote: …", "…"].map((value) => <td key={value} className="border-t border-slate-200 px-4 py-3 whitespace-nowrap">{value}</td>)}</tr><tr>{Array.from({ length: 8 }, (_, index) => <td key={index} className="h-12 border-t border-slate-200 px-4 py-3">…</td>)}</tr></tbody></table></div><h3 className="mt-6 font-bold text-slate-950">Abschlusscheckliste</h3><ul className="mt-3 grid gap-2 sm:grid-cols-2">{["Subnetzberechnungen geprüft", "keine Netz-/Broadcast-Adresse als Host", "alle Masken entsprechen /26", "Gateway liegt im lokalen Subnetz", "lokale Kommunikation getestet", "Gateway-Erreichbarkeit getestet", "subnetzübergreifend getestet", "Fehler dokumentiert", "finalen Adressplan dokumentiert"].map((item) => <li key={item} className="flex gap-3 rounded-lg bg-slate-50 p-3 text-sm"><span aria-hidden="true">□</span><span>{item}</span></li>)}</ul><p className="mt-4 text-sm">Diese Checkliste und die Übung werden nicht gespeichert und verändern keinen Lernfortschritt.</p></Phase>
  </div>;
}

function Phase({ number, title, children }: { number: string; title: string; children: React.ReactNode }) { return <section aria-labelledby={`phase-${number}`} className="rounded-2xl border border-slate-200 bg-slate-50 p-5 sm:p-7"><p className="text-sm font-semibold text-blue-700">Phase {number}</p><h2 id={`phase-${number}`} className="mt-1 text-2xl font-bold tracking-tight text-slate-950">{title}</h2><div className="mt-4">{children}</div></section>; }
function SubnetCard({ name, network, range, broadcast }: { name: string; network: string; range: string; broadcast: string }) { return <div className="rounded-xl border border-blue-200 bg-blue-50 p-4"><h3 className="font-bold text-blue-950">{name}</h3><dl className="mt-2 text-sm"><div><dt className="font-semibold">Netz</dt><dd><code>{network}</code></dd></div><div className="mt-2"><dt className="font-semibold">Gewöhnliche Hosts</dt><dd><code className="break-all">{range}</code></dd></div><div className="mt-2"><dt className="font-semibold">Broadcast</dt><dd><code>{broadcast}</code></dd></div></dl></div>; }
function TopologyBlock({ title, text }: { title: string; text: string }) { return <div className="rounded-xl border border-blue-200 bg-white p-4"><h3 className="font-bold text-slate-950">{title}</h3><p className="mt-1 text-sm">{text}</p></div>; }
function Expected({ children }: { children: React.ReactNode }) { return <p className="mt-4 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-950"><strong>Erwartung:</strong> {children}</p>; }
function Trouble({ title, config, children }: { title: string; config: string; children: React.ReactNode }) { return <article className="rounded-xl border border-amber-200 bg-white p-5"><h3 className="font-bold text-slate-950">{title}</h3><p className="mt-2 font-mono text-sm font-semibold text-amber-900">{config}</p><p className="mt-3 text-sm leading-6">{children}</p></article>; }
function TableHead({ children }: { children: React.ReactNode }) { return <th scope="col" className="px-4 py-3 font-bold whitespace-nowrap">{children}</th>; }
