import { LearningObjectives } from "./learning-objectives";
import { SubnetRangeCheck } from "./subnet-lesson-checks";
import { SubnetRangeVisualization, type SubnetRange } from "./subnet-reference-visualization";

const ranges: readonly SubnetRange[] = [
  { label: "Subnetz 1", cidr: "192.168.10.0/26", network: "192.168.10.0", firstHost: "192.168.10.1", lastHost: "192.168.10.62", broadcast: "192.168.10.63" },
  { label: "Subnetz 2", cidr: "192.168.10.64/26", network: "192.168.10.64", firstHost: "192.168.10.65", lastHost: "192.168.10.126", broadcast: "192.168.10.127" },
  { label: "Subnetz 3", cidr: "192.168.10.128/26", network: "192.168.10.128", firstHost: "192.168.10.129", lastHost: "192.168.10.190", broadcast: "192.168.10.191" },
  { label: "Subnetz 4", cidr: "192.168.10.192/26", network: "192.168.10.192", firstHost: "192.168.10.193", lastHost: "192.168.10.254", broadcast: "192.168.10.255" },
];

export function SubnetLessonFour() {
  return <div className="space-y-10 text-base leading-7 text-slate-700 sm:text-lg sm:leading-8">
    <LearningObjectives context="lesson" objectives={["Subnetzgrenzen mithilfe der Blockgröße auflisten", "Netz- und Broadcast-Adresse eines Blocks bestimmen", "ersten und letzten gewöhnlichen Host ableiten", "den Subnetzbereich einer gegebenen Hostadresse finden", "häufige Grenzwertfehler erkennen"]} />
    <section aria-labelledby="method-heading"><h2 id="method-heading" className="text-2xl font-bold tracking-tight text-slate-950">Die Methode in acht Schritten</h2><ol className="mt-5 list-decimal space-y-2 pl-6"><li>Präfix und Maske bestimmen.</li><li>Relevantes Maskenoktett identifizieren.</li><li>Blockgröße mit <code>256 − Maskenwert</code> bestimmen.</li><li>Subnetzgrenzen in Schritten der Blockgröße auflisten.</li><li>Netzadresse = Start des Blocks.</li><li>Broadcast = nächste Subnetzgrenze − 1.</li><li>Erster gewöhnlicher Host = Netzadresse + 1.</li><li>Letzter gewöhnlicher Host = Broadcast − 1.</li></ol><aside className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-slate-900">Die Hostschritte 7 und 8 gelten für konventionelle IPv4-Subnetze. Besondere Präfixe wie <code>/31</code> und <code>/32</code> werden anders behandelt.</aside></section>
    <section aria-labelledby="range-example-heading"><h2 id="range-example-heading" className="text-2xl font-bold tracking-tight text-slate-950">192.168.10.0/24 in /26-Blöcke teilen</h2><p className="mt-4"><code>/26</code> entspricht <code>255.255.255.192</code>. Die Blockgröße ist <code>256 − 192 = 64</code>; mögliche Grenzen im vierten Oktett sind <code>0, 64, 128, 192</code>.</p><SubnetRangeVisualization ranges={ranges} caption="Vier zusammenhängende /26-Bereiche" /><p className="mt-4 text-sm leading-6">Die Karten sind in Adressreihenfolge angeordnet. Jeder Broadcast liegt unmittelbar vor der nächsten Netzadresse; der letzte Block endet bei <code>.255</code>.</p></section>
    <section aria-labelledby="host-example-heading"><h2 id="host-example-heading" className="text-2xl font-bold tracking-tight text-slate-950">Gegebene Hostadresse einordnen</h2><p className="mt-4">Für <code>192.168.10.150/26</code> lauten die Grenzen <code>0, 64, 128, 192</code>. Der Wert 150 liegt im Block <code>128–191</code>.</p><dl className="mt-5 grid gap-3 sm:grid-cols-2"><Fact label="Netzadresse" value="192.168.10.128" /><Fact label="Broadcast" value="192.168.10.191" /><Fact label="Erster gewöhnlicher Host" value="192.168.10.129" /><Fact label="Letzter gewöhnlicher Host" value="192.168.10.190" /></dl><p className="mt-4">Das ist praktisch bei der Fehlersuche: Nicht die Hostadresse selbst, sondern die beiden umgebenden gültigen Blockgrenzen bestimmen das Subnetz.</p></section>
    <SubnetRangeCheck />
    <section aria-labelledby="l4-mistakes"><h2 id="l4-mistakes" className="text-2xl font-bold tracking-tight text-slate-950">Typische Denkfehler</h2><ul className="mt-5 grid gap-3 sm:grid-cols-2">{[["Bei /26 endet Broadcast immer auf .255.","Nur der letzte der vier /26-Blöcke endet dort; die anderen enden auf .63, .127 und .191."],["Eine Netzadresse endet immer auf .0.","Bei /26 sind auch .64, .128 und .192 gültige Starts."],["Ich runde einfach auf den nächsten Zehner.","Grenzen sind Vielfache der Blockgröße, keine Zehnerschritte."],["Die Hostadresse selbst ist automatisch die Netzadresse.","Nur ein gültiger Blockstart ist Netzadresse."],["Die Blockgröße sagt direkt den Broadcastwert.","Sie liefert den Abstand; Broadcast ist die nächste Grenze minus 1."]].map(([wrong,fix]) => <li key={wrong} className="rounded-xl border border-slate-200 bg-white p-4"><strong className="text-slate-950">Falsch: „{wrong}“</strong><p className="mt-2 text-sm leading-6">{fix}</p></li>)}</ul></section>
    <section aria-labelledby="filius-l4"><h2 id="filius-l4" className="text-2xl font-bold tracking-tight text-slate-950">Filius-Verbindung</h2><p className="mt-4">Plane zwei PCs mit <code>255.255.255.192</code>: PC1 <code>192.168.10.20/26</code>, PC2 <code>192.168.10.70/26</code>. PC1 gehört zu <code>192.168.10.0/26</code>, PC2 zu <code>192.168.10.64/26</code>. Sie liegen in verschiedenen Subnetzen; Routing konfigurierst du hier noch nicht.</p></section>
  </div>;
}

function Fact({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-xl border border-blue-200 bg-blue-50 p-4"><dt className="text-sm font-semibold text-blue-800">{label}</dt><dd className="mt-1"><code className="break-all font-bold text-blue-950">{value}</code></dd></div>; }
