import { LearningObjectives } from "./learning-objectives";
import { PrefixPlanningCheck } from "./subnet-lesson-checks";
import { SubnetRangeVisualization, type SubnetRange } from "./subnet-reference-visualization";

const plan: readonly SubnetRange[] = [
  { label: "Büro Nord", purpose: "Arbeitsplätze", cidr: "192.168.10.0/26", network: "192.168.10.0", mask: "255.255.255.192", firstHost: "192.168.10.1", lastHost: "192.168.10.62", broadcast: "192.168.10.63" },
  { label: "Büro Süd", purpose: "Arbeitsplätze", cidr: "192.168.10.64/26", network: "192.168.10.64", mask: "255.255.255.192", firstHost: "192.168.10.65", lastHost: "192.168.10.126", broadcast: "192.168.10.127" },
  { label: "Server", purpose: "Interne Dienste", cidr: "192.168.10.128/26", network: "192.168.10.128", mask: "255.255.255.192", firstHost: "192.168.10.129", lastHost: "192.168.10.190", broadcast: "192.168.10.191" },
  { label: "Gäste", purpose: "Gastgeräte", cidr: "192.168.10.192/26", network: "192.168.10.192", mask: "255.255.255.192", firstHost: "192.168.10.193", lastHost: "192.168.10.254", broadcast: "192.168.10.255" },
];

export function SubnetLessonFive() {
  return <div className="space-y-10 text-base leading-7 text-slate-700 sm:text-lg sm:leading-8">
    <LearningObjectives context="lesson" objectives={["einen passenden Präfix für eine einfache Hostanforderung wählen", "erforderliche Hosts von Gesamtadressen unterscheiden", "gleich große, nicht überlappende Bereiche planen", "Überlappungen und ungültige Grenzen erkennen", "Subnetzberechnungen systematisch prüfen und dokumentieren"]} />
    <section aria-labelledby="requirements-heading"><h2 id="requirements-heading" className="text-2xl font-bold tracking-tight text-slate-950">Von der Anforderung zum Präfix</h2><p className="mt-4">Wähle für eine klar definierte Anforderung den kleinsten praktischen Block, der noch genügend <strong>gewöhnliche Hostadressen</strong> enthält. Gesamtadressen und Hostadressen sind nicht dasselbe.</p><dl className="mt-5 grid gap-3 sm:grid-cols-3"><Requirement hosts={50} prefix="/26" reason="64 gesamt · 62 gewöhnliche Hosts; /27 mit 30 ist zu klein." /><Requirement hosts={20} prefix="/27" reason="32 gesamt · 30 gewöhnliche Hosts; /28 mit 14 ist zu klein." /><Requirement hosts={10} prefix="/28" reason="16 gesamt · 14 gewöhnliche Hosts." /></dl><aside className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm leading-6 text-slate-900"><strong>Planungsreserve zählt:</strong> Der kleinste rechnerisch passende Block ist nicht automatisch in jeder realen Planung ideal. Erwartetes Wachstum oder betriebliche Reserven können einen größeren Block begründen; diese Entscheidung muss dokumentiert werden.</aside></section>
    <PrefixPlanningCheck />
    <section aria-labelledby="equal-plan-heading"><h2 id="equal-plan-heading" className="text-2xl font-bold tracking-tight text-slate-950">Vier gleich große Netze planen</h2><p className="mt-4">Aus <code>192.168.10.0/24</code> werden vier getrennte Netze benötigt. Mit <code>/26</code> entstehen vier gleich große Blöcke zu je 64 Adressen. Sie grenzen unmittelbar aneinander, überlappen nicht und decken den ursprünglichen <code>/24</code>-Block vollständig ab.</p><SubnetRangeVisualization ranges={plan} caption="Ein einfacher dokumentierter /26-Subnetzplan" /><p className="mt-4 text-sm leading-6">Alle Einträge verwenden die Maske <code>255.255.255.192</code>. Unterschiedliche Anforderungen können konzeptionell andere Präfixe nahelegen; eine optimierte gemischte Zuteilung (VLSM) ist bewusst noch nicht Thema.</p></section>
    <section aria-labelledby="overlap-heading"><h2 id="overlap-heading" className="text-2xl font-bold tracking-tight text-slate-950">Überlappungen erkennen</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><OverlapCard title="Überlappt" first="192.168.10.0/26 · 0–63" second="192.168.10.32/27 · 32–63" explanation="Der gesamte /27-Bereich liegt innerhalb des /26-Bereichs. Beide dürfen im selben Adressplan nicht als unabhängige, nicht überlappende Zuteilungsblöcke gelten." warning /><OverlapCard title="Überlappt nicht" first="192.168.10.0/26 · 0–63" second="192.168.10.64/26 · 64–127" explanation="Der zweite Bereich beginnt unmittelbar nach dem Broadcast des ersten." /></div></section>
    <section aria-labelledby="checklist-heading"><h2 id="checklist-heading" className="text-2xl font-bold tracking-tight text-slate-950">Planungscheckliste</h2><ol className="mt-5 grid gap-3 sm:grid-cols-2">{["Wie viele Netze werden benötigt?","Wie viele Hosts sind erforderlich?","Welcher Adressblock ist verfügbar?","Welcher Präfix passt?","Wie groß ist der Block?","Wo liegen die Netzgrenzen?","Wie lauten Netz, Broadcast und Hostbereiche?","Überlappen geplante Bereiche?","Gibt es sinnvolle Wachstumsreserve?","Ist das Ergebnis dokumentiert?"].map((item,index) => <li key={item} className="flex gap-3 rounded-xl border border-slate-200 bg-white p-4"><span aria-hidden="true" className="grid size-8 shrink-0 place-items-center rounded-full bg-blue-100 text-sm font-bold text-blue-900">{index + 1}</span><span>{item}</span></li>)}</ol></section>
    <section aria-labelledby="verification-heading"><h2 id="verification-heading" className="text-2xl font-bold tracking-tight text-slate-950">Eine /26-Rechnung selbst prüfen</h2><ul className="mt-5 list-disc space-y-2 pl-6"><li>Maske: <code>255.255.255.192</code></li><li>Blockgröße: <code>64</code></li><li>Starts sind Vielfache von 64: <code>0, 64, 128, 192</code></li><li>Jeder Bereich enthält genau 64 Adressen.</li><li>Das nächste Netz folgt direkt nach dem vorherigen Broadcast.</li><li>Kein Bereich überschneidet einen anderen.</li></ul></section>
    <section aria-labelledby="planning-errors"><h2 id="planning-errors" className="text-2xl font-bold tracking-tight text-slate-950">Häufige Planungsfehler</h2><ul className="mt-5 list-disc space-y-2 pl-6"><li><code>/27</code> für 50 Hosts wählen: 30 gewöhnliche Hostadressen reichen nicht.</li><li>Netz- und Broadcast-Reservierung in konventionellen Subnetzen vergessen.</li><li>Starts verwenden, die keine gültigen Blockgrenzen sind.</li><li>Bereiche überlappen lassen oder Lücken nicht erklären.</li><li>Aus Gewohnheit jedes Netz als <code>/24</code> planen.</li><li>Den kleinsten Block ohne Wachstumsreserve wählen.</li><li>„Größer“ oder „kleiner“ pauschal als besser behandeln.</li></ul></section>
    <section aria-labelledby="filius-preview"><p className="text-sm font-semibold text-blue-700">Nächste Lektion</p><h2 id="filius-preview" className="mt-1 text-2xl font-bold tracking-tight text-slate-950">Praxis: Subnetting mit Filius</h2><p className="mt-4">Dort setzt du berechnete Pläne um: mehrere IP-Subnetze konfigurieren, Kommunikation im selben Subnetz prüfen, fehlende Kommunikation zwischen Subnetzen ohne Routing beobachten, geeignetes Routing ergänzen und Verkehr untersuchen. Der vollständige Laboraufbau bleibt der eigenen Praxislektion vorbehalten.</p></section>
  </div>;
}

function Requirement({ hosts, prefix, reason }: { hosts: number; prefix: string; reason: string }) { return <div className="rounded-xl border border-blue-200 bg-blue-50 p-4"><dt className="font-bold text-blue-950">{hosts} Hosts</dt><dd className="mt-2"><code className="text-xl font-bold text-slate-950">{prefix}</code><p className="mt-2 text-sm leading-6">{reason}</p></dd></div>; }
function OverlapCard({ title, first, second, explanation, warning = false }: { title: string; first: string; second: string; explanation: string; warning?: boolean }) { return <article className={`rounded-xl border p-5 ${warning ? "border-amber-300 bg-amber-50" : "border-emerald-300 bg-emerald-50"}`}><h3 className="font-bold text-slate-950">{title}</h3><code className="mt-3 block break-all text-sm">{first}</code><code className="mt-1 block break-all text-sm">{second}</code><p className="mt-3 text-sm leading-6">{explanation}</p></article>; }
