import type { ReactNode } from "react";
import { FundamentalsLesson, ResponsiveTable, TextFlow, type LessonSection } from "./fundamentals-lesson-elements";
import { SingleChoiceCheck } from "./single-choice-check";

type LessonContent = { objectives: readonly string[]; intro: ReactNode; sections: readonly LessonSection[]; visual?: ReactNode; scenario: { title: string; situation: ReactNode; tasks: readonly ReactNode[]; solution: ReactNode }; takeaway: readonly ReactNode[]; relatedLinks?: readonly { href: string; label: string }[] };

const lessons: Record<string, LessonContent> = {
  "virtualisierung-host-gast-hypervisor": {
    objectives: ["physisches und virtuelles System unterscheiden", "Host, Gast, VM und Hypervisor erklären", "Typ-1 und Typ-2 einordnen"],
    intro: <p>Virtualisierung bildet Rechen-, Speicher- und Netzressourcen abstrahiert ab. Mehrere isolierte Gastsysteme können dadurch kontrolliert dieselbe physische Plattform nutzen.</p>,
    sections: [
      { title: "Host, Hypervisor und Gast", paragraphs: [<>Der Host stellt physische Ressourcen bereit. Der Hypervisor verwaltet virtuelle Hardware und Ausführung; die virtuelle Maschine ist die abgegrenzte Maschinenumgebung, in der gewöhnlich ein eigenes Gastbetriebssystem läuft.</>, <>Die Abstraktion erleichtert Bereitstellung und Isolation, hebt physische Grenzen aber nicht auf. Ein Ausfall des Hosts kann alle darauf laufenden Gäste betreffen.</>], activity: <SingleChoiceCheck title="Rolle erkennen" question="Welche Komponente stellt einer VM virtuelle CPU, RAM und Geräte bereit?" inputName="virtualization-role" correctOptionId="hypervisor" successMessage="Der Hypervisor vermittelt die virtuellen Ressourcen." options={[{id:"guest",label:"das Gastbetriebssystem allein",explanation:"Es nutzt die bereitgestellte virtuelle Hardware."},{id:"hypervisor",label:"der Hypervisor",explanation:"Richtig."},{id:"registry",label:"eine Container-Registry",explanation:"Sie verteilt Images."},{id:"sla",label:"ein SLA",explanation:"Das beschreibt Serviceziele."}]} /> },
      { title: "Typ 1 und Typ 2", paragraphs: [<>Ein Typ-1-Hypervisor läuft als Virtualisierungsschicht direkt auf der Hardware beziehungsweise als spezialisierte Hostplattform. Ein Typ-2-Hypervisor läuft als Anwendung auf einem allgemeinen Hostbetriebssystem.</>, <>Die Kategorie hängt von der Architektur, nicht vom Herstellernamen ab. Typ 1 ist häufig im Rechenzentrum, Typ 2 etwa für lokale Tests; die Eignung folgt Anforderungen und Betriebsmodell.</>] },
    ],
    visual: <ResponsiveTable caption="Hypervisor-Konzepte" headers={["Typ", "Architektur", "typischer Kontext"]} rows={[["Typ 1","Hardware → Hypervisor → Gäste","Server-/Rechenzentrumsbetrieb"],["Typ 2","Hardware → Host-OS → Hypervisor-Anwendung → Gäste","Arbeitsplatz, Schulung, Test"]]} />,
    scenario: { title: "Testumgebung auf einem Notebook", situation: <p>Eine Administratorin benötigt kurzzeitig zwei isolierte Gastbetriebssysteme auf ihrem bestehenden Desktop-Betriebssystem.</p>, tasks: ["Welcher Hypervisortyp ist konzeptionell naheliegend?", "Welche Hostgrenze bleibt bestehen?"], solution: <p>Ein Typ-2-Hypervisor ist für den lokalen Test plausibel. CPU, RAM, Storage und Sicherheit hängen weiterhin vom Notebook und Hostbetriebssystem ab.</p> },
    takeaway: ["VMs abstrahieren physische Ressourcen.", "Typ 1 und 2 beschreiben die Lage des Hypervisors.", "Virtualisierung erzeugt nicht automatisch Redundanz."],
  },
  "vm-ressourcen-und-betriebsgrenzen": {
    objectives: ["vCPU, virtuellen RAM, Datenträger und NIC erklären", "Zuweisung und physische Kapazität unterscheiden", "Snapshot, Hochverfügbarkeit und Backup abgrenzen"],
    intro: <p>Virtuelle Hardware ist eine kontrollierte Sicht auf Hostressourcen. Planung berücksichtigt Spitzenlast, Reserven, konkurrierende Gäste und die reale I/O-Kette.</p>,
    sections: [
      { title: "Ressourcen sind nicht unbegrenzt", paragraphs: [<>vCPU wird auf physische Rechenzeit abgebildet, virtueller RAM auf Arbeitsspeichermechanismen, virtuelle Disks auf reale Storage-Pfade und vNICs auf virtuelle sowie physische Netze. Zuweisung bedeutet je nach Plattform nicht, dass alles jederzeit exklusiv reserviert ist.</>, <>Überbelegung kann Auslastung verbessern, erhöht aber das Risiko von Engpässen. Monitoring, Prioritäten, Reserven und Lasttests machen Annahmen überprüfbar.</>], activity: <SingleChoiceCheck title="Engpass beurteilen" question="Vier VMs besitzen zusammen mehr vCPU als der Host physische Kerne. Welche Aussage ist angemessen?" inputName="virtualization-resources" correctOptionId="workload" successMessage="Ob das tragfähig ist, hängt von gleichzeitiger Last und Ressourcensteuerung ab." options={[{id:"impossible",label:"Das ist technisch immer unmöglich.",explanation:"vCPU kann zeitlich auf physische CPUs verteilt werden."},{id:"unlimited",label:"Damit ist Rechenleistung unbegrenzt.",explanation:"Der Host bleibt die physische Grenze."},{id:"workload",label:"Lastprofil und Überbelegung müssen gemessen werden.",explanation:"Richtig."},{id:"backup",label:"Das ersetzt ein Backup.",explanation:"Ressourcenzuweisung ist keine Sicherung."}]} /> },
      { title: "Betriebsgrenzen benennen", paragraphs: [<>Eine VM ist nicht automatisch hochverfügbar. Ohne redundante Hosts, Storage-/Netzpfade, Orchestrierung und getestete Wiederanlaufprozesse bleibt der Host ein möglicher gemeinsamer Ausfallpunkt.</>, <>Ein Snapshot hält einen Zustand oder Änderungen eng an derselben Virtualisierungs-/Storage-Umgebung fest. Er ist nützlich für kurze Rücksetzpunkte, aber keine unabhängige Sicherungsstrategie.</>] },
    ],
    visual: <TextFlow caption="VM-Kapazität planen" steps={["Workload messen", "vCPU/RAM/I/O zuweisen", "Konkurrenz und Reserve", "Monitoring", "kontrolliert anpassen"]} />,
    scenario: { title: "Acht Server auf einem Host", situation: <p>Ein einzelner Host trägt acht produktive VMs und deren Snapshots auf demselben Storage. Ein zweiter Host und unabhängige Backups fehlen.</p>, tasks: ["Welche Verfügbarkeitsrisiken bestehen?", "Was leisten die Snapshots nicht?"], solution: <p>Host und Storage sind gemeinsame Ausfallpunkte. Snapshots schützen nicht unabhängig vor Host-/Storage-Ausfall, Ransomware, Adminfehler oder ungeeigneter Aufbewahrung und ersetzen getestete Backups nicht.</p> },
    takeaway: ["Virtuelle Ressourcen bleiben an reale Kapazität gebunden.", "Überbelegung braucht Evidenz und Grenzen.", "VM, Snapshot und Hochverfügbarkeit sind kein Backup."],
    relatedLinks: [{href:"/lernen/backup-datensicherung/datei-image-und-snapshot",label:"Backup: Image und Snapshot"},{href:"/lernen/storage-und-raid/raid-oder-backup-praxis",label:"Storage: RAID und Backup"}],
  },
  "vm-und-container-unterscheiden": {
    objectives: ["VM- und Containerarchitektur unterscheiden", "Isolation und Kernelbezug erklären", "Startzeit, Ressourcenbedarf und Portabilität vorsichtig vergleichen"],
    intro: <p>Container sind keine kleinen virtuellen Maschinen. Beide kapseln Workloads, aber auf unterschiedlichen Abstraktionsebenen.</p>,
    sections: [
      { title: "Eigener Gast oder gemeinsamer Kernel", paragraphs: [<>Eine VM virtualisiert eine Maschine und enthält gewöhnlich ein eigenes Gastbetriebssystem mit eigener Kernelumgebung. Ein Container isoliert Prozesse und nutzt konzeptionell den Kernel des Hosts.</>, <>Container paketieren Anwendung und Abhängigkeiten. Der gemeinsame Kernel reduziert typischerweise Overhead und Startzeit, schafft aber andere Kompatibilitäts- und Isolationsgrenzen als eine VM.</>], activity: <SingleChoiceCheck title="Architektur erkennen" question="Welche Aussage trifft einen Container am besten?" inputName="virtualization-vm-container" correctOptionId="kernel" successMessage="Container isolieren Prozesse und teilen konzeptionell den Hostkernel." options={[{id:"mini-vm",label:"Er ist immer eine VM mit kleiner Festplatte.",explanation:"Die Kernelarchitektur unterscheidet sich."},{id:"kernel",label:"Er isoliert Prozesse und nutzt den Hostkernel.",explanation:"Richtig."},{id:"backup",label:"Er ist automatisch ein Backup der Anwendung.",explanation:"Image und Laufzeitinstanz ersetzen kein Backup."},{id:"ha",label:"Er überlebt automatisch jeden Hostausfall.",explanation:"Dafür braucht es weitere Architektur."}]} /> },
      { title: "Eignung statt Rangliste", paragraphs: [<>VMs erlauben unterschiedliche Gastbetriebssysteme und starke Maschinenabgrenzung; Container ermöglichen häufig dichte, reproduzierbare Anwendungsbereitstellung. Konkrete Isolation hängt bei beiden von Konfiguration und Plattform ab.</>, <>Portabilität bedeutet nicht, dass jedes Image überall unverändert läuft: Prozessorarchitektur, Kernelmerkmale, Laufzeit, externe Dienste, Daten und Konfiguration bleiben relevant.</>] },
    ],
    visual: <ResponsiveTable caption="VM und Container vergleichen" headers={["Aspekt", "VM", "Container"]} rows={[["Abstraktion","virtuelle Maschine","isolierte Prozesse/Anwendung"],["Kernel","gewöhnlich eigener Gastkernel","Hostkernel wird geteilt"],["Start/Overhead","typischerweise höher","typischerweise geringer"],["Portabilität","VM-Format und virtuelle Hardware","Image plus kompatible Laufzeit/Architektur"],["Hostausfall","ohne HA betroffen","ohne Orchestrierung/Redundanz betroffen"]]} />,
    scenario: { title: "Legacy-System und Web-API", situation: <p>Eine alte Anwendung benötigt ein eigenes nicht zum Host passendes Betriebssystem. Eine neue Web-API läuft auf derselben unterstützten Kernelplattform und soll reproduzierbar starten.</p>, tasks: ["Welche Kapselung ist je Workload plausibel?", "Welche Annahmen müssen getestet werden?"], solution: <p>Für das Legacy-Gastbetriebssystem ist eine VM plausibel; die API kann als Container passen. Treiber, Kernel-/Architekturkompatibilität, Persistenz, Netzwerk, Isolation und Betrieb werden getestet.</p> },
    takeaway: ["VM virtualisiert eine Maschine; Container isoliert Prozesse.", "Container teilen den Hostkernel.", "Weniger Overhead bedeutet nicht automatisch passende Sicherheit oder Hochverfügbarkeit."],
  },
  "container-grundlagen": {
    objectives: ["Image, Container und Registry unterscheiden", "Ports und Konfiguration einordnen", "persistente Daten vom austauschbaren Container trennen"],
    intro: <p>Containerbetrieb trennt ein versioniertes Anwendungsabbild von der laufenden Instanz und von Daten, die einen Neustart oder Austausch überleben sollen.</p>,
    sections: [
      { title: "Vom Image zur Instanz", paragraphs: [<>Ein Image ist ein unveränderlich gedachtes, versioniertes Paket aus Anwendung und Abhängigkeiten. Ein Container ist eine laufende Instanz dieses Images. Eine Registry speichert und verteilt Images; Vertrauensquelle, Signatur und Version sind relevant.</>, <>Ports werden nicht allein durch das Image sicher veröffentlicht. Laufzeit und Netzkonfiguration legen fest, welche Endpunkte intern oder extern erreichbar sind.</>], activity: <SingleChoiceCheck title="Begriff zuordnen" question="Wo wird ein versioniertes Anwendungsabbild typischerweise gespeichert und verteilt?" inputName="virtualization-container" correctOptionId="registry" successMessage="Eine Registry verwaltet und verteilt Images." options={[{id:"volume",label:"nur im Datenvolume",explanation:"Volumes dienen typischerweise persistenten Daten."},{id:"registry",label:"in einer Registry",explanation:"Richtig."},{id:"sla",label:"im SLA",explanation:"Ein SLA beschreibt Serviceziele."},{id:"guest",label:"im Gastkernel jedes Containers",explanation:"Container besitzen nicht gewöhnlich je einen eigenen Gastkernel."}]} /> },
      { title: "Konfiguration und Persistenz", paragraphs: [<>Umgebungswerte und Konfigurationsdateien parametrisieren dieselbe Imageversion. Geheimnisse gehören in geeignete Secret-Verwaltung und weder ins Image noch in frei lesbare Dokumentation.</>, <>Dateien im beschreibbaren Container-Layer können beim Austausch verloren gehen. Zustandsdaten benötigen bewusst geplante Volumes, externe Dienste, Berechtigungen und Backups.</>] },
    ],
    visual: <TextFlow caption="Containerbereitstellung" steps={["vertrauenswürdiges Image", "Konfiguration/Secrets", "Containerinstanz", "Port/Netz", "persistenter Datenspeicher"]} />,
    scenario: { title: "Datenbank im Container", situation: <p>Eine Datenbank schreibt alle Daten nur in den austauschbaren Container-Layer; das Passwort steht im Image.</p>, tasks: ["Welche zwei Hauptprobleme bestehen?", "Welche Konzepte korrigieren sie?"], solution: <p>Daten können beim Austausch verloren gehen und das Passwort ist im Image offengelegt. Persistenter Speicher mit eigenem Backup sowie geeignete Secret-/Konfigurationsverwaltung sind erforderlich.</p> },
    takeaway: ["Image, Container und Registry sind verschiedene Rollen.", "Ports und Konfiguration werden bewusst gesetzt.", "Persistenz und Geheimnisse liegen nicht unkontrolliert im Container-Layer."],
  },
  "cloud-service-und-bereitstellungsmodelle": {
    objectives: ["Cloud und On-Premises einordnen", "IaaS, PaaS und SaaS unterscheiden", "Public, Private und Hybrid Cloud anwenden"],
    intro: <p>Cloud Computing stellt IT-Ressourcen als standardisierte, bedarfsgerecht beziehbare Dienste bereit. Eigentumsort, Betriebsverantwortung und Servicemodell müssen getrennt betrachtet werden.</p>,
    sections: [
      { title: "IaaS, PaaS und SaaS", paragraphs: [<>IaaS stellt grundlegende Rechen-, Speicher- und Netzressourcen bereit; der Kunde verantwortet typischerweise mehr vom Betriebssystem aufwärts. PaaS stellt eine verwaltete Anwendungsplattform bereit, während der Kunde Anwendung und Daten verantwortet.</>, <>SaaS liefert eine nutzbare Anwendung als Dienst. Der Anbieter betreibt mehr Schichten, aber Kunde und Nutzer behalten Aufgaben etwa bei Identitäten, Datenklassifikation, Konfiguration und zulässiger Nutzung. FaaS kann als ereignisbezogene Ausführung einzelner Funktionen eingeordnet werden.</>], activity: <SingleChoiceCheck title="Servicemodell wählen" question="Ein Team möchte eigenen Code bereitstellen, aber Laufzeit, Patching der Plattform und Skalierung als Dienst beziehen. Was passt am ehesten?" inputName="virtualization-cloud-service" correctOptionId="paas" successMessage="PaaS stellt eine verwaltete Plattform für eigenen Anwendungscode bereit." options={[{id:"iaas",label:"IaaS mit selbst verwaltetem Betriebssystem",explanation:"Das überlässt dem Team mehr Plattformbetrieb."},{id:"paas",label:"PaaS",explanation:"Richtig."},{id:"saas",label:"SaaS als fertige Fachanwendung",explanation:"Hier soll eigener Code laufen."},{id:"raid",label:"RAID",explanation:"RAID ist kein Cloud-Servicemodell."}]} /> },
      { title: "Public, Private und Hybrid", paragraphs: [<>Public Cloud nutzt Dienste einer geteilten Anbieterplattform; Mandanten werden logisch getrennt. Private Cloud ist eine Cloud-Umgebung für eine Organisation, intern oder extern betrieben. Hybrid Cloud verbindet private/on-premises und Public-Cloud-Ressourcen in einem abgestimmten Modell.</>, <>Multi-Cloud bezeichnet die Nutzung mehrerer Cloudanbieter und ist nicht automatisch Hybrid Cloud. Auch ein extern gehosteter Server ist nicht allein deshalb Cloud Computing.</>] },
    ],
    visual: <ResponsiveTable caption="Cloud-Modelle" headers={["Modell", "bereitgestellt", "Kunde fokussiert"]} rows={[["IaaS","virtuelle Infrastruktur","OS, Anwendungen, Daten"],["PaaS","verwaltete Plattform/Laufzeit","Anwendung, Daten, Konfiguration"],["SaaS","fertige Anwendung","Nutzung, Identitäten, Daten, Einstellungen"],["Public Cloud","geteilte Anbieterplattform","vertraglich isolierter Dienst"],["Private Cloud","organisationsbezogene Cloud","eigener/vertraglicher Betrieb"],["Hybrid Cloud","gekoppelte private und öffentliche Umgebungen","Integration und Platzierung"]]} />,
    scenario: { title: "Drei Bedarfe", situation: <p>Ein Team braucht eine VM mit eigener Serverkonfiguration, eine Plattform für eigenen Webcode und eine fertige Kollaborationsanwendung.</p>, tasks: ["Ordne IaaS, PaaS und SaaS zu.", "Welche Verantwortung bleibt jeweils beim Kunden?"], solution: <p>VM: IaaS; Webplattform: PaaS; Kollaboration: SaaS. Identitäten, Daten, Konfiguration, Nutzung und Vertragsprüfung bleiben in unterschiedlichem Umfang beim Kunden.</p> },
    takeaway: ["Servicemodell und Bereitstellungsmodell sind verschiedene Achsen.", "IaaS, PaaS und SaaS teilen Verantwortung unterschiedlich.", "Multi-Cloud ist nicht automatisch Hybrid Cloud."],
  },
  "cloud-entscheidung-und-verantwortung": {
    objectives: ["Skalierbarkeit und Elastizität unterscheiden", "Cloud-/On-Premises-Faktoren abwägen", "Verfügbarkeit, Sicherheit und Datenschutz nicht automatisch annehmen"],
    intro: <p>Cloud und On-Premises sind keine Qualitätsstufen. Die richtige Architektur folgt Last, Risiko, Verantwortung, Daten, Kompetenzen und Exit-Anforderungen.</p>,
    sections: [
      { title: "Skalieren und elastisch reagieren", paragraphs: [<>Skalierbarkeit ist die Fähigkeit, erhöhte Last durch Ressourcenänderung zu bewältigen. Elastizität ist die dynamische Anpassung an schwankenden Bedarf, einschließlich Zurückskalieren.</>, <>Ein skalierbarer Entwurf ist nicht automatisch elastisch; Automatisierung, Messwerte, Grenzen und Kostenkontrolle werden geplant und getestet.</>], activity: <SingleChoiceCheck title="Begriff unterscheiden" question="Ressourcen steigen bei Last automatisch an und sinken später wieder. Welcher Begriff passt?" inputName="virtualization-elasticity" correctOptionId="elastic" successMessage="Die dynamische Anpassung an wechselnde Last ist Elastizität." options={[{id:"elastic",label:"Elastizität",explanation:"Richtig."},{id:"backup",label:"Backup",explanation:"Das betrifft Wiederherstellung."},{id:"license",label:"Lizenzübertragung",explanation:"Das beschreibt keine Lastanpassung."},{id:"acceptance",label:"Abnahme",explanation:"Das ist ein Übergabe-/Vertragsprozess."}]} /> },
      { title: "Trade-offs und geteilte Verantwortung", paragraphs: [<>Verglichen werden Kostenmodell, Skalierung, Administrationsaufwand, Verfügbarkeitsanforderung, Internetabhängigkeit, Datenstandort, Datenschutz, Sicherheitsverantwortung, Anbieterbindung und Migration/Exit.</>, <>Cloud ist weder automatisch sicher noch hochverfügbar. Regionen, Zonen, Backups, Identitäten, Konfiguration, Monitoring und vertragliche Ziele müssen passend entworfen werden; auch ein Container überlebt keinen Hostausfall ohne weitere Architektur.</>] },
    ],
    visual: <ResponsiveTable caption="Entscheidungsfaktoren" headers={["Faktor", "Leitfrage"]} rows={[["Verfügbarkeit","welche Ausfälle muss der Dienst überstehen?"],["Daten","wo, wie und durch wen werden Daten verarbeitet?"],["Sicherheit","welche Kontrollen übernimmt Anbieter/Kunde?"],["Kosten","welche Grund-, Nutzungs- und Exitkosten entstehen?"],["Abhängigkeit","wie gelingt Export, Migration und Notbetrieb?"],["Netz","welche Latenz und Internetabhängigkeit sind tragbar?"]]} />,
    scenario: { title: "Saisonaler Kundenservice", situation: <p>Die Last steigt dreimal jährlich stark. Personendaten werden verarbeitet; bei Internetausfall muss ein eingeschränkter Notbetrieb möglich sein.</p>, tasks: ["Welche Cloud-Vorteile und Risiken sind relevant?", "Welche Nachweise braucht die Entscheidung?"], solution: <p>Elastische Kapazität kann helfen. Datenschutz, Datenstandort, Rollen, Verfügbarkeit, Kostenobergrenzen, Export, Notbetrieb und Wiederherstellung müssen als Anforderungen und Tests dokumentiert werden.</p> },
    takeaway: ["Skalierbarkeit ist nicht dasselbe wie Elastizität.", "Cloud verteilt Verantwortung, entfernt sie nicht.", "Verfügbarkeit und Sicherheit entstehen durch Architektur und Betrieb."],
    relatedLinks: [{href:"/lernen/it-sicherheit/schutzmassnahmen-und-hardening",label:"IT-Sicherheit: Schutzmaßnahmen"},{href:"/lernen/datenschutz/datenschutz-und-datensicherheit",label:"Datenschutz und Datensicherheit"},{href:"/lernen/wirtschaftlichkeit-und-beschaffung/tco-und-amortisation",label:"Wirtschaftlichkeit: TCO"}],
  },
};

export function VirtualizationCloudLesson({ lessonSlug }: { lessonSlug: string }) {
  const lesson = lessons[lessonSlug];
  if (!lesson) return null;
  return <FundamentalsLesson lessonId={`virtualization-${lessonSlug}`} {...lesson} relatedLinks={lesson.relatedLinks}>{lesson.visual}</FundamentalsLesson>;
}
