const flowSteps = ["Browser / HTTP-Client", "DNS-Name auflösen (falls nicht bekannt/gecached)", "IP-Adresse 192.168.10.20", "Webserver", "HTTP-Antwort"];

export function WebServerRequestFlow() { return <figure className="rounded-2xl border border-slate-200 bg-slate-50 p-5 sm:p-6"><figcaption className="font-bold text-slate-950">Konzeptioneller Weg einer Webanfrage</figcaption><p className="mt-2 text-sm leading-6">Der Benutzer startet die Anfrage. Eine DNS-Abfrage ist nur nötig, falls die Adresse nicht bereits bekannt oder gecached ist.</p><ol className="mt-5 grid gap-2" aria-label="Ablauf vom Browser zur HTTP-Antwort">{flowSteps.map((step, index) => <li key={step} className="text-center"><div className="rounded-xl border border-blue-200 bg-white p-3 font-semibold text-slate-900"><span className="sr-only">Schritt {index + 1}: </span>{step}</div>{index < flowSteps.length - 1 && <span aria-hidden="true" className="block py-1 font-bold text-blue-700">↓</span>}</li>)}</ol></figure>; }

export function HttpRequestResponseVisualization() { return <figure className="rounded-2xl border border-slate-200 bg-slate-50 p-5 sm:p-6"><figcaption className="font-bold text-slate-950">Ein Request-Response-Zyklus</figcaption><div className="mt-5 grid gap-4 sm:grid-cols-[1fr_auto_1fr] sm:items-center"><div className="rounded-xl border border-blue-200 bg-white p-4 text-center"><strong>Client</strong><span className="mt-2 block text-sm">sendet Request</span></div><div className="text-center text-sm font-bold text-blue-800"><span className="block sm:hidden">↓ GET /index.html ↓</span><span className="hidden sm:block">GET /index.html →<br />← 200 OK + Inhalt</span></div><div className="rounded-xl border border-blue-200 bg-white p-4 text-center"><strong>Server</strong><span className="mt-2 block text-sm">sendet Response</span></div></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Part title="Request" items={["Methode", "Ziel", "Header", "optionaler Body"]} /><Part title="Response" items={["Status", "Header", "optionaler Body"]} /></div></figure>; }

const urlParts = [["Schema", "https"], ["Host", "www.firma.test"], ["Port", "8443"], ["Pfad", "/azubi/lesson"], ["Query", "id=42"], ["Fragment", "aufgabe"]] as const;
export function UrlBreakdown() { return <figure className="rounded-2xl border border-slate-200 bg-slate-50 p-5 sm:p-6"><figcaption className="font-bold text-slate-950">URL-Bestandteile</figcaption><code className="mt-4 block break-all rounded-xl bg-slate-950 p-4 text-sm leading-6 text-blue-100">https://www.firma.test:8443/azubi/lesson?id=42#aufgabe</code><dl className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{urlParts.map(([label, value]) => <div key={label} className="min-w-0 rounded-xl border border-blue-200 bg-white p-4"><dt className="text-sm font-semibold text-blue-800">{label}</dt><dd className="mt-1 break-all"><code className="font-bold text-slate-950">{value}</code></dd></div>)}</dl><p className="mt-4 text-sm leading-6">Der Browser verarbeitet das Fragment <code>#aufgabe</code> clientseitig; es wird normalerweise nicht als Teil des HTTP-Request-Targets an den Server gesendet.</p></figure>; }

const classes = [["1xx", "Information", "Zwischeninformationen"], ["2xx", "Erfolg", "z. B. 200, 201, 204"], ["3xx", "Weiterleitung", "z. B. 301, 302, 304"], ["4xx", "Request-/Client-Kontext", "z. B. 400, 401, 403, 404"], ["5xx", "Server-/Upstream-Kontext", "z. B. 500, 502, 503, 504"]] as const;
export function HttpStatusOverview() { return <figure><figcaption className="font-bold text-slate-950">Statuscode-Klassen im Überblick</figcaption><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{classes.map(([code, title, detail]) => <article key={code} className="rounded-xl border border-slate-200 bg-white p-4"><p className="text-xl font-black text-blue-800">{code}</p><h3 className="mt-1 font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6">{detail}</p></article>)}</div></figure>; }
function Part({ title, items }: { title: string; items: readonly string[] }) { return <div className="rounded-xl border border-slate-200 bg-white p-4"><h3 className="font-bold text-slate-950">{title}</h3><ul className="mt-2 list-disc pl-5 text-sm">{items.map((item) => <li key={item}>{item}</li>)}</ul></div>; }
