import { LearningObjectives } from "./learning-objectives";
import { MultipleSelectionCheck } from "./multiple-selection-check";
import { SingleChoiceCheck } from "./single-choice-check";

export function HttpsTlsLesson() {
  return <Lesson>
    <LearningObjectives context="lesson" objectives={["HTTPS als durch TLS geschütztes HTTP erklären", "Vertraulichkeit, Integrität und Serverauthentifizierung unterscheiden", "die Rolle eines Serverzertifikats und einer CA erklären", "Hostname, Gültigkeitszeitraum und Vertrauenskette konzeptionell prüfen", "selbstsignierte und durch eine vertrauenswürdige CA ausgestellte Zertifikate unterscheiden", "häufige Zertifikatsfehler erkennen", "Grenzen der Aussagekraft von HTTPS benennen"]} />
    <Section id="https-model" title="HTTP + TLS = HTTPS"><p><strong>HTTP</strong> bleibt das Anwendungsprotokoll für Requests und Responses. Bei <strong>HTTPS</strong> wird diese HTTP-Kommunikation durch <strong>TLS</strong> geschützt. Die Formel ist ein Denkmodell, keine wörtliche Paketsyntax:</p><div className="grid gap-2 text-center font-black text-blue-950 sm:grid-cols-[1fr_auto_1fr_auto_1fr] sm:items-center"><Box>HTTP</Box><span aria-hidden="true">+</span><Box>TLS</Box><span aria-hidden="true">=</span><Box>HTTPS</Box></div><p>HTTP/1.1 und HTTP/2 über HTTPS verwenden gewöhnlich TCP-Port <code>443</code>. HTTP/3 nutzt QUIC über UDP, ebenfalls gewöhnlich Port <code>443</code>. Ein Port allein beweist weder das Protokoll noch TLS.</p></Section>
    <Section id="tls-goals" title="Drei Schutzziele von TLS"><div className="grid gap-4 sm:grid-cols-3"><Card title="Vertraulichkeit">Beobachter im Netz sollen geschützte Anwendungsdaten nicht einfach mitlesen können.</Card><Card title="Integrität">Manipulation geschützter Übertragungsdaten soll erkannt werden.</Card><Card title="Authentifizierung">Der Client prüft die Serveridentität anhand Zertifikatsidentität, Hostname und Vertrauenskette.</Card></div><p>Typisches HTTPS authentifiziert den <strong>Server</strong>, nicht automatisch auch den Client. Clientzertifikate beziehungsweise mTLS existieren, sind für gewöhnliches HTTPS aber nicht erforderlich.</p></Section>
    <section aria-labelledby="not-guaranteed" className="rounded-2xl border-2 border-amber-300 bg-amber-50 p-5 sm:p-7"><h2 id="not-guaranteed" className="text-2xl font-bold text-slate-950">HTTPS bedeutet nicht „Inhalt sicher“</h2><p className="mt-4">HTTPS schützt die Transportverbindung und authentifiziert den Endpunkt gemäß Zertifikatsprüfung. Es garantiert weder einen ehrlichen Betreiber noch harmlose Downloads, fehlerfreie Webanwendungen oder einen unkompromittierten Server. Auch eine bösartige Website kann ein gültiges Zertifikat besitzen.</p><p className="mt-3">Nicht jede Verbindungsmetainformation wird verborgen. Beteiligte Netze sehen beispielsweise weiterhin, dass eine Verbindung stattfindet; je nach Protokoll und Umgebung können weitere Metadaten erkennbar sein.</p></section>
    <Section id="certificate" title="Was ein Serverzertifikat aussagt"><p>Ein X.509-Serverzertifikat bindet Identitätsnamen und öffentliches Schlüsselmaterial nach einem Vertrauensmodell zusammen. Relevant sind konzeptionell: Namen, insbesondere <strong>Subject Alternative Names (SAN)</strong>, öffentlicher Schlüssel, Aussteller, Gültigkeitszeitraum und Signaturbeziehung. Einzelne Felder musst du nicht auswendig lernen.</p><p>Das Zertifikat ist nicht selbst „der Verschlüsselungsalgorithmus“. TLS übernimmt den kryptografischen Schutz; das Zertifikat hilft vor allem bei Identität, Schlüsselzuordnung und Vertrauen.</p></Section>
    <Section id="hostname" title="Hostname-Validierung"><p>Beim Aufruf <code>https://web01.firma.test</code> prüft der Client, ob eine passende Zertifikatsidentität – modern insbesondere ein SAN – für <code>web01.firma.test</code> enthalten ist. Ein Zertifikat nur für <code>mail.firma.test</code> passt nicht automatisch. Ein Wildcard-Name wie <code>*.firma.test</code> kann je nach Regeln geeignete einteilige Hostnamen abdecken; Details sind hier nachrangig.</p></Section>
    <TlsTrustVisualization />
    <Section id="chain" title="Vertrauenskette und CA"><p>Eine <strong>Certificate Authority (CA)</strong> bestätigt Zertifikatsbindungen durch Signaturen. Typisch ist die Kette <strong>Serverzertifikat → Intermediate CA → vertrauenswürdige Root CA</strong>. Der Browser beziehungsweise das Betriebssystem besitzt einen Trust Store mit vertrauten Root-Zertifikaten. Der Server liefert gewöhnlich sein Zertifikat und benötigte Intermediate-Zertifikate; das Root-Zertifikat muss er normalerweise nicht mitsenden.</p><p>Der Client baut und validiert einen Zertifizierungspfad zur vertrauten Wurzel. Verschlüsselung und Identitätsprüfung sind unterschiedliche Konzepte: Verschlüsselter Verkehr zu einem nicht verlässlich identifizierten Gegenüber löst das Identitätsproblem nicht.</p></Section>
    <Section id="self-signed" title="Selbstsigniert und interne CA"><p>Ein selbstsigniertes Zertifikat signiert sich selbst, statt zu einem anderen vertrauenswürdigen Aussteller zu verketten. Das macht Verschlüsselung nicht unmöglich und beweist keine Böswilligkeit. Clients vertrauen der behaupteten Identität jedoch normalerweise erst, wenn dieses Zertifikat oder der passende Trust Anchor ausdrücklich vertraut wird.</p><p>Organisationen können eine interne CA betreiben. Geräte, die deren Root CA kontrolliert vertrauen, können damit ausgestellte interne Zertifikate validieren. Das ist in Labor- und Firmennetzen üblich – Zertifikatswarnungen sollten trotzdem untersucht und nicht blind umgangen werden.</p></Section>
    <Section id="validity" title="Gültigkeit und typische Zertifikatsfehler"><div className="grid gap-3 sm:grid-cols-2"><Card title="Hostname stimmt nicht">Angefragter Name fehlt als passende Zertifikatsidentität.</Card><Card title="Abgelaufen / noch nicht gültig">Aktuelle Zeit liegt außerhalb des Gültigkeitszeitraums.</Card><Card title="Aussteller nicht vertraut">Kein validierbarer Pfad zu einem Trust Anchor im Client.</Card><Card title="Kette unvollständig">Ein benötigtes Intermediate-Zertifikat fehlt möglicherweise.</Card><Card title="Systemzeit falsch">Eine falsche Client- oder Serverzeit kann Gültigkeitsprobleme verursachen.</Card></div><p>Ablauf bedeutet eine Validierungs- beziehungsweise Vertrauensstörung, nicht dass Verschlüsselung mathematisch unmöglich wäre. Browser formulieren Fehler unterschiedlich.</p></Section>
    <Section id="handshake" title="Was vor geschützten HTTP-Daten geschieht"><ol className="list-decimal space-y-2 pl-6"><li>Der Client verbindet sich.</li><li>Client und Server handeln unterstützte TLS-Parameter aus.</li><li>Der Server stellt Zertifikatsinformationen bereit.</li><li>Der Client validiert Identität, Namen, Zeit und Vertrauenskette.</li><li>Kryptografische Schlüssel werden etabliert.</li><li>Erst danach werden geschützte HTTP-Anwendungsdaten ausgetauscht.</li></ol><p>Dies ist bewusst ein modernes, vereinfachtes Modell ohne Cipher-Mathematik oder veraltete RSA-Key-Exchange-Vereinfachung.</p></Section>
    <MultipleSelectionCheck title="HTTPS und TLS prüfen" question="Welche Aussagen über HTTPS/TLS sind korrekt?" inputName="https-tls-statements" correctOptionIds={["conf-integrity", "authentication", "hostname", "not-content-trust"]} successMessage="Richtig: TLS schützt Transportdaten und Zertifikatsvalidierung prüft die Serveridentität; beides bewertet nicht die Vertrauenswürdigkeit des Inhalts." missedCorrectMessage="Prüfe Schutzziele, Zertifikatsidentität und die Grenzen von HTTPS." options={[
      { id: "conf-integrity", label: "TLS kann Vertraulichkeit und Integrität schützen.", explanation: "Das sind zentrale TLS-Schutzziele." },
      { id: "authentication", label: "Zertifikatsvalidierung hilft, die Serveridentität zu authentifizieren.", explanation: "Typisches HTTPS prüft die Serveridentität." },
      { id: "hostname", label: "Der angefragte Hostname muss zu einer geeigneten Zertifikatsidentität passen.", explanation: "Hostname-Validierung verhindert, dass irgendein Zertifikat für jeden Namen gilt." },
      { id: "not-content-trust", label: "Eine gültige HTTPS-Verbindung beweist nicht, dass der Inhalt vertrauenswürdig ist.", explanation: "HTTPS bewertet nicht die Absichten des Betreibers oder den Inhalt." },
      { id: "malware", label: "HTTPS verhindert automatisch Malware.", explanation: "Auch schädliche Inhalte können über HTTPS übertragen werden." },
      { id: "self-signed", label: "Jedes selbstsignierte Zertifikat beweist einen bösartigen Server.", explanation: "Es fehlt normalerweise automatisches Vertrauen; Böswilligkeit folgt daraus nicht." },
      { id: "any-name", label: "Ein Zertifikat für irgendeinen Hostnamen gilt für jede Website.", explanation: "Der angefragte Name muss passend enthalten sein." },
      { id: "dns", label: "TLS ersetzt DNS.", explanation: "DNS löst Namen auf; TLS schützt die Verbindung und prüft Identität." },
    ]} />
    <Section id="inspection" title="Praxis: Zertifikat im Browser untersuchen"><p>Öffne in einer verfügbaren Browseroberfläche die Verbindungs- oder Zertifikatsinformationen. Finde unabhängig von exakten Menübezeichnungen: angefragten Hostnamen, Aussteller, Gültigkeitszeitraum, Zertifikatsnamen/SAN und Vertrauensstatus. Optional ist <code>curl -I https://…</code> ein HTTP-Client-Test; externe Internetverbindung ist nicht erforderlich.</p></Section>
    <Misconceptions items={[["HTTPS bedeutet, dass die Webseite sicher und vertrauenswürdig ist.", "TLS schützt den Transport, nicht die Ehrlichkeit oder Fehlerfreiheit des Inhalts."], ["Das Zertifikat verschlüsselt einfach die Daten.", "TLS schützt kryptografisch; Zertifikate dienen primär Identität, Schlüsselbindung und Vertrauen."], ["Selbstsigniert bedeutet unverschlüsselt.", "Verschlüsselung kann stattfinden, obwohl automatisches Identitätsvertrauen fehlt."], ["Port 443 garantiert HTTPS.", "Ein Port allein bestimmt das tatsächliche Anwendungsprotokoll nicht."], ["Ein gültiges Zertifikat bestätigt jeden Webseiteninhalt.", "Es bestätigt keine inhaltliche Richtigkeit."], ["TLS ersetzt DNS.", "DNS und TLS erfüllen getrennte Aufgaben."]]} />
    <Preview title="Webserver-Fehleranalyse">Als Nächstes grenzt du DNS-, Netzwerk-, Port-, TLS-, HTTP- und Anwendungsfehler anhand von Belegen ein.</Preview>
  </Lesson>;
}

export function WebserverTroubleshootingLesson() {
  const steps = [["Name", "Ist der angefragte Hostname korrekt?"], ["DNS", "Kommt die erwartete Adresse zurück?"], ["IP/Pfad", "Ist grundlegende Erreichbarkeit plausibel?"], ["Port", "Ist der Zielport erreichbar und lauscht der Dienst?"], ["TLS", "Passen Name, Zeitraum und Vertrauenskette?"], ["HTTP", "Trifft eine HTTP-Antwort ein?"], ["Status", "Welche Codeklasse und welcher konkrete Status?"], ["Pfad", "Ist Ressource beziehungsweise Route korrekt?"], ["Anwendung/Upstream", "Ist ein Backend beteiligt und erreichbar?"], ["Logs/Config", "Nach Eingrenzung gezielt Belege prüfen."]];
  return <Lesson>
    <LearningObjectives context="lesson" objectives={["DNS-, IP-, Port-, TLS-, HTTP- und Anwendungsfehler trennen", "eine belegbasierte Diagnosereihenfolge anwenden", "Connection refused und Timeout konzeptionell unterscheiden", "TLS-Zertifikatsfehler einordnen", "4xx-, 5xx- und Upstream-Statuscodes interpretieren", "Browserwerkzeuge, nslookup und curl passend einsetzen", "Beobachtungen vor Änderungen dokumentieren"]} />
    <Section id="layers" title="Vom Namen bis zur Anwendung"><WebTroubleshootingFlow steps={steps} /><p>Eine Antwort einer späteren Schicht belegt oft, dass frühere Schritte für genau diesen Austausch hinreichend funktioniert haben. Ein <code>404 Not Found</code> setzt beispielsweise genug DNS/Netz/Transport/HTTP-Kommunikation voraus, damit ein Server antworten konnte.</p></Section>
    <Section id="connection" title="DNS, Connection refused und Timeout"><div className="grid gap-4 sm:grid-cols-3"><Card title="DNS schlägt fehl">Wenn <code>web01.firma.test</code> in einer gezielten DNS-Abfrage nicht aufgelöst wird, untersuche Resolver und DNS-Daten vor Webinhalten. Eine Browsermeldung allein beweist DNS nicht.</Card><Card title="Connection refused">Der Zielpfad war meist weit genug erreichbar, um abzulehnen, aber am Endpunkt akzeptierte kein Dienst die Verbindung oder eine Policy lehnte aktiv ab. Prüfe Dienst, Port, Listen-Adresse, Firewall und Protokollerwartung.</Card><Card title="Timeout">Die erwartete Verbindung oder Antwort kam nicht rechtzeitig. Routing, Paketverlust/Filterung, Ausfall, Überlastung oder ein langsamer Upstream sind Möglichkeiten – nicht automatisch eine Firewall.</Card></div><p>Lauscht dieser HTTP-Dienst auf <code>8080</code>, muss der Aufruf <code>http://web01.firma.test:8080/</code> den Port nennen; ohne Angabe verwendet HTTP gewöhnlich 80. Port 8080 bedeutet nicht inhärent HTTP – nur dieses Beispiel definiert es so.</p></Section>
    <Section id="tls-failure" title="TLS-Fehler gezielt untersuchen"><p>DNS liefert korrekt, die Verbindung erreicht den Server, aber das Zertifikat gilt für <code>old.firma.test</code> statt für das angefragte <code>portal.firma.test</code>. Das ist Evidenz für Hostname-Mismatch beziehungsweise falsche Zertifikatsbereitstellung. Prüfe Zertifikatsidentitäten sowie Webserver-/Reverse-Proxy-Zuordnung; das blinde Umgehen der Prüfung ist keine Lösung.</p></Section>
    <Section id="http-errors" title="HTTP-Fehler unterscheiden"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Card title="403 Forbidden">Server versteht die Anfrage, verweigert aber Zugriff. Autorisierung, Serverregeln, anwendungsbezogene Policy und je nach Setup Datei-/Verzeichnisrechte kommen infrage.</Card><Card title="404 Not Found"><code>GET /azubi/index.html</code> wurde beantwortet, aber Ressource/Route ist nicht verfügbar. Prüfe URL, Document Root, Routing und Deployment – nicht pauschal DNS.</Card><Card title="500 Internal Server Error">Serverseitige Verarbeitung scheiterte, etwa durch Anwendungsfehler, Konfiguration oder Backend-Abhängigkeit; kein Beweis für Hardwaredefekt.</Card><Card title="502 Bad Gateway">Gateway/Proxy erhielt eine ungültige oder ungeeignete Upstream-Antwort.</Card><Card title="503 Service Unavailable">Dienst ist aktuell nicht verfügbar, beispielsweise wegen Wartung, Überlastung oder ausgefallenem Service.</Card><Card title="504 Gateway Timeout">Gateway/Proxy wartete ohne rechtzeitige Upstream-Antwort.</Card></div><p><code>502</code>, <code>503</code> und <code>504</code> grenzen Kategorien ein, bestimmen aber keine einzigartige Grundursache.</p><div className="grid gap-2 text-center sm:grid-cols-[1fr_auto_1fr_auto_1fr] sm:items-center"><Box>Browser</Box><span aria-hidden="true">→</span><Box>Webserver / Proxy</Box><span aria-hidden="true">→</span><Box>Anwendung</Box></div></Section>
    <Section id="tools" title="Werkzeuge liefern Belege"><div className="grid gap-3 sm:grid-cols-2"><Command value="nslookup web01.firma.test">Prüft die DNS-Antwort gezielt.</Command><Command value="Test-NetConnection web01.firma.test -Port 80">PowerShell: prüft eine TCP-Verbindung, nicht die Korrektheit der Webanwendung.</Command><Command value="Test-NetConnection web01.firma.test -Port 443">PowerShell: prüft TCP, nicht automatisch Zertifikat oder HTTP-Inhalt.</Command><Command value="curl -I http://web01.firma.test/">Fordert per HTTP typischerweise Header mit HEAD an; Serververhalten kann variieren.</Command><Command value="curl -v http://web01.firma.test/">Zeigt Verbindungs-/Requestdetails; niemals Zugangsdaten oder Tokens in Übungen verwenden.</Command><Command value="ss -ltn">Auf einem zugänglichen Linux-Server: lokale lauschende TCP-Sockets prüfen.</Command></div><p><code>ping</code> liefert nur begrenzte ICMP-Evidenz und beweist keinen HTTP-Dienst. <code>nc</code> oder andere Portwerkzeuge können je nach Plattform vorhanden sein; keine Installation ist erforderlich. Browser-Entwicklungswerkzeuge zeigen Request, Status und Header.</p></Section>
    <SingleChoiceCheck title="404 richtig weiterverfolgen" question="nslookup liefert 192.168.10.20, TCP-Port 80 ist erreichbar und GET /missing.html ergibt HTTP 404. Was untersuchst du als Nächstes?" inputName="web-404-next" correctOptionId="path" successMessage="Richtig: Eine HTTP-404-Antwort lenkt zur Ressource, zum Pfad oder Anwendungsrouting." options={[{ id: "path", label: "Angeforderten Pfad, Ressource, Inhalt und Anwendungsrouting", explanation: "Das ist die durch 404 eingegrenzte Ebene." }, { id: "dhcp", label: "Den DHCP-Pool", explanation: "Für ein DHCP-Problem gibt es keinen Beleg." }, { id: "dns", label: "Den DNS-Resolver austauschen", explanation: "DNS hat hier bereits die erwartete Adresse geliefert." }, { id: "mask", label: "Die Subnetzmaske zufällig ändern", explanation: "Die HTTP-Antwort widerspricht dieser unbelegten Maßnahme." }, { id: "tls", label: "Das TLS-Zertifikat", explanation: "Das Szenario verwendet unverschlüsseltes HTTP." }]} />
    <Section id="more-scenarios" title="Zwei weitere Szenarien"><div className="grid gap-4 sm:grid-cols-2"><Card title="Zertifikat für old.firma.test">Bei <code>portal.firma.test</code> liegt ein Hostname-Mismatch oder falsches Zertifikat am Webserver/Proxy nahe – kein generischer DNS-Ausfall.</Card><Card title="502 Bad Gateway">Der Frontend-Proxy antwortet. Untersuche Upstream-Anwendung, Backend-Konnektivität und Antwort; den Browser neu zu installieren ist unbegründet.</Card></div></Section>
    <Section id="checklist" title="Kompakte Checkliste"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Checklist title="Name / DNS" items={["Hostname korrekt?", "Erwartete Adresse?"]} /><Checklist title="Netzwerk" items={["IP, Subnetz, Gateway plausibel?", "Welche Pfad-Evidenz?"]} /><Checklist title="Transport" items={["Korrekter Port?", "Dienst erreichbar/lauschend?"]} /><Checklist title="TLS" items={["Hostname passend?", "Kette vertraut?", "Zeitraum gültig?"]} /><Checklist title="HTTP" items={["Antwort und Status?", "Pfad und Methode?"]} /><Checklist title="Anwendung / Upstream" items={["Backend gesund?", "Logs?", "Proxy-/Upstream-Pfad?"]} /></div><p><strong>Dokumentiere:</strong> beobachtetes Verhalten → Test → Ergebnis → Änderung → erneuter Test.</p></Section>
    <Misconceptions items={[["404 = Server nicht erreichbar.", "404 ist eine HTTP-Antwort des Servers."], ["Connection refused = DNS-Fehler.", "Ablehnung betrifft den Verbindungsendpunkt; DNS ist eine andere Ebene."], ["Timeout beweist Firewall.", "Mehrere Pfad-, Server- und Lastursachen sind möglich."], ["500 bedeutet Hardwaredefekt.", "500 meldet eine serverseitige Verarbeitungsstörung."], ["502 und 504 sind dasselbe.", "502 betrifft eine ungeeignete Upstream-Antwort, 504 deren rechtzeitiges Ausbleiben."], ["Erfolgreicher Ping beweist HTTP.", "ICMP-Evidenz testet keinen Webdienst."], ["Bei Zertifikatsfehlern klickt man einfach auf Weiter.", "Validierungsfehler werden untersucht statt normalisiert."]]} />
    <Preview title="Praxis: Webserver mit Filius">Zum Abschluss baust du DNS, Client und HTTP-Webdienst in einem kontrollierten Lab zusammen und führst gezielte Fehler ein.</Preview>
  </Lesson>;
}

export function WebserverFiliusLesson() {
  return <Lesson>
    <LearningObjectives context="lesson" objectives={["ein einfaches Filius-Webservernetz planen und umsetzen", "statische IPv4-, DNS- und Webserverrollen korrekt zuordnen", "HTTP per IP und Name systematisch testen", "DNS- und Webdienstfehler kontrolliert eingrenzen", "HTTP-Verkehr beobachten, soweit Filius ihn darstellt", "den zusätzlichen Schutz von HTTPS auf ein reales Umfeld übertragen", "Tests und Änderungen nachvollziehbar dokumentieren"]} />
    <section aria-labelledby="scope" className="rounded-2xl border border-blue-200 bg-blue-50 p-5 sm:p-7"><h2 id="scope" className="text-2xl font-bold text-blue-950">Sicherer Laborumfang</h2><p className="mt-3">Das Lab nutzt in Filius zuverlässig vermittelbare Grundkonzepte: Client, Server, Switch, statisches IPv4, DNS- und Webserver-Anwendung, Browser und HTTP. Die konkrete Filius-Version kann Oberflächen und Beobachtungsdetails unterschiedlich zeigen. <strong>HTTPS/TLS wird nicht vorausgesetzt</strong>; der praktische Teil bleibt HTTP, TLS ist der konzeptionelle Transfer für reale Umgebungen.</p></section>
    <Section id="plan" title="Netzplan"><div className="grid gap-3 sm:grid-cols-2"><Data label="Netz" value="192.168.50.0/24" /><Data label="Maske" value="255.255.255.0" /><Data label="Gateway (falls benötigt)" value="192.168.50.1" /><Data label="DNS-Server" value="192.168.50.10" /><Data label="Webserver" value="192.168.50.20" /><Data label="Client" value="192.168.50.100" /><Data label="DNS-Name" value="web.firma.test" /><Data label="A-Record" value="web.firma.test → 192.168.50.20" /></div><p><code>192.168.50.0</code> ist die Netzadresse, <code>192.168.50.255</code> der Broadcast. Gewöhnliche Hosts liegen von <code>.1</code> bis <code>.254</code>; alle vergebenen Adressen sind gültig und konfliktfrei.</p></Section>
    <Section id="topology" title="Topologie und Rollen"><div className="grid gap-2 text-center sm:grid-cols-[1fr_auto_1fr_auto_1fr] sm:items-center"><Box>Client<br /><code>192.168.50.100</code></Box><span aria-hidden="true">↔</span><Box>Switch</Box><span aria-hidden="true">↔</span><Box>DNS <code>.10</code><br />Web <code>.20</code></Box></div><p>DNS-Server und Webserver sind getrennte Rollen und Adressen. Der Switch verbindet das lokale Netz. Ein Gateway ist in diesem einzelnen Subnetz nicht für direkte Client-Server-Kommunikation nötig, kann aber als Planwert eingetragen werden.</p></Section>
    <Section id="phases" title="Arbeitsphasen"><ol className="grid gap-3 sm:grid-cols-2">{["Adressen und Namen planen", "Topologie aus Client, Servern und Switch bauen", "statische Infrastrukturadressen konfigurieren", "DNS-Dienst und A-Record konfigurieren", "Webserver-Anwendung einrichten", "einfache Webseite erstellen", "Client-DNS 192.168.50.10 konfigurieren", "IP-Erreichbarkeit testen", "DNS-Auflösung testen", "Website per Name öffnen", "HTTP-Verkehr beobachten, falls dargestellt", "kontrollierten Webfehler einführen", "systematisch diagnostizieren", "Ergebnisse dokumentieren"].map((step, index) => <li key={step} className="rounded-xl border border-slate-200 bg-white p-4"><strong className="text-blue-700">{index + 1}.</strong> {step}</li>)}</ol></Section>
    <Section id="content" title="Webinhalt und Testziel"><p>Erstelle eine einfache Seite mit der Überschrift <strong>„Azubi Lab Webserver-Test“</strong> und dem Text <strong>„Der Webserver funktioniert.“</strong> Der Empfang dieser Seite zeigt im Lab, dass der Webservice-/Anwendungspfad für diesen Request funktioniert.</p></Section>
    <Section id="test-order" title="In einer sinnvollen Reihenfolge testen"><ol className="list-decimal space-y-2 pl-6"><li>Kann der Client die Webserver-IP erreichen?</li><li>Löst DNS <code>web.firma.test</code> korrekt zu <code>192.168.50.20</code> auf?</li><li>Ist der HTTP-Dienst, soweit Filius dies ermöglicht, per IP zugänglich?</li><li>Öffnet <code>http://web.firma.test/</code> die Seite?</li><li>Liefert der angefragte Pfad den erwarteten Inhalt?</li></ol><p>Ein fehlgeschlagener ICMP-/Ping-Test beweist nicht universell einen Webfehler. Nutze die in deiner Filius-Version unterstützten Tests und sammle mehrere Belege.</p></Section>
    <Section id="observe" title="HTTP beobachten"><p>Falls Filius die Verkehrsbeobachtung unterstützt, suche nur nach tatsächlich sichtbaren Informationen: DNS-Anfrage und -Antwort beim Namensaufruf, HTTP-Request, HTTP-Response, angefragter Pfad und – falls dargestellt – Status oder Inhalt. Nicht jede Version zeigt dieselben Felder.</p></Section>
    <Section id="faults" title="Drei kontrollierte Fehler"><div className="space-y-4"><Fault title="1. Falscher DNS-A-Record">Ändere <code>web.firma.test</code> von <code>192.168.50.20</code> auf die unbenutzte <code>192.168.50.30</code>. DNS kann erfolgreich antworten, obwohl die Daten für den beabsichtigten Webserver falsch sind. Stelle danach <code>.20</code> wieder her.</Fault><Fault title="2. Webdienst nicht verfügbar">Falls deine Filius-Version den Webserverdienst zuverlässig stoppen/deaktivieren kann, stoppe ihn. DNS löst weiter korrekt auf, aber HTTP scheitert. Andernfalls verwende bewusst eine falsche Webserver-/Pfadkonfiguration und dokumentiere genau, was geändert wurde.</Fault><Fault title="3. Ressource fehlt">Fordere eine nicht vorhandene Seite an. Wenn Filius einen Status zeigt, erwarte konzeptionell eine 404-artige Reaktion; andernfalls dokumentiere nur: „Die angeforderte Ressource ist nicht vorhanden.“ Erfinde keinen angezeigten Code.</Fault></div></Section>
    <Section id="tls-transfer" title="Transfer: Was würde HTTPS ergänzen?"><p>Das Filius-Lab nutzt plain HTTP. In einer realen Umgebung würde HTTPS durch TLS <strong>Vertraulichkeit</strong>, <strong>Integrität</strong> und typische <strong>Serverauthentifizierung per Zertifikatsprüfung</strong> ergänzen. Nur Port 80 auf 443 zu ändern erzeugt noch kein HTTPS; TLS-Unterstützung und eine korrekte Zertifikatskonfiguration wären erforderlich.</p></Section>
    <SingleChoiceCheck title="Fehler systematisch eingrenzen" question="web.firma.test soll auf 192.168.50.20 zeigen, öffnet sich per Name aber nicht. Welche Reihenfolge ist am sinnvollsten?" inputName="filius-web-order" correctOptionId="layers" successMessage="Richtig: Erst DNS-Antwort, dann Ziel/Service und schließlich HTTP-Antwort beziehungsweise Pfad prüfen." options={[{ id: "layers", label: "1. DNS-Auflösung prüfen, 2. Ziel-IP/Dienst erreichen, 3. HTTP-Antwort und Pfad prüfen", explanation: "Diese Reihenfolge trennt die Ebenen anhand von Belegen." }, { id: "dhcp", label: "Sofort den DHCP-Pool ändern", explanation: "Das Lab arbeitet statisch; dafür gibt es keine Evidenz." }, { id: "mask", label: "Die Subnetzmaske zufällig ersetzen", explanation: "Unbelegte Änderungen erschweren die Diagnose." }, { id: "tls", label: "Zertifikatsvalidierung deaktivieren", explanation: "Das Lab verwendet HTTP und ein Validierungs-Bypass wäre keine saubere Lösung." }, { id: "404", label: "Ohne HTTP-Antwort bereits 404 annehmen", explanation: "404 kann erst aus einer HTTP-Antwort abgeleitet werden." }]} />
    <Section id="documentation" title="Dokumentationsvorlage"><dl className="grid gap-3 sm:grid-cols-2">{["Gerät", "IPv4", "Maske", "Gateway", "DNS-Server", "DNS-Name", "Dienst", "Port", "angeforderte URL", "Testergebnis", "beobachteter Fehler", "Korrektur"].map((field) => <div key={field} className="rounded-xl border border-slate-200 bg-white p-4"><dt className="font-bold text-slate-950">{field}</dt><dd className="mt-1 text-sm text-slate-500">____________________</dd></div>)}</dl></Section>
    <Memory items={["DNS-Antwort kann technisch funktionieren und trotzdem falsche Daten liefern.", "Korrekte Namensauflösung beweist keinen laufenden Webdienst.", "Eine HTTP-Antwort grenzt den Fehler auf eine spätere Schicht ein.", "Beobachtung, Test, Ergebnis, Änderung und Retest dokumentieren."]} />
  </Lesson>;
}

function TlsTrustVisualization() { const checks = [["Hostname", "web01.firma.test passt zur Zertifikatsidentität"], ["Gültigkeit", "Aktuelle Zeit liegt im Zertifikatszeitraum"], ["Vertrauenskette", "Signaturen führen zu einer Root CA im Trust Store"]]; return <figure className="rounded-2xl border border-slate-200 bg-slate-50 p-5 sm:p-6"><figcaption className="font-bold text-slate-950">Zertifikatsprüfung für https://web01.firma.test</figcaption><ol className="mt-5 grid gap-2 text-center"><li><Box>Browser fordert <code className="break-all">https://web01.firma.test</code> an</Box><Arrow /></li><li><Box>Webserver präsentiert Serverzertifikat<br /><span className="text-sm">Identität: web01.firma.test</span></Box><Arrow /></li><li><Box>Intermediate CA signiert Serverzertifikat</Box><Arrow /></li><li><Box>Root CA ist im Browser-/System-Trust-Store vertraut</Box></li></ol><dl className="mt-5 grid gap-3 sm:grid-cols-3">{checks.map(([term, meaning]) => <div key={term} className="rounded-xl border border-blue-200 bg-white p-4"><dt className="font-bold text-blue-900">Prüfung: {term}</dt><dd className="mt-2 text-sm leading-6">{meaning}</dd></div>)}</dl></figure>; }
function WebTroubleshootingFlow({ steps }: { steps: readonly (readonly string[])[] }) { return <figure className="rounded-2xl border border-slate-200 bg-slate-50 p-5 sm:p-6"><figcaption className="font-bold text-slate-950">Entscheidungsfluss mit Bedeutung</figcaption><ol className="mt-5 grid gap-2 sm:grid-cols-2">{steps.map(([name, meaning], index) => <li key={name} className="rounded-xl border border-blue-200 bg-white p-4"><p className="font-bold text-blue-900">{index + 1}. {name}?</p><p className="mt-1 text-sm leading-6">{meaning}</p></li>)}</ol></figure>; }
function Lesson({ children }: { children: React.ReactNode }) { return <div className="space-y-10 text-base leading-7 text-slate-700 sm:text-lg sm:leading-8">{children}</div>; }
function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) { return <section aria-labelledby={id} className="space-y-4"><h2 id={id} className="text-2xl font-bold tracking-tight text-slate-950">{title}</h2>{children}</section>; }
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <article className="min-w-0 rounded-xl border border-slate-200 bg-white p-4"><h3 className="font-bold text-slate-950">{title}</h3><p className="mt-2 break-words text-sm leading-6">{children}</p></article>; }
function Box({ children }: { children: React.ReactNode }) { return <div className="min-w-0 rounded-xl border border-blue-200 bg-white p-4 break-words">{children}</div>; }
function Arrow() { return <span aria-hidden="true" className="block py-1 font-bold text-blue-700">↓</span>; }
function Data({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-xl border border-blue-200 bg-blue-50 p-4"><dt className="text-sm font-semibold text-blue-800">{label}</dt><dd className="mt-1 break-all font-bold text-blue-950">{value}</dd></div>; }
function Command({ value, children }: { value: string; children: React.ReactNode }) { return <article className="min-w-0 rounded-xl border border-slate-200 bg-white p-4"><code className="block overflow-x-auto whitespace-pre-wrap break-words font-bold text-blue-900">{value}</code><p className="mt-2 text-sm leading-6">{children}</p></article>; }
function Checklist({ title, items }: { title: string; items: readonly string[] }) { return <section className="rounded-xl border border-slate-200 bg-white p-4"><h3 className="font-bold text-slate-950">{title}</h3><ul className="mt-2 list-disc pl-5 text-sm">{items.map((item) => <li key={item}>{item}</li>)}</ul></section>; }
function Fault({ title, children }: { title: string; children: React.ReactNode }) { return <article className="rounded-xl border border-amber-200 bg-amber-50 p-5"><h3 className="font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6">{children}</p></article>; }
function Misconceptions({ items }: { items: readonly (readonly [string, string])[] }) { return <section><h2 className="text-2xl font-bold text-slate-950">Typische Fehlvorstellungen</h2><dl className="mt-5 space-y-4">{items.map(([wrong, correction]) => <div key={wrong} className="rounded-xl border border-slate-200 bg-white p-4"><dt className="font-bold text-slate-950">Falsch: „{wrong}“</dt><dd className="mt-2 text-sm"><strong>Korrektur:</strong> {correction}</dd></div>)}</dl></section>; }
function Preview({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-slate-50 p-5 sm:p-6"><p className="text-sm font-semibold text-blue-700">Nächste Lektion</p><h2 className="mt-1 text-xl font-bold text-slate-950">{title}</h2><p className="mt-3 text-sm leading-6">{children}</p></section>; }
function Memory({ items }: { items: readonly string[] }) { return <aside className="rounded-2xl border border-blue-200 bg-blue-950 p-5 text-white sm:p-6"><h2 className="text-sm font-bold uppercase tracking-[0.12em] text-blue-200">Merksätze</h2><ul className="mt-3 space-y-2 font-semibold">{items.map((item) => <li key={item}>{item}</li>)}</ul></aside>; }
