import { HttpConceptMatchingCheck, HttpStatusMatchingCheck } from "./http-matching-check";
import { LearningObjectives } from "./learning-objectives";
import { MultipleSelectionCheck, type MultipleSelectionOption } from "./multiple-selection-check";
import { HttpRequestResponseVisualization, HttpStatusOverview, UrlBreakdown, WebServerRequestFlow } from "./webserver-visualizations";

const webserverOptions: readonly MultipleSelectionOption[] = [
  { id: "requests", label: "Ein Webserver empfängt HTTP-Anfragen.", explanation: "Das ist seine zentrale Aufgabe." },
  { id: "responses", label: "Ein Webserver sendet HTTP-Antworten.", explanation: "Er beantwortet Requests mit Responses." },
  { id: "dns-before", label: "DNS kann vor der Webanfrage den Servernamen auflösen.", explanation: "Danach kann der Client die Zieladresse verwenden." },
  { id: "host", label: "Webserver-Software kann auf einem physischen oder virtuellen Host laufen.", explanation: "Host und Software sind getrennte Konzepte." },
  { id: "dns-html", label: "DNS liefert die HTML-Seite aus.", explanation: "DNS löst Namen auf; HTTP überträgt Webinhalte." },
  { id: "one-ip", label: "Jeder Webserver muss genau eine IP-Adresse verwenden.", explanation: "Hosts können mehrere Adressen haben und eine Adresse kann mehrere Sites bedienen." },
  { id: "browser-server", label: "Der Browser ist der Webserver.", explanation: "Bei dieser Interaktion ist der Browser der HTTP-Client." },
  { id: "http-ip", label: "HTTP weist Clients automatisch IP-Adressen zu.", explanation: "IP-Konfiguration erfolgt etwa manuell oder über DHCP, nicht durch HTTP." },
];

export function WebServerIntroductionLesson() { return <Lesson>
  <LearningObjectives context="lesson" objectives={["den Zweck eines Webservers erklären", "Browser beziehungsweise Client und Webserver unterscheiden", "Serverhost und Webserver-Software unterscheiden", "das Client-Server-Kommunikationsmodell erklären", "DNS-Auflösung mit anschließender IP-Kommunikation verbinden", "TCP-Ports als Dienstendpunkte konzeptionell erklären", "HTTP-Port 80 und HTTPS-Port 443 erkennen", "statische und dynamische Webinhalte konzeptionell unterscheiden", "Webserver und DNS unterscheiden"]} />
  <Section id="definition" title="Was ist ein Webserver?"><p>Ein <strong>Webserver ist Software, die HTTP-Anfragen empfängt und HTTP-Antworten sendet</strong>. Beispiele sind Apache HTTP Server, nginx und Microsoft IIS. Das ist keine Produktbewertung: Alle illustrieren dieselbe grundlegende Rolle.</p><div className="grid gap-3 sm:grid-cols-3"><Card title="Serverhost">Physische oder virtuelle Maschine, auf der Dienste laufen.</Card><Card title="Webserver-Software">Nimmt HTTP-Requests an und liefert HTTP-Responses.</Card><Card title="Inhalt / Webanwendung">HTML, CSS, Bilder, JavaScript oder durch eine Anwendung erzeugte Daten.</Card></div><p>Ein Host kann neben dem Webserver weitere Dienste ausführen. Deshalb sind weder der Host noch die Software einfach „die Webseite“.</p></Section>
  <Section id="client-server" title="Browser und Server sprechen miteinander"><p>Der Browser ist bei dieser HTTP-Interaktion der <strong>Client</strong>. Er fordert beispielsweise <code>http://web01.firma.test/</code> an; der Webserver unter <code>192.168.10.20</code> antwortet.</p><div className="grid gap-3 sm:grid-cols-2"><Card title="Browser → Request → Webserver">Der Client fragt eine Ressource an.</Card><Card title="Webserver → Response → Browser">Der Server liefert ein Ergebnis zurück.</Card></div><p>Auch Kommandozeilenwerkzeuge wie <code>curl</code>, Anwendungen und API-Clients können HTTP-Clients sein. Browser sind nur das bekannteste Beispiel.</p></Section>
  <Section id="dns-ip" title="DNS findet die Adresse – HTTP holt den Inhalt"><p>Falls die Adresse nicht bereits bekannt oder gecached ist, kann DNS <code>web01.firma.test</code> zu <code>192.168.10.20</code> auflösen. Anschließend kommuniziert der Client mit dieser IP-Adresse.</p><p><strong>DNS löst den Namen auf. DNS liefert nicht die Webseite.</strong> Erst HTTP regelt Webanfrage und Webantwort. Ebenso vergibt HTTP keine IP-Adressen; dafür kennst du beispielsweise DHCP oder manuelle Konfiguration.</p><WebServerRequestFlow /></Section>
  <Section id="tcp-ports" title="HTTP, Transport und Ports"><p>HTTP-Anwendungsdaten werden über Netzwerkverbindungen transportiert. Für den Anfängerblick gilt: <strong>HTTP → Transport → IP</strong>. HTTP/1.1 und HTTP/2 verwenden typischerweise TCP. HTTP/3 verwendet QUIC über UDP; dessen Details sind hier nicht erforderlich.</p><dl className="grid gap-3 sm:grid-cols-3"><Data label="HTTP" value="häufig TCP 80" /><Data label="HTTPS (HTTP/1.1/2)" value="häufig TCP 443" /><Data label="HTTP/3" value="QUIC/UDP, häufig 443" /></dl><p>Eine IP-Adresse identifiziert ein Ziel im IP-Netz; ein Transport-Port identifiziert dort einen Dienstendpunkt. Port 443 ist daher nicht „immer TCP“.</p></Section>
  <Section id="content" title="Statische und dynamische Inhalte"><div className="grid gap-3 sm:grid-cols-2"><Card title="Statisch">Eine vorhandene HTML-, CSS-, Bild- oder JavaScript-Ressource wird ausgeliefert, ohne ihren Inhalt pro Anfrage zu erzeugen. Sie kann durch Administration oder Deployment sehr wohl geändert werden.</Card><Card title="Dynamisch">Eine Webanwendung erzeugt die Antwort etwa aus Request, Anwendungslogik, Datenbankdaten, angemeldetem Benutzer oder aktuellen Informationen.</Card></div><p>Ein Webserver kann statische Dateien direkt liefern und/oder Requests an eine Anwendungslaufzeit weiterreichen. In realen Systemen können Webserver, Reverse Proxy und Application Server getrennt oder integriert sein. Webserver bedeutet daher nicht automatisch „gesamte Anwendungslogik“.</p></Section>
  <MultipleSelectionCheck title="Webserver verstehen" question="Welche Aussagen über einen Webserver sind korrekt?" options={webserverOptions} correctOptionIds={["requests", "responses", "dns-before", "host"]} successMessage="Richtig: Webserver-Software verarbeitet HTTP, während DNS zuvor Namen auflösen kann und der Host die Software ausführt." missedCorrectMessage="Prüfe die Rollen von HTTP, DNS, Client und Serverhost." inputName="webserver-concepts" />
  <Misconceptions items={[["DNS lädt die Webseite.", "DNS löst Namen auf; HTTP überträgt Webanfrage und Webantwort."], ["Der Server ist einfach die Webseite.", "Host, Webserver-Software und Inhalt beziehungsweise Anwendung sind verschiedene Konzepte."], ["HTTP vergibt IP-Adressen.", "IP-Konfiguration gehört zu Mechanismen wie DHCP oder manueller Konfiguration."], ["Statische Webseite bedeutet, dass die Datei niemals verändert wird.", "Statisch beschreibt die Erzeugung bei der Anfrage, nicht die Dauerhaftigkeit."], ["HTTP nutzt immer TCP.", "HTTP/1.1 und HTTP/2 nutzen typischerweise TCP; HTTP/3 nutzt QUIC über UDP."]]} />
  <Section id="practice-one" title="Beobachten statt installieren"><p>Gib in einer lokalen Übungsumgebung <code>http://server.firma.test/</code> in die Browser-Adresszeile ein. Falls <code>curl</code> bereits vorhanden ist, ist <code>curl http://server.firma.test/</code> eine optionale Alternative: curl handelt dabei als HTTP-Client. Internetzugang ist nicht erforderlich.</p></Section>
  <Memory items={["Webserver = empfängt HTTP-Anfragen und sendet HTTP-Antworten.", "Browser = HTTP-Client.", "DNS → Name zur Adresse.", "HTTP → Web-Kommunikation.", "HTTP ≠ DHCP.", "DNS ≠ Webserver."]} />
</Lesson>; }

export function HttpRequestResponseLesson() { return <Lesson>
  <LearningObjectives context="lesson" objectives={["eine HTTP-Anfrage erklären", "eine HTTP-Antwort erklären", "Konzepte der Request-Zeile identifizieren", "Konzepte der Response-Statuszeile identifizieren", "Header und Body unterscheiden", "erklären, warum nicht jede Anfrage oder Antwort einen Body hat", "eine einfache GET-Transaktion beschreiben", "HTTP als grundsätzlich zustandslos verstehen", "HTTP-Ergebnis und darunterliegende Konnektivität unterscheiden"]} />
  <Section id="request" title="Die HTTP-Anfrage"><p>Ein Request teilt dem Server mit, welche Verarbeitung der Client für welches Ziel wünscht. Dieses <strong>vereinfachte HTTP/1.1-Beispiel</strong> zeigt eine typische GET-Anfrage:</p><Code>{`GET /index.html HTTP/1.1\nHost: web01.firma.test\nUser-Agent: Beispielclient\nAccept: text/html`}</Code><dl className="grid gap-3 sm:grid-cols-2"><Data label="GET" value="Methode" /><Data label="/index.html" value="Request-Target / Pfad" /><Data label="HTTP/1.1" value="Protokollversion" /><Data label="Host und weitere Zeilen" value="Header" /></dl><p>Ein Request kann einen Body tragen. POST, PUT oder PATCH übertragen je nach Anwendung häufig Daten. GET wird beim typischen Browsen normalerweise ohne Request-Body verwendet; eine universelle Aussage „GET kann niemals einen Body haben“ wäre unnötig absolut.</p></Section>
  <Section id="response" title="Die HTTP-Antwort"><p>Der Server antwortet mit Status, Metadaten und – falls passend – Inhalt:</p><Code>{`HTTP/1.1 200 OK\nContent-Type: text/html\nContent-Length: ...\n\n<html>...</html>`}</Code><p>Dies ist ebenfalls ein <strong>vereinfachtes HTTP/1.1-Beispiel</strong>: Version, Statuscode und bei HTTP/1.x eine Reason Phrase stehen vor den Headern; der optionale Body folgt nach einer Leerzeile. HTTP/2 und HTTP/3 verwenden auf der Leitung nicht exakt diese textuelle Darstellung.</p><HttpRequestResponseVisualization /></Section>
  <Section id="headers" title="Host, Content-Type und Content-Length"><p>Mehrere Namen wie <code>www.firma.test</code> und <code>portal.firma.test</code> können beide auf <code>192.168.10.20</code> zeigen. Der <code>Host</code>-Header lässt einen HTTP/1.1-Webserver oder Reverse Proxy erkennen, welcher Host angefragt wurde.</p><p><code>Content-Type</code> beschreibt den Medientyp eines Bodys, etwa <code>text/html</code>, <code>application/json</code> oder <code>image/png</code>. Er ist HTTP-Metadatum und nicht bloß eine Dateiendung. <code>Content-Length</code> kann die Bodygröße in Bytes nennen, ist aber nicht in jeder Antwort vorhanden; andere Übertragungsrahmungen existieren.</p></Section>
  <Section id="many" title="Eine Seite, viele Requests"><p>Eine sichtbare Webseite kann separate Requests für HTML, CSS, JavaScript, Bilder, Fonts und API-Aufrufe auslösen. <strong>Eine Webseite ist daher nicht automatisch genau eine HTTP-Anfrage.</strong></p></Section>
  <Section id="stateless" title="HTTP merkt sich nicht automatisch Benutzer"><p>HTTP ist auf Protokollebene grundsätzlich zustandslos: Jeder Request soll unabhängig verständlich sein. Anwendungen können Zustand mit Cookies, serverseitigen Sessions oder Tokens ergänzen; HTTP selbst erinnert sich nicht inhärent zwischen Requests an einen Benutzer.</p></Section>
  <HttpConceptMatchingCheck />
  <Section id="interpret" title="Eine vollständige Transaktion lesen"><Code>{`Request\nGET / HTTP/1.1\nHost: web01.firma.test\n\nResponse\nHTTP/1.1 200 OK\nContent-Type: text/html\n\n<html>...</html>`}</Code><ul className="list-disc pl-6"><li>Der Client sendet den Request; der Server sendet die Response.</li><li>Methode: GET; angefragter Host: web01.firma.test.</li><li>Statuscode: 200; Content-Type: text/html.</li></ul></Section>
  <Misconceptions items={[["Eine Webseite wird mit genau einer HTTP-Anfrage geladen.", "Weitere Ressourcen führen häufig zu weiteren Requests."], ["HTTP-Header sind Teil des HTML-Codes.", "Header sind HTTP-Metadaten; HTML kann im Body stehen."], ["200 OK bedeutet, dass DNS und Netzwerk generell überall funktionieren.", "200 bestätigt die erfolgreiche HTTP-Verarbeitung dieser Transaktion, nicht jede Infrastrukturkomponente global."], ["Content-Type ist einfach die Dateiendung.", "Content-Type ist vom Absender kommuniziertes HTTP-Metadatum."], ["HTTP merkt sich automatisch Benutzer zwischen Requests.", "Anwendungsmechanismen wie Cookies, Sessions oder Tokens ergänzen Zustand."], ["Jede HTTP-Antwort enthält HTML.", "Ein Body kann JSON, ein Bild, eine Datei oder andere Daten enthalten – oder fehlen."]]} />
  <Section id="practice-two" title="Praxis mit Entwicklungswerkzeugen"><p>Öffne konzeptionell den Netzwerkbereich der Browser-Entwicklungswerkzeuge und suche Request-URL, Methode, Status und Content-Type. Optional zeigt <code>curl -i http://server.firma.test/</code> bei üblichem curl-Gebrauch Response-Header zusammen mit dem Body. Eine Installation ist nicht erforderlich.</p></Section>
  <Memory items={["Request: Client → Server", "Response: Server → Client", "HTTP-Request: Methode + Ziel + Header + ggf. Body", "HTTP-Response: Status + Header + ggf. Body", "Eine Webseite kann viele Requests erzeugen."]} />
</Lesson>; }

export function HttpUrlMethodsStatusLesson() { return <Lesson>
  <LearningObjectives context="lesson" objectives={["eine URL in wichtige Bestandteile zerlegen", "Schema, Host, Port, Pfad, Query und Fragment unterscheiden", "gängige HTTP-Methoden erklären", "wichtige Request- und Response-Header interpretieren", "HTTP-Statuscodes klassifizieren", "Weiterleitungen und häufige Client-/Serverfehler erkennen", "Statuscodes als HTTP-Ergebnis statt sichere Grundursache verstehen", "gängige Statuscodes bei der Fehlersuche verwenden"]} />
  <Section id="url" title="Eine URL zerlegen"><UrlBreakdown /><p>Ohne expliziten Port ergibt das Schema typischerweise den Standard: HTTP nutzt 80, HTTPS 443. <code>:8080</code> und <code>:8443</code> sind häufig verwendete Alternativen, aber keine vorgeschriebenen Ersatzports; insbesondere bedeutet 8080 nicht automatisch HTTPS.</p></Section>
  <Section id="methods" title="Gängige HTTP-Methoden"><dl className="grid gap-3 sm:grid-cols-2"><Data label="GET" value="Repräsentation abrufen" /><Data label="POST" value="Daten übermitteln oder Verarbeitung anstoßen" /><Data label="PUT" value="typischerweise Repräsentation am Ziel ersetzen/erstellen" /><Data label="PATCH" value="semantisch für teilweise Änderung vorgesehen" /><Data label="DELETE" value="Entfernung einer Ressource anfordern" /><Data label="HEAD" value="GET-ähnliche Metadaten ohne Response-Body" /><Data label="OPTIONS" value="Kommunikationsoptionen/Fähigkeiten erfragen" /></dl><p>Das sind HTTP-Semantik und typische REST-Konventionen, keine Garantie für jede Anwendung. POST bedeutet beispielsweise nicht zwingend „Datenbankeintrag erstellen“.</p><aside className="rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm"><strong>Vertiefung, nicht zum Auswendiglernen:</strong> GET und HEAD sind als „safe“ für keine angeforderte Zustandsänderung vorgesehen. PUT und DELETE sind semantisch idempotent: Wiederholung hat denselben beabsichtigten Effekt. Eine konkrete Implementierung kann dennoch Fehler besitzen; auch POST ist nicht in jeder denkbaren Anwendung zwingend nicht-idempotent.</aside></Section>
  <Section id="important-headers" title="Wichtige Header"><div className="grid gap-4 sm:grid-cols-2"><HeaderList title="Request-Header" items={[["Host", "angefragter Host"], ["Accept", "akzeptierte Medientypen"], ["User-Agent", "Client-Information"], ["Authorization", "Anmeldedaten oder Token, falls verwendet"], ["Content-Type", "Format des Request-Bodys"]]} /><HeaderList title="Response-Header" items={[["Content-Type", "Medientyp des Bodys"], ["Content-Length", "Bodygröße, wenn vorhanden"], ["Location", "Ziel, häufig bei Redirects"], ["Cache-Control", "Caching-Anweisungen"], ["Set-Cookie", "Client soll Cookie-Information speichern"]]} /></div><p>Ein Authorization-Header ist nicht automatisch verschlüsselt. Transportvertraulichkeit gehört zu HTTPS/TLS und folgt in Lektion 4; echte Zugangsdaten gehören nie in Lehrbeispiele.</p></Section>
  <Section id="status" title="Statuscodes einordnen"><HttpStatusOverview /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[["200 OK", "Ressource erfolgreich verarbeitet"], ["201 Created", "Ressource erstellt"], ["204 No Content", "Erfolg ohne Response-Body"], ["301 Moved Permanently", "dauerhafte Weiterleitung"], ["302 Found", "temporäre/Fund-Weiterleitung"], ["304 Not Modified", "Cache-Repräsentation weiter nutzbar"], ["400 Bad Request", "ungeeignete/fehlerhafte Anfrage"], ["401 Unauthorized", "Authentifizierung fehlt oder ist ungültig"], ["403 Forbidden", "verstanden, aber Zugriff verweigert"], ["404 Not Found", "angefragte Ressource nicht gefunden"], ["405 Method Not Allowed", "Methode für das Ziel nicht erlaubt"], ["500 Internal Server Error", "serverseitige Verarbeitung fehlgeschlagen"], ["502 Bad Gateway", "ungeeignete Upstream-Antwort am Gateway"], ["503 Service Unavailable", "Dienst aktuell nicht verfügbar"], ["504 Gateway Timeout", "keine rechtzeitige Upstream-Antwort"]].map(([title, text]) => <Card key={title} title={title}>{text}</Card>)}</div></Section>
  <Section id="details" title="Wichtige Unterschiede"><p><strong>401 ist nicht 403:</strong> Trotz historischer Reason Phrase bedeutet 401 konzeptionell, dass erforderliche Authentifizierung fehlt oder ungültig ist. Bei 403 hat der Server die Anfrage verstanden, verweigert aber Autorisierung beziehungsweise Zugriff.</p><p><strong>404 ist eine HTTP-Antwort:</strong> Für Anfänger heißt sie „Ressource nicht gefunden“ (oder der Server legt sie in manchen Fällen nicht offen). Damit hat ein HTTP-Server geantwortet – anders als bei fehlgeschlagenem DNS, Timeout oder abgelehnter TCP-Verbindung.</p><p><strong>502, 503 und 504:</strong> 502 beschreibt eine ungeeignete Upstream-Antwort am Gateway/Proxy, 503 einen aktuell nicht verfügbaren Dienst und 504 eine nicht rechtzeitige Upstream-Antwort. Sie grenzen HTTP-Kategorien ein, beweisen aber keine exakte physische Grundursache.</p></Section>
  <Section id="redirect" title="Weiterleitungen"><p>Ein 3xx-Status kann den Client mit <code>Location: https://www.firma.test/new</code> zu einem anderen Ziel führen. 301 steht konzeptionell für eine permanente, 302 für eine temporäre beziehungsweise „Found“-Weiterleitung. Details zu Methoden und Caching bleiben späteren Vertiefungen vorbehalten.</p></Section>
  <HttpStatusMatchingCheck />
  <Section id="troubleshooting" title="Symptome praktisch unterscheiden"><dl className="grid gap-3 sm:grid-cols-2"><Data label="DNS-Fehler" value="Servername nicht auflösbar" /><Data label="Connection refused" value="Ziel erreichbar denkbar, aber kein Listener akzeptiert die Verbindung" /><Data label="Timeout" value="keine rechtzeitige Verbindung/Antwort" /><Data label="404" value="HTTP-Antwort, Ressource nicht gefunden" /><Data label="500" value="HTTP-Antwort mit serverseitigem Fehler" /><Data label="502 / 504" value="häufig Intermediär-/Upstream-Kontext" /></dl><p>Jedes Symptom ist ein Diagnosehinweis, kein Beweis für eine einzige physische Ursache.</p></Section>
  <Misconceptions items={[["404 bedeutet, dass DNS kaputt ist.", "404 beweist, dass eine HTTP-Antwort eingetroffen ist."], ["500 bedeutet, dass der ganze Server ausgeschaltet ist.", "500 ist eine serverseitige HTTP-Fehlerantwort."], ["401 und 403 sind dasselbe.", "401 betrifft erforderliche Authentifizierung; 403 verweigerten Zugriff."], ["Port 8080 bedeutet automatisch HTTPS.", "Alternative Ports bestimmen nicht allein das Schema."], ["Der URL-Fragmentteil #… wird normal an den Webserver gesendet.", "Das Fragment verarbeitet üblicherweise der Client."], ["POST bedeutet immer Datenbankeintrag erstellen.", "Die konkrete Anwendungssemantik entscheidet."], ["Jede erfolgreiche HTTP-Antwort ist 200.", "Auch andere 2xx-Statuscodes wie 201 und 204 melden Erfolg."]]} />
  <Section id="practice-three" title="Praxisbeobachtung"><p>Suche in Browser-Entwicklungswerkzeugen Request-URL, Methode, Status und Response-Header. Optional fordert <code>curl -I http://server.firma.test/</code> abhängig vom Serververhalten Metadaten über HEAD an; <code>curl -i ...</code> zeigt Header plus Body. curl muss nicht installiert werden.</p></Section>
  <Memory items={["URL: Schema + Host + Port + Pfad + Query + Fragment", "2xx: Erfolg", "3xx: Weiterleitung", "4xx: Request-/Client-Kontext", "5xx: Server-/Upstream-Kontext", "404 ≠ DNS-Fehler", "401 ≠ 403"]} />
  <section className="rounded-2xl border border-slate-200 bg-slate-50 p-5 sm:p-6"><p className="text-sm font-semibold text-blue-700">Nächste Lektion</p><h2 className="mt-1 text-xl font-bold text-slate-950">HTTPS und TLS-Grundlagen</h2><p className="mt-3 text-sm leading-6">Als Nächstes geht es darum, warum HTTP allein keine Transportverschlüsselung bietet, was TLS schützt, wie Zertifikate, Hostnamenprüfung und Vertrauenskette konzeptionell zusammenspielen und wie sich HTTP und HTTPS unterscheiden.</p></section>
</Lesson>; }

function Lesson({ children }: { children: React.ReactNode }) { return <div className="space-y-10 text-base leading-7 text-slate-700 sm:text-lg sm:leading-8">{children}</div>; }
function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) { return <section aria-labelledby={id} className="space-y-4"><h2 id={id} className="text-2xl font-bold tracking-tight text-slate-950">{title}</h2>{children}</section>; }
function Card({ title, children }: { title: string; children: React.ReactNode }) { return <article className="rounded-xl border border-slate-200 bg-white p-4"><h3 className="font-bold text-slate-950">{title}</h3><p className="mt-2 text-sm leading-6">{children}</p></article>; }
function Data({ label, value }: { label: string; value: string }) { return <div className="min-w-0 rounded-xl border border-blue-200 bg-blue-50 p-4"><dt className="text-sm font-semibold text-blue-800">{label}</dt><dd className="mt-1 break-words font-semibold text-blue-950">{value}</dd></div>; }
function Code({ children }: { children: string }) { return <pre className="overflow-x-auto whitespace-pre-wrap break-words rounded-xl bg-slate-950 p-4 text-sm leading-6 text-blue-100"><code>{children}</code></pre>; }
function HeaderList({ title, items }: { title: string; items: readonly (readonly [string, string])[] }) { return <div className="rounded-xl border border-slate-200 bg-white p-5"><h3 className="font-bold text-slate-950">{title}</h3><dl className="mt-3 space-y-3">{items.map(([name, meaning]) => <div key={name}><dt><code className="font-bold text-blue-900">{name}</code></dt><dd className="text-sm">{meaning}</dd></div>)}</dl></div>; }
function Misconceptions({ items }: { items: readonly (readonly [string, string])[] }) { return <section><h2 className="text-2xl font-bold text-slate-950">Typische Fehlvorstellungen</h2><dl className="mt-5 space-y-4">{items.map(([wrong, correction]) => <div key={wrong} className="rounded-xl border border-slate-200 bg-white p-4"><dt className="font-bold text-slate-950">Falsch: „{wrong}“</dt><dd className="mt-2 text-sm"><strong>Korrektur:</strong> {correction}</dd></div>)}</dl></section>; }
function Memory({ items }: { items: readonly string[] }) { return <aside className="rounded-2xl border border-blue-200 bg-blue-950 p-5 text-white sm:p-6"><h2 className="text-sm font-bold uppercase tracking-[0.12em] text-blue-200">Merksätze</h2><ul className="mt-3 space-y-2 font-semibold">{items.map((item) => <li key={item}>{item}</li>)}</ul></aside>; }
