import { LearningObjectives } from "./learning-objectives";
import { MultipleSelectionCheck, type MultipleSelectionOption } from "./multiple-selection-check";
import { WindowsAdministrationMatchingCheck, WindowsDirectoryMatchingCheck, WindowsInventoryClassificationCheck, WindowsPathClassificationCheck, WindowsPermissionMatchingCheck, WindowsToolMatchingCheck } from "./windows-checks";
import { NtfsPermissionOverview, WindowsArchitectureOverview, WindowsEditionOverview, WindowsInventoryFlow, WindowsPathOverview, WindowsProcessServiceOverview, WindowsShellComparison } from "./windows-visualizations";

const windowsOptions: readonly MultipleSelectionOption[] = [
  { id: "os", label: "Windows ist ein Betriebssystem.", explanation: "Es verwaltet Ressourcen und stellt Anwendungen Systemfunktionen bereit." },
  { id: "powershell", label: "PowerShell ist eine Administrations-Shell und Skriptumgebung.", explanation: "PowerShell ist Shell und Automatisierungsumgebung, nicht der Terminalhost." },
  { id: "terminal", label: "Windows Terminal ist ein Terminalhost für verschiedene Shells.", explanation: "Es kann unter anderem PowerShell und CMD hosten." },
  { id: "uac", label: "Auch administrative Benutzer können eine UAC-Rechteerhöhung sehen.", explanation: "Gruppenmitgliedschaft bedeutet nicht, dass jeder Prozess bereits voll erhöht läuft." },
  { id: "same", label: "Windows Terminal und PowerShell sind exakt dasselbe.", explanation: "Terminalhost und Shell haben unterschiedliche Rollen." },
  { id: "all-admin", label: "Jeder Windows-Prozess läuft immer mit Administratorrechten.", explanation: "Prozesse laufen in unterschiedlichen Sicherheitskontexten; Least Privilege bleibt wichtig." },
  { id: "kernels", label: "Home, Pro und Enterprise haben völlig unabhängige Windows-Grundlagen.", explanation: "Editionen positionieren gemeinsame Windows-Grundlagen für verschiedene Szenarien." },
  { id: "disable-uac", label: "UAC sollte für Administration normalerweise deaktiviert werden.", explanation: "UAC unterstützt kontrollierte Rechteerhöhung und sollte nicht pauschal deaktiviert werden." },
];

export function WindowsIntroductionLesson() { return <LessonBody>
  <LearningObjectives context="lesson" objectives={["erklären, was Windows als Betriebssystem leistet", "Betriebssystem, Anwendung und Benutzeroberfläche unterscheiden", "Home, Pro, Enterprise und Education auf hoher Ebene einordnen", "Kernel-Mode und User-Mode konzeptionell unterscheiden", "Benutzersitzung und Systemdienste unterscheiden", "Administratorrechte und UAC auf Einsteigerniveau erklären", "verstehen, warum Administrator-Mitgliedschaft nicht jeden Prozess automatisch erhöht", "gängige grafische und textbasierte Verwaltungsoberflächen erkennen", "Windows Terminal und PowerShell unterscheiden"]}/>
  <Section title="Windows ist mehr als der Desktop"><p>Windows ist das Betriebssystem: Es koordiniert Hardware, Speicher, Prozesse, Ein-/Ausgabe, Sicherheit und Netzwerkfunktionen und bietet Anwendungen stabile Schnittstellen. Explorer und der Desktop bilden eine grafische Shell für die Benutzersitzung; sie sind weder der Kernel noch das gesamte Betriebssystem.</p><p>Desktop-/Client-Windows ist für interaktive Arbeitsplatzsysteme ausgelegt. Eine angemeldete Person arbeitet in einer <strong>Benutzersitzung</strong>. Systemdienste erfüllen Hintergrundaufgaben in eigenen Sicherheits- und Startkontexten; einige laufen unabhängig von einer interaktiven Anmeldung, andere nur unter bestimmten Bedingungen.</p></Section>
  <WindowsEditionOverview />
  <Section title="Kernel, User Mode und Treiber"><p>Der Windows-Kernel und zugehörige Executive-/Kernkomponenten übernehmen zentrale Funktionen: Prozess- und Threadplanung, Speicherverwaltung, Sicherheitsmechanismen, Ein-/Ausgabe sowie die Integration von Hardware und Netzwerkfunktionen. Der Kernel ist ein zentraler Teil, aber nicht das gesamte Windows.</p><p>Gewöhnliche Anwendungen laufen überwiegend im <strong>User Mode</strong> mit begrenztem Zugriff. Kernel-Mode-Code besitzt deutlich weiterreichenden Zugriff; Fehler können das ganze System treffen. Treiber können abhängig von ihrer Architektur im Kernel Mode arbeiten.</p></Section>
  <WindowsArchitectureOverview />
  <Section title="Oberflächen für Konfiguration und Administration"><p><strong>Einstellungen</strong> sind die moderne grafische Konfigurationsfläche. Je nach Aufgabe und Windows-Version ergänzen sie Computerverwaltung, Geräte-Manager, Dienste, Ereignisanzeige, Task-Manager, Systemsteuerung und MMC-basierte Werkzeuge. Exakte Menüpfade verändern sich; entscheidend ist die Rolle des Werkzeugs.</p><p>CMD und PowerShell sind Shells. Windows Terminal ist eine Terminalanwendung, die unterschiedliche Shell-Profile hosten kann. Keines dieser Werkzeuge ist selbst der Kernel.</p></Section>
  <Section title="Administrator und UAC"><p>Ein Konto kann zur lokalen Gruppe <strong>Administratoren</strong> gehören. Mit aktivierter Benutzerkontensteuerung (UAC) laufen die meisten interaktiv gestarteten Anwendungen gewöhnlich zunächst ohne den vollen erhöhten Administratortoken. Erst eine angeforderte und bestätigte Rechteerhöhung startet einen erhöhten Kontext. UAC wird nicht pauschal deaktiviert und permanente Erhöhung ist keine normale Arbeitsweise.</p></Section>
  <Section title="Konten hängen von der Umgebung ab"><p>Windows kann mit einem lokalen Konto, einem Microsoft-Konto oder einer Organisationsidentität aus Domänen-/Entra-Kontexten verwendet werden. Wo Identität geprüft und verwaltet wird, hängt von der Umgebung ab. Active Directory und Entra-Administration folgen in späteren Modulen.</p></Section>
  <MultipleSelectionCheck title="Windows-Grundverständnis" question="Welche Aussagen über Windows sind korrekt?" options={windowsOptions} correctOptionIds={["os", "powershell", "terminal", "uac"]} successMessage="Richtig: Betriebssystem, Shell, Terminalhost und kontrollierte Rechteerhöhung sind sauber getrennt." missedCorrectMessage="Gesucht sind vier Aussagen zu Windows, PowerShell, Windows Terminal und UAC." inputName="windows-basics" />
  <Misconceptions items={[["Windows Terminal = PowerShell.", "Windows Terminal ist ein Host; PowerShell ist eine darin nutzbare Shell und Administrationsumgebung."], ["Administrator bedeutet, dass jedes Programm automatisch voll erhöht läuft.", "UAC trennt den normalen interaktiven Kontext gewöhnlich von gezielter Erhöhung."], ["UAC ist nur störend und sollte deaktiviert werden.", "UAC unterstützt kontrollierte Rechteerhöhung und bleibt normalerweise aktiv."], ["Windows Home und Pro sind völlig unterschiedliche Betriebssysteme.", "Editionen adressieren unterschiedliche Anforderungen auf gemeinsamen Windows-Grundlagen."], ["Der Desktop ist das Betriebssystem.", "Der Desktop ist eine grafische Shell; das Betriebssystem umfasst weit mehr Komponenten."], ["Systemdienste laufen nur, wenn ein Benutzer angemeldet ist.", "Viele Dienste können ohne interaktive Anmeldung laufen; Start und Kontext hängen vom jeweiligen Dienst ab."]]}/>
  <SafeBox title="Sicher beobachten"><p><code>winver</code>, <code>whoami</code> und <code>hostname</code> zeigen Version, Ausführungsidentität und Computername. <code>systeminfo</code> liefert eine breite Zusammenfassung und kann etwas dauern; es ist nicht für jede Eigenschaft die einzige maßgebliche Quelle. PowerShells <code>Get-ComputerInfo</code> kann sehr umfangreich ausgeben. Für diese Grundbeobachtung ist keine Erhöhung nötig.</p></SafeBox>
  <Memory items={["Windows = Betriebssystem.", "Edition ≠ komplett anderes Betriebssystem.", "Windows Terminal = Terminalhost.", "PowerShell = Shell + Automatisierungs-/Administrationsumgebung.", "Administrator ≠ automatisch jeder Prozess erhöht.", "UAC = kontrollierte Rechteerhöhung."]}/>
 </LessonBody>; }

export function WindowsShellLesson() { return <LessonBody>
  <LearningObjectives context="lesson" objectives={["Command Prompt, PowerShell und Windows Terminal unterscheiden", "Shell und Terminalhost erklären", "sichere, nur lesende Befehle ausführen", "in CMD und PowerShell navigieren", "Befehle und Hilfe entdecken", "textorientierte CMD-Ausgabe und PowerShell-Objektpipeline konzeptionell unterscheiden", "Aliase vorsichtig einordnen", "Pfad, Benutzer und Host erkennen", "unbekannte Befehle nicht blind erhöht ausführen", "shellabhängige Syntax erkennen"]}/>
  <Section title="Host und Shell sind verschiedene Rollen"><p><strong>Windows Terminal</strong> ist eine Terminalanwendung und kann Profile für PowerShell, Command Prompt und weitere installierte Shells hosten. <strong>cmd.exe</strong> ist der traditionelle Windows-Befehlsinterpreter: Er bleibt für viele Aufgaben nützlich, ist aber nicht automatisch die beste Lösung jeder modernen Administration. <strong>PowerShell</strong> ist Shell sowie Automatisierungs- und Skriptumgebung.</p></Section>
  <WindowsShellComparison />
  <Section title="Navigation und Befehle"><Comparison rows={[["aktueller Ort", "cd", "Get-Location"], ["Inhalt auflisten", "dir", "Get-ChildItem"], ["Ort wechseln", "cd C:\\Windows", "Set-Location C:\\Windows"]]}/><p>PowerShell stellt häufig Aliase wie <code>cd</code>, <code>dir</code> oder <code>ls</code> bereit. Das macht CMD, GNU/Linux-Werkzeuge und PowerShell nicht semantisch identisch; <code>ls</code> ist dort häufig nur ein Alias für <code>Get-ChildItem</code>.</p><p><code>whoami</code> zeigt die Ausführungsidentität, <code>hostname</code> den Computernamen. Die Shell hält einen aktuellen Arbeitsort – die Grundlage relativer Pfade in Lektion 3.</p></Section>
  <Section title="PowerShell systematisch entdecken"><p>Cmdlets folgen häufig <strong>Verb-Noun</strong>, etwa <code>Get-Process</code>, <code>Get-Service</code> und <code>Get-ChildItem</code>. <code>Get-Command</code>, <code>Get-Command *service*</code> und <code>Get-Help Get-ChildItem</code> unterstützen die Suche. Lokale PowerShell-Hilfe kann je nach installierten Hilfedaten unterschiedlich ausführlich sein.</p><p>Traditionelle CMD-Werkzeuge reichen häufig Text weiter. PowerShell-Pipelines können strukturierte .NET-Objekte zwischen Befehlen übertragen – PowerShell kann trotzdem auch Text verarbeiten.</p></Section>
  <Section title="Hilfe und Status"><p>CMD bietet <code>help</code>, <code>dir /?</code>, außerdem <code>ver</code> und <code>where</code>. <code>%ERRORLEVEL%</code> macht häufig den Exitcode eines zuvor passenden CMD-Befehls sichtbar. In PowerShell bezieht sich <code>$LASTEXITCODE</code> auf das letzte native Programm, wo anwendbar; <code>$?</code> bildet zusätzlich PowerShell-Erfolgssemantik ab. Diese Größen sind verwandt, aber nicht identisch.</p></Section>
  <WindowsToolMatchingCheck />
  <SafeBox title="Sichere Befehlsgewohnheiten"><ul className="list-disc space-y-2 pl-6"><li>Ziel-Shell und Hilfe bestimmen.</li><li>Aktuellen Pfad prüfen und lesende von ändernden Befehlen unterscheiden.</li><li>Nicht automatisch „Als Administrator“ starten.</li><li>Keine Skripte aus unbekannten Quellen einfügen.</li><li>Wirkung eines unbekannten Befehls vor Ausführung verstehen.</li></ul></SafeBox>
  <Misconceptions items={[["CMD, PowerShell und Windows Terminal sind dasselbe.", "CMD und PowerShell sind unterschiedliche Shells; Terminal ist ein Host."], ["ls in PowerShell beweist, PowerShell sei Linux.", "ls kann ein PowerShell-Alias für Get-ChildItem sein."], ["Jeder CMD-Befehl funktioniert identisch in PowerShell.", "Syntax, Auflösung und Semantik können abweichen."], ["PowerShell braucht immer Administratorrechte.", "Lesen und Navigation funktionieren häufig mit normalen Rechten."], ["Keine Ausgabe bedeutet Fehlschlag.", "Manche erfolgreichen Befehle bleiben still; Status und Dokumentation helfen."], ["Terminal als Administrator macht jeden Befehl sicher.", "Erhöhung vergrößert die Wirkung, nicht die Sicherheit eines Befehls."]]}/>
  <Section title="Praxis: nur lesen und navigieren"><ol className="list-decimal space-y-2 pl-6"><li>Erkenne am Prompt, ob CMD oder PowerShell läuft.</li><li>Zeige Benutzer mit <code>whoami</code> und Host mit <code>hostname</code>.</li><li>Zeige den Ort mit <code>cd</code> oder <code>Get-Location</code>.</li><li>Liste ihn mit <code>dir</code> oder <code>Get-ChildItem</code>.</li><li>Wechsle mit <code>cd</code> oder <code>Set-Location</code> in ein vorhandenes, unkritisches Verzeichnis.</li><li>Kehre in CMD über <code>cd %USERPROFILE%</code>, in PowerShell über <code>Set-Location $HOME</code> zurück.</li><li>Lies Hilfe mit <code>dir /?</code> oder <code>Get-Help Get-ChildItem</code>.</li></ol><p>Keine Erhöhung und keine Dateiänderung sind erforderlich.</p></Section>
 </LessonBody>; }

export function WindowsFilesystemLesson() { return <LessonBody>
  <LearningObjectives context="lesson" objectives={["Laufwerksbuchstaben und Laufwerkswurzeln erklären", "absolute und relative Pfade unterscheiden", ". und .. verwenden", "Benutzerprofilpfade und Umgebungsvariablen verstehen", "lokale und UNC-Netzwerkpfade unterscheiden", "wichtige Windows-Verzeichnisse erkennen", "Program Files, ProgramData und AppData unterscheiden", "Dateiendungen einordnen", "Windows-Groß-/Kleinschreibung nuanciert beschreiben", "Laufwerksbuchstaben nicht mit physischen Datenträgern verwechseln"]}/>
  <Section title="Laufwerke und Pfadwurzeln"><p><code>C:\</code> und <code>D:\</code> bezeichnen logische Laufwerks-/Volumen-Namensräume. Ein Buchstabe ist nicht zwangsläufig eine gesamte physische Festplatte; Partitionen, Volumes und Netzzuordnungen lösen diese einfache Beziehung auf. <code>C:\</code> ist die Wurzel von C:, während Linux <code>/</code> als Wurzel eines gemeinsamen eingehängten Dateisystembaums verwendet.</p></Section>
  <WindowsPathOverview />
  <Section title="Absolute und relative Pfade"><p><code>C:\Users\Azubi\Documents\bericht.txt</code> ist ein vollständig qualifizierter lokaler Pfad. Vom aktuellen Ort <code>C:\Users\Azubi</code> verweist <code>Documents\bericht.txt</code> relativ auf dieselbe Datei. <code>.</code> steht für den aktuellen, <code>..</code> für den übergeordneten Ort; <code>..\Public</code> ist daher relativ.</p></Section>
  <Section title="Benutzerprofil und AppData"><p>Profile liegen häufig unter <code>C:\Users\&lt;Benutzer&gt;</code>, aber Anwendungen sollten keine universelle Installationsannahme daraus machen. CMD expandiert <code>%USERPROFILE%</code>; PowerShell nutzt für das Home des aktuellen Benutzers <code>$HOME</code>. Das sind unterschiedliche Shell-Syntaxen.</p><p>Zum Profil gehören häufig Desktop, Documents, Downloads und AppData. <code>AppData\Roaming</code> ist für potenziell roamingfähige Profildaten in passenden Umgebungen gedacht – tatsächliches Roaming ist nicht garantiert. <code>AppData\Local</code> enthält maschinenlokale, <code>AppData\LocalLow</code> bei manchen Anwendungen Daten eines niedrigeren Integritätskontexts.</p></Section>
  <Section title="Wichtige System- und Anwendungsorte"><DirectoryGrid/><p><code>C:\Windows\System32</code> enthält auf 64-Bit-Windows üblicherweise 64-Bit-Systembinärdateien. Die historisch verwirrende 32-Bit-Kompatibilität nutzt unter anderem SysWOW64. Nicht jede Anwendung hält sich perfekt an alle Verzeichniskonventionen.</p></Section>
  <Section title="UNC und gemappte Laufwerke"><p><code>\\fileserver\azubi\Dokumente</code> ist ein UNC-Pfad: <code>fileserver</code> ist der Server, <code>azubi</code> die Freigabe, danach folgen Unterordner. Ein Netzlaufwerk wie Z: kann bequem darauf abbilden, ist aber weder erforderlich noch die zugrunde liegende UNC-Identität.</p></Section>
  <Section title="Groß-/Kleinschreibung, Endungen und Attribute"><p>Die typische Windows-/NTFS-Erfahrung ist case-preserving, aber bei gewöhnlichem Win32-Zugriff weitgehend case-insensitive: <code>Datei.txt</code> und <code>datei.txt</code> bezeichnen meist denselben Pfad. Bestimmte moderne Kontexte oder konfigurierte Verzeichnisse können case-sensitive sein.</p><p>Endungen wie <code>.txt</code>, <code>.exe</code>, <code>.ps1</code> und <code>.docx</code> helfen bei Dateitypzuordnung, garantieren aber weder Inhalt noch Sicherheit. Verborgene bekannte Endungen können <code>rechnung.pdf.exe</code> irreführend darstellen. Hidden-/System-Attribute unterscheiden sich von der Linux-Konvention führender Punkte.</p></Section>
  <WindowsPathClassificationCheck/><WindowsDirectoryMatchingCheck/>
  <Misconceptions items={[["C: ist immer eine komplette physische Festplatte.", "Der Buchstabe bezeichnet einen zugewiesenen logischen Laufwerksnamensraum."], ["Windows-Netzlaufwerke brauchen zwingend einen Laufwerksbuchstaben.", "UNC-Pfade greifen ohne Mapping direkt auf Freigaben zu."], ["ProgramData ist dasselbe wie Program Files.", "Program Files enthält häufig Programmdateien; ProgramData gemeinsame Anwendungsdaten."], ["AppData\\Roaming wird garantiert auf jedem PC synchronisiert.", "Name und vorgesehene Rolle garantieren kein tatsächlich eingerichtetes Roaming."], ["Windows-Dateinamen sind unter allen Umständen case-insensitive.", "Spezifische Kontexte können Verzeichnisse case-sensitive behandeln."], ["Eine .txt-Dateiendung beweist, dass die Datei harmlos ist.", "Endung, tatsächlicher Inhalt und Sicherheit sind getrennt."], ["UNC und gemapptes Laufwerk sind dasselbe.", "Ein Mapping ist eine bequeme Laufwerksansicht auf eine Ressource mit eigener UNC-Identität."]]}/>
  <SafeBox title="Sicher üben"><p>CMD: <code>cd</code>, <code>dir</code>, <code>echo %USERPROFILE%</code>. PowerShell: <code>Get-Location</code>, <code>Get-ChildItem</code>, <code>$HOME</code>. Untersuche – soweit dein Konto lesen darf – <code>C:\Users</code>, <code>C:\Windows</code>, <code>C:\Program Files</code> und <code>C:\ProgramData</code>. Für UNC genügt das konzeptionelle Beispiel; keine Freigabe und keine Erhöhung sind nötig.</p></SafeBox>
  <Section title="Als Nächstes: Benutzer, Gruppen und NTFS-Berechtigungen"><p>Die nächste Lektion behandelt lokale Benutzer, Gruppen, das SID-Konzept, Administratorrechte, NTFS-Berechtigungen, Vererbung und effektiven Zugriff.</p></Section>
 </LessonBody>; }

export function WindowsPermissionsLesson() { return <LessonBody>
  <LearningObjectives context="lesson" objectives={["Benutzer und Gruppen unterscheiden", "Gruppen als skalierbare Berechtigungsverwaltung erklären", "SID konzeptionell erklären", "Authentifizierung und Autorisierung unterscheiden", "gängige NTFS-Berechtigungssätze erkennen", "Allow, Deny und Vererbung sorgfältig einordnen", "effektiven Zugriff aus direkten, Gruppen- und geerbten Einträgen verstehen", "Eigentümerschaft sowie Administrator/UAC erklären", "Freigabe- und NTFS-Berechtigungen unterscheiden", "Full Control nicht als pauschalen Fix einsetzen"]}/>
  <Section title="Lokale Benutzer, Gruppen und SID"><p>Ein lokales Konto existiert in der lokalen Sicherheitsdatenbank und gilt primär für diesen Computer, etwa <code>PC01\azubi</code> oder <code>PC01\administrator</code>. Lokale Gruppen wie <strong>Users</strong> und <strong>Administrators</strong> bündeln Benutzer, damit Rechte nicht einzeln gepflegt werden müssen. Welche grafischen Verwaltungswerkzeuge verfügbar sind, hängt von Edition und Version ab.</p><p>Ein <strong>SID (Security Identifier)</strong> identifiziert einen Windows-Sicherheitsprinzipal wie Benutzer oder Gruppe intern. Wird ein Konto umbenannt, entsteht allein durch den neuen Namen konzeptionell keine völlig neue Sicherheitsidentität. SID-Formate müssen hier nicht auswendig gelernt werden.</p></Section>
  <Section title="Authentifizierung und Autorisierung"><p><strong>Authentifizierung</strong> fragt: „Wer bist du?“ <strong>Autorisierung</strong> fragt danach: „Was darfst du?“ Eine erfolgreiche Anmeldung als Anna beweist daher nicht, dass Anna jede Datei lesen darf.</p></Section>
  <Section title="NTFS-Berechtigungssätze"><dl className="grid gap-3 sm:grid-cols-2">{[["Read", "Inhalte und Eigenschaften lesen"], ["Write", "Inhalte anlegen oder schreiben, soweit anwendbar"], ["Read & Execute", "lesen und ausführbare Inhalte starten"], ["Modify", "typisch lesen, ausführen, ändern und löschen"], ["Full Control", "umfassender, einschließlich weitergehender Berechtigungsverwaltung"]].map(([name, meaning]) => <div key={name} className="rounded-xl border border-slate-200 p-4"><dt className="font-bold text-slate-950">{name}</dt><dd className="mt-1 text-sm">{meaning}</dd></div>)}</dl><p><strong>Modify ist nicht Full Control.</strong> Eine Anwendung, die Dateien schreiben muss, benötigt deshalb nicht pauschal Full Control; vergeben wird nur das Erforderliche.</p></Section>
  <Section title="Allow, Deny und effektiver Zugriff"><p>ACLs können <strong>Allow</strong>- und <strong>Deny</strong>-Einträge enthalten. „Deny wins immer“ ist keine universell ausreichende Regel: Explizite Deny-Einträge haben starke Priorität, doch die Auswertung hängt vom vollständigen Zugriffstoken, ACE-Typ und -Reihenfolge, Vererbung und den angefragten Rechten ab. Ein sauberes Gruppen-/Allow-Design ist leichter zu verstehen als unnötige Deny-Einträge.</p><p>Effektiver Zugriff kann aus direkten Benutzereinträgen, mehreren Gruppen und geerbten Einträgen entstehen. Nicht nur die ACL-Zeile mit dem Benutzernamen zählt.</p></Section>
  <NtfsPermissionOverview />
  <Section title="Vererbung und Eigentümerschaft"><p>Einträge von <code>C:\Daten</code> können an <code>C:\Daten\Azubi</code> vererbt werden. Geerbte und explizite Einträge können gleichzeitig bestehen; ein Kind muss daher nicht exakt dieselben Berechtigungen wie sein Elternordner haben.</p><p>NTFS-Objekte besitzen einen Eigentümer. Eigentümerschaft ist für Sicherheitsverwaltung relevant und kann unter Windows-Regeln die Möglichkeit beeinflussen, Berechtigungen zu verwalten. Eine Besitzübernahme ist aber kein alltäglicher Reparaturtrick und wird hier nicht ausgeführt.</p></Section>
  <Section title="Administrators, UAC und Freigaben"><p>Mitgliedschaft in <strong>Administrators</strong> bedeutet nicht, dass normale Prozesse ständig voll erhöht laufen. Änderungen an geschützten Ressourcen können UAC-Rechteerhöhung verlangen; UAC wird weder umgangen noch deaktiviert.</p><p>Bei lokalem Dateizugriff wirken NTFS-Berechtigungen. Beim Zugriff über eine SMB-Freigabe können Freigabe- <em>und</em> NTFS-Berechtigungen beteiligt sein; die anwendbare, restriktivere effektive Kombination kann begrenzen. Freigaberechte ersetzen NTFS nicht.</p></Section>
  <WindowsPermissionMatchingCheck />
  <Section title="Szenario: Warum darf Anna ändern?"><p>Anna ist Mitglied von <strong>Users</strong> und <strong>Support</strong>. Auf <code>C:\Daten\Support</code> erhält Support <strong>Modify</strong>, Users <strong>Read</strong>. Anna kann ändern, weil ihr Zugriffstoken die Support-Mitgliedschaft und damit den anwendbaren Modify-Eintrag enthält.</p></Section>
  <SafeBox title="Nur lesend beobachten"><p><code>whoami</code>, <code>whoami /groups</code> und <code>icacls &quot;%USERPROFILE%\Documents&quot;</code> lesen Identitäts-, Gruppen- beziehungsweise ACL-Informationen. PowerShell bietet je nach Windows-Version, Architektur und Kontext <code>Get-LocalUser</code>, <code>Get-LocalGroup</code> sowie <code>Get-LocalGroupMember -Group &quot;Users&quot;</code>; diese LocalAccounts-Cmdlets sind nicht überall verfügbar. Keine Konten oder ACLs werden geändert.</p></SafeBox>
  <Misconceptions items={[["Anmeldung erfolgreich = Zugriff auf jede Datei.", "Anmeldung authentifiziert; Autorisierung entscheidet je Ressource."], ["Gruppen sind nur organisatorische Ordner für Benutzer.", "Gruppen sind Sicherheitsprinzipale und vereinfachen Rechtevergabe."], ["Full Control ist der normale Fix für Schreibprobleme.", "Least Privilege verlangt nur die tatsächlich nötigen Rechte."], ["NTFS-Berechtigungen spielen bei Netzwerkfreigaben keine Rolle.", "Bei SMB können Freigabe- und NTFS-Berechtigungen gemeinsam begrenzen."], ["Nur direkt am Benutzer eingetragene Rechte zählen.", "Gruppen und Vererbung fließen ebenfalls in effektiven Zugriff ein."], ["Deny wins immer, egal wie die ACL aufgebaut ist.", "Zugriffsauswertung berücksichtigt Token, ACE-Typ/-Reihenfolge, Vererbung und angefragte Rechte; explizites Deny hat starke, aber nicht als isolierter Slogan ausreichende Priorität."]]}/>
  <Memory items={["Authentifizierung = Wer bist du?", "Autorisierung = Was darfst du?", "SID = interne Sicherheitskennung.", "Gruppen vereinfachen Rechteverwaltung.", "Modify ≠ Full Control.", "Freigaberechte ersetzen NTFS nicht."]}/>
</LessonBody>; }

export function WindowsAdministrationLesson() { return <LessonBody>
  <LearningObjectives context="lesson" objectives={["Prozess und PID erklären und untersuchen", "Prozess und Windows-Dienst unterscheiden", "Dienstzustand und Starttypen einordnen", "Prozessbeendigung von Dienststeuerung unterscheiden", "installierte Software über verschiedene Quellen einordnen", "Windows-Update-Phasen und ausstehenden Neustart erklären", "Produktionsänderungen geplant durchführen", "Ereignisanzeige als Diagnosequelle nutzen"]}/>
  <Section title="Prozesse und Task-Manager"><p>Ein <strong>Prozess</strong> ist eine laufende Instanz eines Programms oder Workloads; die <strong>PID</strong> identifiziert diese Instanz. Eine Anwendung kann mehrere Prozesse besitzen. Task-Manager, <code>Get-Process</code> und <code>tasklist</code> zeigen Prozesse sowie je nach Ansicht CPU-, Speicher-, Datenträger- und Netzwerkindikatoren, Autostart, Benutzer oder Dienste. Die exakte Oberfläche variiert.</p><p>Ein Prozess kann über Task-Manager, <code>Stop-Process</code> oder <code>taskkill</code> beendet werden. Das ist systemändernd, hier keine Übung und nicht die erste Standardlösung.</p></Section>
  <Section title="Windows-Dienste"><p>Dienste sind Hintergrundfunktionen, die der <strong>Service Control Manager</strong> verwaltet. Ein Dienst kann in einem eigenen, einem geteilten oder mehreren Prozessen wirken: Prozess und Dienst sind nicht dasselbe. <code>Get-Service</code>, <code>sc query</code> und <code>services.msc</code> dienen zur Beobachtung.</p><p>Zustände umfassen <strong>Running</strong>, <strong>Stopped</strong> und Übergangszustände. Starttypen umfassen Automatic, Automatic (Delayed Start), Manual und Disabled. Manual bedeutet keinen gewöhnlichen automatischen Bootstart, schließt aber Start durch Bedarf oder Trigger nicht aus.</p><p><code>Start-Service</code>, <code>Stop-Service</code>, <code>Restart-Service</code> und <code>Set-Service</code> verändern Zustand oder Konfiguration. Vor jeder autorisierten Änderung werden Zweck, Ursache und Abhängigkeiten ermittelt.</p></Section>
  <WindowsProcessServiceOverview />
  <Section title="Ereignisanzeige"><p>Event Viewer beziehungsweise <strong>Ereignisanzeige</strong> ist eine zentrale Diagnosequelle. Application, System und Security sind wichtige klassische Protokolle, daneben existieren viele weitere Kanäle. Prüfe Zeitstempel, Quelle/Provider, Event ID, Level und Nachricht im Kontext; Event IDs müssen nicht auswendig gelernt werden.</p><p><code>Get-WinEvent -LogName System -MaxEvents 20</code> und <code>Get-WinEvent -LogName Application -MaxEvents 20</code> sind lesende Beispiele. Berechtigungen, Protokollgröße und Umgebung beeinflussen Ergebnisse; Security ist keine Pflichtübung.</p></Section>
  <Section title="Installierte Software inventarisieren"><p>Software gelangt über MSI, EXE-Installer, Microsoft Store beziehungsweise MSIX/AppX-artige Pakete, optional <code>winget</code> oder Unternehmensverteilung auf Windows. Es gibt keine universelle Datenbank für jedes Programm. Einstellungen → installierte Apps ist eine GUI-Quelle; <code>Get-AppxPackage</code> betrachtet passende paketierte Apps, <code>winget list</code> den erkannten Bestand, falls winget verfügbar ist.</p><aside className="rounded-xl border border-amber-300 bg-amber-50 p-4 text-sm"><strong>Nicht als allgemeine Inventur verwenden:</strong> <code>Win32_Product</code> kann langsam sein und MSI-Konsistenzprüfungen beziehungsweise Reparaturverhalten auslösen.</aside></Section>
  <Section title="Windows Update"><p>Windows Update kann anwendbare Updates erkennen, herunterladen, bereitstellen/installieren und gegebenenfalls einen Neustart verlangen. Sicherheits-/Qualitätsupdates, kumulative Wartung, Feature-/Versionsupgrades und – abhängig von Konfiguration – Treiberupdates sind grobe Kategorien. Nicht jedes Update besitzt dasselbe Neustartverhalten.</p><p>„Installiert/bereitgestellt“ und „Neustart ausstehend“ sind getrennte Zustände. Auf Kunden- und Produktionssystemen gilt: inventarisieren, Änderung verstehen, Backup-/Recovery-Erwartung prüfen, Störung einplanen, Ausgangszustand dokumentieren, absichtlich aktualisieren und anschließend verifizieren.</p></Section>
  <WindowsAdministrationMatchingCheck />
  <Section title="Szenario: Prozess sichtbar, Dienst gestoppt"><p>Der Anwendungsprozess läuft, doch sein lokaler benötigter Dienst ist gestoppt. Das zeigt: Anwendung und abhängiger Dienst sind verschiedene Komponenten; ein sichtbarer Prozess beweist weder Dienstzustand noch Gesamtfunktion. Vor einem Start wird untersucht, warum der Dienst stoppte.</p></Section>
  <Misconceptions items={[["Prozess und Dienst sind dasselbe.", "Ein Dienst ist eine verwaltete Funktion und kann andere Prozessbeziehungen besitzen."], ["Wenn der Prozess sichtbar ist, funktioniert die Anwendung.", "Abhängigkeiten und tatsächliche Funktion müssen separat geprüft werden."], ["Manual bedeutet, ein Dienst kann nur per Klick starten.", "Bedarfs- und Triggerstarts können weiterhin möglich sein."], ["Task beenden ist immer die beste erste Fehlerbehebung.", "Zuerst Zustand, Ursache und Abhängigkeiten untersuchen."], ["Win32_Product ist die beste allgemeine Softwareinventur.", "Die Abfrage kann langsam sein und MSI-Prüfungen auslösen."], ["Windows Update bedeutet immer sofortigen Neustart.", "Phasen und Neustartbedarf unterscheiden sich."], ["Ein installierter Patch bedeutet immer, dass kein Neustart nötig ist.", "Ein Neustart kann noch ausstehen."]]}/>
</LessonBody>; }

export function WindowsInventoryLesson() {
  const phases = [["1. Windows identifizieren", "winver · systeminfo oder Get-ComputerInfo · hostname"], ["2. Sicherheitskontext", "whoami · whoami /groups"], ["3. Storage und Pfade", "Get-Volume · Get-PSDrive -PSProvider FileSystem"], ["4. Prozesse", "Get-Process oder tasklist"], ["5. Dienste", "Get-Service oder sc query"], ["6. Software", "installierte Apps · optional winget list / Get-AppxPackage"], ["7. Updates", "Windows-Update-Anzeige nur beobachten"], ["8. Netzwerk", "ipconfig /all · route print"], ["9. DNS", "ipconfig /all · optional nslookup"], ["10. Ereignisse", "Event Viewer · optional Get-WinEvent"], ["11. Dokumentieren", "Beobachtung, Bedeutung, Auffälligkeit, nächster Check"]] as const;
  const categories = ["System", "User", "Storage", "Processes", "Services", "Software", "Updates", "Network", "DNS", "Events"];
  return <LessonBody>
    <LearningObjectives context="lesson" objectives={["Edition, Version, Build, Hostname und Architektur erfassen", "Identität und Gruppenmitgliedschaften lesen", "CPU, Speicher, Volumes und wichtige Pfade untersuchen", "Prozesse und Dienste getrennt dokumentieren", "Software- und Updatezustand beobachten", "IP-Konfiguration, Routing und DNS erfassen", "lauschende Verbindungen mit Prozessen korrelieren", "Ereignisse als kontextabhängige Evidenz lesen", "Befunde strukturiert dokumentieren"]}/>
    <SafeBox title="Sicherheitsregel"><p><strong>Beobachten → dokumentieren → Hypothese bilden → nur autorisiert ändern.</strong> Das Lab benötigt keine Erhöhung und keine Konto-/ACL-Änderung, Prozessbeendigung, Dienststeuerung, Softwareänderung, Updateinstallation, Neustart oder Netzwerkänderung.</p></SafeBox>
    <WindowsInventoryFlow />
    <Section title="Auftrag und elf Phasen"><p>Du erhältst einen unbekannten Windows-PC zur Bestandsaufnahme und darfst nichts verändern. Ermittle Edition/Build, Hostname, aktuellen Benutzer und Gruppen, freien Speicher, je einen Prozess und Dienst, Softwareevidenz, IP-Adresse, Standardgateway, DNS-Server, einen lauschenden TCP-Endpunkt und ein aktuelles Systemereignis.</p><ol className="space-y-3">{phases.map(([title, commands]) => <li key={title} className="min-w-0 rounded-xl border border-slate-200 p-4"><h3 className="font-bold text-slate-950">{title}</h3><code className="mt-2 block overflow-x-auto whitespace-nowrap text-sm">{commands}</code></li>)}</ol></Section>
    <Section title="System, Benutzer, Hardware und Storage"><p><code>winver</code> zeigt Version/Build grafisch; <code>systeminfo</code> oder das umfangreiche <code>Get-ComputerInfo</code> liefern Systemdaten, <code>hostname</code> den Namen. Notiere Edition, Version/Build und sichtbare Architektur. Für CPU/Memory eignen sich Task-Manager sowie lesend <code>Get-CimInstance Win32_ComputerSystem</code> und <code>Get-CimInstance Win32_OperatingSystem</code>.</p><p><code>whoami</code> und <code>whoami /groups</code> zeigen Identität und Gruppen. <code>Get-LocalUser</code> ist optional, wo verfügbar. <code>Get-Volume</code> und <code>Get-PSDrive -PSProvider FileSystem</code> lesen Volumes beziehungsweise Dateisystemlaufwerke. Die Datenträgerverwaltung darf konzeptionell betrachtet werden; Partitionen werden nicht geändert. WMIC ist veraltet/optional und keine universelle Empfehlung.</p></Section>
    <Section title="Prozesse, Dienste, Software und Updates"><p><code>Get-Process</code> oder <code>tasklist</code> liefern Prozessnamen und PID sowie je nach Werkzeug Ressourcenwerte. <code>Get-Service</code> oder <code>sc query</code> zeigen laufende und gestoppte Dienste; Dienstname und Anzeigename können verschieden sein. Nichts wird beendet oder umgeschaltet.</p><p>Für Software dient die installierte-Apps-Ansicht, optional <code>winget list</code> oder für passende Pakete <code>Get-AppxPackage</code>. <code>Win32_Product</code> bleibt ausgeschlossen. In Windows Update wird nur der angezeigte Update-/Neustartzustand notiert; „Nach Updates suchen“ kann je nach Richtlinie Erkennung/Download anstoßen und gehört nicht zur streng beobachtenden Basisübung.</p></Section>
    <Section title="Netzwerk, DNS und Ports"><p><code>ipconfig /all</code> zeigt Adapter-, Adress-, DHCP- und DNS-Angaben; <code>route print</code> die Routingtabelle einschließlich möglicher Standardroute. <code>nslookup</code> kann eine DNS-Abfrage beobachten. Es werden weder Cache noch Adaptereinstellungen verändert.</p><p><code>netstat -ano</code> oder, wo verfügbar, <code>Get-NetTCPConnection</code> zeigt TCP-Endpunkte und PID-Bezug. <strong>LISTENING</strong> bedeutet, dass ein lokaler TCP-Endpunkt Verbindungen annimmt; es beweist nicht die Gesundheit der Anwendung.</p></Section>
    <Section title="Ereignisse als Evidenz"><p>Untersuche im Event Viewer oder mit <code>Get-WinEvent -LogName System -MaxEvents 20</code> Zeitstempel, Provider, Level, Event ID und Nachricht. Ein einzelnes Warning-/Error-Ereignis beweist ohne zeitlichen und technischen Kontext keine Ursache.</p></Section>
    <Section title="Dokumentationsvorlage"><div className="overflow-x-auto"><table className="w-full min-w-[50rem] border-collapse text-left text-sm"><thead><tr>{["Kategorie", "Tool/Befehl", "Beobachtung", "Bedeutung", "Mögliche Auffälligkeit", "Nächster Check"].map((heading) => <th key={heading} className="border-b p-3">{heading}</th>)}</tr></thead><tbody>{categories.map((category) => <tr key={category}><th className="border-b p-3">{category}</th>{["…", "…", "…", "…", "…"].map((cell, index) => <td key={index} className="border-b p-3">{cell}</td>)}</tr>)}</tbody></table></div><p>Die Vorlage ist nicht persistent; sie dient als Arbeitsstruktur.</p></Section>
    <WindowsInventoryClassificationCheck />
    <Memory items={["Inventur zuerst, Reparatur später.", "Prozess ≠ Dienst ≠ lauschender Socket.", "LISTENING ≠ gesunde Anwendung.", "Ein Ereignis allein ≠ bewiesene Ursache.", "Keine Änderung ohne Bedarf und Autorisierung."]}/>
  </LessonBody>;
}

function LessonBody({ children }: { children: React.ReactNode }) { return <div className="space-y-10 text-base leading-7 text-slate-700 [&_code]:break-words sm:text-lg sm:leading-8">{children}</div>; }
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="text-2xl font-bold tracking-tight text-slate-950">{title}</h2><div className="mt-4 space-y-4">{children}</div></section>; }
function SafeBox({ title, children }: { title: string; children: React.ReactNode }) { return <aside className="rounded-2xl border border-amber-200 bg-amber-50 p-5 sm:p-6"><h2 className="text-xl font-bold text-slate-950">{title}</h2><div className="mt-3 text-sm leading-7 sm:text-base">{children}</div></aside>; }
function Memory({ items }: { items: readonly string[] }) { return <aside className="rounded-2xl bg-blue-950 p-5 text-white"><h2 className="text-xl font-bold">Merksätze</h2><ul className="mt-3 list-disc space-y-2 pl-6 text-sm">{items.map((item) => <li key={item}>{item}</li>)}</ul></aside>; }
function Misconceptions({ items }: { items: readonly (readonly [string, string])[] }) { return <section><h2 className="text-2xl font-bold text-slate-950">Typische Fehlvorstellungen</h2><dl className="mt-5 space-y-3">{items.map(([wrong, correction]) => <div key={wrong} className="rounded-xl border border-slate-200 bg-white p-4"><dt className="font-bold text-slate-950">Falsch: „{wrong}“</dt><dd className="mt-2 text-sm"><strong>Korrektur:</strong> {correction}</dd></div>)}</dl></section>; }
function Comparison({ rows }: { rows: readonly (readonly string[])[] }) { return <div className="overflow-x-auto"><table className="w-full min-w-[34rem] border-collapse text-left text-sm"><thead><tr><th className="border-b p-3">Aufgabe</th><th className="border-b p-3">CMD</th><th className="border-b p-3">PowerShell</th></tr></thead><tbody>{rows.map(([task, cmd, ps]) => <tr key={task}><th className="border-b p-3">{task}</th><td className="border-b p-3"><code>{cmd}</code></td><td className="border-b p-3"><code>{ps}</code></td></tr>)}</tbody></table></div>; }
function DirectoryGrid() { const items = [["C:\\Windows", "Windows-Systemverzeichnis"], ["C:\\Program Files", "häufig 64-Bit-Anwendungen auf 64-Bit-Windows"], ["C:\\Program Files (x86)", "häufig 32-Bit-Anwendungen auf 64-Bit-Windows"], ["C:\\ProgramData", "profilunabhängige gemeinsame Anwendungsdaten"], ["C:\\Users", "übliche Benutzerprofilhierarchie"]]; return <dl className="grid gap-3 sm:grid-cols-2">{items.map(([path, role]) => <div key={path} className="min-w-0 rounded-xl border border-slate-200 bg-white p-4"><dt><code className="break-all font-bold">{path}</code></dt><dd className="mt-2 text-sm">{role}</dd></div>)}</dl>; }
