const editions = [
  ["Home", "Privatnutzer-orientierte Einsatzszenarien"], ["Pro", "Professionelle und geschäftliche Anforderungen"], ["Enterprise", "Zentral verwaltete Unternehmensumgebungen"], ["Education", "Bildungseinrichtungen und Bildungsszenarien"],
] as const;

export function WindowsEditionOverview() {
  return <figure><figcaption className="text-2xl font-bold text-slate-950">Editionen auf einen Blick</figcaption><p className="mt-3">Die Wahl hängt von benötigten Funktionen, Verwaltung, Sicherheit, Lizenzierung und betrieblichen Anforderungen ab – nicht von einem völlig anderen Windows-Grundmodell.</p><div className="mt-5 grid gap-3 sm:grid-cols-2">{editions.map(([name, role]) => <div key={name} className="rounded-xl border border-slate-200 bg-white p-4"><strong className="text-blue-950">{name}</strong><p className="mt-1 text-sm leading-6">{role}</p></div>)}</div></figure>;
}

export function WindowsArchitectureOverview() {
  const layers = ["Anwendungen und Benutzersitzung", "Windows-Dienste und User-Mode-Systemkomponenten", "Windows-Kernel und zugehörige Kernkomponenten", "Treiber", "Hardware"];
  return <figure aria-labelledby="windows-layers"><figcaption id="windows-layers" className="text-2xl font-bold text-slate-950">Konzeptionelles Windows-Schichtenmodell</figcaption><p className="mt-3">Das Modell trennt Verantwortungen; einzelne Dienste und Treiber können je nach Architektur in unterschiedlichen Kontexten arbeiten.</p><div className="mt-5 grid gap-2">{layers.map((layer, index) => <div key={layer} className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-center font-semibold"><span className="sr-only">Schicht {index + 1}: </span>{layer}</div>)}</div><div className="mt-4 grid gap-3 lg:grid-cols-3">{["GUI-Werkzeuge", "CMD", "PowerShell"].map((tool) => <div key={tool} className="min-w-0 rounded-xl border border-slate-300 bg-white p-3 text-center text-sm font-bold break-words">{tool}: Schnittstelle/Werkzeug, nicht der Kernel</div>)}</div></figure>;
}

export function WindowsShellComparison() {
  return <figure><figcaption className="text-2xl font-bold text-slate-950">Zwei Shells, ein Terminalhost</figcaption><div className="mt-5 grid min-w-0 gap-4 md:grid-cols-2"><Terminal title="Command Prompt (cmd.exe)" lines={["C:\\Users\\Azubi> whoami", "firma\\azubi"]} labels="Prompt und Befehl in Zeile 1; Ausgabe in Zeile 2."/><Terminal title="PowerShell" lines={["PS C:\\Users\\Azubi> Get-Location", "", "Path", "----", "C:\\Users\\Azubi"]} labels="PowerShell-Prompt und Befehl in Zeile 1; strukturierte Ausgabe darunter."/></div><p className="mt-4 text-sm">Windows Terminal kann beide Shells als Profile hosten. Prompt, Befehl und Ausgabe gehören zur jeweiligen Shell-Sitzung.</p></figure>;
}

function Terminal({ title, lines, labels }: { title: string; lines: readonly string[]; labels: string }) { return <div className="min-w-0 rounded-xl bg-slate-950 p-4 text-slate-100"><h3 className="font-sans text-sm font-bold text-blue-200">{title}</h3><pre className="mt-3 overflow-x-auto text-sm"><code>{lines.join("\n")}</code></pre><p className="mt-3 font-sans text-xs text-slate-300">{labels}</p></div>; }

export function WindowsPathOverview() {
  const local = [["Laufwerk", "C:"], ["Wurzel", "\\"], ["Ordner", "Users → Azubi → Documents"], ["Datei", "bericht.txt"]];
  const unc = [["Server", "fileserver"], ["Freigabe", "azubi"], ["Pfad", "Dokumente"]];
  return <figure><figcaption className="text-2xl font-bold text-slate-950">Pfade zerlegen</figcaption><PathCard path="C:\\Users\\Azubi\\Documents\\bericht.txt" parts={local}/><PathCard path="\\\\fileserver\\azubi\\Dokumente" parts={unc}/></figure>;
}
function PathCard({ path, parts }: { path: string; parts: readonly (readonly string[])[] }) { return <div className="mt-5 min-w-0 rounded-xl border border-slate-200 bg-white p-4"><code className="block overflow-x-auto whitespace-nowrap rounded bg-slate-950 p-3 text-sm text-white">{path}</code><dl className="mt-4 grid gap-2 sm:grid-cols-2">{parts.map(([term, value]) => <div key={term} className="min-w-0 rounded-lg bg-slate-50 p-3"><dt className="text-xs font-bold uppercase text-slate-500">{term}</dt><dd className="mt-1 break-words font-mono text-sm">{value}</dd></div>)}</dl></div>; }

export function NtfsPermissionOverview() { return <figure><figcaption className="text-2xl font-bold text-slate-950">Wie Berechtigungen zusammenkommen</figcaption><p className="mt-3">Textliche Kennzeichnungen machen direkte, gruppenbasierte, geerbte und explizite Einträge unabhängig von Farben verständlich.</p><div className="mt-5 grid gap-3 md:grid-cols-3"><FlowCard title="Benutzer" lines={["Anna", "Mitglied: Users", "Mitglied: Support"]}/><FlowCard title="Ordner C:\\Daten\\Support" lines={["Gruppe Support → Modify", "Gruppe Users → Read"]}/><FlowCard title="Ergebnis (konzeptionell)" lines={["Token enthält beide Gruppen", "anwendbare Einträge werden ausgewertet", "Anna kann über Support ändern"]}/></div><div className="mt-5 grid gap-3 sm:grid-cols-2"><FlowCard title="Elternordner C:\\Daten" lines={["Users → Read", "als vererbbar markiert"]}/><FlowCard title="Kind C:\\Daten\\Support" lines={["geerbt: Users → Read", "explizit: Support → Modify", "beide Arten können koexistieren"]}/></div></figure>; }
export function WindowsProcessServiceOverview() { return <figure><figcaption className="text-2xl font-bold text-slate-950">Dateien, Prozesse, Dienste und Updates</figcaption><div className="mt-5 grid gap-4 md:grid-cols-3"><FlowCard title="Anwendung" lines={["installierte Dateien", "↓ wenn ausgeführt", "Prozess(e) mit PID"]}/><FlowCard title="Dienst" lines={["Service Control Manager", "↓ verwaltet Dienst", "↓ Prozess(e), eventuell geteilt"]}/><FlowCard title="Windows Update" lines={["erkennen → herunterladen", "→ installieren/bereitstellen", "→ eventuell Neustart"]}/></div></figure>; }
export function WindowsInventoryFlow() { return <figure><figcaption className="text-2xl font-bold text-slate-950">Sichere Untersuchungsmethode</figcaption><ol className="mt-5 grid gap-3 sm:grid-cols-4">{["1. Beobachten", "2. Dokumentieren", "3. Hypothese bilden", "4. Nur autorisiert ändern"].map((step) => <li key={step} className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-center font-bold text-blue-950">{step}</li>)}</ol></figure>; }
function FlowCard({ title, lines }: { title: string; lines: readonly string[] }) { return <div className="min-w-0 rounded-xl border border-slate-200 bg-white p-4"><h3 className="font-bold text-slate-950">{title}</h3><ul className="mt-3 space-y-2 text-sm">{lines.map((line) => <li key={line} className="break-words"><code>{line}</code></li>)}</ul></div>; }
